### ISSUE TITLE
Config file not found on windows

### ISSUE THREAD

**Issue by vbatushev** [liximomo/vscode-sftp#1]
Config file:
![Config file](https://file.modx.pro/files/5/3/6/5364d92f1b1c20855ce9ba116bcead00.png)
Result of execute SFTP:Sync to Remote:
![Result of execute SFTP:Sync to Remote](https://file.modx.pro/files/b/6/e/b6e71648a975ffd152ce7e46e538e95c.png)
Windows 10, VSCode 1.12.2

**Comment by liximomo** [comment]
Make sure these:
1. the config file exists in the workspace.
2. The file you have executed the command and the config file has an ancestor directory.

please provide your workspace file structure.

**Comment by vbatushev** [comment]
My workspace:
![My workspace](https://file.modx.pro/files/b/6/6/b66bd4d9481f9ed7e7255861f09afb80.png)

**Comment by liximomo** [comment]
What message does it show?
Keep looking at the left of the status bar.

**Comment by vbatushev** [comment]
![Full height](https://file.modx.pro/files/7/2/7/7274c72944066d726c140cadf8cdf4ce.png)

**Comment by liximomo** [comment]
@vbatushev Upgrade your extension to 0.4.2.

**Comment by vbatushev** [comment]
Don't work...

**Comment by liximomo** [comment]
The problem should be the path separate. Sorry for not testing it on windows. I didn't have a windows PC on my hand. Please upgrade to 0.4.3.

**Comment by vbatushev** [comment]
sorry, but it does not work.

**Comment by liximomo** [comment]
Sorry! I will fix this!

**Comment by liximomo** [comment]
Please try again!  Upgrade!

**Comment by vbatushev** [comment]
No :(

**Comment by liximomo** [comment]
I got a windows PC and fix it finally. Upgrade to @0.4.8. 😃

**Comment by vbatushev** [comment]
New error:
![Error](https://file.modx.pro/files/3/d/d/3dd9a533683d7a5843b7e4589b67d734.png)

**Comment by vbatushev** [comment]
The extension always tries to read the privateKeyPath parameter. If null => error, if empty string - it cann't find key.

**Comment by liximomo** [comment]
Yes. I realized it. @0.4.10

**Comment by liximomo** [comment]
I wrote this for myself. So I didn't test it so much. But I'd like to fix it when anyone else got some trouble.

**Comment by vbatushev** [comment]
Yeeeeees! Working!
But small problem: After changing config, I have to reload the VSCode.

**Comment by liximomo** [comment]
Please make sure this. I tested it on windows PC and my mac, both don't need to reload the VSCode.

**Comment by vbatushev** [comment]
All ok.

**Comment by fuzzy76** [comment]
This also happens if you try to set up the extension from an editor that has no directory opened.

**Comment by isatiso** [comment]
I got this error on @0.8.0 again
![default](https://user-images.githubusercontent.com/31960249/30729421-fa970abc-9f91-11e7-8a6d-302c56893dad.png)

**Comment by AndreasHeintze** [comment]
I do also got this problem. I just recently installed both VS Code and SFTP so I guess it's the latest version. I have multiple folders added to the workspace and one sftp.json file for each folder. It seems to work if I restart VS Code after each time I have made changes to one of the sftp.json files.

**Comment by liximomo** [comment]
Ok. Please provide me the logs. 
> Set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)

**Comment by dylanh724** [comment]
Still happening in March.

**Comment by Rih** [comment]
I got this error 

[error] Error: (d:\MisCosas\Development_Codemakers\TransRuta\code\application\modules\admin) config file not found
	at Object.getConfig (C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\modules\config.js:137:15)
	at FileCommand.<anonymous> (C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:37:41)
	at Generator.next (<anonymous>)
	at C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:3:12)
	at FileCommand.handleFile (C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:33:16)
	at pendingTasks.concat.map.target (C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:54:72)
	at Array.map (native)
	at FileCommand.<anonymous> (C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:54:53)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Rodrihgo\.vscode\extensions\liximomo.sftp-1.1.11\out\src\commands\FileCommand.js:4:58)
	at <anonymous>
