### ISSUE TITLE
快捷键绑定

### ISSUE THREAD

**Issue by yiludege** [liximomo/vscode-sftp#10]
绑定快捷键需要命令行，请问这个插件的命令行是啥，非常感谢！（在输出栏都是debug的内容，能否只显示文件改动的结果，对于debug的输出可以在config中单独设置是否开启）

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/27845747-6f1017e2-6164-11e7-918a-8ad8641a8b7d.png)
vscode内的插件详情页就有.
