### ISSUE TITLE
Files are downloaded from the server but cannot be edited

### ISSUE THREAD

**Issue by samehel** [liximomo/vscode-sftp#1001]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I am connected successfully, However, I am unable to edit the files on the server. It only gives me the option to edit locally. Whenever I try editing I get the message "Cannot edit in read-only editor"

**To Reproduce**

```
{
    "name": "example",
    "host": "hostname",
    "protocol": "ftp",
    "port": 21,
    "username": "exampleUsername",
    "password": "examplePassword",
    "remotePath": "/",
    "uploadOnSave": true
}
```

**Expected behavior**
The file is downloaded and I can edit the file and with ever edit I make followed by a save, I expect it to save online as well.

**Comment by Yohn** [comment]
Once you edit the file locally and then save it, it'll upload to your server. You may have to right click on the file in explorer and select upload or sync local -> remote to auto upload to the server.
