### ISSUE TITLE
Command 'sftp.config.default' not found 

### ISSUE THREAD

**Issue by Soleguia** [liximomo/vscode-sftp#101]
## Actual Behavior
SFTP: config only responds: command 'sftp.config.default' not found
Upload doesn't work, Download doesn't work.

  ### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 sftp doesn't appear  as an option

## Specifications

  - Version: sftp 1.0.3
  - Platform: VS Code 1.18 and 1.19

**Comment by liximomo** [comment]
Please change a computer to see whether it still happens. It's probably a bug of vscoe.

**Comment by Soleguia** [comment]
I've tried it in other computer and it works.

I've downgraded VS Code to 1.8 and still not working.
Back to 1.9 still not working.

Any ideas?
Please?

Thank you.

**Comment by alireainc** [comment]
Same issue. Uninstalled and reinstalled. Worked after that and because my workspace sftp config file was still there, I did not have to reconfigure anything to upload. Whole process took less than a minute.

**Comment by alexdinari** [comment]
Same issue here as well. Tried to uninstall and install, but still not working. Help please.

**Comment by iaimmiac** [comment]
@liximomo Tried on different computer and it works perfectly fine (VS Code 1.20.0)

**Comment by c01nd01r** [comment]
I have similar problem.
VSCode 1.20.0 (1.20.0)
`command 'sftp.config.default' not found`
Setup `"sftp.printDebugLog": true`, but nothing in Output.
Trying to re-install extension, reloading VSCode - no result.

**Comment by c01nd01r** [comment]
I removed `/Users/c01nd01r/.vscode/extensions/liximomo.sftp-1.0.4/` and it all worked.

**Comment by robertheessels** [comment]
Deleting a folder like `/Users/c01nd01r/.vscode/extensions/liximomo.sftp-1.0.4/` and reinstalling sftp fixed my issue in #94  also!

**Comment by mgborgman** [comment]
I tried removing `/Users/mattborgman/.vscode/liximomo.sftp-1.0.4`, no success. Also removed `/Users/mattborgman/.vscode/liximomo.sftp-1.0.5` and reinstalled, still not working. Have uninstalled SFTP and reinstalled it via VSCode as well. Still getting upload failed error.

**Comment by Fransferdy** [comment]
I am having this same issue with Ubuntu, vscode 1.25 and sftp 1.27. Uninstalling sftp, and vscode did not fix the issue. it started to happen when I changed the name of the project folder.

**Comment by vincurekf** [comment]
I am getting the same issue, Ubuntu, VSCode 1.25.1, sftp 1.2.7. Happens on new project while creating config file and in old previously working projects. Yesterday I installed VSC update and everything worked fine. Today I restarted PC and sftp does not work.

Deleting `~/.vscode/extensions/liximomo.sftp-1.2.7` and reinstalling sftp does not help.

Still getting error: `command 'sftp.config.default' not found`
![screenshot_2018-07-27_15-23-26](https://user-images.githubusercontent.com/2306998/43323172-21e35906-91b1-11e8-8884-a34b8c3982a8.png)

**Comment by pricenw** [comment]
If you need a quick fix like I did go to [here](https://liximomo.gallery.vsassets.io/_apis/public/gallery/publisher/liximomo/extension/sftp/1.2.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage) which is the 1.2.6 version turn off auto updates and then rename the file extension to .VSIX

Source: https://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline
