### ISSUE TITLE
sftp seems to only upload dirty files

### ISSUE THREAD

**Issue by dorian-marchal** [liximomo/vscode-sftp#104]
Maybe allow upload of clean files via a config param ?

## Steps to Reproduce the Problem
- Set `uploadOnSave` to `true`.
- Open a file.
- Do __not__ modify it.
- Save it (Ctrl + S).

## Expected Behavior
sftp upload my file to the server. 

## Actual Behavior

Nothing happens.

**Comment by liximomo** [comment]
The only way is to set a shortcut to `sftp: upload` command, like `ctrl + shift + u`. Then use `ctrl + shift + u` instead of `ctrl + s`.

**Comment by dorian-marchal** [comment]
Could the possibility to upload clean files on `Ctrl + S` be added to `vscode-sftp`, as an option ?

**Comment by liximomo** [comment]
Sadly, no.

Dorian Marchal <notifications@github.com> 于 2018年2月8日周四 21:10写道：
