### ISSUE TITLE
Setup config using ssh error

### ISSUE THREAD

**Issue by stevernguyen** [liximomo/vscode-sftp#108]
Hi,

I'm trying using ssh instead password login. But when i upload or download then my received error **[sftp] ENOENT: no such file or directory, open '~/.ssh/id_rsa'**

While i check the id_rsa has exists in directory .ssh

Please tell me how to set up ssh.
Thanks!

**Comment by wallacethefmh** [comment]
use full path, that said I can't get this to work anyways.

**Comment by stevernguyen** [comment]
@wallacethefmh 
Thanks. It worked for me.
