### ISSUE TITLE
SFTP always searching for config

### ISSUE THREAD

**Issue by alexbet** [liximomo/vscode-sftp#11]
Since this last version, even though I have the SFTP config for the workspace...

![appgames_net](https://user-images.githubusercontent.com/3966760/27877534-0a4b87fe-6189-11e7-91b8-89358db69d6d.png)

... It still constantly says that it is searching for SFTP config in the status bar.

![screen shot 2017-07-05 at 1 48 54 pm](https://user-images.githubusercontent.com/3966760/27877581-399a9f04-6189-11e7-9ca2-8c99b768d773.png)

It seems like something is wrong and SFTP is constantly searching for the config file after you moved the config file to the .vscode folder. 

I think this needs fixing. Thanks!

**Comment by liximomo** [comment]
Just reload the vscode.

**Comment by DifficultNick** [comment]
The only thing that helps is to remove config file and extension. And then instal it again. After reloading the vscode everything breaks again

**Comment by alexbet** [comment]
Reloading VSCode doesn't help actually. When I reload, it happens again. Something is obviously not right.

**Comment by liximomo** [comment]
Please provide more infomations:
Extension version?OS? VScode Version

**Comment by alexbet** [comment]
My software versions:
- Mac OS 10.12.5
- VSCode 1.13.1
- SFTP 0.7.1

**Comment by DifficultNick** [comment]
@liximomo as i understand, you've updated plugin and now it says that `SFTP is ready` instead of `SFTP searching configs` after VSC was reloaded.
This is good, but the problem is that it doesn't work after VSC reload.
It works only first time when it was configured until VSC closed.

**Comment by liximomo** [comment]
What is your Workspace directory structure?
Where did you put the config file in?
And any output?(view -> output -> sftp)

**Comment by alexbet** [comment]
Now with 0.7.2, it says SFTP ready for me too. :)

**Comment by DifficultNick** [comment]
OS: Win7
Structure: main folder with subfolder. 
`.vscode` with `.sftpConfig` and `settings` is in the main folder.
In the output i see `[debug]: config at @workroot` and all my configs

**Comment by liximomo** [comment]
@DifficultNick I don't see any problems here. The extension said it's ready and it's really ready. What problems do you have?

**Comment by liximomo** [comment]
@alexbet Should it say "SFTP not ready"?

**Comment by DifficultNick** [comment]
@liximomo 
these are steps that produce my problem:
1) create a folder with file and open it (folder) in VSC
2) ctrl+shift+P -> strp:Config and make all config here (watcher.autoUpload: true)
3) make some changes in file and save it
4) everything works fine! file was saved to ftp
5) close VSC and open it again
6) make some changes in file and save it
7) **nothing happens**

**Comment by liximomo** [comment]
Sorry. I could not re-produce your problem.
5. close VSC and open it again
Dis VSC open the same folder?
Did you see 'SFTP ready' showing in the lower left corner?
If all these are true, please provide me the full log of extension. (view -> output -> sftp)

**Comment by DifficultNick** [comment]
@liximomo
yes, all this true.
Here is the log:
```
[debug]: config at @workroot {
    "host": "host",
    "port": 6121,
    "username": "username",
    "password": "password",
    "protocol": "ftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": true,
    "interactiveAuth": false,
    "remotePath": "/remotePath/",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": true,
        "autoUpload": true,
        "autoDelete": true
    },
    "ignore": [
        "c:/path to main folder/**/.vscode",
        "c:/path to main folder/**/.git",
        "c:/path to main folder/**/.DS_Store",
        "c:/path to main folder/**/.sftpConfig.json",
        "/remotePath/**/.vscode",
        "/remotePath/**/.git",
        "/remotePath/**/.DS_Store",
        "/remotePath/**/.sftpConfig.json"
    ],
    "configRoot": "c:/path to main folder"
}
```
and nothing else logs on save

**Comment by liximomo** [comment]
@DifficultNick 
Make some changes in a file and save it.
Watching out the lower left corner, is there any text show up?
Are there any logs in sftp output channel?

**Comment by DifficultNick** [comment]
No, as i said there is nothing concerning sftp nor in the left corner nither in the output when i save file after step 5

**Comment by liximomo** [comment]
I did reproduce it.
The problem was 
```
watcher": {
    "files": true
}
```
The value of `files` should be false or a glob pattern string(e.g "**/.js",).

I will add config validation in the next version.

**Comment by DifficultNick** [comment]
Sorry man!
I should read the documentation more attentively. I thought that `files` is bool.

thank you!
