### ISSUE TITLE
[sftp] Handshake failed: no matching client->server cipher

### ISSUE THREAD

**Issue by mohanhambar** [liximomo/vscode-sftp#110]
On Windows 7.
VSC Insider version 1.20.0
sftp version 1.0.4

After  upgrade to sftp version , No upload or download in workspaces that worked until today. 
Getting below  error [sftp] Handshake failed: no matching client->server cipher

**Comment by liximomo** [comment]
Config `algorithms` in sftp.json. Get more detail in readme.

**Comment by mohanhambar** [comment]
Thanks , working fine. 
Closing the issue
