### ISSUE TITLE
Watcher Ignores

### ISSUE THREAD

**Issue by designgears** [liximomo/vscode-sftp#111]
I have a feature request, I need a way to add an ignored path to the watcher. I know this can be done for ignoring the directory when it's copied but this doesn't keep the watcher from watching the .git folder or a massive image folder, etc... 

> [debug]: task: upload c:\project\.git
> [debug]: ignore: c:\project\.git

**Comment by AdsonCicilioti** [comment]
I have a question about that.

Does the Watch option consider the ignore option for your action policy?

If yes, how can I tell the watch to watch everything and use?

**Comment by franzarmas** [comment]
I am also interested in this new feature.

**Comment by socks415** [comment]
Also, very interested in this feature

**Comment by ShaharHD** [comment]
In my setup I use `"uploadOnSave": true,` instead of watcher. seems to be more granular (watcher keeps uploading my entire .git folder...)

**Comment by designgears** [comment]
@ShaharHD That doesn't work for my needs, I switch branches a lot during the day at work depending on what patch I'm working on. I need everything to sync up when the branch changes.

**Comment by liximomo** [comment]
@designgears I up to you what directories to watch. It will get ignored if you don't include it in watcher.

**Comment by ShaharHD** [comment]
@designgears I would suggest then that after every branch change, do a full manual sync and still work with the `"uploadOnSave": true` until someone fixes the watcher to be aware of the ignore list

**Comment by designgears** [comment]
@ShaharHD that doesn't work for my situation.

@liximomo it's a waste of resources to watch a folder you won't be uploading, and prone to crashing depending on the folder size. The ignores need to happen on the watch side not the upload side and filtered. 

Doesn't seem like you're too keen on fixing this, closing this and using a different plugin.

**Comment by liximomo** [comment]
@designgears Yes. It's  a waste of resources. So it doesn't watch anything in the beginning! You don't need to ignore anything. You just select what to watch? Why does it need a ignore option? You don't want to watch it, you just not pick it.

**Comment by designgears** [comment]
@liximomo you're assuming I'm working on some tiny little app. I'm working in an environment with many file formats, hundreds of folders and git branches, I don't have the time to specify each folder and file type for each branch. I do have time to ignore a few specific huge image folders and git directories that are a common problem across all of them.
