### ISSUE TITLE
Feature: Ability to cancel a download

### ISSUE THREAD

**Issue by Chrissteven81** [liximomo/vscode-sftp#114]
## Expected Behavior
[Description of the expected behavior]

## Actual Behavior
[Description of the actual behavior]

## Steps to Reproduce the Problem

  1. Start a long running download

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version: 1.0.4
  - Platform: W10, 1.20.1

**Comment by liximomo** [comment]
Support in v1.7.0.
