### ISSUE TITLE
subsequently change folder path

### ISSUE THREAD

**Issue by herzenA** [liximomo/vscode-sftp#115]
## Expected Behavior
subsequently change the upload path

## Actual Behavior
Is it actually possible to remove a part of the upload path?
Example: /lib/tomcat/webapps/inform/index.js
Remove: /inform/

## Steps to Reproduce the Problem

  1. Change upload folder

## Specifications

  - Version: 1.0.4
  - Platform: Windows

**Comment by liximomo** [comment]
```
{
  "context": "/lib/tomcat/webapps/inform",
  "remotePath":   "/lib/tomcat/webapps",
}
```
