### ISSUE TITLE
Need feature "uploadOnGitChange"

### ISSUE THREAD

**Issue by viT-1** [liximomo/vscode-sftp#118]
## Expected Behavior
When i change the file and save SFTP uploads that file on remote server.
When i revert all changes locally by Git (without Ctrl+S) nothing happens.

## Actual Behavior
When i revert all changes (one or list of files) locally by Git (without Ctrl+S)
SFTP should upload these files to remote server.

## Steps to Reproduce the Problem

  1. Configure SFTP with "uploadOnSave": true
  2. Change content of the file
  3. Revert changes by Git/SVN
  4. Check the file on remote server

## Specifications
  - Version: 1.0.4
  - Platform: VS Code 1.18.0-insider

**Comment by liximomo** [comment]
You should use `watcher` for external change. You can find `watcher` option in README.

**Comment by viT-1** [comment]
I found the most appropriate answer here: https://github.com/liximomo/vscode-sftp/issues/88#issuecomment-359715872
Thanks!
