### ISSUE TITLE
How to configure if the server has two step verification.

### ISSUE THREAD

**Issue by zinechant** [liximomo/vscode-sftp#119]
Thanks for your extension. It's very useful. But I encountered a tricky situation here.

The server I am using has two-step verifications. I would have to enter a message received on my cell phone if I would like to ssh to the server. How to configure the settings in this case? Thanks!

And is there any other work around that could avoid entering the text message received on the phone every time. Some ideas maybe create a tunnel while the first access and let the following SFTP go through the tunnel.

## Specifications

  - Version: sftp:1.0.5    vscode:1.20.1(f88bbf9137d24d36d968ea6b2911786bfe103002)
  - Platform: Ubuntu 16.04  (4.13.0-32-generic #35~16.04.1-Ubuntu SMP x86_64)

**Comment by liximomo** [comment]
Try setting `interactiveAuth ` to `true`.
