### ISSUE TITLE
Always download on open

### ISSUE THREAD

**Issue by sharva** [liximomo/vscode-sftp#127]
**Just a small feature request if its possible.**

When a file opens, it would be good to trigger download from remote. This helps ensure the files are latest. This can be a config option "downloadOnOpen" just like "uploadOnSave"

**Comment by diico** [comment]
+1

**Comment by marekmaurizio** [comment]
+1

**Comment by foosen** [comment]
+1

**Comment by liximomo** [comment]
Implemented in v1.1.4.
