### ISSUE TITLE
Use Active file where "diff" command can not find a target, from command pallete.

### ISSUE THREAD

**Issue by MarekLew** [liximomo/vscode-sftp#128]
At the start I would like to say that you choose `SFTP: diff`` from the list of files works fine.

## Expected Behavior

Show diff to current active file or show prompt to select or accept current file.

## Actual Behavior

If selected `SFTP: diff` from commant palette I see notification:

`The "diff" command can not find a target.`

## Specifications

  - Version: 1.1.0
  - Platform:  windows 10

**Comment by liximomo** [comment]
Fix in v1.1.1.
