### ISSUE TITLE
sftp.config.default not found

### ISSUE THREAD

**Issue by Jack89ita** [liximomo/vscode-sftp#129]
## Expected Behavior
Press F1 -> SFTP: Config -> create a new config file in .vscode folder

## Actual Behavior
Error prompt: Command 'sftp.config.default' not found

## Steps to Reproduce the Problem

  1. Press F1
  2. Select SFTP: Config

### Extension Logs
  Setting sftp.printDebugLog to true do not print anything.
 

## Specifications

  - Version: SFTP 1.1.0
  - Platform: Windows 7

**Comment by liximomo** [comment]
Fix in v1.1.1.

**Comment by Jack89ita** [comment]
Perfect! Thank you!
