### ISSUE TITLE
Message "Upload done" on bottom bar not showing

### ISSUE THREAD

**Issue by stefano-tonanni** [liximomo/vscode-sftp#130]
## Expected Behavior
Message "Upload done" on status bottom bar

## Actual Behavior
Message not showing

## Steps to Reproduce the Problem

  1. Use "upload on save" option
  2. Modify a file
  3. Save file
  4. Upload done but no message shown on bottom bar

### Extension Logs
  no log
 

## Specifications

  - Version: 1.1.0
  - Platform: win7 x64

**Comment by liximomo** [comment]
Fix in v1.1.2.

**Comment by liximomo** [comment]
Fix in v1.1.2
