### ISSUE TITLE
Some questions- External View/access/compare

### ISSUE THREAD

**Issue by thenexus00** [liximomo/vscode-sftp#131]
## Quesitions

1. In the features list you have "Compare a local file with remote file." but I can not see how to view the remote (the server) files and how to compare, I am connected and all good.

2. I checked all views but if possible it would be good to add a tab or option in the Explorer bar to switch between the local and live if not already. It may exist but it depends on the response with 1.

## Specifications

  - Version: Latest
  - Platform: Mac OS

**Comment by liximomo** [comment]
> Compare a local file with remote file.

This means `SFTP: diff` command.
