### ISSUE TITLE
Diff Not Working

### ISSUE THREAD

**Issue by mcarlson64** [liximomo/vscode-sftp#134]
Diff does not work. When I try the diff command on a file, nothing happens. Even if I make a change to the local file, save it without uploading, and try again, nothing happens. I can upload and download files fine, but Diff does not work.

  ### My config
  {
   "protocol": "ftp",
    "host": "23.253.142.20",
    "port": 21,
    "username": "xxx",
    "password": "xxx",
    "remotePath": "www/TLG_PBCE/",
    "uploadOnSave": false
  }

  ### Extension Logs
  [info] run command diff {"$mid":1,"fsPath":"/Library/WebServer/Documents/TLG_PBCE/index.cfm","external":"file:///Library/WebServer/Documents/TLG_PBCE/index.cfm","path":"/Library/WebServer/Documents/TLG_PBCE/index.cfm","scheme":"file"}
[info] disable watcher
 

## Specifications

  - Extension: sftp 1.1.2
  - Version: Visual Studio Code Version 1.21.1
  - Platform: Mac OS 10.10.5

**Comment by mcarlson64** [comment]
Maybe it's server related? It appears to work when the remote files are on a Unix server, but not when they are on a Windows server.

**Comment by liximomo** [comment]
What are the logs after `[info] disable watcher`?

**Comment by mcarlson64** [comment]
There are no logs after that in the cases where it doesn't work. For the sites where it is working, I get the following logs after that:

[info] enable watcher
[info] diff /Library/WebServer/Documents/innovo-wordpress/abcxyz/index.html

**Comment by mcarlson64** [comment]
It looks like this has been fixed in version 1.1.3 as it is working now.
