### ISSUE TITLE
FR: adding support for pagent

### ISSUE THREAD

**Issue by Offerel** [liximomo/vscode-sftp#137]
Hi there,

sine i use do not allow password access to my SSH server, i use pagent on Windows to access my server. Can you please add support for pagent or keybased access also on Windows? I would prefer setup via pagent other a path to the keyfile.

**Comment by Offerel** [comment]
Yes, i know. But the readme says, that i should set `"agent": null`. If i do this, i get `[sftp] All configured authentication methods failed`. However, i could successfully connect via putty and winscp with pagent.

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/37566608-70183050-2af6-11e8-8ea7-bf62fadcd026.png)
![image](https://user-images.githubusercontent.com/9816225/37566611-7b382af8-2af6-11e8-995d-5a5cc2a82c1c.png)

**Comment by Offerel** [comment]
Ok, if i understand this correctly, i should use

```
{
    "protocol": "sftp",
    "host": "192.168.178.33",
    "port": 22,
    "username": "user",
    "uploadOnSave": true,
    "remotePath": "/path/to/folder",
    agent: pageant
}
```
instead of my current code with the quotes:


```
{
    "protocol": "sftp",
    "host": "192.168.178.33",
    "port": 22,
    "username": "user",
    "uploadOnSave": true,
    "remotePath": "/path/to/folder",
    "agent": "pagent"
}
```

**Comment by liximomo** [comment]
```
{
  "agent": "pagent"
}
```

**Comment by Offerel** [comment]
Ahhhh.... now it works... many many thx. I use `"agent": "pageant"`
