### ISSUE TITLE
folder .vscode isn't uploaded

### ISSUE THREAD

**Issue by Offerel** [liximomo/vscode-sftp#138]
## Expected Behavior
if i didn't use the "ignore" setting, all folders should be automatically uploaded.

## Actual Behavior
the folder .vscode and it's files are not uploaded/synced

## Steps to Reproduce the Problem
1. setup the config
2. a folder .vscode is created with at least the file sftp.json
3. save sftp.json
4. the file isn't uploaded to the path

## Requisites (**important to diagnose the problem!**)
config:

```
"protocol": "sftp",
    "host": "192.168.178.2",
    "port": 22,
    "username": "user",
    "password": "password",
    "uploadOnSave": true,
    "remotePath": "/path/to/my/remote/repository"
}
```

## Specifications

  - Version:vcs 1.21.1 / sftp 1.1.2
  - Platform: Windows 10 Home client / OpenSSH Server on Debian 9

**Comment by liximomo** [comment]
Fix in v1.1.3.
