### ISSUE TITLE
Feature proposal: sftp context by git branch

### ISSUE THREAD

**Issue by ursbraem** [liximomo/vscode-sftp#139]
Just a proposal, maybe you like it
 
## Example config
```
[
  {
    "context-git-branch": "master",
    "remotePath": "/remote/public_html",
    (...) 
  },
  {
    "context-git-branch": "dev",
    "remotePath": "/remote/staging", 
    (...) 
  }
]
```

So when switching branches, the sftp context would change as well

**Comment by tazeverywhere** [comment]
+1 !

**Comment by liximomo** [comment]
This could be done by githooks.

**Comment by ursbraem** [comment]
Thanks! I'm now using different config files, like this

```
.vscode/sftp-live.json
.vscode/sftp-dev.json
.vscode/sftp.json
```
And depending on the context I just paste the content of one of the first files into sftp.json. So probably something like `cp .vscode/sftp-{branchname} .vscode/sftp.json`

**Comment by dr1ss** [comment]
I think the context should just be a name to be honest, like jetbrains does on their IDEs.. you put a name to a context with a remote path, then when you want to upload/download, tu select the context based on the name. and in addition to that u can set a default context for autoupload

**Comment by Lynn-cc** [comment]
> Thanks! I'm now using different config files, like this
> 
> ```
> .vscode/sftp-live.json
> .vscode/sftp-dev.json
> .vscode/sftp.json
> ```
> 
> And depending on the context I just paste the content of one of the first files into sftp.json (much more robust than renaming all the time)
> 
> So probably in the post-checkout-hook it would only need something like `cp .vscode/sftp-{branchname} .vscode/sftp.json`

I found that using `Ctrl+Shift+P` to upload project wouldn't know the current `sftp.json` setting, how could I update the config ?

**Comment by ursbraem** [comment]
> I found that when I using Ctrl+Shift+P to upload project, it wouldn't know the current sftp.json setting, how could I update the config ?

I guess that feature isn't available. I still copy & paste the content of the "note" json (e.g. `sftp-dev.json`) to the wired `sftp.json` file when I need to

**Comment by ursbraem** [comment]
Not depending on the git branch, but here's a working example for SFTP with multiple profiles (on mac with pubkey, same server).

```
{
    "name": "multi profile",
    "protocol": "sftp",
    "host": "server.com",
    "port": 123,
    "privateKeyPath": "/Users/mac_username/.ssh/id_rsa",
    "uploadOnSave": true,
    "username": "hosting_username",
    "agent": "$SSH_AUTH_SOCK",
    "passphrase": true,
    "profiles": {
        "dev": {
            "name": "dev",
            "remotePath": "/path/to/dev/"
        },
        "live": {
            "name": "live",
            "remotePath": "/path/to/prod/"
        }
    },
    "defaultProfile": "live"
}

Switch with cmd+Shift+P `SFTP: Change profile`
Control at the bottom of vscode:

![image](https://user-images.githubusercontent.com/1446443/66384704-891e4b00-e9bf-11e9-8236-91c34d66f3dc.png)
