### ISSUE TITLE
SFTP - Authentication via RSA token

### ISSUE THREAD

**Issue by Santhoshkumar-M** [liximomo/vscode-sftp#14]
Hi,

I am using RSA token authentication for my servers, How can I connect using SFTP plugin with asking password every time instead of configuring directly in config.

Regards,
Santhoshkumar Murugesan.

**Comment by liximomo** [comment]
Config Like the one below.
```
{
  host: 'host',
  port: 22,
  username: 'username',
  password: null,
  protocol: 'sftp',
  interactiveAuth: true,
  ...
}
```
And Make sure to set this in /etc/ssh/sshd_config on your server:
```
ChallengeResponseAuthentication yes
```

**Comment by Santhoshkumar-M** [comment]
Thanks mate.. It's working...!!!!!
