### ISSUE TITLE
Can take a notification after uploaded?

### ISSUE THREAD

**Issue by chenwei791129** [liximomo/vscode-sftp#140]
Can take a notification after uploaded?

**Comment by liximomo** [comment]
It has. On the left of your bottom bar. 
![image](https://user-images.githubusercontent.com/9816225/37576693-838da986-2b68-11e8-85a7-f822b7612202.png)

**Comment by chenwei791129** [comment]
oh, thank you
i got it!

**Comment by netizen-ais** [comment]
Comming from atom, I miss the real toast "notifications". I've seen that VS Code has something like those. Edit: settings sync extension does that!
