### ISSUE TITLE
possible to support reading gitignore file as for ignoring file

### ISSUE THREAD

**Issue by chrisduong** [liximomo/vscode-sftp#142]
In the repository, we have a `.gitignore` file, in most cases, we definitely want to ignore the same files in `sftp`.

Do you think we should support this in the configuration as they have the same format.

**Comment by AdsonCicilioti** [comment]
good idea!

**Comment by liximomo** [comment]
Support in v1.2.7.  See https://github.com/liximomo/vscode-sftp/wiki/Config#ignorefile.
