### ISSUE TITLE
need delayed syncing

### ISSUE THREAD

**Issue by qiwihui** [liximomo/vscode-sftp#145]
## Expected Behavior

I make a tar file to the folder to sync to my remote server. When I try to generate the tar file, sftp upload the tmp file, so there will be lots of unneeded file on the remote server. Is is possible to make it sync after detect some file changed.

**Comment by linkjay** [comment]
couldn't you use "ignore" in your config?

```
"ignore": [
    ".vscode",
    ".git",
    ".DS_Store",
    "tmp"
  ]
```

**Comment by qiwihui** [comment]
The unneeded  file name seems to be generated randomly but has the same prefix `zi`. It is ok to use ignore in the config. I wonder what to fill in the config if they are not different totally.

```bash
> ls
zi8kQxww  ziEOi3pX  zigikxV5  ziHz5Brw  zinlLV0e  zinwv6fg  ziYBC0lP
```

**Comment by thetheodoros** [comment]
I am not sure but I guess this has something to do with some issues I have encountered lately. 

When git pulling or changing branch sftp seems to lock files.

**Comment by linkjay** [comment]
globs should be able to help you here

```
"ignore": [
    "zi*"
  ]
```

test: https://i.linkjay.io/iSHqkT.gif

**Comment by cfmatre** [comment]
I'd also like to see some kind of deferred upload. When I build it uploads the same files 20 times while files in my output folder "dist" are updated. If it could have a timeout that gets postponed for each "watch event" it would just upload when the builder is done, or when it for some reason takes a lot of time. A 2 seconds delay would be nice. To have the delay/deferr in settings would be supreme.
