### ISSUE TITLE
need for auto-upload changed / overwritten / copied files

### ISSUE THREAD

**Issue by BenGermany** [liximomo/vscode-sftp#148]
This ext is very great! Happy to have it. It would be great, if it could auto-upload not only files on save, but them to that will be copied / overwritten in the folder. I tried watcher wile using vs code, but this didnt work. Why i need it? I develop in a workspace with two different folders. folder a is my server, folder b my dev workspace. About 100 times and more i build (one) code-file in b and then copy it to a (overwrite old file in a) - and then every time i must right mouse context sftp upload. This would be very nice via a watcher and not only on save, like an option alwaysUploadOnChange for example :)

**Comment by liximomo** [comment]
There must be some problem with you watcher config! Show me you watcher config, I can help you set it up.

**Comment by BenGermany** [comment]
👍 

Yes, you are totally right, now i am knowing while testing watcher my glob was "\*.\*" but the uploaded files has no ending - now, everything works fine, the automatic uploads and their upload-info works great!

But, there is an issue, i havent categorizised because of ignoring... while testing, when i am running an server on port 8080 on my webserver and do an sftp file upload, it is aborted. OK, ignoring this, i killed the server every time cause the new upload is the new server to start (i am new in developing in Go and trying it), so the upload runs fine and then i start the new server and vice versa.

But, now i testet it with the file watcher and the correct glob ("*"), and now, while running the server on port 80 (yes, 80, not 8080), and then save the new build directly in my sftp-upload-dir, the following output appears in VS Code terminal window:

[info] config at d:\server {"protocol":"sftp","host":"xxx.xxx.xxx.xxx","port":22,"username":"xxx","password":"xxx","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"server","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[],"watcher":{"files":"*","autoUpload":true},"concurrency":512,"context":"d:\\server"}
[info] connected
[info] [watcher] upload d:\server\handler
[info] connected
[info] [watcher] upload d:\server\handler
[info] connected
[info] [watcher] upload d:\server\handler
[info] connected
[error] upload d:\server\handler 
 Error: Failure
	at SFTPStream._transform (C:\Users\Ben\.vscode\extensions\liximomo.sftp-1.1.6\node_modules\ssh2-streams\lib\sftp.js:410:27)
	at SFTPStream.Transform._read (_stream_transform.js:167:10)
	at SFTPStream._read (C:\Users\Ben\.vscode\extensions\liximomo.sftp-1.1.6\node_modules\ssh2-streams\lib\sftp.js:181:15)
	at SFTPStream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SFTPStream.Writable.write (_stream_writable.js:241:11)
	at Channel.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Channel.emit (events.js:191:7)

Thats while running an Go-Server on Port 80, but uploading via sftp on Port 22

Any ideas?
