### ISSUE TITLE
show action while uploading

### ISSUE THREAD

**Issue by BenGermany** [liximomo/vscode-sftp#149]
This ext is really cool. I love it! But, i often load files of some MB up to my server and it needs some seconds. While working in vs code, there appears the connected info, then ... ... ... (nothing) ... ... ... and then for only a second "upload done" - bamm. What? Is done? Or not? I cannot watch for it. It would be very nice if this upload-process could be shown... with dots or anything else, the main thing: i know, there is the uploading-process-info or nothing and if not, its always be done. This would be great!

**Comment by liximomo** [comment]
I will optimize it.

**Comment by liximomo** [comment]
Try v1.1.6.

**Comment by BenGermany** [comment]
Great job! Thank you very much 🥇
