### ISSUE TITLE
Question: is is possible to store config in user settings instead?

### ISSUE THREAD

**Issue by mikestp27** [liximomo/vscode-sftp#150]
We like your plugin; thank you.  But we may not be able to continue using it as is unless you help us with this question.
Instead of declaring settings in sftp.json, would it be possible to store them in the user settings file?   
Reasons:
-several users on same project, each user has own "username" to access sftp
-privateKeyPath also not the same for all users (some on Linus, some on MacOS, some on Windows)
-host different in a few cases as some users working on "main" server and some on "test" server

Thank you.

**Comment by franklinyu** [comment]
I guess it makes sense to store some default (like `privateKeyPath`) in user settings, but `remotePath` definitely belongs to project settings.

By the way I don’t think `sftp.json` should be shared between users, or even checked in source control.
