### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by stefanomonteiro** [liximomo/vscode-sftp#151]
## Expected Behavior
Connect to FTP account

## Actual Behavior
Displays the message: "Timed out while waiting for handshake"

## Steps to Reproduce the Problem

  1. Added to sftp.json:
`{
    "protocol": "ftp",
    "host": "www.fv-mag.com",
    "username": "Stefanofv",
    "remotePath": "./"
}`
  2. Right Clicked on a file and selected "SFTP:Diff"
  3. Waited and received the message "Timed out while waiting for handshake"

**Comment by liximomo** [comment]
You can config `connectTimeout` in sftp.json. The default is 10000 (10s). Try to change it to 20000.

**Comment by ShireneJ** [comment]
Hi, can you please explain to how I do the above.  I am having a similar problem having just downloaded the extension and trying to get it up and running but have been unable to connect, receiving that same error message.  So, how do I config connectTimeout in sftp.json?

**Comment by alondonb** [comment]
> You can config `connectTimeout` in sftp.json. The default is 10000 (10s). Try to change it to 20000.

Have tried this up to 50000. Still no luck. Any other ideas? Thank you.

**Comment by pratt1305** [comment]
Hi i also tried uploading from it im getting error

] Error: connect ETIMEDOUT 217.160.233.31:22
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14) 

i increase timeout to 30000s
