### ISSUE TITLE
diff, upload or download not working

### ISSUE THREAD

**Issue by x-wf** [liximomo/vscode-sftp#153]
## Expected Behavior
When I used to right click on a File->Diff, it used to work, not it appears 'file not exist' when it clearly exists;

## Actual Behavior
Since I've restarted my computer (I was not aware if there was any updates to do with vscode or sftp plugin), all functionalities have stopped working with FTP;

## Steps to Reproduce the Problem

  1. Right click on file
  2. Diff
  3."file not exist"

## Requisites (**important to diagnose the problem!**)
The file is located at /www/zendsvr6/htdocs/efsc-deve/<user>/app/theme/js (server-wide)
And locally my file is located at C:\Users\<user>\Documents\GitProject\EFSC\app\theme\js (client-side)

  ### Extension Logs
With  `sftp.printDebugLog` set to true, I retrieved this when I click on 'Diff'
![image](https://user-images.githubusercontent.com/18358292/37897753-deea4110-30de-11e8-8f0c-7fb605c7e46b.png)

## Specifications

  - Version: 1.1.6
  - Platform: Windows 7 Enterprise

**Comment by liximomo** [comment]
@x-wf  I've made a [fix-package](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) .  Please help me test it and post the logs.

**Comment by x-wf** [comment]
@liximomo The logs posted with this issue are with a fix-package referenced in an issue previously opened by someone else, but I took time to test with the latest fix-package you posted, and I have the same result (file not exists)

**Comment by x-wf** [comment]
I've fallen back to 1.0.0 which works perfectly. 
It would be very useful if this problem could be fixed

**Comment by liximomo** [comment]
@x-wf  Please use the latest [fix-package](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) .  I can solve this by analyzing the logs.

**Comment by x-wf** [comment]
Yes, sure!
Here it is:
![image](https://user-images.githubusercontent.com/18358292/37911996-5ac0eb7a-3109-11e8-928f-dc72c2e431f5.png)

**Comment by x-wf** [comment]
It is the directory listing ...
I just hid the directory listing due to security reasons.
If you need it, please tell me here so I can post not-so sensitive information.
