### ISSUE TITLE
[sftp] Illegal argument: pattern error when missing watcher.files option

### ISSUE THREAD

**Issue by spward** [liximomo/vscode-sftp#158]
## Expected Behavior
not sure

## Actual Behavior
gives me an error at the bottom right that says [sftp] Illegal argument: pattern

## Steps to Reproduce the Problem

  1. Load up VS Code

### Extension Logs
I set this up and I dont have output sftp
 

## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
Does this happen right after you install vscode? And what os and version of vscode you have.

**Comment by spward** [comment]
windows 10 and I have the most up to date vscode

**Comment by spward** [comment]
I'm new to vscode sorry

**Comment by liximomo** [comment]
Does this happen right after you install sftp? Have you done something with vscode-sftp?

**Comment by spward** [comment]
it happens as soon as i install sftp. it didnt start doing this until I tried connecting my sftp to it not everytime I install it does it.

**Comment by liximomo** [comment]
So you have a sftp.json cofing? Can you post your config here？

**Comment by spward** [comment]
{
		"name": "ccuresearch.coastal.edu",
		"host": "ccuresearch.coastal.edu",
		"port": 8822,
		"protocol": "sftp",
		"username": "username",
		"password": "password",
		"remotePath": "/var/students/spward/csci409sp18",
		"uploadOnSave": true,
        "watcher": {
            "autoUpload": true,
            "autoDelete": false
		}
}

**Comment by liximomo** [comment]
You are missing `files` option in ` watcher`! You can delete the whole `watcher` section or add the `files` option.
