### ISSUE TITLE
Files edited externally are uploaded with 'watcher["files"]' set to false, if 'uploadOnSave' is set to true

### ISSUE THREAD

**Issue by duanehutchins** [liximomo/vscode-sftp#16]
Issue: 

If `uploadOnSave` is `true`, then files saved externally will upload, even if `watcher["files"]` is `false`.

Relevant Settings: 
```
{
    ...
    "uploadOnSave": true,
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    }
}
```

Steps to duplicate:
- [ ] Create a new file `myfile.txt`
- [ ] Set `uploadOnSave` to `true` 
- [ ] Set `watcher["files"]` to `false`
- [ ] Change `myfile.txt` with Notepad (or any external program) and save.
- [ ] Note that `myfile.txt` is uploaded to the server, even though `watcher["files"]` is `false`.

What should happen:
* When `watcher["files"]` is `false`, files changed externally should not upload, even when `uploadOnSave` is `true`.

Please fix this. It is very annoying. It causes my local `.git/` files to upload to the server.

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/28488946-bab03ccc-6ee8-11e7-804f-f69ee2594bc4.png)
The external changes only contain create and delete.It's the behavior of vscode watcher.
I will describe it more accurately in RAEDME.

**Comment by duanehutchins** [comment]
How can I disable auto-uploading external edited files?

What's happening is I check out a new branch in git, and the entire .git/ folder is uploaded to the sftp server.

**Comment by liximomo** [comment]
Q: How can I disable auto-uploading external edited files?
A: Close vscode editor.

Why wouldn't you ignore `.git` folder?

```
// .sftpConfig
 ignore: [
   "**/.git",
  ],
```

**Comment by duanehutchins** [comment]
Heh. I know I can disable it by closing the editor. I could also set uploadOnSave to false before checking out a new git branch.

I guess I should have said, how can I do it without closing the editor or disabling uploadOnSave?  The .git folder is only one issue with checking out a git branch.  Sftp uploads all of the files in the branch that changed. Sometimes, I don't want that to happen. If I want to sync the entire folder, I can sync it.  I like uploadOnSave because it only syncs the file I save.

A similar extension, [ftp-sync](https://github.com/lukasz-wronski/vscode-ftp-sync), only uploads changed files when saved in the vscode editor (not from external sources).

There's an issue with ignoring "**/.git/**" that I'll mention in #15, but in the cases of other files/folders. I don't want to ignore them completely. I only want them synced when saved inside vscode or I explicitly sync the project.

**Comment by liximomo** [comment]
> A similar extension, ftp-sync, only uploads changed files when saved in the vscode editor (not from external sources).
That's the reason why I write another one. I think that be aware of external change it's a power, not a limitation. I will consider adding a config to change this behavior.

**Comment by liximomo** [comment]
@duanehutchins Now it works the way you like.
