### ISSUE TITLE
Error : Directoryname not valid

### ISSUE THREAD

**Issue by LucasBrd** [liximomo/vscode-sftp#160]
## Expected Behavior
Files are uploaded when we do a manual upload or upload a file at the root of the working directory on auto upload on save.

## Actual Behavior

Uploading with ⬆+ ctrl + P or uploading a file at the root of the working directory gives this error : 

`[sftp] Directoryname not valid`

Came from issue #146 
I removed and reinstalled the package 2 days ago, nothing changes, and if I get this error no files at all are uploaded with manual upload.

The FTP server is FileZilla on a Windows Server 2016 Vultr VM

## Steps to Reproduce the Problem

  1. Setup SFTP with `remotePath : "/"`
  1. Upload with ⬆+ ctrl + P => SFTP> Upload or upload a file located at the root of the working directory with right click + SFTP: Upload

### Extension Logs

```
[debug] run command upload
[debug] < 220-FileZilla Server 0.9.60 beta\r\n220-written by Tim Kosse (tim.kosse@filezilla-project.org)\r\n220 Please visit https://filezilla-project.org/
[debug] > USER dev
[debug] < 331 Password required for dev
[debug] > PASS ******
[debug] < 230 Logged on
[debug] > FEAT
[debug] < 211-Features:\r\n MDTM\r\n REST STREAM\r\n SIZE\r\n MLST type*;size*;modify*;\r\n MLSD\r\n UTF8\r\n CLNT\r\n MFMT\r\n EPSV\r\n EPRT\r\n211 End
[debug] > TYPE I
[debug] < 200 Type set to I
[info] upload /Users/macbookpro/Dropbox/Company/Sous-traitance/Company/code
[debug] > PASV
[debug] < 227 Entering Passive Mode (XX,XX,XX,XX,195,110)
[debug] > LIST /
[debug] < 150 Opening data channel for directory listing of "/"
[debug] < 226 Successfully transferred "/"
[debug] > MKD /
[debug] < 550 Directoryname not valid
[error]: Error: Directoryname not valid
	at makeError (/Users/macbookpro/.vscode/extensions/liximomo.sftp-1.1.7/node_modules/ftp/lib/connection.js:1067:13)
	at Parser.<anonymous> (/Users/macbookpro/.vscode/extensions/liximomo.sftp-1.1.7/node_modules/ftp/lib/connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (/Users/macbookpro/.vscode/extensions/liximomo.sftp-1.1.7/node_modules/ftp/lib/parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (/Users/macbookpro/.vscode/extensions/liximomo.sftp-1.1.7/node_modules/ftp/lib/connection.js:273:20)
	at emitOne (events.js:96:13)
```
### FileZilla FTP server log

```
(000067)4/2/2018 12:21:45 PM - dev (XX.XX.XX.XX)> PASV
(000067)4/2/2018 12:21:45 PM - dev (XX.XX.XX.XX)> 227 Entering Passive Mode (XX.XX.XX.XX.XX)
(000067)4/2/2018 12:21:45 PM - dev (XX.XX.XX.XX)> LIST /
(000067)4/2/2018 12:21:45 PM - dev (XX.XX.XX.XX)> 150 Opening data channel for directory listing of "/"
(000067)4/2/2018 12:21:45 PM - dev (XX.XX.XX.XX)> 226 Successfully transferred "/"
(000067)4/2/2018 12:21:45 PM - dev (XX.XX.XX.XX)> MKD /
(000067)4/2/2018 12:21:45 PM - dev (XX.XX.XX.XX)> 550 Directoryname not valid
```

## Specifications

  - Version: 1.1.7
  - Platform: High Sierra 10.13.3
  - VScode version : 1.18.1
  - FileZilla FTP Server : 0.9.60 beta

**Comment by liximomo** [comment]
What's you config?

**Comment by liximomo** [comment]
@pi-vincent What's your config?

**Comment by liximomo** [comment]
@LucasBrd  @pi-vincent I've made a [fix](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge). Please help me test it.

**Comment by pi-vincent** [comment]
It works great, bravo!
I haven't seen any side effect so far. I'll tell you if any new problem occure.
Thanks, Vincent.

**Comment by liximomo** [comment]
Ok! I will make an update soon.

**Comment by invtlabs** [comment]
@liximomo  Hi, I got same problem where i can find update ?
