### ISSUE TITLE
support for GSSAPI ?

### ISSUE THREAD

**Issue by jmarandet** [liximomo/vscode-sftp#162]
Hi,
this is not an issue but just a question ; is it possible to use GSSAPI authentication mode ?
It is an SSH option that leverages Kerberos.
I am not pretty sure but it seems that it can be enabled with the -o SSH option flags GSSAPIAuthentication and GSSAPIDelegateCredentials set to yes.

**Comment by liximomo** [comment]
It's not possible. 😔

**Comment by jmarandet** [comment]
Too bad... So it became useless.
I eventualy build a simple sync solution in half a day... 
do not try to re-invent the wheel if you want to make it squarred

**Comment by liximomo** [comment]
Glab to know that you have a solution. 👍
