### ISSUE TITLE
Exclude Folders

### ISSUE THREAD

**Issue by spward** [liximomo/vscode-sftp#163]
## Expected Behavior
Not include the .vscode files to the server
## Actual Behavior
files with sftp info is uploaded

## Steps to Reproduce the Problem

  1. Upload files

### Extension Logs
I was wondering if there was a way to exclude the .vscode folder because I feel like that is a very big breach issue. Everytime I try to upload it adds the .vscode folder and I was wondering if there was an easy way to stop it from uploading them.

Thanks
 

## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
See `ignore` option in [here](https://github.com/liximomo/vscode-sftp/wiki/Config).

**Comment by OpenWaygate** [comment]
After I add `ignore: ['~/.vscode']`, there remains a `.vscode` folder appears in `SFTP:EXPLORER`
![image](https://user-images.githubusercontent.com/27287694/61169920-130f7100-a595-11e9-8a0d-a99662c3ecf8.png)

How to make it disappear in `SFTP:EXPLORER` ?
