### ISSUE TITLE
Will not Sync at all if one server is offline in multiple server configuration

### ISSUE THREAD

**Issue by mrunc** [liximomo/vscode-sftp#165]
## Expected Behavior
If I have configured two servers to sync to and one server goes offline It should still sync to the online server

## Actual Behavior
I get "[sftp] Timed out while waiting for handshake" error and it doesn't sync to the online server
Also Note that the always online server is first in list

## Steps to Reproduce the Problem

        [
          {
              "protocol": "sftp",
              "host": "online.server.com",
              "username": "admin",
              "privateKeyPath": "xxxxxxxxxxx_id_rsa",
              "remotePath": "xxxxxxxxx",
              "uploadOnSave": true,
              "syncMode": "full",
              "ignore": ["\\.sublime-(project|workspace)", "sftp-config(-alt\\d?)?\\.json",
              "sftp-settings\\.json", "/venv/", "\\.svn/", "\\.hg/", "\\.git/", "\\.vscode", "*.code-workspace",
              "\\.bzr", "_darcs", "CVS", "\\.DS_Store", "Thumbs\\.db", "desktop\\.ini",
              "vendor", "\\.stfolder", "\\.idea", "\\.stignore", "\\.stglobalignore",
              "cache","composer\\.(phar|lock|json)", "\\.o", "\\.ko", "\\.obj", "\\.elf",
              "\\.ilk", "\\.map", "\\.exp", "\\.gch/", "\\.pch", "libs"
              ]
          },
          {
              "protocol": "sftp",
              "host": "offline.server.com",
              "username": "admin",
              "privateKeyPath": "xxxxxxx_id_rsa",
              "remotePath": "xxxxxxxxx",
              "uploadOnSave": true,
              "syncMode": "full",
              "ignore": ["\\.sublime-(project|workspace)", "sftp-config(-alt\\d?)?\\.json",
              "sftp-settings\\.json", "/venv/", "\\.svn/", "\\.hg/", "\\.git/", "\\.vscode", "*.code-workspace",
              "\\.bzr", "_darcs", "CVS", "\\.DS_Store", "Thumbs\\.db", "desktop\\.ini",
              "vendor", "\\.stfolder", "\\.idea", "\\.stignore", "\\.stglobalignore",
              "cache","composer\\.(phar|lock|json)", "\\.o", "\\.ko", "\\.obj", "\\.elf",
              "\\.ilk", "\\.map", "\\.exp", "\\.gch/", "\\.pch", "libs"
              ]
          }
      ]
 

## Specifications

  - Version: VSCode 1.22.1 - SFTP 1.1.7
  - Platform: macOS High Sierra 10.13.4

**Comment by mrunc** [comment]
Oh OK I got it now but it would really be helpful to sync the whole workspace/project to multiple machines

**Comment by liximomo** [comment]
It's already on my todo list.
