### ISSUE TITLE
Could add ignore file path or folder not sync ? 

### ISSUE THREAD

**Issue by jizhu** [liximomo/vscode-sftp#167]
## Expected Behavior
[Description of the expected behavior]

## Actual Behavior
[Description of the actual behavior]

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version:1.1.7
  - Platform:  macos 10.12.3 vscode 1.17.2

**Comment by ohadcn** [comment]
just add to your sftp.json file:

```
"ignore": [
".vscode",
".git",
".DS_Store",
"config.json",
 ...
]
```
