### ISSUE TITLE
Disable File Permission Sync

### ISSUE THREAD

**Issue by James9074** [liximomo/vscode-sftp#17]
## Expected Behavior
The ability to upload a file without it's permissions

## Actual Behavior
Files upload with permission sets. I'm working in a locked down 644-only environment, but keep having to `chmod +x` shell scripts on the server after upload. It would be useful to include an option to disable this, perhaps `"transferFilePermissions": false`

## Steps to Reproduce the Problem

  1. Download a file with executable permissions (755) from a server via sftp
  2. Change it's permissions to 644, upload it back with sftp
  3. Check the file permissions on the server.

  - Version: .7.7
  - Platform: Windows

**Comment by liximomo** [comment]
When you sync a.txt to remote b.txt. The b.txt may not exist yet. And you can not get the permission of b.txt. There is a lot of work to keep permissions of the target file.  This will slow down the speed of synchronization. I really need consider this.

**Comment by James9074** [comment]
Absolutely, I noticed this plugin is 50x faster than most of the other sftp plugins, very likely due to that. We'd have to do some polling of the remote file and re-set the permissions after each upload if the file did exist.

If I opened a PR with the changes (as an optional flag) would you consider it, or should I hold off?

**Comment by liximomo** [comment]
One thing is important to the speed is that all IO is paralleled and asynchronous. In fact, there is no permissions preservation. Every file is created with a default mode '0666'.  So probably the option should be named `preserveFilePermissions` with values of `origin` or `target` or  `none`.  `origin` would be the local file when upload and the remote file when download.

PR is very welcome.

**Comment by mickelj** [comment]
I will second @James9074. I am working with a host that requires 644 on PHP files, but changes always upload as 666.

**Comment by JustDevZero** [comment]
My behaviour is similar but oposite.

In my case I have some files in local with 755.
In remote they are also 755.

But sudenly, when it's uploading they became all 644.

I guess it has something to deal with the umask, but I can't modify it.

:(

**Comment by liximomo** [comment]
@JustDevZero  The default mode is 666. It is the umask result in 644.

**Comment by AhmedDaou** [comment]
cool plugin , the only issue I have is the file permission uploaded with the default permission

**Comment by levinit** [comment]
remote dir and local dir umask both are 0022.but it will change my file's permission to 666

**Comment by skunchamwar** [comment]
can we make upload to remote with permissions preserved?

**Comment by liximomo** [comment]
Now `sftp` will preserve permissions of origin files?

**Comment by heliomoreira** [comment]
Hi liximomo,

When I edit a file locally, the permission on remote server changed to 666 in that file.

This causes 500 Error because remove execution permission.

I have the Visual Studio Code 1.18.1.

Thanks
