### ISSUE TITLE
Confirm Download

### ISSUE THREAD

**Issue by dmonteirosouza** [liximomo/vscode-sftp#171]
## Expected Behavior
Is it possible to add a download confirmation when I open a file?
Also a confirmation if the server file is different.
## Actual Behavior
"downloadOnOpen": true,
"downloadConfirm": true,
## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
You can set "downloadOnOpen" to 'confirm' in v1.1.9.
