### ISSUE TITLE
Timeout while connecting to server

### ISSUE THREAD

**Issue by web-vitality** [liximomo/vscode-sftp#172]
https://github.com/liximomo/vscode-sftp/issues/135

Hi, still does not connect. I set the time at 20.40 and 60 seconds. I can not figure out what I'm doing wrong.

[error]: Error: Timeout while connecting to server
    at Timeout.setTimeout (C:\Users\Vitaliy\.vscode\extensions\liximomo.sftp-1.1.7\out\src\model\Client\FTPClient.js:31:28)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by liximomo** [comment]
I believe that is a problem of your network or FTP server.

**Comment by web-vitality** [comment]
I tried to connect at home and at work and to various FTP servers. so for me it struck strange that it does not work. Maybe I'm not filling the configuration file correctly or missing some parameters that need to be filled in and I do not do it?

**Comment by afxgroup** [comment]
Same here. And of course with filezilla all works correctly. I've also tried to remove the secure but same issue

**Comment by liximomo** [comment]
@afxgroup @web-vitality Try the [debug-package](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) and give me the **full** logs.

**Comment by craiglintott** [comment]
I experienced the same problem when using Microsoft's ftp service. When i use FileZilla server, it works perfectly.

**Comment by afxgroup** [comment]
where does it save the log file?

**Comment by afxgroup** [comment]
[debug] run command sync to local
[debug] ftpclient timeout
[error]: Error: Timeout while connecting to server
	at Timeout.setTimeout [as _onTimeout] (C:\Users\andre\.vscode\extensions\liximomo.sftp-1.1.7\out\src\model\Client\FTPClient.js:34:28)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
[debug] ftpclient disconnected
[debug] ftpclient disconnected
[debug] ftpclient disconnected

Nothing else

**Comment by web-vitality** [comment]
[debug] [connection] < 'SSH-2.0-OpenSSH_5.3\r\n'
[debug] ftpclient timeout
[error]: Error: Timeout while connecting to server
    at Timeout.setTimeout (C:\Users\Vitaliy\.vscode\extensions\liximomo.sftp-1.1.7\out\src\model\Client\FTPClient.js:34:28)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[debug] ftpclient disconnected
[debug] ftpclient disconnected

**Comment by BI7PRK** [comment]
```LOG
[debug] run command upload {"$mid":1,"fsPath":"d:\\phpweb\\webroot\\default\\app\\controllers\\AuthController.php","external":"file:///d%3A/phpweb/webroot/default/app/controllers/AuthController.php","path":"/d:/phpweb/webroot/default/app/controllers/AuthController.php","scheme":"file"}
[{"$mid":1,"fsPath":"d:\\phpweb\\webroot\\default\\app\\controllers\\AuthController.php","external":"file:///d%3A/phpweb/webroot/default/app/controllers/AuthController.php","path":"/d:/phpweb/webroot/default/app/controllers/AuthController.php","scheme":"file"}]
[debug] < SSH-2.0-OpenSSH_7.4
[error]: Error: Timeout while connecting to server
	at Timeout.setTimeout [as _onTimeout] (C:\Users\BI7PRK\.vscode\extensions\liximomo.sftp-1.1.7\out\src\model\Client\FTPClient.js:31:28)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by elax102** [comment]
I'm also getting this issue. I can't sync with remote. I get a "Timeout while connecting to server" error. I'm able to connect with Filezilla and another ftp plugin (ftp-sync). I'm guessing its something to do with the config but I don't know what it could be.

`[info] config at /Users/alex/Documents/Primax/MPL/MPL-FTP {"name":null,"protocol":"ftp","host":"...","port":22,"username":"...","password":"...","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":true,"remotePath":"/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/Users/alex/Documents/Primax/MPL/MPL-FTP"}
[debug] run command sync to remote
[debug] ftpclient timeout
[debug] ftpclient disconnected
[error]: Error: Timeout while connecting to server
	at Timeout.setTimeout [as _onTimeout] (/Users/alex/.vscode/extensions/liximomo.sftp-1.1.7/out/src/model/Client/FTPClient.js:34:28)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
[debug] ftpclient disconnected
[debug] ftpclient disconnected`

**Comment by liximomo** [comment]
The default port is 22 no matter what `protocol` you set. I guess you should config it to 21 when using `ftp`.

**Comment by liximomo** [comment]
The default port is 22 no matter what `protocol` you set. I guess you should config it to 21 when using `ftp`.

**Comment by elax102** [comment]
@liximomo thanks, that fixed the issue. Things seems to be working now.

```{
    "protocol": "ftp",
    "host": "...",
    "username": "...",
    "password": "...",
    "remotePath": "...",
    "port": 21,
    "uploadOnSave": true,
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": false
    }
}

**Comment by BI7PRK** [comment]
haha...  i made a mistake -->> port:22

**Comment by web-vitality** [comment]
xaxaxaxa... I also put port 21 and the file was loaded without problems. I hope it will be like this :)

**Comment by emkayy** [comment]
Maybe you could include a switch for the default of port depending on the "protocol" setting?

**Comment by 2pay** [comment]
the same error, 

```
{
    "protocol": "ftp",
    "host": "mydomain.com",
    "port": 21,
    "username": "myusername",
    "password": "mypassword",
    "secure": true,
    "remotePath": "/"
}
```

i am use other ftpclient working.

**Comment by shengbinxu** [comment]
![image](https://user-images.githubusercontent.com/3232275/48886526-41560a00-ee67-11e8-8542-e974ef6ac000.png)
同样的问题，我用的是ubuntu下的vsftp server， 使用filezilla可以连接，这里却报超时。
![image](https://user-images.githubusercontent.com/3232275/48886576-719da880-ee67-11e8-8c2d-b2c5c33ecddf.png)

**Comment by liximomo** [comment]
@shengbinxu 请单独新开个 issue.

**Comment by shengbinxu** [comment]
@liximomo 已开

**Comment by emmy-omega** [comment]
Adding
"remoteTimeOffsetInHours": -3
to the config worked for me

**Comment by vqthang** [comment]
If your server is so far, the connection maybe timeout, so you should increase the connectTimeout:
“connectTimeout”:(how long in milliseconds to wait for the connection)

**Comment by macarole** [comment]
> The default port is 22 no matter what `protocol` you set. I guess you should config it to 21 when using `ftp`.

thank you, it works for me

**Comment by guleriagishere** [comment]
how to increase sftp timeout in extension.

I am using bastion server for sftp so it take time to connect to private server and thus timeout errors.

**Comment by moamen-ui** [comment]
@guleriagishere add `"connectTimeout": 10000` to the object, and change 10000 with your value.
```
   "name": "My Server",
    "host": "0.0.0.0",
    "protocol": "sftp",
    "port": 22,
    "username": "username",
    "remotePath": "/",
    "connectTimeout": 200000,
    "uploadOnSave": true
```

**Comment by anibabbar** [comment]
> 
> 
> The default port is 22 no matter what `protocol` you set. I guess you should config it to 21 when using `ftp`.

thanks!!

**Comment by tommycloud** [comment]
In my case change the port to 22 then back to 21 solve the isssue.
