### ISSUE TITLE
AutoDelete option does not work 

### ISSUE THREAD

**Issue by franzarmas** [liximomo/vscode-sftp#174]
Hello, the extension is great but I have detected a fault .. it happens that the autoDelete option does not work .. when I create a file from VS if it synchronizes correctly and I create it on the server .. but when I delete that file using the graphic interface of VS .. in the SFTP records it appears that it was supposedly deleted .. but in reality the server did not get deleted ..

This is my SFTP configuration: http://prntscr.com/j2e9x9

**Comment by liximomo** [comment]
Set option `sftp.printDebugLog` to `true` in your preference, then reload vscode, reproduce the problem, get the logs from `view -> output-> sftp`.

**Comment by franzarmas** [comment]
Again when I create the file if I create it on the server .. but when I delete it by right clicking and Delete from the VSCode interface the file is deleted from VSCode but not from the Server...

![descarga](https://user-images.githubusercontent.com/36080351/38962324-53008e6e-4332-11e8-959b-ae89cc7440a7.png)

**Comment by tilonorrinco** [comment]
Also have the problem. My config is the same
http://prntscr.com/j7qdl7

**Comment by pinyht** [comment]
same problem

**Comment by L1aoXingyu** [comment]
same problem

**Comment by mattwood1** [comment]
same problem

**Comment by kordianslowacki** [comment]
same problem

**Comment by liximomo** [comment]
Fix in v1.1.10.

**Comment by mattwood1** [comment]
Anyone else having an issue getting this update? I seem to be stuck on 1.1.9, I'm now two versions behind. I've also removed and reinstalled the extension. Is there anything else I could try?

**Comment by mattwood1** [comment]
I thought I'd update as I needed to update VS Code itself to get the update. Thanks all.

**Comment by CWrecker** [comment]
not fixed
, when i delete files locally, the do not reflect the changes on the server

**Comment by stephenstack** [comment]
same issue, unable to resolve. Hope it could be fixed soon

**Comment by liximomo** [comment]
@stephenstack File a new issue.
