### ISSUE TITLE
Ability to cancel a upload

### ISSUE THREAD

**Issue by heminei** [liximomo/vscode-sftp#175]
I can't cancel upload process. Can you create a command like "Stop current upload"?

**Comment by liximomo** [comment]
What does "Stop current upload"?

If I am uploading a single file. What does it do?
If  I am uploading multiple files. What does it do?

**Comment by robertopc** [comment]
Stop all transfers.

**Comment by liximomo** [comment]
@robertopc If I call a stop in the middle of upload when uploading a single file. What to do with the part that has been sent.

**Comment by robertopc** [comment]
Stop after upload a file for no corruption. 
Or save a copy of the original file and resend the original in background.

**Comment by liximomo** [comment]
Duplicate of #114 .

**Comment by ShuangjunLiu** [comment]
I have uploaded a very large file that I want to cancel. 
I call the command SFTP: cancel all transfer.  
Yet the transfer still stuck in progress. 

Can you help? 
![image](https://user-images.githubusercontent.com/19880963/49973634-e2cef980-ff03-11e8-94f8-2da8c6f57534.png)
