### ISSUE TITLE
Possible to upload current file with keyboard shortcut?

### ISSUE THREAD

**Issue by richardwo** [liximomo/vscode-sftp#176]
Is it possible to upload the current file via a keyboard shortcut.

I can upload an individual file with the context menu and selecting 'SFTP: Upload', so this is what I want to trigger with a keystroke.
Using the command palette the 'SFTP: Upload' option uploads the whole folder.

Thanks.

**Comment by liximomo** [comment]
preference -> keyboard shortcuts

**Comment by richardwo** [comment]
the SFTP:Upload command listed in keyboard shortcuts uploads the whole folder, I just want to upload the single file I'm working on.

**Comment by liximomo** [comment]
Keep the focus on the file you are working with while using keyboard shortcuts.

**Comment by richardwo** [comment]
Thanks - that works. One more thing, I want to use a macro so I can save the file then upload with a single keyboard shortcut.
I have tried command "sftp.trans.remote" in the macro but this tries to upload the folder, any suggestions?

**Comment by richardwo** [comment]
I'm using https://marketplace.visualstudio.com/items?itemName=geddski.macros do to the macros.

**Comment by richardwo** [comment]
Can't find a way to give the file focus when using a macro so closing.
