### ISSUE TITLE
Ability to select server when executing commands.

### ISSUE THREAD

**Issue by ozanorhan** [liximomo/vscode-sftp#177]
Is it possible to select between different configurations when using upload or diff commands. I have two configurations one for local test server and other for production. When i want to diff it only diffs the last config in the sftp.json array. 
I know 'context' exist but it doesn't help me since the code base is same across the servers.

**Comment by liximomo** [comment]
The anwser is in [README](https://github.com/liximomo/vscode-sftp#profiles).
