### ISSUE TITLE
Allow array of key paths for privateKeyPath config

### ISSUE THREAD

**Issue by kiwdahc** [liximomo/vscode-sftp#179]
Would it be possible to add the ability to pass an array of key paths to the "privateKeyPath" config option? This is because at my work we keep a copy of our sites and would like to have this hidden .sftp file kept as a copy with the path to multiple users key in the config.

If this isn't possible would it be possible to set up multiple configs based on some sort of parameter? Possibly a file search boolean etc?

**Comment by liximomo** [comment]
Maybe you could use a relative path for privateKeyPath like '~/.ssh/id_rsa'.
