### ISSUE TITLE
Problem with multiple connections

### ISSUE THREAD

**Issue by heminei** [liximomo/vscode-sftp#180]
## Actual Behavior
I have two connection. One with uploadOnSave: true, second with uploadOnSave: false. When I save the file is not upload automatically. Also when I click upload manually, the file is uploaded with last connection aways.

## Steps to Reproduce the Problem

```js
[
    {
        "protocol": "sftp",
        "host": "test",
        "username": "test",
        "password": "test",
        "remotePath": "/home/www",
        "uploadOnSave": true,
        "syncMode": "full",
        "ignore": [
            ".vscode",
            ".git"
        ],
        "watcher": {
            "files": "{**/*.css,**/*.css.map}",
            "autoUpload": true,
            "autoDelete": true
        }
    },
    {
        "protocol": "ftp",
        "port": 21,
        "host": "test",
        "username": "test",
        "password": "test",
        "remotePath": "/public_html",
        "uploadOnSave": false,
        "syncMode": "full",
        "ignore": [
            ".vscode",
            ".git"
        ]
    }
]
```

## Specifications

  - Version: 1.1.7
  - Platform: Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by liximomo** [comment]
The array config only works with different `context` setting.
