### ISSUE TITLE
Permissions change on upload

### ISSUE THREAD

**Issue by TheWebDuck** [liximomo/vscode-sftp#181]
## Expected Behavior
[Description of the expected behavior]

When I upload a file using sftp the file that has been uploaded should keep the same permissions as the local it was uploaded from

## Actual Behavior
[Description of the actual behavior]

Local file is permissions 644
Upload file to remote
Remote file is 655

When using a standard stand alone sftp program the permissions stay the same.

## Steps to Reproduce the Problem

  1. right click on file
  1. choose upload
  1. file is uploaded but permissions have been changed by sftp program

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version:
  - Platform:

**Comment by chzhuo** [comment]
I have the same problem.
When i use `sftp` command to upload executable files, it didn't lose executable permission. but using vscode-sftp it will lose.

**Comment by MarekLew** [comment]
No. Remote permisin must by remote. Try upload from Windows to linux and then have tomatos when locale permision change remote.

**Comment by xornet-sl** [comment]
> No. Remote permisin must by remote. Try upload from Windows to linux and then have tomatos when locale permision change remote.

Ok. Then it must be configurable behaviour. It is bad idea when you want to support only one and broken system (windows). In any other OS permissions must be preserved. It is unexpected behaviour when I write executable bash script and on remote system this file becomes non-executable ony because of existence of one broken OS in the world which I don't use at all.

**Comment by pakLebah** [comment]
I can confirm this issue. The permission changed by the extension because `scp` command respects remote file permission setting.

Please fix this. Thank you.
