### ISSUE TITLE
How to config sftp.json file that I can connect to a remote server via PrivateKey? any examples?

### ISSUE THREAD

**Issue by marchboy** [liximomo/vscode-sftp#184]
## Specifications

  - Version: 1.22.2
  - Platform: Windows x64

**Comment by caboosesw** [comment]
I'll tack onto this ... here is what I am trying based on my working config in Sublime Text ...

{
    "protocol": "sftp",
    "host": "x.x.x.x",
    "username": "bob",
    "remotePath": "./proja/",
    "privateKeyPath": "C:/Users/USER/Dropbox/Software/thekey.pem"
}

... it parses fine but when I try to initiate a download or sync I get a "[sftp] no such file."  I am not sure if it is referring to the privateKeyPath (I changed the string and got a different error so I assume no) or to something else.

**Comment by serdarsen** [comment]
I've removed the dot in the remodePath ("./var/www/html/mywebsite") and it's working now :

```
{
    "protocol": "sftp",
    "host": "xxx.xxx.xx.xx",
    "username": "myserverusername",
    "remotePath": "/var/www/html/mywebsite",
    "privateKeyPath": "/home/mylocalusername/.ssh/id_rsa"
}
```

**Comment by marchboy** [comment]
yes, it works. thank you for your reply.@caboosesw @serdarsen

**Comment by serdarsen** [comment]
You are welcome

**Comment by aroraayush** [comment]
I need help. trying to connect with the extension. I guess the readme should have some better examples of connecting to the server. 
I am on Windows 10. I installed the extension. It created a ftp-sync.json. I added my config to it with many PnCs. My last try had the following config:
```
{
    "remotePath": "/var/www/html/folderName",
    "host": "***.***.***.***",
    "username": "userName",
    "port": 21,
    "secure": false,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": "C:\\Users\\********\\id_rsa.pem",
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": false,
        "extensionsToInclude": [],
        "path": ""
    }
}
```
Later, I tried creating a "sftp.json" in .vscode folder with the following config
```
{
    "protocol": "sftp",
    "host": "***.***.***.***",
    "username": "userName",
    "remotePath": "/var/www/html/folderName",
    "privateKeyPath": "C:\\Users\\********\\id_rsa.pem",
    "uploadOnSave": true,
    "watcher": {
        "files": "**/*",
        "autoUpload": false,
        "autoDelete": true
    }
}
```
But, either of the way, I am unable to connect to server :-\
Before closing this issue, please help

**Comment by liximomo** [comment]
Delete sftp.json and using `sftp: config` command to create a config file.

**Comment by aroraayush** [comment]
@marchboy Port number was 22. Other than that it worked. 

Thanks a lot !!!

**Comment by aroraayush** [comment]
@liximomo Thank to you as well

**Comment by beto-aveiga** [comment]
> I'll tack onto this ... here is what I am trying based on my working config in Sublime Text ...
> 
> {
> "protocol": "sftp",
> "host": "x.x.x.x",
> "username": "bob",
> "remotePath": "./proja/",
> "privateKeyPath": "C:/Users/USER/Dropbox/Software/thekey.pem"
> }
> 
> ... it parses fine but when I try to initiate a download or sync I get a "[sftp] no such file." I am not sure if it is referring to the privateKeyPath (I changed the string and got a different error so I assume no) or to something else.

When the **privateKeyPath** is wrong you will get this message:
`NOENT: no such file or directory, open '/the-path/to-your/private-key`

`No such file` is when, for some reason, the sftp can't get into the remote path directly, of course the error is not self explanatory.

In my case, I was setting an absolute path and it wasn't working, then I tried a relative path (considering the directory of an ssh session) and it worked. I'm not sure why but maybe it can help somebody.
