### ISSUE TITLE
 Timeout while connecting to server

### ISSUE THREAD

**Issue by jcleng** [liximomo/vscode-sftp#185]
## Expected Behavior
[Description of the expected behavior]
 Timeout while connecting to server for wdcp ftp maybe ftp passive mode .
使用的wdcp开的服务器,但是不清楚是不是开启了主动或者被动模式,我们没有服务器的权限,排错的时候连接我们自己的ftp是能成功连接的.
## Actual Behavior
[Description of the actual behavior]
Timeout 
## Steps to Reproduce the Problem

  1.config:
{
    "protocol": "ftp",
    "host": "39.xx.xx.12",
    "username": "lxxxxxxx1m",
    "password": "ljcxxxxxxxxom",
    "remotePath": "/public_html/",
    "port": 22,
    "connectTimeout": 3600
}

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 [debug] run command (list) download
[debug] < SSH-2.0-OpenSSH_5.3
[error]: Error: Timeout while connecting to server
	at Timeout.setTimeout [as _onTimeout] (C:\Users\冷晶川\.vscode\extensions\liximomo.sftp-1.1.7\out\src\model\Client\FTPClient.js:31:28)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)

## Specifications

  - Version:1.1.7
  - Platform:win10x64 1709 16299.309

**Comment by liximomo** [comment]
我觉得是 ftp 的端口填错了吧。一般都是  21。
