### ISSUE TITLE
Browse remote files without downloading everything

### ISSUE THREAD

**Issue by klicperajo** [liximomo/vscode-sftp#186]
It would be great if the extension supported the possibility of browsing the files on the remote server without downloading everything. If I open a file, only this single file is downloaded and then synced on save (or explicitly). The Atom extension [remote-ftp](https://atom.io/packages/remote-ftp) offers exactly this functionality. It is great for browsing directories with data and log files.

## Expected Behavior
Sync only the list of files when listing the directory. Download files only when they are directly opened.

## Actual Behavior
Every single file is downloaded when the directory is listed.

## Steps to Reproduce the Problem

  1. Run command SFTP: List
  2. Look at all the files being downloaded!

## Requisites
This is more of a feature request. I don't think there are any requisites.

**Comment by BI7PRK** [comment]
yes, how to download all files a site?

**Comment by liximomo** [comment]
Try [vscode-remote-fs](https://github.com/liximomo/vscode-remote-fs)
