### ISSUE TITLE
EISDIR: illegal operation on a directory, read vs code

### ISSUE THREAD

**Issue by rawcy** [liximomo/vscode-sftp#187]
## Expected Behavior
using privateKeyPath set up to use the private key to log in server
"privateKeyPath": "c:\\Users\\<username>\\.ssh",
## Actual Behavior
error on providing the privateKeyPath string value.
"privateKeyPath": "c:\\Users\\<username>\\.ssh",

## Steps to Reproduce the Problem
 add following line in config

  "privateKeyPath": "c:\\Users\\<username>\\.ssh",

## Requisites (**important to diagnose the problem!**)
 add following line in config

  "privateKeyPath": "c:\\Users\\<username>\\.ssh",

when using "password": "<password>" , eveything worked.

  ### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 
[info] config at c:\Users\cyin\OneDrive - Microsoft\github\Ansible-Networking {"name":"<project>","protocol":"sftp","host":"<servername>","port":22,"username":"<username>","password":null,"connectTimeout":20000,"agent":null,"privateKeyPath":"c:\\Users\\<username>\\.ssh\\","passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/<username>/<project-folder>","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"full","ignore":[".vscode",".git",".DS_Store"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"c:\\Users\<username>\\<project-folder>"}
[debug] run command upload
[error]: Error: EISDIR: illegal operation on a directory, read

## Specifications

  - Version: 1.1.7
  - Platform: windows 10

**Comment by liximomo** [comment]
It's should be `"privateKeyPath": "c:\\Users\\.ssh\\id_rsa",`
