### ISSUE TITLE
Can I config the local path?

### ISSUE THREAD

**Issue by yghipw** [liximomo/vscode-sftp#19]
I hava a porject with webpack. The build result is in "dist" folder.
 How can I upload the "dist" folder to remote by this ext ?
 thank u.

**Comment by liximomo** [comment]
Ignore other files or just put config file into `dist` folder.

**Comment by yghipw** [comment]
Thanks again.

**Comment by maciekkukuczka** [comment]
What is `.sftpConfig` file? Uou mean `.sftp.json` ? if so, placing it in the nested directory does not work.
Is there any other way to send only `.dist` folder?

**Comment by speiffer829** [comment]
Yeah I tried putting the the whole `.vscode` folder in my `dist` of my Vue project and it still uploaded the `dist` folder in addition to everything I actually wanted

**Comment by suxscribe** [comment]
I've set "context" option to
`"context": "dist"`
in sftp.json and it works - puts everything in dist folder to ftp
