### ISSUE TITLE
Fails to download json files

### ISSUE THREAD

**Issue by AlbertRF147** [liximomo/vscode-sftp#191]
## Expected Behavior
Having a dir structure with some .json files in the root, I would expect it to download everything with no problem to my local dir.

## Actual Behavior
FTP download gets stuck if it finds any .json file in the root directory and fails to download anything else.

## Steps to Reproduce the Problem

  1. Place some .json file in the root ftp directory.
  2. Try downloading from the root folder. Download should fail.
  3. Add a "ignore": "*.json" line in the config file. Now download should work.

## Requisites (**important to diagnose the problem!**)
{
    "name": "test",
    "protocol": "ftp",
    "host": "ftp.*****.com",
    "port": 21,
    "username": "****",
    "password": "****",
    "uploadOnSave": true
    "remotePath": "./"
}

  ### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 Don't know how to get that...

## Specifications

  - Version: 1.1.7
  - Platform: Windows 10

**Comment by liximomo** [comment]
1. Open User Settings.

    * On Windows/Linux - File > Preferences > Settings
    * On macOS - Code > Preferences > Settings
2. Set sftp.printDebugLog to true and reload vscode.
3. Reproduce the problem, get the logs from View > Output > sftp.
