### ISSUE TITLE
Upload one file to multiple context at the same time(同步一份代码都多个服务器)

### ISSUE THREAD

**Issue by guodf** [liximomo/vscode-sftp#193]
[
    {
        "context": "rancher",
        "host": "194.168.1.13",
        "username": "root",
        "password": "***",
        "remotePath": "/root/rancher",
        "uploadOnSave": true
    },
    {
        "context": "rancher",
        "host": "194.168.1.14",
        "username": "root",
        "password": "***",
        "remotePath": "/root/rancher",
        "uploadOnSave": true
    },
    {
        "context": "rancher",
        "host": "194.168.1.15",
        "username": "root",
        "password": "***",
        "remotePath": "/root/rancher",
        "uploadOnSave": true
    }
]
Error： "Matches multiple schemas when only one must validate.",
最后只有194.168.1.15这台被更新了

**Comment by frog1014** [comment]
same requirement, please, thanks.

**Comment by tanzhihang** [comment]
我也遇到这个问题

**Comment by unional** [comment]
dup of #107

**Comment by rainbow57** [comment]
context的名字设置成唯一试试看

**Comment by liximomo** [comment]
dup of #107
