### ISSUE TITLE
open single file directly

### ISSUE THREAD

**Issue by skyer9** [liximomo/vscode-sftp#194]
## Expected Behavior

if i know full path of some file. `/lib/classes/some/folder/of/test.asp`. i wanna directly open that file with inputting `/lib/classes/some/folder/of/test.asp`.

## Actual Behavior

for `/lib/classes/some/folder/of/test.asp`.
i have to select `lib` folder, select `classes` folder, select `some` folder, select `of` folder, select `test.asp` file,

**Comment by liximomo** [comment]
1. Open User Settings.

    * On Windows/Linux - File > Preferences > Settings
    * On macOS - Code > Preferences > Settings
2. Set sftp.printDebugLog to true and reload vscode.
3. Reproduce the problem, get the logs from View > Output > sftp.
