### ISSUE TITLE
Sync to remote just upload all files from folder to ftp, no matter the diffs/changes

### ISSUE THREAD

**Issue by kolnogorov** [liximomo/vscode-sftp#196]
## Expected Behavior
After `SFTP: Sync to remote` - SFTP plugin should retrieve files, diff them and upload to FTP only those files which have changed.

This bug appeared after the latest update at May, 17. Before that, everything was great.

## Actual Behavior
After `SFTP: Sync to remote` - SFTP plugin just reupload ALL files to ftp, no matter, were they changed or not. Even if there's no any difference between local project and the project on ftp - SFTP just upload all the project to ftp, file to file.

## Steps to Reproduce the Problem

  1. Choose `SFTP: Sync to remote` in Command pallette.
  2. Select a folder to sync.
  3. Wait for "diff" and then watch how SFTP uploads every single files from the folder to ftp, even with no difference.

### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
 
```
[info] config at /Users/xxx {"name":null,"protocol":"sftp","host":"xxx","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/xxx/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"full","ignore":[".git",".vscode",".DS_Store","logs","xxx/node_modules"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"context":"/xxx/}
[trace] run sync to remote task at /Users/xxx
[info] sync /Users/xxx
```

All paths are correct, i just cleared paths and credentials for the security reasons.  
Everything was ok for a very long time and i did change nothing, plugin just became buggy after the latest update. 

## Specifications

  - Version: sftp plugin 1.1.9 
  - Platform: macOS High Sierra 10.13.4

It's a great plugin, pity it has broken. I wish there was a way to downgrade to previous version, which worked great.

Thank you!

**Comment by SaleCar** [comment]
I have same problem... can someone fix this? ;)

**Comment by amard33p** [comment]
Same issue on 1.1.12

**Comment by scrnjakovic** [comment]
Same here. If i have file on server File.JPG and file.jpg on local, when I try to sync, it "uploads" file.jpg but it stays File.JPG on server. Like it's case insensitive which is wrong.

**Comment by kolnogorov** [comment]
> So it begs the question - was this feature even there?

Yes, i have been using this plugin for a while, and didn't have this problems. I appeared after the latest update.

**Comment by lyutian** [comment]
@kolnogorov, I notice that you used `"syncMode":"full"`, according to the user guide, `SFTP: Sync To Remote` will be the same with `SFTP: Upload` when `"syncMode":"full"` set.

Sadly, this `sync` function is still not work, even I used `"syncMode":"update"`.

Someone can try `"syncMode":"update"` and give us update?

**Comment by 0x4d48** [comment]
I tried `"syncMode":"update"`, doesn't work, uploads all files. Please fix.

**Comment by liximomo** [comment]
Good news.  v1.6.0 will only transfer the changed files.

**Comment by Lynn-cc** [comment]
I have the same problem and my sftp version is v1.12.2. Was this problem solved ?

**Comment by davide-strati** [comment]
Same here.
