### ISSUE TITLE
command palette not working for me.

### ISSUE THREAD

**Issue by techinpark** [liximomo/vscode-sftp#197]
![vscode](https://user-images.githubusercontent.com/1935442/40211202-3aa4b4a8-5a84-11e8-9096-ce107710dcdc.png)

I already installed sftp (version 1.1.9)
but not showing in the command palette,

i tried already re install but not working.
any ideas?

**Comment by liximomo** [comment]
Open a folder or workspace first.

**Comment by techinpark** [comment]
@liximomo  Thanks for supporting, 
when empty space can't use this command?? 
i want to work directly connected sftp.

**Comment by liximomo** [comment]
When it's empty. It has no idea where to save the remote file.

**Comment by liximomo** [comment]
You should try [vscode-remote-fs](https://github.com/liximomo/vscode-remote-fs) for what you want.
