### ISSUE TITLE
How to create a shortcut with an sftp command?

### ISSUE THREAD

**Issue by slesolliec** [liximomo/vscode-sftp#199]
Hi all,
any idea how I could add a keyboard shortcut to upload the current file?
I've added the following in my **keybindings.json**:

```
{
	"key": "ctrl+alt+s",
	"command": "SFTP: upload",
	"when": "editorTextFocus"
}
```
But I get a:  command "SFTP:upload" not found.

I've tried sftp:upload SFTP:Upload SFTP: Upload ... without any success. :(

**Comment by liximomo** [comment]
* On Windows/Linux - File > Preferences > Keboard Shortcuts
* On macOS - Code > Preferences > Keboard Shortcuts

**Comment by slesolliec** [comment]
Replying my own question:

```
{
	"key": "ctrl+alt+s",
	"command": "sftp.trans.remote",
	"when": "editorTextFocus"
}
```
Thank you for that nice little extension!!!  :+1:

**Comment by niccolomineo** [comment]
Is this still working? I can't see the `sftp.trans.remote` anymore among the available commands to map.

**Comment by liximomo** [comment]
It's get removed. Use `sftp.upload.activeFile` instead.

**Comment by liximomo** [comment]
You need map `sftp.upload.activeFolder` to a different key combination.

**Comment by BursaYazilimCom** [comment]
If you only want to upload the active file, you should configure it as follows:

{
	"key": "ctrl+alt+s",
	"command": "sftp.upload.activeFile",
	"when": "editorTextFocus"
}

If you want to upload the entire folder and its contents, you should configure it like this:

{
	"key": "ctrl+alt+s",
	"command": "sftp.upload.activeFolder",
	"when": "editorTextFocus"
}
