### ISSUE TITLE
Renaming will create another file

### ISSUE THREAD

**Issue by tphan18** [liximomo/vscode-sftp#20]
## Expected Behavior
When renaming a file, that file should be renamed on remote server.

## Actual Behavior
When renaming a file from `foo.js` to `bar.js`, there will be 2 files on the remote server: `foo.js` and `bar.js`. I am fine with this behavior. However, when you are require a Node module like `require('./foo')`, then when you rename from `foo` to `foo.js`, things will get messy.

## Steps to Reproduce the Problem

  1. Create a `foo.js`
  1. Upload the file
  1. Rename it to `bar.js`
  1. There are two files on the remove server.

## Specifications

  - Version: 0.7.8
  - Platform: Wins 7.

**Comment by liximomo** [comment]
You should use `sync to remote` with `syncMode` setting to 'full'.

**Comment by tphan18** [comment]
Thanks. It still does not work as my configs:

```javascript
{
  ...
  "uploadOnSave": true,
  "syncMode": "full",
 ...
}
```

**Comment by liximomo** [comment]
You should run `sync to remote` on the parent folder.
