### ISSUE TITLE
Upload works, download doesn't work.

### ISSUE THREAD

**Issue by klukiyan** [liximomo/vscode-sftp#21]
Hi,
This is the only ftp extension that I found to load not only text files, but also Excel, pictures, etc...
However downloading files from server doesn't work reliably :(

## Expected Behavior
Download all files when "SFTP Download"
## Actual Behavior
Doesn't download. Only uploads

## Steps to Reproduce the Problem

  1. tried to change the config file
  2. tried various file types
  3. followed the debug logs
Upload works ok, download doesn't work.
## Requisites
[debug]: download at Thu Aug 24 2017 15:35:24 GMT+0200 (Central Europe Daylight Time)
[debug]: 
------
target: /Scripts/Projects/TVP/Files
context: transmission file
error: Error: Failed to open file.
------
[debug]: upload at Thu Aug 24 2017 15:35:41 GMT+0200 (Central Europe Daylight Time)
 

## Specifications
[0.7.8]
Win7 x64

**Comment by liximomo** [comment]
It said ` Failed to open  /Scripts/Projects/TVP/Files`.  Are you sure  that `/Scripts/Projects/TVP/Files` exists in remote and you have the read permission?

**Comment by klukiyan** [comment]
@liximomo , yes, it exists and when I use similar sync module in sublime text it works. But this is really only one thing that keeps me from 100% switching fully to vscode

**Comment by klukiyan** [comment]
@liximomo , was trying now on the other project. Sync remote to local ... why it writes that it's uploading something? shouldn't it be downloading instead?

**Comment by liximomo** [comment]
@klukiyan Does download works on other project or folders? I couldn't reproduce it and no one else has the download problem.

**Comment by klukiyan** [comment]
Hi @liximomo ,
on the php web app files it seems to work good :)
I was using also for xlsx, xlsb, xlam files where it refused to properly download. But it's not a big issue anyway, because it was not wise to use ftp server to sync work between my to PCs. Using Git + vs repository works the right way. 
So I'll keep using sftp extension only for my web apps where I need to sync with server for sure

**Comment by liximomo** [comment]
@klukiyan But I want to figure it out. Could you tell me what type of the `/Scripts/Projects/TVP/Files` file, a file or a folder?

**Comment by klukiyan** [comment]
@liximomo 
**xlsb, xlsx, xlam...**
Here is full list with extensions:

> \Projects\TVP\Files\4EBC7500
> \Projects\TVP\Files\Accounts_MD_withBPID_2017-08-13.xlsb
> \Projects\TVP\Files\All_vw_Accounts2017-08-16.xlsx
> \Projects\TVP\Files\Provisions & YBP7 for Kiril 2017-07-28 (wo QV data)_2017-08-03.xlsx
> \Projects\TVP\Files\Provisions & YBP7 for Kiril 2017-07-28 (wo QV data)_2017-08-14.xlsx
> \Projects\TVP\Files\Provisions & YBP7 for Kiril 2017-07-28 (wo QV data)_2017-08-15.xlsx
> \Projects\TVP\Files\RebatesReconAutomation v2.7.9.2.xlsb
> \Projects\TVP\Files\RebatesReconAutomation v2.7.11.xlsb
> \Projects\TVP\Files\RebatesReconAutomation v2.8.0.xlam
> \Projects\TVP\Files\RebatesReconAutomation v2.8.0.xlsb
> \Projects\TVP\Files\vw_Account_Plan-vs-Confirmed.xlsb

Maybe it's the file naming that makes it broken? Or maybe that excel's temporary 4EBC7500 that it creates during saving. I added excel's ~*.xlx files to ignore, but the 4EBC7500 don't know how to add.
If you want I can do more tests, I can even create a folder with a user on my ftp and share with you the details after I encounter the issue again.

**Comment by liximomo** [comment]
@klukiyan That would be great. Thank you for your support.
