### ISSUE TITLE
"self signed certificate" error

### ISSUE THREAD

**Issue by faustoFF** [liximomo/vscode-sftp#210]
Cant upload files to ftp server.

Config:
```
{
    "protocol": "ftp",
    "host": "***",
    "username": "***",
    "password": "***",
    "remotePath": "***",
    "secure": true
}
```

Got error "self signed certificate". How configure extension to ignore self signed certificate?

## Steps to Reproduce the Problem

  1. Upload file to external FTP

### Extension Logs
[debug] < 220 ProFTPD 1.3.5a Server (dev serv) [192.168.100.81]
[debug] > AUTH TLS
[debug] < 234 AUTH TLS successful
[error] Error: self signed certificate
	at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
	at emitNone (events.js:86:13)
	at TLSSocket.emit (events.js:188:7)
	at TLSSocket._finishInit (_tls_wrap.js:610:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
 

## Specifications

  - Version: 1.1.12
  - Platform: 1.24.1

**Comment by liximomo** [comment]
Add this to your config: 

```js
"secureOptions": {"rejectUnauthorized": false}
```

**Comment by dergoldbroiler** [comment]
thank U soo much, i am trying to get this work since 2 hours.. :-D

**Comment by isaumya** [comment]
@liximomo Thank you so much for this. Really can't thank you enough. ❤️

**Comment by Beaurelocation** [comment]
@liximomo https://zebuloncolor.github.io/iSzbgwYEc6QcgKedijmNW0pEc9bHqRnkdfJZIdmNkPkOh7i5c93y/
