### ISSUE TITLE
Afer 1.2.0 update ingores port setings

### ISSUE THREAD

**Issue by KarolisZelvys** [liximomo/vscode-sftp#211]
## Expected Behavior
On save file should automatically upload to server

## Actual Behavior
On file save plugin ignores port settings and trying connect to server with standart port for ftp:21 for sftp:22

## Steps to Reproduce the Problem

  1. Set config:
{
    "protocol": "sftp",
    "host": “ipAddress”,
    "port": 1722,
    "username": “username”,
    "password": “password,
    "remotePath": “path”,
    "uploadOnSave": true,
    "syncMode": "full"
}
  2. Edit file
  3. Save it

### Extension Logs
 [error] Error: connect ECONNREFUSED serverIpAddress
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
 

## Specifications

  - Version: 1.2.0
  - Platform: macOS

**Comment by rickyfeng** [comment]
my sftp server port is 32200, How to configure?

**Comment by vanderb** [comment]
Same problem here on MacOs | Ext-Version 1.2.0.
@rickyfeng: By default you have to set the port in the sftp-settings. But since the last update the port-setting in user-config-file will be ignored / will be reset to sftp-default 22.

**Comment by vanderb** [comment]
Ok, it seems the bug is in the config-file ("out/modules/config.js', Line 113).

The new functionality to use ssh-config-file overrides the user-specific settings.

**Comment by liximomo** [comment]
Fix in v1.2.1.
