### ISSUE TITLE
Port ignored

### ISSUE THREAD

**Issue by miromajdan** [liximomo/vscode-sftp#213]
## Expected Behavior
Accept the port defined in config

## Actual Behavior
Port defined in config is ignored.

## Steps to Reproduce the Problem
Set a port to 222 in config and in log shows it is still 22.

config:
`{
    "protocol": "sftp",
    "host": "******",
    "port": 222,
    "remotePath": "/",
    "username": "*******",
    "password": "******"
}
`

log:
`"[info] config at /test {"name":null,"protocol":"sftp","host":"*******","port":22,"username":"******","password":"******","...
`
## Specifications

  - Version: 1.2.0
  - Platform: macOS

**Comment by vanderb** [comment]
Yes thats a bug, caused by the new ability to use ssh-config-file. I've postet a fix a similar issue-report:

https://github.com/liximomo/vscode-sftp/issues/211
