### ISSUE TITLE
上传需要2-3秒时间，怎么优化上传

### ISSUE THREAD

**Issue by shijunti19** [liximomo/vscode-sftp#216]
直接传服务器的，很频繁的操作
现在每传一个文件需要2-3秒我觉得太慢了，但是在ftp软件里上传很快
我觉的是不是没保持连接，每次上传在重复连接
keepalive

怎么操作，才可以秒传，连续上传文件，单个上传时间最好控制在1秒以内。

**Comment by liximomo** [comment]
能提供 log 吗？

**Comment by shijunti19** [comment]
@liximomo 
没什么错误，就是每次选择上传后，我等他上传要好久
[info] config at laravel56\a031 {"name":"a031","protocol":"ftp","host":"******","port":21,"username":"******","password":"******","connectTimeout":5000,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"remotePath":"/www","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":[".git","/.vscode"],"watcher":{"autoUpload":false,"autoDelete":false},"concurrency":4,"context":"laravel56\\a031"}
[info] upload laravel56\a031\app\Http\Controllers\Api\App\Jd.php
[info] upload laravel56\a031\app\Http\Controllers\Api\App\Jd.php
[info] upload laravel56\a031\app\Http\Controllers\Api\App\Jd.php

![1](https://user-images.githubusercontent.com/5392211/42009312-52f9bd52-7abc-11e8-9964-6aef71bcdffd.gif)
我用filezilla非常快，但是3-6秒的时间我实在受不了
他不算是错误，就是优化而已

**Comment by liximomo** [comment]
@shijunti19 我需要 printDebugLog  设置为 true 下的 log。你可以通过 
  1.  打开用户设置
      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. 设置 `sftp.printDebugLog` to `true` and 重启vscode.

**Comment by shijunti19** [comment]
@liximomo 
服务器使用的宝塔的自动配置的ftp，主动模式，39000-40000端口
`[trace] run upload task at laravel56\a031\app\Http\Controllers\Api\App\Jd.php
[info] upload  laravel56\a031\app\Http\Controllers\Api\App\Jd.php
[debug] > PASV
[debug] < 227 Entering Passive Mode (服务器地址)
这步会卡几秒↑

[debug] > LIST /www/app/Http/Controllers/Api
[debug] < 150 Accepted data connection
[debug] < 226-Options: -a -l \r\n226 10 matches total
[debug] > PASV
[debug] < 227 Entering Passive Mode (服务器地址)
这步会卡几秒↑
[debug] > STOR /www/app/Http/Controllers/Api/App/Jd.php
[debug] < 150 Accepted data connection
[debug] < 226-File successfully transferred\r\n226 0.072 seconds (measured here), 0.56 Mbytes per second`

**Comment by liximomo** [comment]
可以看出你的服务器不能很快的响应 PASV 命令。

**Comment by shijunti19** [comment]
@liximomo 
node里有ftp的主动模式的模块吗？我搜了下好像都没！
因为只用主动模式，所以没去设置被动模式。

**Comment by liximomo** [comment]
@shijunti19 是的哦，目前 node 没有支持主动模式的 ftp 模块。

**Comment by shijunti19** [comment]
好吧，太可惜，看样子我还要去配置下被动模式

**Comment by liximomo** [comment]
目前 ftp 的模块开发基本都处于停滞状态，sftp 更可靠些。

**Comment by shijunti19** [comment]
@liximomo 
是的，几个对比下来sftp最好用
突然想到，如果本地安装filezilla软件，然后调用filezilla的命令去实现上传下载，可能速度什么的都会快不少，这样也不需要去依赖node，而且开源，多平台支持！
