### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by tatic0** [liximomo/vscode-sftp#219]
On the wiki 
https://github.com/liximomo/vscode-sftp/wiki/config

## current text
 // string - Set to 'update' so 'sync command' will only affect thoes files exist in both local and server. Set to 'full', 'sync' will be same as 'download/upload' besides deleting file not exist in origin from target.
  syncMode: 'update',

## replace
'thoes' by 'those'

sed s/thoes/those/g

**Comment by liximomo** [comment]
Thanks.
