### ISSUE TITLE
Cannot create folder on remote server

### ISSUE THREAD

**Issue by kajko1973** [liximomo/vscode-sftp#22]
## Expected Behavior
When I create folder in VSC , and a file in that new folder, when I save the file and upload it, foldershould by created on remote server and file sent. 

## Actual Behavior
Files can be uploaded only if folders exist on server. When I create folder on local machine, I also have to create it manually on remote. When I try to upload file in newly created folder, it fails with error shown below.
sftpConfig.json is properly configured, downloading and uploading files to existing folders works properly.

## Steps to Reproduce the Problem
I have local directory structure like this:
+ igol-source
|-+ .vscode
|  |- .sftpConfig.json
|
|-+ webroot
 
1. create new folder in project workspace (for example igol_source/webroot/admin)
2. create file it this folder (igol_source/webroot/admin/readme.txt)
3. Try to upload readme.txt (either by sftp:Upload or UploadOnSave) 
4. Get error message like below

## Extension Logs 
```
[debug]: upload at Fri Aug 25 2017 19:28:44 GMT+0200 (Środkowoeuropejski czas letni)
[debug]: 
------
target: c:\Users\Paweł\Documents\Igol\igol-source\webroot\admin\readme.txt
context: transmission file
error: Error: /domains/pagal.pl/public_html/igol/webroot/admin/readme.txt: No such file or directory
------
[debug]: remote error {
    "code": 421
}
```

## Specifications

  - Version: sftp 0.7.8, VisualStudioCode 1.15.1
  - Platform: Windows 10

**Comment by liximomo** [comment]
Sorry. I could not reproduce the problem. Can you reproduce the problem with another remote server or in another machine?
