### ISSUE TITLE
config validation fail: prop "port" fails because ["port" must be a number]

### ISSUE THREAD

**Issue by shaynem** [liximomo/vscode-sftp#222]
Getting Port error on upload

```config validation fail: prop "port" fails because ["port" must be a number]```

```
[info] config at /path {"protocol":"sftp","host":"1.1.1.1","port":"1025","username":"******","connectTimeout":10000,"privateKeyPath":"/Users/username/.ssh/id_rsa","interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"remotePath":"/path","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"context":"/path"}
```
```
{
    "protocol": "sftp",
    "host": "1.1.1.1",
    "port": 1025,
    "username": "root",
    "remotePath": "/path",
    "uploadOnSave": true,
    "privateKeyPath": "/Users/username/.ssh/id_rsa"
}
```

**Comment by sunixzs** [comment]
Hi, I can confirm that. The error appears without changing anything in the configuration.
Visual Studio Code 1.25.1 on macos.
sftp 1.2.3

**Comment by liximomo** [comment]
Port should be a number not string.

**Comment by shaynem** [comment]
@liximomo you can see in the config it's not a string..

The port is there without ' ' or " "

**Comment by sunixzs** [comment]
Hi, sry for replying a closed issue. I think there is maybe a missunderstood. The only way to define the port is in`./vscode/sftp.json`, or? There it is defined as a number. It also makes no change if the port is not defined there - then the default value 22 is used?

When I define **sftp** as protocol I get this as info in the output window:
`[info] config at /path/to/workspace {"protocol":"sftp","host":"domain.tld","port":"22",[...]`

When I define **ftp** as protocol I get this as info in the output window:
`[info] config at /path/to/workspace {"protocol":"sftp","host":"domain.tld","port":21,[...]`

**Comment by shaynem** [comment]
@sunixzs this is the same as my original issue. It's strange because in other projects it works fine. Even deleting the .VSCode/sftp.json and recreating it.. same thing happens I'm at a loss unless its defined elsewhere somehow ?

**Comment by sunixzs** [comment]
@shaynem I also get the error in two other projects with sftp configured. Two weeks ago all went fine (didn't open vscode the last two weeks because of holidays).

Here is my backtrace, maybe it helps:
```
[error] Error: config validation fail: prop "port" fails because ["port" must be a number]
	at Object.getConfig (/Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/modules/config.js:232:15)
	at FileCommand.<anonymous> (/Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/commands/FileCommand.js:37:41)
	at Generator.next (<anonymous>)
	at /Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/commands/FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/commands/FileCommand.js:3:12)
	at FileCommand.handleFile (/Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/commands/FileCommand.js:33:16)
	at pendingTasks.concat.map.target (/Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/commands/FileCommand.js:54:72)
	at Array.map (native)
	at FileCommand.<anonymous> (/Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/commands/FileCommand.js:54:53)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/sunixzs/.vscode/extensions/liximomo.sftp-1.2.3/out/src/commands/FileCommand.js:4:58)
	at <anonymous>
```

The only line I find a definition of the default port is in config.js (default port also fails):
```
const merged = Object.assign({}, defaultConfig, { port: protocol === 'ftp' ? 21 : 22 }, config);
```

The configuration of the validation of port is for sftp and ftp the same: `port: Joi.number().integer(),`.
The default port is defined as `port: 22`.

All seems to be right. I don't know, maybe the issue is found in the environment? :-/

**Comment by liximomo** [comment]
Fixs on v1.2.4.

**Comment by sunixzs** [comment]
@liximomo You are great and quite fast. Thank a lot ;-)
