### ISSUE TITLE
SFTP Multiple Profiles

### ISSUE THREAD

**Issue by sebbler1337** [liximomo/vscode-sftp#224]
## Expected Behavior
Connect to the selected Profile

## Actual Behavior
asks for a password

## Steps to Reproduce the Problem

  1. set Config something like this:
`{`
    `"username": "username",`
    `"protocol": "sftp",`
  `  "profiles": {`
  `      "dev": {  `
        `    "host": "some.host.com",  `
          `  "password": "somePassword",`
           ` "port": 2022,`
         `   "remotePath": "/some/remote/path"`
      `  },`
       ` "live": {`
           ` "host": "someother.host.com",`
            `"password": "someOtherPassword",`
           ` "remotePath": "/some/remote/path"`
     `   }`
    `}`
`}`

2. Menu > "sftp: list all"

### Extension Logs
 [error] Error: connect ECONNREFUSED 127.0.0.1:22
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
 

## Specifications

  - Version: sftp 1.2.3 // VSCode 1.25.0
  - Platform: MacOs

What am i missing? Aren't multiple configs with different port and passwords possible?

Help would be appreciated and thanks for the awesome plugin by the way 👍 

Sebastian

**Comment by liximomo** [comment]
Fix in v1.2.4.
