### ISSUE TITLE
Using upload-shortcut uploads the whole workspace

### ISSUE THREAD

**Issue by sebbler1337** [liximomo/vscode-sftp#225]
## Expected Behavior
upload file which has focus

## Actual Behavior
uploads whole workspace

## Steps to Reproduce the Problem

  1. set Shortcut of "sftp: upload" to whatever you like
  2. focus the file you wish to upload
  3. press the shortcut to upload 

## Requisites (**important to diagnose the problem!**)

can't copy the logs cause i need to stop the uploading process first, which i do by closing vscode.
 

## Specifications

  - Version: sftp 1.2.3 // VSCode 1.25.0
  - Platform: MacOs

When i upload a file using the context menu inside the file it works as expected.

Any help would be appreciated

Thanks in regards

Sebastian

**Comment by liximomo** [comment]
#214

**Comment by sebbler1337** [comment]
Thanks!
