### ISSUE TITLE
Ignore from remotePath

### ISSUE THREAD

**Issue by khrizo** [liximomo/vscode-sftp#232]
`"ignore": ['foo']` works with "context" local workspace
`"ignore": ['foo']` but with  "remotePath" to avoid downloading junk not needed, is this poosible?

**Comment by Dixeran** [comment]
Where can I find the ussage of "ignore" option? No descriptions in documation.

**Comment by Dixeran** [comment]
Thanks! I found it right after I leaved the comment :)
