### ISSUE TITLE
差异同步整个项目到服务器

### ISSUE THREAD

**Issue by songxianling** [liximomo/vscode-sftp#233]
背景：目前到代码项目中有前端代码也有后端代码；开发过程中编辑前端代码；保存自动同步到服务器是没有问题
问题：团队协作不免要更新其他人的代码；通过终端pull下来代码以后；不会自己的检测到有那些文件发生了改变；只能自己手动右键文件夹；将整个文件夹再同步一次；同理；编辑sass文件；gulp转成css；html引用的是css；sass编译的css文件也不会上传
盼望：将整个项目目录监听；我更新其他人的代码；只要有变化；不管是php代码；还是gulp压缩的代码；都能自动的上传

**Comment by liximomo** [comment]
watcher不就可以解决这个吗，建议你先看看github上的wiki。

宋现令 <notifications@github.com> 于 2018年7月12日周四 16:15写道：

**Comment by songxianling** [comment]
配置了watcher里面的files属性；自动上传也是true；但是没有效果
![image](https://user-images.githubusercontent.com/16551088/42675618-72f65894-86a7-11e8-9cc0-607ffe5c1cc2.png)

**Comment by liximomo** [comment]
../Public/**/*

宋现令 <notifications@github.com> 于 2018年7月13日周五 14:17写道：

**Comment by liximomo** [comment]
@songxianling 不支持数组实现哦. `node glob` 自己支持多模式:

```
files: {Public,Application}/**/*.*
```

**Comment by joych3n** [comment]
files设置glob等同‘../‘是吗？是不是监听整个项目？
