### ISSUE TITLE
Ignore is not working on uploads

### ISSUE THREAD

**Issue by cblackmon** [liximomo/vscode-sftp#241]
## Expected Behavior
Ignore should ignore the files specified from being uploaded/downloaded. It uploads just fine - it just doesn't ignore anything.

## Actual Behavior
Putting strings into ignore array isn't ignoring.

## Steps to Reproduce the Problem

  1. Add strings to ignore.
  2. Update file that should be ignored.
  3. VSCode output shows file was uploaded anyway.
  4. Check SFTP in another method (I used Filezilla) and confirmed file had changed.

### Extension Logs

```
[info] [file-save] upload c:\Users\chris.blackmon\Local Sites\app\public\wp-content\themes\executive-pro\sass\_ie-src.scss
[info] transfer c:\Users\chris.blackmon\Local Sites\app\public\wp-content\themes\executive-pro\build\css\style.css
[info] [watcher] upload c:\Users\chris.blackmon\Local Sites\app\public\wp-content\themes\executive-pro\build\css\style.css
[info] transfer c:\Users\chris.blackmon\Local Sites\app\public\wp-content\themes\executive-pro\build\css\style.min.css
[info] [watcher] upload c:\Users\chris.blackmon\Local Sites\app\public\wp-content\themes\executive-pro\build\css\style.min.css
```
 

## Specifications

  - Version: 1.2.5
  - Platform: Windows 10

## sftp.json
```
{
	"protocol": "sftp",
	"context": "C:/Users/chris.blackmon/Local Sites/app/public",
	"host": "xxx.xxx.xx.xx",
	"port": 2222,
	"username": "xxx",
	"password": "xxx",
	"remotePath": "./",
	"uploadOnSave": true,
	"watcher": {
		"files": "{wp-content/themes/executive-pro/build/css/*.css, wp-content/themes/executive-pro/build/css/*.min.css,}",
		"autoUpload": true,
		"autoDelete": false
	},
	"ignore": [
		"newtest.txt",
		"wp-content/themes/executive-pro/sass/*.scss"
	]
}
```

**Comment by cblackmon** [comment]
Also wanted to say great extension. My workaround is just keybinding the upload/download for files not being watched. I guess I was just curious is watch and ignore were able to work in tandem.

**Comment by liximomo** [comment]
Did you see `[info] transfer c:\Users\chris.blackmon\Local Sites\app\public\wp-content\themes\executive-pro\sass\_ie-src.scss` in output? `[file-save] upload` tells what you do, `transfer` tells what sftp actually do.

**Comment by cblackmon** [comment]
Thanks for the guidance there - I was able to confirm `_ie-src.scss` did not change on the remote side.

I guess the messaging for when you have something in the ignore is not in the output tab in VSCode? I think that is what was tripping me up.

**Comment by liximomo** [comment]
I will make the output more clear. Thanks for you feedback.
