### ISSUE TITLE
sftp.trans.remote

### ISSUE THREAD

**Issue by MarekLew** [liximomo/vscode-sftp#242]
For https://github.com/liximomo/vscode-sftp/issues/214

**bug**: `selectFileFallbackToConfigContext` is used for `sftp.trans.remote` and this not have sense.
Beaus from command palete: `SFTP: Upload`  work like `SFTP: Sync to Remote` (update all files)

Please use `selectFileOnly` for  `sftp.trans.remote`

  - Version:
  - Platform:

**Comment by liximomo** [comment]
`SFTP: Upload` and `SFTP: Sync to Remote` are not same. If we use `selectFileOnly`, there is no way to trigger a whole project upload or download.

**Comment by MarekLew** [comment]
From command palete 'SFTP: Upload' upload all files. Whi?

**Comment by MarekLew** [comment]
> SFTP: Upload and SFTP: Sync to Remote are not same. If we use selectFileOnly, there is no way to trigger a whole project upload or download.

For update one or selected files use SFTP: Upload. For all project SFTP: Sync to Remote. Why 'SFTP: Upload '  upload whole project? It's the same function like  'SFTP: Sync to Remote', it's not necesery.

**Comment by poweredbymak** [comment]
You can not assign keys to "SFTP: Upload" the current file. Why?

**Comment by MarekLew** [comment]
@poweredbymak autor używa tej samej funkcji do wysyłania aktualnego pliku, grupy plików i całego projektu.  Skrót klawiszowy wysyłał plik. Z palety poleceń wysyłany był projekt. A z menu w exlorerze zaznaczone pliki. Wszystko działało tak jak sobie wymyślił ale zmieniło się zachowanie(vsc) przy używaniu skrótów i jest identyczne jak wywołanie z palety poleceń. Zamiast usunąć wysyłanie całego projektu za pomocą "SFTP: Upload"(bo Sync już to ma)  lub dodać domyślnie parametr "args":[null] do skrótu klawiszowego to czeka na poprawki deweloperów vsc, wycofujące ostatnie zmiany.

**Comment by poweredbymak** [comment]
Aha. Czyli zostaje nam czekać. Dzięki za wyjaśnienie.

**Comment by MarekLew** [comment]
@poweredbymak ci z vsc raczej nie wycofają zmiany a w funkcji 'selectFileFallbackToConfigContext' wystarczy zmienić dwie linijki i wtedy jest praktycznie identyczna z 'selectFileOnly'
