### ISSUE TITLE
corrupted files - every 65536th character missing on download/upload

### ISSUE THREAD

**Issue by vitamindck** [liximomo/vscode-sftp#244]
## Expected Behavior
Expect 1:1 representation of file on download (and upload)

## Actual Behavior
Every 65536th character is removed from the download when using ssh2/ssh2-streams

## Steps to Reproduce the Problem

I can not reliably reproduce the issue but I could create a demo and screenshare with you if you like. I'm able to reproduce it within 5 minutes but not on demand with reliable replication steps.

I download/upload a file larger than 200k and experience character removal.

please see the ssh2 developer's request https://github.com/mscdex/ssh2-streams/issues/78#issuecomment-406392923
I have spent several hours this evening trying to figure out how to debug a vscode plugin, specifically the sftp plugin with no luck. (first attempt doing this)

### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
 
I followed these steps - the logs look 100% normal when this issue occurs. [trace] execute diff for /Users/filepath/etcetc... no errors.

## Specifications

  - Version: vscode 1.25.1 / sftp 1.2.5
  - Platform: osx 10.13.6, node v8.11.3, npm 5.10.0, ssh2 ^0.6.1 (0.6.1 currently)

**Comment by necmettin** [comment]
Were you able to reproduce this after reboots, with different servers, from different locations, and/or with different network connections? Do other SFTP-related addons behave the same (if they do, this is more likely a server settings problem than an extension)?

It's been years since I had last gone through missing bytes problems similar to yours, and none of them were editor-related. It was always a connection problem; either with my local connection or the internet provider.

**Comment by vitamindck** [comment]
Thanks for taking the time @necmettin. I've tested on Windows & Mac and from two separate networks and the issue persists. I did more testing 12 days ago and still lost every 65536th character

**Comment by vitamindck** [comment]
This is the same issue - https://github.com/mscdex/ssh2-streams/issues/43
A co-worker and I came to the same conclusion and he implemented a fix by changing the highWaterMark to 32x1024. I have yet to confirm this myself, but I'll report back once I do.

**Comment by jnsbal** [comment]
I can confirm the issue still persists. With fastGet it works for me everytime

**Comment by vitamindck** [comment]
Changing the high water mark did fix the issue for our team. It'd be great if this were fixed in the mscdex/ssh2-streams package but alternatively if you could convert the sftp package to fastGet that would be spectacular. This problem also occurs with https://github.com/liximomo/vscode-remote-fs

**Comment by aaronmott** [comment]
This happens to me with larger files, seems changing the highWaterMark to one character less fixes it at the extension level.
