### ISSUE TITLE
Features request, replace the folder on upload

### ISSUE THREAD

**Issue by lilywang711** [liximomo/vscode-sftp#247]
## Expected Behavior
when upload Folder(/projects/dist/) to remotePath(/www/www/) , and what I expected was that dist floder was not uploaded, only the files inside will be uploaded.
 This is the current feature of Sublime SFTP.

## Actual Behavior
 In fact, the dist was also uploaded to /www/www. The result path is  /www/www/dist

## Steps to Reproduce the Problem
The following is my configuration
`{
    "name": "wall_web",
    "protocol": "sftp",
    "host": "xx.xx.xx.xx",
    "port": "22",
    "privateKeyPath": "xx/.ssh/id_rsa",
    "username": "root",
    "remotePath": "/www/www/",
    "uploadOnSave": "true",
    "ignore": [
        "\\.vscode-(project|workspace)", "sftp(-alt\\d?)?\\.json",
        "sftp-settings\\.json", "/venv/", "\\.svn/", "\\.hg/", "\\.git/",
        "\\.bzr", "_darcs", "CVS", "\\.DS_Store", "Thumbs\\.db", "desktop\\.ini"
    ]
}
`

## Specifications

  - Version: 1.2.3 
  - Platform: Mac OS

**Comment by liximomo** [comment]
```json
"context":  './dist'
```

**Comment by lilywang711** [comment]
thanks
