### ISSUE TITLE
Feature Request: New Command Palette Command "SFTP: Upload file"

### ISSUE THREAD

**Issue by AlexMax** [liximomo/vscode-sftp#249]
It appears to be possible to upload a file by right clicking in the buffer and selecting "SFTP: Upload".  However, selecting "SFTP: Upload" from the command palette (cmd-p) has unexpected results - instead of uploading the current buffer, it seems to upload an entire directory that you get to select.

Would it be possible to add an "SFTP: Upload file" or "SFTP: Upload buffer" to the command palette, which uploads the currently selected buffer?  Or, maybe rename "SFTP: Upload" to "SFTP: Upload directory" and make "SFTP: Upload" operate on the current buffer?

I presume that there would also need to be a "Download" equivalent as well.

**Comment by andremacola** [comment]
#214

**Comment by MarekLew** [comment]
Why this is cloused without comment?

**Comment by AlexMax** [comment]
@MarekLew Presumably because it’s a duplicate.
