### ISSUE TITLE
File and Folder renames on local leave old files in remote

### ISSUE THREAD

**Issue by TuxujPes** [liximomo/vscode-sftp#250]
## Expected Behavior
As a user, when I rename a file on local and it is auto-uploaded on save:
- I can see my renamed file on remote
- I can not see the file with old name anymore

## Actual Behavior
When I rename a file on local, both files with new and old names exist on remote

## Steps to Reproduce the Problem

  1. Rename File through VSCode.
  1. Make a change in a newly renamed file - upload changes
  1. Observe 2 files instead of 1.

### Extension Logs
 ```
[info] config at /Users/ohdear/Projects/RASPBERRY/SomethingSimple {"protocol":"sftp","host":"192.168.1.106","port":22,"username":"******","password":"******","connectTimeout":10000,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"remotePath":"./SomethingSimple","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"context":"/Users/ohdear/Projects/RASPBERRY/SomethingSimple"}
[info] transfer /Users/ohdear/Projects/RASPBERRY/SomethingSimple/test-pins-RENAMED/turn_on_the_lights-RENAMED.py
[info] [file-save] upload /Users/ohdear/Projects/RASPBERRY/SomethingSimple/test-pins-RENAMED/turn_on_the_lights-RENAMED.py
```

 ### sftp.json
```
{
    "protocol": "sftp",
    "host": "192.168.1.106",
    "username": "***",
    "password": "***",
    "remotePath": "./SomethingSimple",
    "uploadOnSave": true
}
````
 

## Specifications

  - Version: 10.13.4 (17E199)
  - Platform: MacOS High Sierra

**Comment by sunixzs** [comment]
Hi @TuxujPes. Maybe you can do something with the configuration parameter `syncMode`?
The default `syncMode=update` removes no files on sync. 
If `syncMode=full`, files, which do not exists, will be removed on the other side while syncing.
I think automatically on file change this is not possible. The sync is only possible on folders. Possibly sftp is not able to know, that a file was renamed. A rename looks like removing a file and adding a new file with another name.

**Comment by liximomo** [comment]
This is expected.

**Comment by shakelabstudio** [comment]
This worked for me, add this:
...

```
"uploadOnSave": true,
"watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
      }
```
