### ISSUE TITLE
Upload directories

### ISSUE THREAD

**Issue by netdjw** [liximomo/vscode-sftp#252]
## Expected Behavior
I have this directory structure:
```
dist/
  index.html
  img/
      logo.png
      hero.jpg
  css/
      style.css
  js/
      index.js
```

And I have this config file:
```
    {
        "name": "myprojcet.com",
        "privateKeyPath": "d:/mypriv.ppk",
        "username": "myuser",
        "protocol": "sftp",
        "remotePath": "/home/myuser/web/myproject.com/skins/",
        "host": "myserver.com",
        "watcher": {
            "files": "dist/*",
            "autoUpload": true
        }
    }
```

Now the index.html is loading up, but the img, css and js directories aren't.

1. I tried to use multiple contexts solution, but it didn't helped.
2. Tried to use in "files" options like this: "dist/*|dist/*/*" with | : ; , and ! spearators.

  - Version: 1.2.5
  - Platform: Windows 10

**Comment by liximomo** [comment]
dist/**/*

Balázs Winkler <notifications@github.com> 于 2018年7月23日周一 22:08写道：

**Comment by netdjw** [comment]
Thanks. This solved the problem.

I suggest to implement this answer to the basic documentation.
