### ISSUE TITLE
configure remotPath and wacher

### ISSUE THREAD

**Issue by darkiron** [liximomo/vscode-sftp#255]
## Expected Behavior
upload in www/ folder

and watch file in public folder

## Actual Behavior
create subfolder in www/
files in public folder was not uploaded
## Steps to Reproduce the Problem
use sftp.json:
```
{
    "name": "yourname",
    "context": "../",
    "protocol": "ftp",
    "host": "yourip",
    "port": 21,
    "username": "youruser",
    "password": "yourpass",
    "remotePath": "/www",
    "connectTimeout": 10000,
    "uploadOnSave": true,
    "syncMode": "update",
    "ignore": [
     ...
    ],
    "watcher": {
        "files": "**/public/dist/*",
        "autoUpload": true,
        "autoDelete": false
    },
    "concurrency": 4,
    "secure": false
}
```

## Requisites (**important to diagnose the problem!**)
folder architecture:

```|work folder
|- .vscode
|-src
|-public
| |- dist
```
### Extension Logs
  nothing
## Specifications

  - Version:1.2.5
  - Platform: OS X

**Comment by liximomo** [comment]
Delete  `"context": "../"` and change "watcher.files" to "public/dist/**/*",

**Comment by darkiron** [comment]
yeah I found this. THX
