### ISSUE TITLE
折腾半天没有连上我的阿里云虚拟主机，你能否给个例子？

### ISSUE THREAD

**Issue by lanmanck** [liximomo/vscode-sftp#256]
{
    "host": "qxu0000000.my3w.com",
    "username": "qxu0000000",
    "remotePath": "/",
    "password": "daaaaaaaaa"
}
这样就行了吗？端口号21不用？那个remotepath是啥玩意儿，我怎么知道是什么path，别人的都不用啊。

**Comment by lanmanck** [comment]
还有这货能做成文件树吗？挨个目录切换选择是不是很累？

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp#example-configs
