### ISSUE TITLE
Accept SFTP flags

### ISSUE THREAD

**Issue by alexrada** [liximomo/vscode-sftp#257]
## Expected Behavior
SSH Connection through proxy

## Actual Behavior
not connecting

## Steps to Reproduce the Problem
You need to have a private network of servers, and one to work as proxy.
In order to connect to server B, the connection goes through proxy

## SFTP flags
Solution is to pass sftp flags, like:
"sftp_flags": [
        "-o",
        "ProxyCommand ssh -e none proxy-vpn-server -p 22  exec nc %h %p 2>/dev/null"
    ],

**Comment by liximomo** [comment]
Not possible :(

**Comment by alexrada** [comment]
I've seen that, but how do you pass a command?

**Comment by liximomo** [comment]
You can't.
