### ISSUE TITLE
File deletion isn't working

### ISSUE THREAD

**Issue by xornet-sl** [liximomo/vscode-sftp#262]
## Expected Behavior
When I delete a file locally it is supposed to be deleted remotely as well. Espessialy if syncMode is set to "full".

## Actual Behavior
There is no way to automatically delete remote file from VSCode. Even if I set watcher with autoDelete: true, it won't be deleted! Watcher works only if I delete files from terminal by 'rm' command.

## Specifications

  - Version: 1.2.8
  - Platform: vscode 1.25.1 @ Linux Arch (updated)

**Comment by nove1398** [comment]
I get a similar situation

**Comment by liximomo** [comment]
## Steps to Reproduce the Problem

  1. one.
  1. two.
  1. three.

## Requisites (**important to diagnose the problem!**)

  ### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by xornet-sl** [comment]
## Steps to Reproduce the Problem
1. Setup sftp directory. I use this configuration:
```json
{
    "name": "name",
    "protocol": "sftp",
    "host": "HOSTNAME",
    "port": 22,
    "username": "USERNAME",
    "remotePath": "/PATH",
    "uploadOnSave": true,
    "syncMode": "full",
    "agent": "$SSH_AUTH_SOCK"
}
```
2. Synchronize local and remote files.
3. Right-click on any file in your synchronized folder and delete it from VSCode.
4. Nothing happens on remote side.
5. Change sftp config to this (add watcher, set uploadOnSave to false according to manual):
```json
{
    "name": "name",
    "protocol": "sftp",
    "host": "HOSTNAME",
    "port": 22,
    "username": "USERNAME",
    "remotePath": "/PATH",
    "uploadOnSave": false,
    "syncMode": "full",
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "agent": "$SSH_AUTH_SOCK"
}
```
6. Delete file again.
7. Nothing happens on remoe side.
8. Open external terminal window.
9. Type `rm <some_file_from_watched_path>`
10. Only now file will be deleted on remote side.
### Extension Logs
There is no logs. Extension just doesn't catch file deletion event. The log is clean when I remove file using VSCode.

**Comment by liximomo** [comment]
The watcher can only detect external file update. This is expected.  If you want delete if from vscode. Using (Remote Explorer)[https://github.com/liximomo/vscode-sftp#remote-explorer].

**Comment by xornet-sl** [comment]
@liximomo ok then. But it would be a nice feature to have menu options such as "SFTP: delete local and remote" or even "SFTP: rename local and remote". These features realized quite good in Sublime Text sftp plugin for example.
It is very annoying that I need to switch panels/delete files twice/resync just to keep directory fully synchronized after such a simple operation. And why the watcher skip internlly deleted files? What is the reason? I think that it is expected that watcher must just watch the filesystem and synchronize changes no matter where these changes came from.

**Comment by liximomo** [comment]
I want to keep remote file operations in Remote Explorer. You should create a new issue for the `SFTP: delete local and remote` feature. I want to know how many people are interested in this.

If the watcher watches both internal and external files it will be a resource wasted.
