### ISSUE TITLE
插件总是无法启动是怎么回事？

### ISSUE THREAD

**Issue by pearroc** [liximomo/vscode-sftp#263]
你好，请问一下vscode上的vscode-sftp插件总是无法随软件同步启动？
感觉有时间需要等上N久左下解才会显示SFTP\ftp
或者当左下解有更新提示后，点击更新了重启才会显示
请问这是什么原因造成的？如何解决

**Comment by liximomo** [comment]
可能是你其他插件安得太多了, 你可是尝试仅启用 vscode-sftp, 比较一下启动时间.

**Comment by pearroc** [comment]
好的，我按你的方法试试
后面发现卸载后重装可以启动
