### ISSUE TITLE
watcher.files must respect ignore rules

### ISSUE THREAD

**Issue by xornet-sl** [liximomo/vscode-sftp#264]
## Expected Behavior
watcher has only one "watcher.files" glob which is white list. But there is one blacklist that can be used as black list - "ignore". When everything is watched it is supposed that it won't touch ignored files (.git for example)

## Actual Behavior
Right now "ignore" is useless if watcher watches everything and there is no way to specify black list for watcher.

## Steps to Reproduce the Problem
```
"watcher": {
        "files": "**/*",
        "autoUpload": true,
},
 "ignore": [
        ".vscode",
        ".git",
        ".DS_Store"
]
```
and try touch any "ignored" file. It will be uploaded.

## Specifications

  - Version: 1.2.8
  - Platform: 1.25.1 @ Linux Arch (updated)

**Comment by liximomo** [comment]
Can you provide the logs?

**Comment by xornet-sl** [comment]
@liximomo Oh, I don't know why this happend but now I haven't this issue... May be I just hadn't saved sftp.json before I did upload.. Sorry for this mess.
