### ISSUE TITLE
Problem whit SFTP (remotePath)

### ISSUE THREAD

**Issue by JohnJosy** [liximomo/vscode-sftp#265]
## Expected Behavior
When I saved the file, the file was being loaded in the right path

## Actual Behavior

Now when I save the file it is not loaded into the remote folder, but it creates a string out of the remote folder

## Steps to Reproduce the Problem

  1. I make changes.
  2. Save the File.
  3. FileZilla check and note that it did not save the file in the correct folder. The system inserts the extension "/httdocs/nameFile"

This is my sftp.json
{
    "protocol": "ftp",
    "name": "albergoalcorso.it",
    "context": "online",
    "host": "****",
    "username": "****",
    "password": "****",
    "remotePath": "./httpdocs/", => problem
    "ignore": [
        "sftp-config.json",
        ".remote-sync.json",
        "gulpfile.js",
        "package-lock.json",
        "package.json",
        "/node_modules"
    ],
    "connectTimeout": 1000,
    "uploadOnSave": true
}

  ### Extension Logs
  [trace] execute upload for \\internal\Siti\_produzione\albergoalcorso.it.dev\online\aeroporto-malpensa.php
[debug] > PASV
[debug] < 227 Entering Passive Mode (185,21,118,50,237,13)
[debug] > LIST /
[debug] < 150 Opening BINARY mode data connection for file list
[debug] < 226 Transfer complete
[debug] > PASV
[debug] < 227 Entering Passive Mode (185,21,118,50,244,52)
[debug] > STOR \\httpdocs\\aeroporto-malpensa.php
[debug] < 150 Opening BINARY mode data connection for \\httpdocs\\aeroporto-malpensa.php
[debug] < 226 Transfer complete
[info] transfer \\internal\Siti\_produzione\albergoalcorso.it.dev\online\aeroporto-malpensa.php
 

## Specifications

  - Version: 1.3.0
  - Platform: Windows 10

**Comment by gabrieldodan** [comment]
I have similar problem ...

**Comment by ragokin** [comment]
It looks like on windows it using the windows style "\"  for the upload path, and its not being converted when transmitting to a UNIX box. Files end up in the users home directory on unix systems with the filename being \$remotePath\normal\path\to\file instead of $remotePath/normal/path/to/file

**Comment by vargavd** [comment]
I have the similar problem. This morning it worked like charm, but since the new version came down 2 hours ago, my files are going to the home directory on the server. It is pretty annoying. Does anyone know any solution or quick fix?

**Comment by JohnJosy** [comment]
If I enter "\" instead of "/", the sftp.json file goes into error .... Is it possible to downgrade the version?

**Comment by JohnJosy** [comment]
If I enter "\" instead of "/", the sftp.json file goes into error .... Is it possible to downgrade the version?

**Comment by ragokin** [comment]
@JohnJosy 
https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/

**Comment by JohnJosy** [comment]
But do you think it will be something that can be solved on Windows?

**Comment by rbrucecel** [comment]
How to downgrade... 1.3 is broken.

**Comment by callumbooth** [comment]
having the same issue

**Comment by vargavd** [comment]
@ragokin 
I have tried this downgrade method, but when I install the previous version, it updated it automatically. I also setup the "update.channel": "none" settings, but didnt help. I think we have to wait until the author fixes that issue.

**Comment by ragokin** [comment]
@vargavd 
You can turn of automatic updates of extensions in VScode with the ... menu - should have mentioned that sorry!

1. disable auto updates
2. unisntall sftp
3. use the information from that link to reinstall.

**Comment by ragokin** [comment]
"extensions.autoUpdate": false

**Comment by liximomo** [comment]
Sorry, I can't understand the problem.

ragokin <notifications@github.com> 于 2018年8月2日周四 22:42写道：

**Comment by JohnJosy** [comment]
The problem is that on Windows when I go to save no longer saves in the folder we want (in my case httpdocs) but out of the folder scleta happens this:
![screenshot_1](https://user-images.githubusercontent.com/19427698/43591825-7b1b7892-9674-11e8-92b1-d983df986339.png)

**Comment by JohnJosy** [comment]
The problem is that on Windows when I go to save no longer saves in the folder we want (in my case httpdocs) but out of the chosen folder happens this:
![screenshot_1](https://user-images.githubusercontent.com/19427698/43591862-96a9d2d4-9674-11e8-89a8-c37f40325c46.png)

**Comment by rbrucecel** [comment]
Same for Linux server ... When uploading in version 1.3 the files are not going into the correct location on the server.  They go into the home ~ folder of the server account with the path attached to the files name.   It worked fine before 1.3

The file name becomes "\web\admin\includes\manage.php" instead of going into the "\web\admin\includes\" directory with the name "manage.php"

**Comment by ragokin** [comment]
@liximomo Sorry - "extensions.autoUpdate": false - thats a vscode setting that allows users to downgrade to 1.2.7, otherwise vscode will autoupdate it to 1.3. It's not directly related to the issue, just a workaround for now.

**Comment by omgdracula** [comment]
@ragokin Is there a way to downgrade if we already updated?

**Comment by vargavd** [comment]
@ragokin 
Thanks a lot, the "extensions.autoUpdate": false worked :)

**Comment by vargavd** [comment]
So everyone: 

- open the vscode settings and insert "extensions.autoUpdate": false line.
- uninstall sftp (not just disable)
- restart vscode
- install the 1.2.7 version as it is described here: https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/
By the way, the link to the 1.2.7 version is that:
https://liximomo.gallery.vsassets.io/_apis/public/gallery/publisher/liximomo/extension/sftp/1.2.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by rbrucecel** [comment]
Thanks, vargavd... got me back up and running.   I'll wait for a fix to 1.3

**Comment by funkymonk91** [comment]
The update broke upload/download/diff functionality for me as well. Going to revert back to 1.2.7 until a fix is pushed out.
