### ISSUE TITLE
How to create multiple config?

### ISSUE THREAD

**Issue by thebatclaudio** [liximomo/vscode-sftp#27]
## Expected Behavior
When I launch the "SFTP: Config" command and I just have a config file, I expect that it creates a new config file 

## Actual Behavior
It open the actual config file

**Comment by liximomo** [comment]
It just give you an default config.You can simplely copy it to anywhere, just make sure it in an `. vscode` folder.

**Comment by timhecker** [comment]
Please @liximomo, may you explain this process in a more specific way? Thanks.

**Comment by liximomo** [comment]
refer to [readme](https://github.com/liximomo/vscode-sftp#example)

**Comment by timhecker** [comment]
Sorry @liximomo, but I can't understand. Simply, I need an FTP config for DEV environment and a different FTP config for PROD environment. Is this possible with your extension? Thanks.

**Comment by liximomo** [comment]
No if they share the same context.

**Comment by mityukov** [comment]
> > Simply, I need an FTP config for DEV environment and a different FTP config for PROD environment. Is this possible with your extension? 
>
> No if they have the same context.

Are there any plans?
