### ISSUE TITLE
请问我的配置有问题吗？为什么 download 不下来远程服务器的文件

### ISSUE THREAD

**Issue by zhangyile** [liximomo/vscode-sftp#272]
## Expected Behavior
希望能正常运行

## Actual Behavior
我是按照文档里说的那样配置的

## Steps to Reproduce the Problem

一直在转圈圈，debug 打开后也没有输出
我在终端使用 sftp 命令是可以正常上去的，也是可以看到文件的！

## Requisites (**important to diagnose the problem!**)

![image](https://user-images.githubusercontent.com/25133858/43723427-37073c28-99ca-11e8-94d9-ae98927f9284.png)

  ### Extension Logs
 
无输出

## Specifications

  - Version: 1.3.3
  - Platform: visual studio code 版本 1.25.1 (1.25.1)

**Comment by liximomo** [comment]
试试 v1.3.4. Remote Explorer 这个新特性刚开发出来, 我没有那么多机器和服务器做测试, 现在会有些不稳定, 迭代几次就好了.
