### ISSUE TITLE
Can not connect to remote server through a proxy

### ISSUE THREAD

**Issue by netw0rkf10w** [liximomo/vscode-sftp#277]
Hello,

First of all thank you so much for the plugin!

When using it to sync with a remote server through a proxy, I got some timed out errors.

Suppose that my remote server is `123.456.789.0` (access with username and password) and my proxy server is `user@proxy.server` (access with public SSH key). I created a file `~/.ssh/config ` with the following content:

```
Host 123.456.789.0
    ProxyCommand ssh -W %h:%p username@proxy.server 123.456.789.0
```

Now in the terminal I can do `ssh username@123.456.789.0` without any problem, but when setting the plugin in VS Code:

```
 {
    "protocol": "sftp",
    "host": "123.456.789.0",
    "port": 22,
    "username": "username",
    "remotePath": "/home/username/",
    "uploadOnSave": true,
    "connectTimeout": 30000,
    "agent": "$SSH_AUTH_SOCK",
    "privateKeyPath": "/Users/username/.ssh/id_rsa"
}
```
I obtained the following error after saving a file:

> [error] Error: Timed out while waiting for handshake
> 	at Timeout._onTimeout (/Users/username/.vscode/extensions/liximomo.sftp-1.3.5/node_modules/ssh2/lib/client.js:695:19)
> 	at ontimeout (timers.js:386:14)
> 	at tryOnTimeout (timers.js:250:5)
> 	at Timer.listOnTimeout (timers.js:214:5)

My remote server is running Ubuntu and my local machine is on Mac OS High Sierra.

Thank you in advance for your help!

## Specifications

  - Version: 1.3.5
  - Platform: Mac OS High Sierra

**Comment by liximomo** [comment]
It doesn't support proxy. ☹️

D. Khuê Lê-Huu <notifications@github.com> 于 2018年8月7日周二 18:37写道：

**Comment by liximomo** [comment]
Planning...

**Comment by liximomo** [comment]
See [connection hopping](https://github.com/liximomo/vscode-sftp#connection-hopping).
