### ISSUE TITLE
QUESTION : SSH behind HTTP proxy possible ?

### ISSUE THREAD

**Issue by gnn06** [liximomo/vscode-sftp#28]
This is not an issue but just a question. I don't how to ask it. Sorry.

II would like to use your extension behind an HTTP proxy.
Does it possible ?

I don't how if a special conf is necessary in my visual code studio. It access correctly to Internet to download extension.

Best regards

## Expected Behavior
[Description of the expected behavior]

## Actual Behavior
[Description of the actual behavior]

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Extension Logs 
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
You need config a system proxy.

**Comment by liximomo** [comment]
https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions
