### ISSUE TITLE
Support for *.code-workspace

### ISSUE THREAD

**Issue by gerardolima** [liximomo/vscode-sftp#280]
Is support to code workspace with multiple workspaceFolder planned?

**Comment by gerardolima** [comment]
#featurerequest

**Comment by liximomo** [comment]
It's already supported.

**Comment by gerardolima** [comment]
Not really. I mean putting the configuration inside the *. code-workspace files.

**Comment by liximomo** [comment]
No plans for this.

**Comment by gerardolima** [comment]
Would you be open to a PR to implement it?

**Comment by gerardolima** [comment]
Maybe an approach like this would work (https://github.com/thisboyiscrazy/vscode-rsync/blob/master/README.md)

**Comment by liximomo** [comment]
@gerardolima PR is welcome.

**Comment by vPackets** [comment]
Have trouble to understand how each of my folders can have a separate SFTP config ...

**Comment by liximomo** [comment]
Using context in a single folder project. Using `SFTP: config` command in a multi-root workspace.

**Comment by vPackets** [comment]
Not sure if that's what I ve done but I have a multi root workspace and I am now able to have a separate SFTP config for each of my folders. the sftp.json is now per folder.

Thanks !

**Comment by vPackets** [comment]
Looks like I understood what you meant. Sorry for the overhead.

With context in a multi root workspace, I would be able to have a single file at the root of the workspace where I would define all the folders...

Looks like a nice alternative .

Thanks again !

**Comment by gerardolima** [comment]
hi, @liximomo, could, please, provide some documentation on how to set the project up and build/test/run?

**Comment by SidIcarus** [comment]
@gerardolima did you make any progress on this?

**Comment by liximomo** [comment]
It's already supported, with another way.

**Comment by gerardolima** [comment]
hey, @SidIcarus, I couldn't find time to develop it, at the time (please see my comments above), and now I don't use this plugin anymore, but this plugin worked fine for me, though! The only con was to have lots of sftp.json files scattered through the many sub-projects.
