### ISSUE TITLE
Support for exceptions in ignore

### ISSUE THREAD

**Issue by gerardolima** [liximomo/vscode-sftp#281]
Is there any way to override the "ignore" setting in "sftp.json"?

It would be very helpful to ignore node_modules, but *not* ignore node_modules/@types.

**Comment by gerardolima** [comment]
I already tried the .gitignore syntax:

    ...
    "node_modules",
    "!node_modules/@types",
    ...

**Comment by liximomo** [comment]
``` 
...
"node_modules/*",
"!node_modules/@types",
...
```

**Comment by gerardolima** [comment]
Thanks a lot!!
