### ISSUE TITLE
初始配置sftp.json，Remote Explorer连接不上FTP的问题

### ISSUE THREAD

**Issue by fillchars** [liximomo/vscode-sftp#283]
感谢作者更新了Remote Explorer这个功能；

我这在使用过程中遇到一些奇怪的问题：
1、打开一个空的文件夹，配置好sftp.json文件，是可以链接到FTP并下载源码，这些都是成功的；然后来到Remote Explorer，预览不了FTP上的文件结构，右下角跳出这样的错误，但是我重启整个vsc，Remote Exploer就能使用了；
![image](https://user-images.githubusercontent.com/24713976/43955890-9f5d67cc-9cd4-11e8-976a-7eca634b44d8.png)
Can't find config for remote resource remote://localhost:21/?remoteId%3D1%26fsPath%3D%2F.
2、如果我直接在FTP（不通过插件）上增加了一个文件（比如目录lib下新增一个abc.txt），那么在Remote Explorer上点击更新，再进入lib目录的时候，会跳出这样的错误：
![image](https://user-images.githubusercontent.com/24713976/43955794-47953484-9cd4-11e8-8a60-7ccad6a1b766.png)
Can't find config for remote resource remote://localhost:21/lib?remoteId%3D1%26fsPath%3D%2Flib.
3、Remote Explorer的源码预览功能目前只能打开一个源码吗？如果要同时预览多个源码，但我只打开一个tab；

版本：
**vsc:**
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
**sftp:** 
1.3.7

**Comment by liximomo** [comment]
你的配置有问题吧, 请把配置和全 log 贴出来

**Comment by liximomo** [comment]
这个应该和 #287 问题一样, 看下 v1.3.9 是否还有此问题.
