### ISSUE TITLE
No failure info but not synchronizing

### ISSUE THREAD

**Issue by 26XINXIN** [liximomo/vscode-sftp#288]
I succeeded synchronizing my local files to the remote server for several times, but after that I can't do that anymore. The output doesn't shows any failures. The only info it prints is something like:

```
[info] transfer dir/to/my/local/files
```

My files on the remote server haven't been updated. Do you have any idea what is happening?

Thanks.

**Comment by liximomo** [comment]
Use upload instead of sync.

**Comment by 26XINXIN** [comment]
It doesn't work for both sync and upload. The remote explorer is up to date, but the files on the remote server don't change. Here is my config:

```
{
    "protocol": "sftp",
    "host": "10.8.***.**",
    "port": 22,
    "username": "y*******p",
    "password": "*******",
    "remotePath": "~/repo/data_stream/",
    "passive": false,
    "interactiveAuth": false,
    "uploadOnSave": false,
    "syncMode": "update",
    "ignore": [
        ".vscode/",
        ".git/",
        ".DS_Store",
        "words_idf.rst",
        "*.csv"
    ],
    "watcher": {
        "files": "**/*",
        "autoUpload": false,
        "autoDelete": false
    }
}
``` 

I'm sure that the username, password, host and remotePath are correct. Is there something wrong with my config?

**Comment by liximomo** [comment]
> the files on the remote server don't change

How do you confirm this? From remote explorer or remote machine?

**Comment by 26XINXIN** [comment]
From the remote machine. The remote explorer shows the updates but not the machine.

**Comment by liximomo** [comment]
Do you mean that the remote explorer shows the updated content but the
machine still keeps the old?

**Comment by 26XINXIN** [comment]
Yes.

> 在 2018年8月16日，下午12:57，X.L <notifications@github.com> 写道：
> 
> Do you mean that the remote explorer shows the updated content but the
> machine still keeps the old?
>

**Comment by liximomo** [comment]
That's impossible. Please reconfirm the files in the remote machine.

**Comment by 26XINXIN** [comment]
I just re-examined it. I create a new test file in my repo and do both sync to remote and upload project. Then I refreshed the remote explorer. The new file shows   up in the remote explorer. And I logged on to the remote machine and found nothing happened.


> 在 2018年8月16日，下午1:37，X.L <notifications@github.com> 写道：
> 
> That's impossible. Please reconfirm the files in the remote machine.
>

**Comment by 26XINXIN** [comment]
I finally solved the problem:

* relaunch the vscode;
* replace the remotePath to the absolute path.

Then it works well with upload. I'm still wondering why sync to remote doesn't work.

**Comment by 26XINXIN** [comment]
I finally figure out what's the difference between sync and upload. thanks a lot!
