### ISSUE TITLE
Changing Git Branch locally does not change on remote

### ISSUE THREAD

**Issue by KasiL** [liximomo/vscode-sftp#294]
## Expected Behavior
when I change a branch locally, the branch should also change on the server

## Actual Behavior
Changing a branch locally, changes files locally, however, those same files are not changed on the remote server

## Steps to Reproduce the Problem
When working on local development, I change branches from "branch A" to "branch B", all my files locally change, but when I SFTP to the server, it still shows all the files from Branch A. 

## Requisites (**important to diagnose the problem!**)

This is the setup on sftp.json

{
    "name": "PROJECT NAME",
    "host": "SERVER IP ADDRESS",
    "port": 22,
    "username": "root",
    "protocol": "sftp",
    "agent": output of echo $SSH_AUTH_SOCK, 
    "privateKeyPath": "/Users/MY-KEY/.ssh/id_rsa",
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/mnt/PROJECT/var/www/html",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
    "files": false,
    "autoUpload": false,
    "autoDelete": true
    },
    "ignore": [
    "**/.vscode/**",
    "**/.git/**",
    "**/.DS_Store"
    ]
    }

  ### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
 

## Specifications

  - Version: 1.3.10
  - Platform:

**Comment by liximomo** [comment]
```
"uploadOnSave": false,
"watcher": {
"files": "**/*",
"autoUpload": true,
"autoDelete": true
},
```
