### ISSUE TITLE
Run previous config

### ISSUE THREAD

**Issue by sfarley85** [liximomo/vscode-sftp#295]
## Expected Behavior
I should be able to run an existing config file rather than creating a new one each time I need to switch or re-open VSCode.

## Actual Behavior
I can't get sftp to use a previous config. View command doesn't work, and if I try any other commands it errors telling me it can't find the config even if that is the currently open file. I have to use the config command, which just creates a new config file that I have to re-configure and now have 2 of. I feel like this functionality probably exists and I'm just not seeing it, but figured would report in case not. 

## Steps to Reproduce the Problem

1. Create a config file
2. Close VS Code or create a different config file
3. Now try and use the previous configuration

## Requisites (**important to diagnose the problem!**)
Doesn't seem relevant to the issue, but let me know if more info needed. 

### Extension Logs
Doesn't seem relevant to the issue, but let me know if more info needed. 
 

## Specifications

  - Version: 1.3.11
  - Platform: MacOS

**Comment by liximomo** [comment]
I have no idea what you're talking about.

**Comment by sfarley85** [comment]
Let's say I have a config file I save and use. Then let's say I close vscode and come back later. How do I use that same config file?

**Comment by liximomo** [comment]
Open the same folder you've created the config.

**Comment by sfarley85** [comment]
So yeah I open the same folder and file, but that doesn't do the trick. I must be doing something strange I guess and am unable to describe it.

**Comment by liximomo** [comment]
Can you record a gif?

**Comment by sfarley85** [comment]
I see what I was doing now, I was just trying to select the file from the explorer, whereas it only is enabled if you actually open it via something like File>Open. Sorry for the obtuse question.
