### ISSUE TITLE
[Feature] Exclude Paths

### ISSUE THREAD

**Issue by mashiox** [liximomo/vscode-sftp#296]
Hello

Is there support or plans to exclude particular files or directories from download and upload operations? 

In my particular use case, I need to exclude a selection of remote sub-directories of the `remotePath` from downloading to my disk.

**Comment by liximomo** [comment]
[wiki][https://github.com/liximomo/vscode-sftp/wiki/Config#ignore]

**Comment by mashiox** [comment]
Completely missed that, thank you very much!
