### ISSUE TITLE
Global configuration or context-free connections

### ISSUE THREAD

**Issue by jgoux** [liximomo/vscode-sftp#299]
Hello,

I find this extension awesome, so thanks for the great work!

I want to use it to be my integrated SFTP explorer in VS Code when I need to edit some scripts on remote servers. I didn't find a way through the documentation to declare multiple connections (contexts array is close, but is...contextual lol), independently of my current opened project.

A bit like the list of servers declared in WinSCP : 
![image](https://user-images.githubusercontent.com/1443499/44712403-f2d7e000-aab0-11e8-92af-d807c4ccc214.png)

Is it possible?

**Comment by liximomo** [comment]
This is for you [remote-fs](https://github.com/liximomo/vscode-remote-fs).

**Comment by jgoux** [comment]
This seems exactly what I want, thanks @liximomo ! ⭐️
