### ISSUE TITLE
不能自动同步

### ISSUE THREAD

**Issue by Vincentzc** [liximomo/vscode-sftp#3]
我刚刚安装的时候是可以在保存的时候自动同步到远程的，但是第二天就不可以了，只能手动同步，中间也没有安装别的插件也没有修改配置。不知道什么原因。以下是我的配置。机器是虚拟机。以下是我的配置：
{
    "host": "192.168.0.246",
    "port": 22,
    "username": "root",
    "password": "centos",
    "protocol": "sftp",
    "privateKeyPath": null,
    "passphrase": null,
    "remotePath": "/etc/vsftpd",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files":null,
        "autoUpload": true,
        "autoDelete": false
    },
    "ignore": [
        "**/.vscode",
        "**/.git",
        "**/.DS_Store",
        "**/.sftpConfig.json"
    ]
}

**Comment by liximomo** [comment]
目前无法重现，也未见到他人反应。建议检查插件是否最新版本，重启编辑器。如果依然有问题，请打开 视图-输出-sftp，提供 debug 信息。

**Comment by Vincentzc** [comment]
升级后问题没有再出现了，谢谢。
