### ISSUE TITLE
Can I browse remote directories with the plugin?

### ISSUE THREAD

**Issue by wzup** [liximomo/vscode-sftp#30]
With ST3 SFTP plugin I can browse remote directories, actually whole remote server. And select arbitrary files and open them in editor. However I cannot see this functionality in this plugin. Does it exist? How to use it?

Here is all options. Is there something like `browse remote`?

![sftp](https://user-images.githubusercontent.com/3880497/30445511-c8013052-99b8-11e7-9b33-e470007a5759.png)

**Comment by liximomo** [comment]
Currently, it does not support.

**Comment by Jack89ita** [comment]
:+1: for this!

**Comment by liximomo** [comment]
It's in v1.0.0.
