### ISSUE TITLE
How to use ~/.ssh/config in Linux?

### ISSUE THREAD

**Issue by hrvoj3e** [liximomo/vscode-sftp#303]
How to use ~/.ssh/config in Linux ?

`~/.ssh/config`
```
Host somehost
    Hostname 192.168.1.84
    Port 8400
    User someuser
```
`.vscode/sftp.json`
```
{
    "protocol": "sftp",
    "host": "somehost",
    "remotePath": "/home/someuser",
    "agent": "$SSH_AUTH_SOCK"
}
```

**Comment by liximomo** [comment]
It will use `~/.ssh/config` automatically.

**Comment by hrvoj3e** [comment]
"will" as in "work in progress" or it should work now in latest stable version?
Will it support whole ssh_config syntax - e.g. "Match" or "Include config.d/*"?

**Comment by liximomo** [comment]
It works in the latest stable version. Only support these: HostName, Port, User, IdentityFile, ConnectTimeout.
