### ISSUE TITLE
Allow manually upload an excluded (ignored) file

### ISSUE THREAD

**Issue by johnnytemp** [liximomo/vscode-sftp#307]
Thanks for this great plugin.  I would suggest it to allow manually upload a file which is excluded (ignored) by the `ignore` or `ignoreFile` setting.  May give a prompt.

## Expected Behavior
Allow manual "SFTP: Upload" action for an excluded file to prompt for confirmation.

## Actual Behavior
Manual trigger "SFTP: Upload" for an excluded file does nothing.

## Steps to Reproduce the Problem

Already clear enough?

## Specifications

  - Version: 1.4.1  (vscode version 1.26.0)
  - Platform: macOS

## Note

Ignore files are sometimes different files in local against the server, thus not to be uploaded when `uploadOnSave`.  However, it doesn't mean I will never upload such file to server?

Or please provide a "SFTP: Force Upload" command (with confirmation) would be great.

**Comment by johnnytemp** [comment]
Besides, it may not clear what behavior is proper when upload a directory, that itself may be ignored, or it contains ignored files...

**Comment by liximomo** [comment]
@johnnytemp Try v1.5.0. The Download/Upload on file will automatically disregard ignore rules. You can use [Alt Commands](https://github.com/liximomo/vscode-sftp#alt-commands) `Force Download/Upload` to work with folders.

**Comment by johnnytemp** [comment]
Tested that it works. Thank you very much. ^^
