### ISSUE TITLE
Error: Activating extension 'liximomo.sftp' failed

### ISSUE THREAD

**Issue by markbref** [liximomo/vscode-sftp#314]
## Steps to Reproduce the Problem

Update vscode to v.1.27.2

## Requisites (**important to diagnose the problem!**)
 Developer tools console:
```
 INFO no standard startup: panel is active
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Activating extension 'liximomo.sftp' failed: Cannot find module './FileSystem'.
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:276
```
  ### Extension Logs
  none

## Specifications

  - Version: 1.27.2
  - Platform: Linux Ubuntu 18.04

![screenshot from 2018-09-14 11-41-44](https://user-images.githubusercontent.com/8521425/45542984-b4ae2080-b813-11e8-93ed-5ce46a818dc6.png)

**Comment by liximomo** [comment]
Try v1.5.3.

**Comment by markbref** [comment]
v1.5.3
Developer tools console:
```
[Extension Host] Activating extension 'liximomo.sftp' failed: Cannot find module './RemoteClient'.
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:276
```

**Comment by markbref** [comment]
Could be something to do with: https://github.com/Microsoft/TypeScript/issues/3792

**Comment by liximomo** [comment]
@markbref Thanks for the information. Try v1.5.4.

**Comment by markbref** [comment]
v1.5.4
Working again, thanks! :slightly_smiling_face: 

closing issue
