### ISSUE TITLE
FEATURE REQUEST: Add a parameter for connection name

### ISSUE THREAD

**Issue by klopp1892** [liximomo/vscode-sftp#315]
Hey guys,

Can we set up somehow a connection name for each connection from the remote explorer? I have a lot of FTP/SFTP connections defined, having to open a lot of them to figure out which is the one I need for the moment.

Please see the attached screenshot. Due to the fact that I have "remotePath": "/", the first directory name is empty. I don't want to have the directory name in there, but a custom name.
![screenshot](https://user-images.githubusercontent.com/42695717/45569041-0e8c0600-b867-11e8-8c89-e2b7171ff0dd.png)

**Comment by huanqingdong** [comment]
great,i need this feature too.

**Comment by liximomo** [comment]
v1.5.8 shows name now.
