### ISSUE TITLE
Feature Request: adapt for the new multi-root workspaces

### ISSUE THREAD

**Issue by sstoychev** [liximomo/vscode-sftp#32]
One of the major changes which is coming is the ability to open multiple folders at the same time.
Could you adapt it for this?
Currently when I have 2 folders opened at the same time it is working only for the first one.

https://code.visualstudio.com/updates/v1_16#_multi-root-workspace-tips-for-extension-authors

**Comment by liximomo** [comment]
I'm working on it.

**Comment by liximomo** [comment]
Done! Try 0.8.0. Feedback is welcome!

**Comment by sstoychev** [comment]
I was about to write it is not working correctly and you released 8.0.1 ;)

Now everything works! Awesome!
