### ISSUE TITLE
Watched CSS file only uploaded if using wildcard

### ISSUE THREAD

**Issue by arcaswebdesign** [liximomo/vscode-sftp#320]
## Expected Behavior
I have a watcher set for a single CSS file **"files": "templates/shaper_helixultimate/css/custom.css",** which is a file compiled to by SCSS so that after compilation the file is then FTP'd up.

## Actual Behavior
The file is recompiled (confirmed by viewing the file itself) but the watcher doesn't upload it. I _can_ get the watcher to upload it by changing it to **"files": "templates/shaper_helixultimate/css/*.css",** instead.

## Steps to Reproduce the Problem
1. Create an SCSS file
2. Use "Live Sass Compiler" extension (v3.0.0) to monitor this file and compile to custom.css
3. Set SFTP to watch the custom.css file and upload on change
4. Make a change to the SCSS file, then confirm it's been compiled into custom.css. Check if file has been uploaded (since it's been changed by the compiler) but it has not.
5. Adjust the SFTP watcher to watch for *.css instead of custom.css.
6. Make another change to SCSS file, confirm it's been compiled. Check if file has been uploaded by SFTP watched - it has now been uploaded.

## Requisites (**important to diagnose the problem!**)
- Use Live Sass Compiler (or other) to compile and modify the stylesheet the watcher is watching

  ### Extension Logs
[info] [file-save] d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss
[trace] handle upload file for d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss
[debug] < 220-#########################################################\r\n220-Please upload your web files to the public_html directory.\r\n220-Note that letters are case sensitive.\r\n220-#########################################################\r\n220 This is a private system - No anonymous login
[debug] > USER arcas@avizandum.co.uk
[debug] < 331 User arcas@avizandum.co.uk OK. Password required
[debug] > PASS ******
[debug] < 230-Your bandwidth usage is restricted\r\n230 OK. Current restricted directory is /
[debug] > FEAT
[debug] < 211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n UTF8\r\n TVFS\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n211 End.
[debug] > TYPE I
[debug] < 200 TYPE is now 8-bit binary
[trace] transfer from d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss to /templates/shaper_helixultimate/scss/custom/_base.scss
[debug] > PASV
[debug] < 227 Entering Passive Mode (77,104,180,91,135,68)
[debug] > LIST -al /templates/shaper_helixultimate/scss
[debug] < 150 Accepted data connection
[debug] < 226-Options: -a -l \r\n226 13 matches total
[debug] > PASV
[debug] < 227 Entering Passive Mode (77,104,180,91,135,80)
[debug] > STOR /templates/shaper_helixultimate/scss/custom/_base.scss
[debug] < 150 Accepted data connection
[debug] < 226-File successfully transferred\r\n226 0.168 seconds (measured here), 4.55 Kbytes per second
[info] transfer d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss
[info] config at d:\xampp\htdocs\avizandum {"remotePath":"/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"port":21,"name":"Avizandum","host":"uk51.siteground.eu","username":"******","password":"******","watcher":{"files":"templates/shaper_helixultimate/css/*.css","autoUpload":true,"autoDelete":false}}
[debug] < 226 Logout.
[info] [file-save] d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss
[trace] handle upload file for d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss
[debug] < 220-#########################################################\r\n220-Please upload your web files to the public_html directory.\r\n220-Note that letters are case sensitive.\r\n220-#########################################################\r\n220 This is a private system - No anonymous login
[debug] > USER arcas@avizandum.co.uk
[debug] < 331 User arcas@avizandum.co.uk OK. Password required
[debug] > PASS ******
[debug] < 230-Your bandwidth usage is restricted\r\n230 OK. Current restricted directory is /
[debug] > FEAT
[debug] < 211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n UTF8\r\n TVFS\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n211 End.
[debug] > TYPE I
[debug] < 200 TYPE is now 8-bit binary
[trace] transfer from d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss to /templates/shaper_helixultimate/scss/custom/_base.scss
[debug] > PASV
[info] [watcher-update] d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\css\custom.css
[trace] handle upload for d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\css\custom.css
[trace] transfer from d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\css\custom.css to /templates/shaper_helixultimate/css/custom.css
[debug] < 227 Entering Passive Mode (77,104,180,91,135,166)
[debug] > LIST -al /templates/shaper_helixultimate/scss
[debug] < 150 Accepted data connection
[debug] < 226-Options: -a -l \r\n226 13 matches total
[debug] > PASV
[debug] < 227 Entering Passive Mode (77,104,180,91,135,198)
[debug] > LIST -al /templates/shaper_helixultimate
[debug] < 150 Accepted data connection
[debug] < 226-Options: -a -l \r\n226 21 matches total
[debug] > PASV
[debug] < 227 Entering Passive Mode (77,104,180,91,135,12)
[debug] > STOR /templates/shaper_helixultimate/scss/custom/_base.scss
[debug] < 150 Accepted data connection
[debug] < 226-File successfully transferred\r\n226 0.167 seconds (measured here), 4.61 Kbytes per second
[debug] > PASV
[info] transfer d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\scss\custom\_base.scss
[debug] < 227 Entering Passive Mode (77,104,180,91,135,219)
[debug] > STOR /templates/shaper_helixultimate/css/custom.css
[debug] < 150 Accepted data connection
[debug] < 226-File successfully transferred\r\n226 0.189 seconds (measured here), 122.04 Kbytes per second
[info] transfer d:\xampp\htdocs\avizandum\templates\shaper_helixultimate\css\custom.css
 

## Specifications
  - Version:1.5.6
  - Platform: Windows 10 x64

**Comment by liximomo** [comment]
The fix [vscode](https://github.com/Microsoft/vscode/issues/57475) will be released in September.
