### ISSUE TITLE
Suggestion: Upload a list of files with a status bar button

### ISSUE THREAD

**Issue by gsabater** [liximomo/vscode-sftp#326]
## Expected Behavior
With Deploy Reloaded ( https://github.com/mkloubert/vscode-deploy-reloaded ) I can define a list of files (for example, bundle.js and bundle.css, or all my composer folder, etc), and then, setup a statusbar button that would upload all those files when pressed.

I like this extension way more, but the other feature is a life saver when you are working with webpack all the time and you need to upload those files constantly.

You can watch the files for changes, but sometimes those files have not changed on your computer or you simply need to upload a local unchanged file.

Thanks

**Comment by liximomo** [comment]
I would consider this.

**Comment by liximomo** [comment]
Currently, I will not add the custom status bar button. You can upload a list of files via keybindings. 

```jsonc
{
    "key": "ctrl+shift+cmd+u",
    "command": "sftp.upload",  //  or  "sftp.download", "sftp.syncToRemote", "sftp.syncTolocal"
    "args": [
      "/path/to/file",
      "/must/be/absolute/path",
    ]
}
```
