### ISSUE TITLE
How to map a folder?

### ISSUE THREAD

**Issue by elieobeid7** [liximomo/vscode-sftp#334]
I have a local folder, I have the exact copy on the server. No need to sync, folders already exist

I want that  if I edit locally a file in `folder/someotherfolder/file`, it gets saved in the exact location on the server. 

In other words, I don't want to keep searching for a file remotely, download and edit. How to do that?

**Comment by liximomo** [comment]
1. open your local folder with vscode.
2. run command `SFTP: Config`.
3.  set `remotePath` to  `/folder/someotherfolder/`

**Comment by elieobeid7** [comment]
Okay thank you and nice profile picture btw, I might steal it :)

**Comment by elieobeid7** [comment]
btw your solution implies that for every folder in my project, I have to create a config file. That sucks

**Comment by liximomo** [comment]
1. Open folder /a.
2. Run command SFTP: Config
3.  Use ` context`.

```
[
   {
      "context": "/a/b"
      "remotePath": "/remote/a/b"
   },
   {
      "context": "/a/c"
      "remotePath": "/remote/a/c"
   }
}
```

**Comment by elieobeid7** [comment]
Yeah I understood Sir, I'm just saying that it would be better if it works like PHPStorm, where you only specify the parent directory

```
[
   {
      "context": "/a/b"
      "remotePath": "/remote/a/b"
   }
]
```

And then if you edit `/a/b/c/d/`, it will automatically map that to the equivalent remote path, without explicitly writing it in Json. PHPstorm stfp does that by default, and I think sublime text sftp too, although not sure about sublime.

Because as it stands, when you create a new local directory, you should create it on the remote server and then tell the plugin in Json to map it, like your example. What I want is that the plugin create the directory and map it automatically. PHPstorm does that.

Anyhow I'll close the issue now, if that feature is implemented now or in the future let me know.

**Comment by liximomo** [comment]
@elieobeid7 It's did works like PHPStorm.

**Comment by elieobeid7** [comment]
Ahh! okay sorry for misunderstanding
