### ISSUE TITLE
Directly download remote file/folder

### ISSUE THREAD

**Issue by arcaswebdesign** [liximomo/vscode-sftp#338]
## Expected Behavior
Whilst browsing the remote server it would be nice to be able to right-click on a file or folder and be able to select it for upload/download, just as we can do from the local folder view. Or just to be able to open it directly by double clicking and still be able to edit it.

## Actual Behavior
We only have the ability to Delete or Reveal in Explorer when right-clicking and when double-clicking a remote file to open, it is opened in read-only mode so no edits can be made.

## Steps to Reproduce the Problem

  1. Browse remote folders
  1. Select a file or folder for download and right click.

## Requisites (**important to diagnose the problem!**)
n/a
 

## Specifications

  - Version: VS: 1.27.2 / SFTP: 1.5.10
  - Platform: Windows x64

**Comment by CWrecker** [comment]
is it possible to delete files on the ftp server from the local project menu which is synced with the ftp server, but not on the SFTP browser?

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/wiki/Setting#downloadwhenopeninremoteexplorer

**Comment by senica** [comment]
This doesn't solve the problem of downloading an entire directory. I've finding working with this plugin very cumbersome because of this. You should still be able to right-click and download something.

I ended up having to create a directory locally, then right clicking locally and syncing. It's nice to be able to just stay in the remote view and work on files (when I absolutely have to).

**Comment by arcaswebdesign** [comment]
The approach I take, @senica, is to browse the remote directory and select any file within it, then right-click and download it. I then switch to my local listings and the folder will have been created for me with the single file I downloaded within it. I then simply right-click on the folder which was created and click to download the entire folder.
