### ISSUE TITLE
doesn't upload php file and deleting doesn't work

### ISSUE THREAD

**Issue by xdon82** [liximomo/vscode-sftp#339]
doesn't upload php file and deleting doesn't work

**Comment by CWrecker** [comment]
i have this same issue. deleting doesn't work. i want to be able to delete files not from the SFTP menu, but from my project file menu or windows explorer, is this possible to do this and update on the ftp server?

**Comment by liximomo** [comment]
@CWrecker Please file a new issue according to the template.
