### ISSUE TITLE
Config file not found on windows

### ISSUE THREAD

**Issue by fahjan** [liximomo/vscode-sftp#34]
Today after upgrade vscode ... i cant upload any file.
## Steps to Reproduce the Problem
Config file:
![image](https://user-images.githubusercontent.com/2186011/30728599-c6f11ac0-9f61-11e7-86b0-d1a5ed032bf7.png)

Error:
![image](https://user-images.githubusercontent.com/2186011/30728616-eb2665bc-9f61-11e7-966a-136403f46675.png)

my plugin
![image](https://user-images.githubusercontent.com/2186011/30728719-a98ef528-9f62-11e7-8ec9-8df36735a27e.png)

## Requisites

windows 10
 vscode
![image](https://user-images.githubusercontent.com/2186011/30728739-e11f1842-9f62-11e7-8a9c-b5f2c6410e86.png)

**Comment by liximomo** [comment]
Could you provide me the log?

**Comment by liximomo** [comment]
I think the 0.8.1 would fix this.

**Comment by karaichev** [comment]
I have the same problem.
VSCode 1.16.1
sftp 0.8.1

![image](https://user-images.githubusercontent.com/5627125/30774095-0efbec26-a086-11e7-8438-b7e121a8077b.png)

```
[error]: context: undefined reason: Error: (d:\sk\projects\vscode) config file not found
	at runTask (C:\Users\sk\.vscode\extensions\liximomo.sftp-0.8.1\out\src\helper\createCommand.js:13:19)
	at Array.forEach (native)
	at runTasks (C:\Users\sk\.vscode\extensions\liximomo.sftp-0.8.1\out\src\helper\createCommand.js:16:52)
	at getTarget.then.target (C:\Users\sk\.vscode\extensions\liximomo.sftp-0.8.1\out\src\helper\createCommand.js:22:9)
	at <anonymous>
```

**Comment by liximomo** [comment]
Could you provide me the log from vs code startup?

**Comment by fahjan** [comment]
Now, Only now. its working...
Thank you too much 👍

**Comment by liximomo** [comment]
@karaichev just reload vscode.

**Comment by karaichev** [comment]
@liximomo Excellent. It works now. Thank you!
