### ISSUE TITLE
Feature Request: Open terminal and connect to SSH using settings stored in sftp.json

### ISSUE THREAD

**Issue by andrewreal** [liximomo/vscode-sftp#341]
Would it be possible to add a feature to open an SSH Terminal (probably using the built in VS Code Terminal) using the connection settings stored in the sftp.json file?

While working on a remote server it's often useful to log into the server and run commands like tail to monitor a debug or error log. Using the same configuration file would help to reduce the amount of typing required to login or set up another extension to SSH.

**Comment by liximomo** [comment]
Support in v1.7.2
