### ISSUE TITLE
diff with remote has no activeFile option

### ISSUE THREAD

**Issue by yu-cover** [liximomo/vscode-sftp#342]
When I set keyboard shortcuts to `diff with remote`，There is an error appear：` can't read property 'resource' of undefind`.
This is the same with `upload file` shortcut command，but this can be instead with command `upload active file` .
`diff with remote` command has no `active` option

**Comment by liximomo** [comment]
Support in v1.5.12.

**Comment by yu-cover** [comment]
> Support in v1.5.12.

谢谢支持
