### ISSUE TITLE
"uploadOnSave" not working for non-subdirectory context

### ISSUE THREAD

**Issue by qqkookie** [liximomo/vscode-sftp#343]
## Expected Behavior
"uploadOnSave" option should work even for the context which is NOT subdirectory of working folder (where the .vscode/sftp.jason is)  but referenced like "../../aaa". If  uploadOnSave is set "true" for the context, then remote file is retrieved, and "Edit in local" and edit and save, then it should be uploaded to automatically remote.

## Actual Behavior
The "uploadOnSave" option does not work for such context. User have to issue command explicitly to upload the saved file, with  either "Upload" context menu or Ctrl-Shift-P  and "SFTP: Upload Active File" command. Other files in the working folder are successfully updated on save in remote host, as expected.

## Steps to Reproduce the Problem

For example,  working source folder is C:/GitHub/working ( and .vscode/sftp.json lives)
and remote file to edit is download into C: /Users/Smith/Desktop/LocalXYZ",
{
    "name": "Remote",
    "context": "../../Users/Smith/Desktop/LocalXYZ",
    "protocol": "ftp",
    "host": "remotehost.com",
    "username": "smith",
    "password": "pw",
    "remotePath": "/RemoteXYZ",
    "autoUpload": true,
    "uploadOnSave": true
}

1. Load project files with "Open Folder" menu and select "C:/GitHub/working" folder.
2. Open  SFTP pane and select remote file to edit. for example "xyzmemo.txt"
4.  On context menu, select "Edit in Local"
5.  Do some edit and save with Ctrl-S
6. Check if the remote "xyzmemo.txt" file is modified (Not modified!)
7. On "xyzmemo.txt" edit window context menu, select "Upload"
8. Check again if the remote file is modified (Uploaded and modified!)

### Extension Logs
Enabled sftp debug logging, but no sftp log is displayed in Output panel 

## Specifications

  - Version: sftp 1.5.11, vscode:  1.27.2
  - Platform: Windows  10

I hope that the  the "context:" option supports absolute path name like "C:/Users/Smith/Desktop/LocalXYZ", as well as relative path like  "../../Users/Smith/Desktop/LocalXYZ". I tried both, but neither are working "uploadOnSave" option.

**Comment by liximomo** [comment]
It's expected. VSCode doesn't watch files outside of working folders.
