### ISSUE TITLE
Can you please rename context menu items?

### ISSUE THREAD

**Issue by flddr** [liximomo/vscode-sftp#345]
Sorry, it might be a little creepy, but i can never remember what those two items in the VS Code context menu should do (without lost my data):

![image](https://user-images.githubusercontent.com/42785945/46634244-7ecd3500-cb50-11e8-9768-20fd4696abd6.png)

To understand:
Means **Sync To Remote** more **Sync _From Local_ To Remote** or **Sync _Local_ To Remote**? The same for **Sync To Local**. Means it more **Sync _From Remote_ To Local** or **Sync _Remote_ To Local**?

I am dare to use those functions because i never know if something wrong happens if i am a little bit to busy :) Btw.: they never did what i thought they would do.

So, better could be:
`Sync To Remote (Upload Files)` or `Sync To Local (Download Files)`
`Sync To Remote (Local is Master)` or `Sync To Local (Remote is Master)`
or something like this :)

Maybe you have better names at all ;)

Thank you 👍

**Comment by liximomo** [comment]
Good advice!

**Comment by liximomo** [comment]
Done in  v1.6.0.
