### ISSUE TITLE
Feature Request: Prompt for ssh key passphrase

### ISSUE THREAD

**Issue by objcow** [liximomo/vscode-sftp#346]
It feels very insecure to have to save my ssh key passphrase in plaintext in order to use keys to authenticate with servers. Since vscode-sftp already prompts for ssh password when it's not stored, can we do this for key passphrases as well?

**Comment by liximomo** [comment]
```
"passphrases": true
```

**Comment by nickdaugherty** [comment]
Why is this not in the docs? It's also `"passphrase": true` (single). Took me forever to figure this out.

**Comment by jgrizou** [comment]
This worked for me:
```
"passphrase": true,
"interactiveAuth": true
```

Note that "passphrase" is singular - no trailing 's'
