### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by advokatb** [liximomo/vscode-sftp#35]
Hi. Please explain what
 `[sftp] Received exit code 1 while establishing SFTP session`
error means?
I put valid credentials for ftp server, but upload fails with this eror.
Can't figure out what is wrong?

**Comment by liximomo** [comment]
Please provide your config.

**Comment by advokatb** [comment]
`{
    "host": "ftp.server.com",
    "port": 22,
    "username": "login_name",
    "password": "password",
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": true,
    "interactiveAuth": false,
    "remotePath": "/wp-content/themes/azaza/",
    "uploadOnSave": false,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "**/.vscode/**",
        "**/.git/**",
        "**/.DS_Store"
    ]
}`

**Comment by liximomo** [comment]
I think the problem is about of your server. This may help [exit code 1](https://www.linuxquestions.org/questions/linux-software-2/ssh-exits-on-successful-login-4175458708/).

**Comment by johncarey84** [comment]
I just had this same issue exit code 1. Turns out my ssh password was expired. Resetting the password solved the issue.
