### ISSUE TITLE
When "passive=false" it opens an passive Connection

### ISSUE THREAD

**Issue by Azoth128** [liximomo/vscode-sftp#354]
## Expected Behavior
When write "passive=false" into the settings the client should't open a passive connection.

## Actual Behavior
The Client opens a Passive Connection with PASV-commands.

## Steps to Reproduce the Problem

  1. Setting up an FTP-Connetion with "passive=false"
  2. enable debug-print
  3. Run a command and see debug output

### Extension Logs (anonym)
[debug] < 220 Microsoft FTP Service
[debug] > USER myUser
[debug] < 331 Password required for myUser.
[debug] > PASS ******
[debug] < 230 User logged in.
[debug] > FEAT
[debug] < 211-Extended features supported:
[debug] <  LANG EN*\r\n UTF8
[debug] <  AUTH TLS;TLS-C;SSL;TLS-P;\r\n PBSZ\r\n PROT C;P;\r\n CCC\r\n HOST
[debug] <  SIZE\r\n MDTM\r\n REST STREAM\r\n211 END
[debug] > TYPE I
[debug] < 200 Type set to I.
[debug] > PASV
[debug] < 227 Entering Passive Mode (x,x,x,x,238,85).
[debug] > ABOR
[debug] < 226 ABOR command successful.

   ### Settings (anonym)

{
    "name": "myName",
    "protocol": "ftp",
    "host": "myHost",
    "port": 21,
    "username": "myUsername",
    "password": "myPass",
    "remotePath": "/myDir",
    "passive": false,
    "secure": false
}

## Specifications

  - Version: 1.6.0
  - Platform: Windows 10 build 17763.55

**Comment by liximomo** [comment]
It doesn't support active mode.
