### ISSUE TITLE
Problems with Azure SFTP (username)

### ISSUE THREAD

**Issue by mformanu** [liximomo/vscode-sftp#357]
## Expected Behavior
The plugin should use the provided username from Azure which contains a backslash-character. Example: "WebsiteOrProjectName\username" is needed as username in the credentials.

## Actual Behavior
"Error in string, unexpected character" is reported through console. The extension tab stops working at all if the username is not removed.

## Steps to Reproduce the Problem

Use my example name as username, error is shown on save.

Thanks in advance!

**Comment by liximomo** [comment]
```json
{
 "username": "WebsiteOrProjectName\\username"
}
```

**Comment by mformanu** [comment]
Well, should have thought about that… Thank you!
