### ISSUE TITLE
Don't create a config file

### ISSUE THREAD

**Issue by missfx** [liximomo/vscode-sftp#36]
## Expected Behavior
SFTP: config creates sftp.json now

## Actual Behavior
SFTP: config, nothing is created in the folder

## Steps to Reproduce the Problem

  1. command -> sftp:config 
![capture d ecran 2017-09-25 a 12 25 25](https://user-images.githubusercontent.com/1321387/30804174-b9e4a22e-a1ec-11e7-8071-3b5d0f44ec34.png)

  2. after select folder, nothing is created
 

### Extension Logs 
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 Ok

## Specifications

  - Version: last plugin version
  - Platform: visual code last Version 1.16.1 (1.16.1)

**Comment by liximomo** [comment]
After your first selection，what happened？Did another list with sub files pop up？

**Comment by missfx** [comment]
Nothing.. 
I tested with an another directory with a sub directory and it's the same, nothing happened

**Comment by tabishz** [comment]
experiencing the same issue, nothing happens.

**Comment by tphan18** [comment]
I got the same issue and had to manually create `.vscode/.sftpConfig.json`

**Comment by liximomo** [comment]
What's your OS? And please provide the logs.
>  set option sftp.printDebugLog to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)

**Comment by missfx** [comment]
Yes ! with 0.8.3 it's ok for me ! 👍  thk u !
