### ISSUE TITLE
How do I use this to work on a GCP instance?

### ISSUE THREAD

**Issue by soham96** [liximomo/vscode-sftp#360]
## Expected Behavior
[Description of the expected behavior]

## Actual Behavior
[Description of the actual behavior]

## Steps to Reproduce the Problem

  1. one.
  1. two.
  1. three.

### Extension Logs
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.printDebugLog` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
 

## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp#example-configs

**Comment by liximomo** [comment]
```
{
  "nane": "trial",
  "host": "192.123.456.789",
  "username": "soham",
  "remotePath": "/absolute/path/to/your/project"
}
```
