### ISSUE TITLE
File uploaded should use remote host timestamp.

### ISSUE THREAD

**Issue by Kernopike** [liximomo/vscode-sftp#361]
## Expected Behavior
The file uploaded should use remote host timestamp.

## Actual Behavior
Use local client timestamp.

## Steps to Reproduce the Problem

  1. modify local file.
  1. auto upload file changed.

## Specifications

  - Version: 1.6.3
  - Platform: Windows

**Comment by liximomo** [comment]
This will break `sync` command if host timestamp has been used.

**Comment by liximomo** [comment]
> CMake (remote host side) can't identify NEW changes by timestamp

Why? If you download a file from remote to local. After you edit it in local, the timestamp will get changed and so the transferred file.

**Comment by Kernopike** [comment]
# My Scenario

## Remote Host

Ubuntu 18 x64 server edition.

```bash
$ timedatectl status
                      Local time: Fri 2018-10-19 20:31:30 CST
                  Universal time: Fri 2018-10-19 12:31:30 UTC
                        RTC time: Fri 2018-10-19 12:31:28
                       Time zone: Asia/Shanghai (CST, +0800)
       System clock synchronized: no
systemd-timesyncd.service active: yes
                 RTC in local TZ: no

$ date
Fri Oct 19 20:32:21 CST 2018

```

## Local client

Windows 7 x64 edition.

Upload file I changed.

### sftp extension

Make example:

#### 1.5.8 Behavior

```bash
$ ll file_changed.cpp
-rw-rw-r-- 1 yy yy 3750 Oct 19 20:32 file_changed.cpp
```

This file(file_changed.cpp) can be compiled by make, which identified this is new version source.

#### 1.6.3 Behavior

```bash
$ ll file_changed.cpp
-rw-rw-r-- 1 yy yy 3752 Oct 19 12:32 file_changed.cpp
```

When I execute make, nothing is compiled. So, this is my problem. I can't `make` new version source.

**Comment by liximomo** [comment]
Ok. I will add an option for this scenario.

**Comment by Kernopike** [comment]
I disable UTC in ubuntu can conquer this issue I mentioned, but found that if file changed in 1 minute(I supposed), `make` will ignore this change. I'm not sure whether can be reproduced by old version(1.5.8).

**Comment by liximomo** [comment]
Try [remotetimeoffsetinhours](https://github.com/liximomo/vscode-sftp/wiki/Config#remotetimeoffsetinhours) option in v1.7.0.

**Comment by Kernopike** [comment]
Could you increase time offset accuracy? For example remote real time offset is actually +0:01:21, if I modify code, auto upload, in this time range, the remote compiller will still ignore this change. 

BTW, I don’t have permission to sync system time.

**Comment by liximomo** [comment]
@Kernopike  You can use a fraction number.
