### ISSUE TITLE
Profiles switch doesn't refresh remote explorer

### ISSUE THREAD

**Issue by deiberdev** [liximomo/vscode-sftp#362]
## Expected Behavior
Refresh sftp remote explorer view when I switch to a new profile.

## Actual Behavior
When I switch to a new remote profile, it really change but the sftp remote explorer view doesn't change.

## Steps to Reproduce the Problem

  1. Current profile: _develop_.
  2. `Ctrl+Shift+P`.
  3. `SFTP: Set Profile`.
  4. Select _production_ profile.

So far both the remote explorer (shows _develop_ profile) and sftp output remains unchanged, but if I check sftp with `SFTP: List`, it is really at _production_ profile. Even if I click ⟳ button, it remains in _develop_ remote explorer view.

### Extension Logs
  No output

## Specifications

  - Version: 1.6.0
  - Platform: Windows 8.1

**Comment by deiberdev** [comment]
I tried that with the ⟳ button, but it doesn't refresh.

**Comment by B0rner** [comment]
Same problem here, using Version 1.7.0 on Ubuntu.
`SFTP: Set Profile` does not change anything Remote Explorer View

**Comment by liximomo** [comment]
Fix in v1.7.4
