### ISSUE TITLE
Upload changed files to remote according to git changes

### ISSUE THREAD

**Issue by duybinh0208** [liximomo/vscode-sftp#363]
## Expected Behavior
We should have a function (can be a menu item or button...) to upload all changed files at the same time from local to remote according to git status.

## Actual Behavior
The function is missing.

## Steps to Reproduce the Problem
  0. Open your git project in Visual Studio Code then install and configure vscode-sftp extension
  1. Changes some files.
  2. Show list of changed files by "git status" to make sure that git has tracked all changed files.
  3. There is no ways to sync these changed files to remote together. Instead, we must open every single file and sync it to remote one by one. This will take a lot of time and not very efficient.

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/wiki/Commands#sftp-upload-changed-files

**Comment by sebastianjung** [comment]
Does this actually work? When i press the button nothing happens. Ouput says the following:

[trace] run command 'Upload Changed Files'

Both debug log settings enabled and vscode restarted.

**Comment by rayr007** [comment]
I don't see the command at all. I only see these 3 upload commands:
- Upload Active File
- Upload Project
- Upload Active Folder

**Comment by mariela21180** [comment]
This has stopped working for me since last update

**Comment by matthewjschultz** [comment]
+1 to @mariela21180; this has stopped working for me too.
