### ISSUE TITLE
Add SSH connect

### ISSUE THREAD

**Issue by Hypdncy** [liximomo/vscode-sftp#366]
Hello there:
I am a loyal fan of sftp, I think it is great, but there are some requirements that can't satisfy me, that is, without the ssh function. When I work, I often use ssh, but it doesn't. I need ssh ”root@domain 22” to link ssh. Can you add this feature? For example: ctrl+shift+p --> SSH-TO-SERVER?
My English is very poor, please forgive me, thank you!
Hypdncy

**Comment by liximomo** [comment]
Duplicate of #341.
