### ISSUE TITLE
[sftp] All configured authentication methods failed

### ISSUE THREAD

**Issue by isaacjoh** [liximomo/vscode-sftp#37]
## Expected Behavior
Trying to upload file to server via sftp

## Actual Behavior
Getting error saying all configured authentication methods failed

## Steps to Reproduce the Problem
This is my sftp.json file:
```
{
    "host": "example@example.com",
    "port": 22,
    "username": "example_username",
    "password": "example_password",
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": true,
    "remotePath": "/example",
    "uploadOnSave": false,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "**/.vscode/**",
        "**/.git/**",
        "**/.DS_Store"
    ]
}
```

## Specifications

  - Version: 0.8.3
  - Platform: Mac OS X El Capitan 10.11.6

**Comment by liximomo** [comment]
I think the error messages it’s clear.

**Comment by liximomo** [comment]
Check your password.

**Comment by isaacjoh** [comment]
my password is correct :/

**Comment by fredyjl** [comment]
having same issue here

**Comment by liximomo** [comment]
Your ssh authentication failed. Check your sshd logs on your server. It has nothing to do with the extension.

**Comment by rubend151** [comment]
The same happened to me because I didn't specified the private key path, my mistake.

**Comment by manu** [comment]
Made modification in the server sshd config file /etc/ssh/sshd_config as below and it started working
<quote>
KexAlgorithms diffie-hellman-group1-sha1,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
Ciphers 3des-cbc,blowfish-cbc,aes128-cbc,aes128-ctr,aes256-ctr,aes192-cbc,aes256-cbc,arcfour
</quote>

**Comment by limux** [comment]
The same password will ok when interactiveAuth is true, so I am sure there is a bug somewhere.

**Comment by Mellnik** [comment]
Can confirm this is indeed a bug. If you have special characters in your password it won't work.

**Comment by luanxia0** [comment]
> The same password will ok when interactiveAuth is true, so I am sure there is a bug somewhere.

this method can solve it.

**Comment by evannalikeyou** [comment]
> The same password will ok when interactiveAuth is true, so I am sure there is a bug somewhere.

 try to enable inter `interactiveAuth`

**Comment by wangleihitcs** [comment]
check your host ip、port、username and password

**Comment by marcosgugeler** [comment]
I have enabled `interactiveAuth` and the problem has gone

**Comment by StarlingMercedes** [comment]
@marcosgugeler how im can active   interactiveAuth ??

**Comment by marcosgugeler** [comment]
@StarlingMercedes go to sftp.json file and add this line:

`"interactiveAuth": true`

Take a look at my file:

```
{
    "name": "My Site",
    "host": "my.ftp.net",
    "protocol": "sftp",
    "port": 5022,
    "username": "myftpuser",
    "password": "mypassword",
    "remotePath": "/home",
    "uploadOnSave": true,
    "interactiveAuth": true
}
```

**Comment by imooni** [comment]
If you have secondary authentication (eg:MFA) ,then the parameter "interactiveAuth" is required.

**Comment by kinh-nguyen** [comment]
for me `interactiveAuth` does not work but setting `privateKeyPath` to my `id_rsa` works.

**Comment by Kos-M** [comment]
whats the point of storing password in config , if we cant use it ?
Same here , 

```
{
    "name": "vps ",
    "host": "1.2.3.4",
    "password": "passwordpassword",
    "protocol": "sftp",
    "port": 22,
    "interactiveAuth": false,
    "username": "lv5",
    "remotePath": "/remote/path",
    "uploadOnSave": true ,
    "ignore": [".vscode" , ".git" , ".gitignore" , ".log"]
}

```

logs : 
```
02-28 13:46:21] [info] config at /my/paths/ {"remotePath":"/remote/path","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".vscode",".git",".gitignore",".log"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"vps ","host":"1.2.3.4","password":"******","port":22,"passive":false,"username":"******"}
```
```
"password":"******","port":22,"passive":false,"username":"******"}
```
Check password hided with * , is really smaller digits number than actual password. Maybe used a default string.. Or masked it with default "******""

**Comment by christianigay** [comment]
> for me `interactiveAuth` does not work but setting `privateKeyPath` to my `id_rsa` works.

thanks this one works

**Comment by nextlogic-ono** [comment]
In my case, server's `/var/log/auth.log` said,
> key type ssh-rsa not in PubkeyAcceptedAlgorithms

which lead to a solution by adding,
> PubkeyAcceptedKeyTypes=+ssh-rsa

in `/etc/ssh/sshd_config` and restart `sshd`.

Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

**Comment by fjd3lg4d0** [comment]
> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

This worked for me, same exact issue.

**Comment by wideflare** [comment]
> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

this works

**Comment by 9cat** [comment]
> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

this solved the problem !

**Comment by microwin7** [comment]
> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

This work `WSL Ubuntu 22.04 LTS` local + `Windows 10`
`password` remove in `sftp.json`
use `"privateKeyPath": "C:\\Users\\ANTON\\.ssh\\id_rsa",`

**Comment by jordansitbon** [comment]
> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

WORK PERFECTLY !

**Comment by utunga** [comment]
With a Ubuntu 22.04 Digital Ocean droplet I found that doing what @windware-ono suggested [above](https://github.com/liximomo/vscode-sftp/issues/37#issuecomment-1120677928) was almost but not quite enough. 

Looking at the` /var/log/auth.log` was very helpful but, looking at why it was failing I saw a different error. Per [this answer](https://unix.stackexchange.com/questions/340844/how-to-enable-diffie-hellman-group1-sha1-key-exchange-on-debian-8-0) i had to enable legacy support for diffie-hellman-group1-sha1 algorithm. After doing this I saw the `key type ssh-rsa not in PubkeyAcceptedAlgorithms` error... and so added `PubkeyAcceptedKeyTypes=+ssh-rsa`as well and then it worked.

So the changes in total was to add this to the bottom of `/etc/ssh/sshd_config` and restart sshd. (`systemctl restart sshd`) after doing that sftp from vscode worked as I wanted.

```
#Legacy changes
KexAlgorithms +diffie-hellman-group1-sha1
Ciphers +aes128-cbc
PubkeyAcceptedKeyTypes=+ssh-rsa
```

**Comment by nnxmxni** [comment]
> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

this worked for me

**Comment by rajhlinux** [comment]
This has worked for me as stated by:

> @StarlingMercedes go to sftp.json file and add this line:
> 
> `"interactiveAuth": true`
> 
> Take a look at my file:
> 
> ```
> {
>     "name": "My Site",
>     "host": "my.ftp.net",
>     "protocol": "sftp",
>     "port": 5022,
>     "username": "myftpuser",
>     "password": "mypassword",
>     "remotePath": "/home",
>     "uploadOnSave": true,
>     "interactiveAuth": true
> }
> ```

I did the following:

First press "F1" on vscode.
Then type "sftp:config" click on that option.
Then enter the following parameters:
```
{
    "name": "S_P",
    "host": "192.168.1.204",
    "protocol": "sftp",
    "port": 2222,
    "username": "user",
    "remotePath": "/home",
    "uploadOnSave": true,
    "interactiveAuth": true
}
```
Note: I left out password, since I rather type it manually.

Save and now everything works. I can finally log into the remote machine.
I'm using port 2222 because I am using OpenSSH server on the remote machine.
The client and host machine are both running on FreeBSD 13.1

Good god, finally we can use SFTP with VSCODE, there is also SSH on VSCode using it's built in terminal.
Great alternative to mobaxterm for us Unix/Linux users.

Happy dev-ing.

**Comment by gary9630** [comment]
> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

You save my day. Really appreciate it! Thank you

**Comment by akellehe** [comment]
ALL of this should be added to the FAQ.

**Comment by LuisFelipe1406** [comment]
> systemctl restart sshd



> In my case, server's `/var/log/auth.log` said,
> 
> > key type ssh-rsa not in PubkeyAcceptedAlgorithms
> 
> which lead to a solution by adding,
> 
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> in `/etc/ssh/sshd_config` and restart `sshd`.
> 
> Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin no longer worked despite `ssh` command working fine.

Thx man, you saved my life hahaha
