### ISSUE TITLE
[Proposal] Custom icon for files open with Remote Explorer

### ISSUE THREAD

**Issue by cyrilgandon** [liximomo/vscode-sftp#370]
## Expected Behavior

Get a visual hint that the file which is open is on remote. (I am not a designer ^^ )

![image](https://user-images.githubusercontent.com/2806672/47415437-b9031d00-d773-11e8-8bf7-016a70b7288f.png)

## Actual Behavior

File open locally or remotely are visually the same.

![sans titre](https://user-images.githubusercontent.com/2806672/47415301-688bbf80-d773-11e8-8391-34aa3bdad159.png)

**Comment by liximomo** [comment]
There is API to do this. But I can hack to show a text symbol in there. It's will in v1.7.2.

**Comment by cyrilgandon** [comment]
@liximomo Thank you, the new marker is awesome, I would not choose a better caracter :+1:
