### ISSUE TITLE
Support mappings of local path to remote path

### ISSUE THREAD

**Issue by frostming** [liximomo/vscode-sftp#374]
I don't know if it's supported but I went through the README and wiki and couldn't find a bit about this.

### Expected behavior:

Set mappings of local path to remote path like this:

```json
{
    ...
    "mapping": [
        {
            "localPath": "path/a",
            "remotPath": "remote/path/a"
        },
       ...
    ],
    ...
}
```
Local and remote path should be relative against local root and remote root respectively.

**Comment by liximomo** [comment]
1. Open "path/a",
2. 
```
{
 "remotPath": "remote/path/a"
}
```

**Comment by frostming** [comment]
@liximomo Yes I know that works but it isn't very flexible since your project root is not always the local root for transfer.

A common project structure is as below.

```
.
|-- README.md
|-- src
|   `-- myapp
|       `-- __init__.py
`-- LICENSE
```
And I just want `src\myapp` to sync somewhere on remote machine. I will be great if we have this feature.

**Comment by liximomo** [comment]
Yes. That why we have `context`.

```
{
  "context": "src/myapp",
  "remotPath": "remote/myapp"
}
```

**Comment by frostming** [comment]
@liximomo Oh it woks, I removed the context line because it causes FileServer error.

Now it works, thanks
