### ISSUE TITLE
uploadOnSave isn't working for my FTP connection

### ISSUE THREAD

**Issue by nguyandy** [liximomo/vscode-sftp#376]
Just want to start off by saying this extension is awesome.
One thing I haven't been able to figure out is with my ftp account.

It does not upload on save.
Here is my config

  {
    "protocol": "ftp",
    "name": "website.com",
    "context": "/",
    "host": "ftp.website.com",
    "username": "username",
    "password": "password",
    "port": 21,
    "remotePath": "/public_html",
    "uploadOnSave": true
  }

From the SFTP Remote Explorer, I right click on my file, "edit in local" since it says I can't edit the file since it is read only when I double click to open the file.

The log shows
[info] remote -> local c:\css\custom.css

But when I save, nothing happens.
However if I manually run SFTP - Upload Active File
Then it works.

Any thoughts why?
Thank you in advance

I'm using Windows 10, Visual Studio Code 1.28.2

**Comment by sassoleo** [comment]
Hello,
How did you fix uploadOnSave when using context? I still can't make auto save work when I use context.
