### ISSUE TITLE
Passphrase being prompted despite SSH agent

### ISSUE THREAD

**Issue by ozupey** [liximomo/vscode-sftp#377]
**Describe the bug**
I'm still being prompted for my SSH key passphrase despite enabling the SSH agent. When I use `ssh` or `sftp` on the command line, I'm never being prompted for my passphrase.

**To Reproduce**
1. Put `"agent": "$SSH_AUTH_SOCK",` in your config
2. Try to do anything that involves SSH
3. Get prompted for a passphrase

This also happens when I put the contents of `echo $SSH_AUTH_SOCK` as the agent.

**Expected behavior**
Use the SSH agent and don't prompt for a passphrase.

**Desktop (please complete the following information):**
 - OS X Mojave
 - VSCode 1.28.2
 - Extension 1.7.1

**Comment by liximomo** [comment]
At least, show me your config.

**Comment by ozupey** [comment]
Thanks for your quick response.

```{
    "protocol": "sftp",
    "host": "dev.myproject.com",
    "port": 22,
    "username": "root",
    "remotePath": "/var/www/myproject/",
    "uploadOnSave": true,
    "privateKeyPath": "/Users/ozupey/.ssh/id_rsa",
    "agent": "$SSH_AUTH_SOCK",
    "passphrase": true,
    "ignore": [".git"]
}```

or

```{
    "protocol": "sftp",
    "host": "dev.myproject.com",
    "port": 22,
    "username": "root",
    "remotePath": "/var/www/myproject/",
    "uploadOnSave": true,
    "privateKeyPath": "/Users/ozupey/.ssh/id_rsa",
    "agent": "/private/tmp/com.apple.launchd.GeEAeHXwlK/Listeners",
    "passphrase": true,
    "ignore": [".git"]
}```

**Comment by liximomo** [comment]
Remove this line `"passphrase": true,`;  

> For an encrypted private key, this is the passphrase string used to decrypt it. Set to true for enable passphrase dialog. This will prevent from using cleartext passphrase in this config.

**Comment by ozupey** [comment]
No joy I'm afraid:
`[error] Error: Encrypted private key detected, but no passphrase given`

**Comment by liximomo** [comment]
Remove this line  `"privateKeyPath": "/Users/ozupey/.ssh/id_rsa"`.

**Comment by ozupey** [comment]
Thanks a lot, that works great! Sending a donation your way soon. 👍

**Comment by liximomo** [comment]
Thanks for your support. 😄
