### ISSUE TITLE
"Diff with remote" is backwards

### ISSUE THREAD

**Issue by AlexMax** [liximomo/vscode-sftp#380]
I'm not really sure this counts as a feature request or a bug, so I'll just describe what confuses me. 
 When I right click on **Diff with Remote**, the added/removed items seem completely swapped.

For example, If I delete lines in my local copy and then click **Diff with Remote**, the diff shows the  local copy on the left and the remote copy on the right, with **+**'s next to the missing lines on the remote copy side.  This seems backwards to me - it should actually show **-**'s next to the removed lines on the local copy side.

Likewise, if I add a line in my local copy and then click **Diff with remote**, it shows **-**'s next to the added lines on the local copy side.  Again, this seems backwards, it should show **+**'s next to the added lines.

I think this could be fixed by reversing the order that you pass the parameters to whatever diff function you are using.

**Comment by liximomo** [comment]
Thanks for your advice.

**Comment by liximomo** [comment]
Fix in v1.7.3
