### ISSUE TITLE
Sync Local->Remote does not delete files/folders

### ISSUE THREAD

**Issue by vctrlt** [liximomo/vscode-sftp#381]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When syning to the remote server, files which don't exist in local but exist in remote, are not deleted in remote server. It happens the other way around too  (remote->local)

**To Reproduce**
1. "syncMode": "full" in the config. file
2. Right click on a folder
3. Run Sync Local->Remote from the contextual menu
4. Check the remote server with SSH, see that files which don't exist on local have not been deleted on remote

**Expected behavior**
Files that don't exist on local and exist on remote should be remove on remote

**Desktop (please complete the following information):**
 - OS: Win
- Version: 1.28.2 (user setup)

**Extension Logs** - *required*

[trace] run command 'Sync Local To Remote'
[trace] handle sync for c:\folder
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPENDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)

**Comment by vctrlt** [comment]
Version is 1.7.2

Full config file:
```

{
    "name": "app",
    "context": "./src/app",
    "protocol": "sftp",
    "port": 22,
    "host": "x.x.x.x",
    "username": "user",
    "remotePath": "/home/user/public",
    "privateKeyPath": "C:/Users/user/.ssh/key.ppk",
    "passphrase": true,
    "uploadOnSave": true,
    "syncMode": "full",
    "ignore": [
        ".vscode",
        ".git",
        "node_modules"
    ]
}

```

**Comment by liximomo** [comment]
```
"syncOption": {
  "delete": true
}
```

**Comment by vctrlt** [comment]
Thank you for the help!

**Comment by CWrecker** [comment]
i get an error, every time i sync local -> remote:
:/ Device or Resource busy

**Comment by CWrecker** [comment]
[error] Error: /: Device or resource busy
    at v (C:\Users\Camden_2\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:70:106078)
    at d.<anonymous> (C:\Users\Camden_2\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:70:106801)
    at emitTwo (events.js:126:13)
    at d.emit (events.js:214:7)
    at d._write (C:\Users\Camden_2\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:70:119623)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at d.Writable.write (_stream_writable.js:290:11)
    at Socket.p (C:\Users\Camden_2\.vscode\extensions\liximomo.sftp-1.8.1\dist\extension.js:70:109172)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20) 

It would be nice if we didnt have to press sync all the time anyways, and any changes made in local are reflected on the ftp server!

**Comment by markusprograms** [comment]
I tried setting the configuration as liximomo advised but it didn't solve the problem, the file still remained on the remote server. I instead created a watcher to track all locally deleted files: 

```json
"watcher": {
    "files": "**/*",
    "autoUpload": true,
    "autoDelete": true
}, 
```

An example configuration would looks something like this: 
```json
{
    "name": "My website",
    "host": "localhost",
    "protocol": "ftp",
    "port": 21,
    "username": "user",
    "remotePath": "/",
    "uploadOnSave": true,
    "useTempFile": false,
    "openSsh": false, 
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    }
}
```

**EDIT**: This fix works on the new SFTP version by Natizyskunk.
