### ISSUE TITLE
Add "Upload File" in context menu of source control panel

### ISSUE THREAD

**Issue by mikestp27** [liximomo/vscode-sftp#382]
**Is this a similar or duplicate feature request?**
- No.

**Is your feature request related to a problem? Please describe.**
This is a request for a new feature

**Describe the solution you'd like**
When looking at the "modified files" in the "Source control" panel (left side bar), it's possible to right-click on a file and "Open File" or "Commit Selected File"...   It would be great to be able to "Upload Selected File" also...  This would allow to commit and upload all from the same panel.  Otherwise, need to go to "File Explorer" panel to upload files and then "Source Control" panel to commit same files.

**Describe alternatives you've considered**
Haven't found any other alternative.

**Does this project help you?**
- Yes. [I'm willing to support you if this can be added.] (https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Support in v1.7.3
