### ISSUE TITLE
Testing a connection after config setup

### ISSUE THREAD

**Issue by zigojacko** [liximomo/vscode-sftp#383]
Just setting up this extension for the first time...

I have a workspace in the explorer and I have just set up a sftp.json config that has been placed in the .vscode directory.

How can I now test the connection and ensure my config is correct? Anyway to browse the remote side (to see if it connects) or do I literally have to test by performing a sync or downloading/uploading a file?

**Comment by liximomo** [comment]
Run `view: show  sftp` in Command Palette.

**Comment by zigojacko** [comment]
Got it, thanks. Bit slow though :open_mouth:
