### ISSUE TITLE
Connection via SSH keys and passphrase not working

### ISSUE THREAD

**Issue by chross** [liximomo/vscode-sftp#387]
**Describe the bug**
An error message is displayed: "Encoding too long" when trying to log in with a SSH key. When using the right-click menu in SFTP: Remote Explorer and selecting "Open SSH in Terminal", SSH will login instantaneously without problems.
Command line shown:
ssh root@ihg -p 22 -i /home/username/.ssh/id_rsa

**To Reproduce**
1. Use the sftp config with privateKeyPath set to the id_rsa key
2. Using a passphrase that fits the rsa key above
3. ERROR: "Encoding too long"

**Expected behavior**
sftp to work normally, i.e. display folder tree

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - VSCode Version [e.g. 1.28.2]
 - Extension Version [e.g. 1.7.3]

**Extension Logs** - *required*
[info] config at /home/username/redacted
{"remotePath":"/space","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"host":"myhost","username":"******","name":"space","privateKeyPath":"/home/username/.ssh/id_rsa","passphrase":"******"}

**Comment by liximomo** [comment]
Check your passphrase.

**Comment by liximomo** [comment]
Just hover on it. 

![image](https://user-images.githubusercontent.com/9816225/48103843-e370d200-e26b-11e8-88e2-30f1b4aa6d04.png)
