### ISSUE TITLE
privateKeyPath interpretation error when containing "~" and used in multiple profiles

### ISSUE THREAD

**Issue by wuqiling97** [liximomo/vscode-sftp#388]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**
when using multiple profiles, and put privateKeyPath in it, "~" in path will be wrongly interpreted as "C:\Program Files\Microsoft VS Code\\\~"

**To Reproduce**
1. open sftp.json
2. use multiple profiles and put "privateKeyPath": "~\.ssh\id_rsa" in it
3. sync files, and the extension will prompt "[error] Error: ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\\\~\.ssh\id_rsa' "

**Expected behavior**
"~\\.ssh\id_rsa" will be interpreted as "C:\Users\your_username\\.ssh\id_rsa"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 1803 build 17134.345
 - VSCode Version: 1.28.2
 - Extension Version: 1.7.3

**Extension Logs** - *required*
note: sensitive information has been replaced by "xx"

[info] config at c:\Users\abc\Code\Lab\meshsdf\meshsdf-src {"remotePath":"/home/wql/meshsdf/meshsdf-src/","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store","build","condor_log","data","condor*",".idea"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"defaultProfile":"lkx","profiles":{"lkx":{"host":"xx.xx.xx.xx","port":36000,"privateKeyPath":"~/.ssh/id_rsa"}},"watcher":{"files":"glob","autoUpload":false,"autoDelete":false}}
[trace] run command 'Sync Local To Remote'
[trace] handle sync for c:\Users\abc\Code\Lab\meshsdf\meshsdf-src
[debug] Local ident: 'SSH-2.0-ssh2js0.2.1'
[debug] Client: Trying 166.111.69.12 on port 3003 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] KEX algorithm: ecdh-sha2-nistp256
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[debug] Client->Server Cipher: aes128-ctr
[debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[debug] Server->Client Cipher: aes128-ctr
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Client->Server HMAC algorithm: hmac-sha2-256
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Server->Client HMAC algorithm: hmac-sha2-256
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (password)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPENDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPENDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] local -> remote c:\Users\abc\Code\Lab\meshsdf\meshsdf-src\.gitignore
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] local -> remote c:\Users\abc\Code\Lab\meshsdf\meshsdf-src\meshsdf.cpp
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] local -> remote c:\Users\abc\Code\Lab\meshsdf\meshsdf-src\sdf.cu
[info] local -> remote c:\Users\abc\Code\Lab\meshsdf\meshsdf-src\CMakeLists.txt
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing WRITE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing FSETSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] local -> remote c:\Users\abc\Code\Lab\meshsdf\meshsdf-src\SDFAlgs.cpp
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] local -> remote c:\Users\abc\Code\Lab\meshsdf\meshsdf-src\SDFAlgs.h
[trace] run command 'Set Profile'
[trace] run command 'Sync Local To Remote'
[trace] handle sync for c:\Users\abc\Code\Lab\meshsdf\meshsdf-src
[error] Error: ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\~\.ssh\id_rsa' 
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)

**Comment by CamelCaseNotation** [comment]
The documentation for the parameter `privateKeyPath` states you must provide an absolute path. `~` itself is an alias for your home directory, and is therefore not an absolute path.

**Comment by liximomo** [comment]
Please try the [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).
