### ISSUE TITLE
Error: Config Not Found

### ISSUE THREAD

**Issue by sktzofrenic** [liximomo/vscode-sftp#394]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**
Nothing works because on upload or on any action, this error is thrown: Config Not Found.

This is confusing because clearly the config is found on startup as evidenced by the log

**To Reproduce**
1. Fresh install of Vs Code on Windows 10
2. Install SFTP
3. Open work space and create config file in .vscode folder
4. Reload VS Code
5. Attempt to upload something by right clicking and choosing upload

**Expected behavior**
I would imagine the upload would complete successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/11902047/48441888-a5d3e380-e75a-11e8-93a8-83a248871d86.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode Version 1.29
 - Extension Version 1.7.4

**Extension Logs** - *required*
```
[info] config at \users\dan\documents\drxserver {"remotePath":"/drx_server","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"host":"server.myground.org","username":"******","password":"******","context":"./Users/Dan/Documents/drx_server"}
[trace] run command 'Upload File'
[error] Error: Config Not Found. (file:///users/dan/documents/drxserver/drxserver/commands.py) 
    at Object.handleCtxFromUri (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4\out\src\fileHandlers\createFileHandler.js:19:15)
    at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4\out\src\commands\abstract\createCommand.js:50:71)
    at Generator.next (<anonymous>)
    at C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4\out\src\commands\abstract\createCommand.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4\out\src\commands\abstract\createCommand.js:3:12)
    at targetList.map (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4\out\src\commands\abstract\createCommand.js:48:62)
    at Array.map (<anonymous>)
    at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4\out\src\commands\abstract\createCommand.js:48:49)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4\out\src\commands\abstract\createCommand.js:4:58)
    at <anonymous> 
```

**Comment by liximomo** [comment]
@sktzofrenic Try the [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by sktzofrenic** [comment]
I tried the debug package and the exact same thing occurs. In the log output, SFTP finds the config file and outputs to the console, then I attempt to upload a file, and I'm told that there is no config file found.

```
[debug] worksapce[0].uri file:///users/dan/documents/myground
[debug] worksapce[0].uri.fspath \users\dan\documents\myground
[info] config at \users\dan\documents\myground {"remotePath":"/_mg","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".git/**"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"host":"server.myground.org","username":"******","password":"******"}
[trace] run command 'Upload File'
[error] Error: Config Not Found. (file:///users/dan/documents/myground/auth.py) 
    at Object.handleCtxFromUri (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4-debug\out\src\fileHandlers\createFileHandler.js:19:15)
    at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4-debug\out\src\commands\abstract\createCommand.js:50:71)
    at Generator.next (<anonymous>)
    at C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4-debug\out\src\commands\abstract\createCommand.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4-debug\out\src\commands\abstract\createCommand.js:3:12)
    at targetList.map (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4-debug\out\src\commands\abstract\createCommand.js:48:62)
    at Array.map (<anonymous>)
    at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4-debug\out\src\commands\abstract\createCommand.js:48:49)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.4-debug\out\src\commands\abstract\createCommand.js:4:58)
    at <anonymous> 
```

**Comment by liximomo** [comment]
The debug package is only intent on diagnosing problems.

**Comment by sktzofrenic** [comment]
C:\users\dan\documents\myground\auth.py is the whole path, and I've wondered the exact same thing. I would think it should start with C: but I've installed a fresh copy of VSCode and the latest version of this extension and no dice. 

The extension used to work wonderfully for me, and to compliment you, this is easily the best SFTP extension out there which is why I'm trying so hard to get it to work.

**Comment by liximomo** [comment]
@sktzofrenic I've made a fix. Try this [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by liximomo** [comment]
@sktzofrenic Please try the [1.7.5-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by sktzofrenic** [comment]
Here is the output with the new debug package:

```
[info] config at \users\dan\documents\myground {"remotePath":"/_mg","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".git/**"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"host":"server.myground.org","username":"******","password":"******"}
[debug] find config for c:\users\dan\documents\myground
[trace] run command 'Upload File'
[debug] find config for \users\dan\documents\myground\application.py
[debug] Trie {
  option: { delimiter: '\\' },
  root: 
   TrieNode {
     token: '@root',
     value: null,
     children: 
      { 'c:': 
         TrieNode {
           token: 'c:',
           value: null,
           children: 
            { users: 
               TrieNode {
                 token: 'users',
                 value: null,
                 children: 
                  { dan: 
                     TrieNode {
                       token: 'dan',
                       value: null,
                       children: 
                        { documents: 
                           TrieNode {
                             token: 'documents',
                             value: null,
                             children: 
                              { myground: 
                                 TrieNode {
                                   token: 'myground',
                                   value: 
                                    FileService {
                                      _eventEmitter: 
                                       EventEmitter {
                                         domain: null,
                                         _events: { BEFORE_TRANSFER: [Function], AFTER_TRANSFER: [Function] },
                                         _eventsCount: 2,
                                         _maxListeners: undefined },
                                      _pendingTransferTasks: Set {},
                                      _schedulers: [],
                                      _watcherService: 
                                       { create: [Function: createWatcher],
                                         dispose: [Function: removeWatcher] },
                                      id: 1,
                                      workspace: '\\users\\dan\\documents\\myground',
                                      baseDir: 'c:\\users\\dan\\documents\\myground',
                                      _watcherConfig: undefined,
                                      _config: 
                                       { remotePath: '/_mg',
                                         uploadOnSave: true,
                                         downloadOnOpen: false,
                                         ignore: [ '.git/**' ],
                                         concurrency: 4,
                                         protocol: 'sftp',
                                         connectTimeout: 10000,
                                         interactiveAuth: false,
                                         secure: false,
                                         passive: false,
                                         remoteTimeOffsetInHours: 0,
                                         port: 22,
                                         host: 'server.myground.org',
                                         username: 'root',
                                         password: 'aQCLmlBx!t26' },
                                      _name: undefined,
                                      _configValidator: [Function: validateConfig] },
                                   children: {},
                                   parent: [Circular] } },
                             parent: [Circular] } },
                       parent: [Circular] } },
                 parent: [Circular] } },
           parent: [Circular] } },
     parent: null } }
[error] Error: Config Not Found. (file:///users/dan/documents/myground/application.py) 
    at Object.handleCtxFromUri (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.5-debug\out\src\fileHandlers\createFileHandler.js:19:15)
    at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.5-debug\out\src\commands\abstract\createCommand.js:50:71)
    at Generator.next (<anonymous>)
    at C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.5-debug\out\src\commands\abstract\createCommand.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.5-debug\out\src\commands\abstract\createCommand.js:3:12)
    at targetList.map (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.5-debug\out\src\commands\abstract\createCommand.js:48:62)
    at Array.map (<anonymous>)
    at FileCommand.<anonymous> (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.5-debug\out\src\commands\abstract\createCommand.js:48:49)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Dan\.vscode\extensions\liximomo.sftp-1.7.5-debug\out\src\commands\abstract\createCommand.js:4:58)
    at <anonymous> 
```

**Comment by sktzofrenic** [comment]
Thank you for helping me try to figure this out. Let me know if there is something more I can do.

**Comment by liximomo** [comment]
I've deleted the log because it contains your password. I will fix this bug in a few days.

**Comment by sktzofrenic** [comment]
I changed my password... Thanks for noticing that.

**Comment by liximomo** [comment]
Good news. I've found the problem.

@sktzofrenic Please try [1.7.5-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

**Comment by liximomo** [comment]
@sktzofrenic Thanks for your support!

**Comment by cjjlovedsn** [comment]
It was possible to set the context to a relative path, but now we have to write the absolute path, otherwise we will report the error.

**Comment by mgiovann** [comment]
> Good news. I've found the problem.
> 
> @sktzofrenic Please try [1.7.5-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

I have the same error and am unable to get it working. When I install from that vsx I get an error.

`Unable to install Extension 'liximomo.sftp-1.7.8-debug' as it is not compatible with Code '1.24.1'.`

Mac 10.13
Code 1.24.1
SFTP 1.7.7

**Comment by liyi193328** [comment]
Unable to install Extension 'liximomo.sftp-1.9.2-debug' as it is not compatible with Code '1.25.1'.

**Comment by mercs600** [comment]
the same issue here

**Comment by leonhardrocha** [comment]
Unable to install Extension 'liximomo.sftp-1.9.2-debug' as it is not compatible with Code '1.26.1'.

**Comment by papafed** [comment]
I am afraid that this bug still exists as of 10 May 2021.
MacOS Big Sur 11.3.1
Visual Studio Code Version: 1.56.0 (Universal)

Here's my output when I try to upload an index.html file.
`[05-10 17:27:51] [info] config at /Users/niall/Documents/websites/45th/dist/ {"remotePath":"/kingetcie/clients/japancentre45/","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"Ionos 45th","host":"home434421094.1and1-data.host","port":22,"username":"******","password":"******","context":"dist/"}
[05-10 17:28:11] [error] Error: Config Not Found. (file:///Users/niall/Documents/websites/45th/index.html) 
	at Object.u [as handleCtxFromUri] (/Users/niall/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:41793)
	at Object.<anonymous> (/Users/niall/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3993)
	at Generator.next (<anonymous>)
	at /Users/niall/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3273
	at new Promise (<anonymous>)
	at r (/Users/niall/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3050)
	at /Users/niall/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3935
	at Array.map (<anonymous>)
	at Object.<anonymous> (/Users/niall/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3928)
	at Generator.next (<anonymous>)
	at s (/Users/niall/.vscode/extensions/liximomo.sftp-1.12.9/dist/extension.js:1:3106)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) `

**Comment by ea-ufficiosw** [comment]
OS: Windows 10 Pro, version 1909
IDE: Visual Studio Code 1.56.0
Extension: SFTP liximomo 1.29.9
Date: 11 May 2021

Same here, the extension works like a charm for an year, now from the last update of Visual studio I got the error.
On the starting phase of loading the configurations from the project, the local sftp.json file it's loaded, the content it's correct, and if I switch the workspace, the content printed on the console change.
Yet, on the commit phase, the extension ignores the existence of stfp.json file and try to loads the config file, that I never created because I never needed it.

_[05-11 10:30:37] [info] config at c:\Users\ufficiosw\eclipse-workspace\soilsense {"remotePath":"/var/www/html","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"****","host":"1.1.1.1","port":22,"username":"******","password":"******"}
[05-11 10:30:45] [warn] ENOENT: no such file or directory, open 'C:\Users\ufficiosw\.ssh\config' load C:\Users\ufficiosw\.ssh\config failed
[05-11 10:30:45] [info] [file-save] c:\Users\ufficiosw\eclipse-workspace\soilsense\application\controllers\up.php
[05-11 10:30:45] [warn] Can't set modified time to the file because Failure
[05-11 10:30:45] [error] Error: No such file_

**Comment by kinoli** [comment]
I'm also seeing this with multiple context.

**Comment by 14714** [comment]
Greetings. I had the same problem with multiple context, but i fixed with a specified **context**, example: 
`"context": "/laragon/www/project/"`

**Comment by ADCREW-LLC** [comment]
I have the same problem on Mac. Here is how I fixed it:

1. Open the SFTP config file. Look closer to the "context": "context": "**/client**/build/",
2. My file directory is a bit complicated. So, by default, the prefix path of the location (generated by SFTP) will be "xxxxxxx/" (ends with splash /). To fix this, please REMOVE THE SLASH / at the beginning of the "/client/build/".
3. The result of the context in the config file now should be: "context": "context": "**client**/build/",

Now it works!

**Comment by ADCREW-LLC** [comment]
You can try to remove the slash / at the beginning of the config data: 
"context": **"client**/build/".
For me, it works.

**Comment by yvesapsy** [comment]
It worked for me only when I used the full path on "context".

**Comment by schuhwerk** [comment]
I had the "same" issue (on windows). The path to my workspace had spaces (in the path-name). Removing all spaces fixed it for me...

**Comment by dvestezarzlkl** [comment]
Hi. After updating to version 1.16.3, I encountered the same issue. Downgrading to 1.16.1 resolved the situation

**Comment by ValbadExe** [comment]
> Hi. After updating to version 1.16.3, I encountered the same issue. Downgrading to 1.16.1 resolved the situation

@dvestezarzlkl  You are right, when doing that it worked. Thank you. 😎🤝🏻
