### ISSUE TITLE
Context  Had to include drive (C:/) when use an absolute path in windows.

### ISSUE THREAD

**Issue by standingpaul** [liximomo/vscode-sftp#395]
I was previously using a context like this: "/Folder1/Folder2/Folder3". 

An update since about a week ago 'broke' it so I now have to use "C:/Folder1/Folder2/Folder3". 

Couldn't see anything obvious in the changlog about this, and I still see examples saying to set context the original way.

To summarise, I have fixed the issue but had to work it out on my own.

I am using Windows 10.

**Comment by Hardhik** [comment]
Thank you so much.
I was just going crazy trying to figure out why the extension stopped syncing files all of a sudden.
In my case it was D:/Folder1/Folder2

I am using Windows 10 too. 

I think the update created today broke it, because it was working for me for past couple of days. Only saw the issue today.

**Comment by liximomo** [comment]
@standingpaul @Hardhik Sorry for that. The change is required to fix another issue. 

The example config `/path/to/folder` is for *inx os. The `context` should be an absolute path or a relative path to the workspace root folder. You should never omit the `drive` part in an absolute path on windows.

**Comment by standingpaul** [comment]
> @standingpaul @Hardhik Sorry for that. The change is required to fix another issue.
> 
> The example config `/path/to/folder` is for *inx os. The `context` should be an absolute path or a relative path to the workspace root folder. You should never omit the `drive` part in an absolute path on windows.

Well, I would normally want to put the C:/ part of the file path, but I'm pretty sure that didn't work originally which is why I had it set the way I did. 

The main reason I raised this an an issue is that I'm pretty sure this is going to affect others using Windows, who will also not be helped by any error messages or documentation.

Paul

**Comment by standingpaul** [comment]
> @standingpaul Please file an issue for this.

You want me to open another one?

Paul

**Comment by liximomo** [comment]
Yes.

standingpaul <notifications@github.com> 于 2018年11月17日周六 18:38写道：
