### ISSUE TITLE
Context Had to include drive (C:/) when using an absolute path in windows.

### ISSUE THREAD

**Issue by standingpaul** [liximomo/vscode-sftp#398]
**Do you read the FAQ?**
- [x ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Same as issue #395.
Was previously forced to use as context '/Folder1/Folder2' in Windows 10, but since an update to the extension, this has changed and now need to use C:/Folder1/Folder2.

This in itself is not a problem, but no errors appeared to be thrown, nor did any documentation appear to warn about this change and so I had to find out for myself why the SFTP was no longer working (once I even worked out that it wasn't working).

**To Reproduce**
1. Use this extension as before in Windows 10
2. Discover that it doesn't recognise the source folder anymore, because you have used "Folder1/Folder2" type of file path previously, where you now need to include the drive letter, e.g. C:/Folder1/Folder2/

**Desktop (please complete the following information):**
Windows 10

**Comment by liximomo** [comment]
@standingpaul Please provide the full extension logs.

**Comment by liximomo** [comment]
> Well, I would normally want to put the C:/ part of the file path, but I'm pretty sure that didn't work originally which is why I had it set the way I did. 

Sorry. I've misunderstood this. I thought that the `C;/` part is not working now.
