### ISSUE TITLE
Uploading and Downloading files - problem

### ISSUE THREAD

**Issue by tgidan** [liximomo/vscode-sftp#400]
While using dreamweaver to upload en download .php files to my school's server everything was fine. But now that my trial version is over for dreamweaver, I needed a different application to make the assignements on. So my teacher advised me to use vs code. There was only one small problem: I can't find my files on the server I saved it on. I can see every folder I saved the file in but i can't seem to the files that are saved in the folder. However I can download files that are outside these folders and upload them. I was wondering if someone had a solution for this. 
If my description of the problem isn't clear, please say so because I have that a lot.
All the files that you can see in the pictures have a Dutch name but that shouldn't matter to much and otherwise I can help you with the translation.

![image](https://user-images.githubusercontent.com/45127217/48664295-c4104b00-ea9c-11e8-82ba-03c085dfe695.png)

![image](https://user-images.githubusercontent.com/45127217/48664306-ed30db80-ea9c-11e8-9d40-ad2fdfa66dc7.png)

![image](https://user-images.githubusercontent.com/45127217/48664324-397c1b80-ea9d-11e8-963a-043d7b56cfbe.png)

Thanks to anyone who can help me

**Comment by liximomo** [comment]
Some ftp servers that do not handle characters like spaces and quotes in directory names well.

**Comment by tgidan** [comment]
> Some ftp servers that do not handle characters like spaces and quotes in directory names well.

Thanks, now I can finally practice at home again :). And thanks for the quick response, I really do appreciate it.
