### ISSUE TITLE
Change connection name with profile

### ISSUE THREAD

**Issue by mtheos** [liximomo/vscode-sftp#401]
**Is this a similar or duplicate feature request?**
- [ X ] No.

**Is your feature request related to a problem? Please describe.**
I have my test and prod configuration saved as 2 profiles. I'm frustrated when my team pushes to the wrong server because they forget which they are connected to.

**Describe the solution you'd like**
I would like to be able to change the name of the connection when the profile changes

**Describe alternatives you've considered**
I have tried adding a name property under each of the profiles but the name of the session does not change with it.
...
   "profiles": {
          "Test": {
                "name": "Test/PP",
                "host": "test.server.com"
          },
          "Live": {
                "name": "Live/PP",
                "host": "live.server.com"
          }
    }
...

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Why the name could help this?

**Comment by mtheos** [comment]
I didn't notice that, I only saw that the name in the explorer didn't change
![capture](https://user-images.githubusercontent.com/27749706/48746741-d5d43700-ecc4-11e8-978e-10402fb80eb2.JPG)
