### ISSUE TITLE
Double sync

### ISSUE THREAD

**Issue by fmarcia** [liximomo/vscode-sftp#402]
When running `SFTP: Sync Remote -> Local` with an active watcher (sftp.json extract below), the sync is done as requested but updated files are synced back.
```json
    ...
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    }
   ...
```

Could you provide a way to avoid this?

**Comment by liximomo** [comment]
No. Just don't use watcher like this unless you only upload files.

**Comment by fmarcia** [comment]
I don't, I have to sync in both ways.
