### ISSUE TITLE
在sftp.json配置中添加注释，保存使用会报错.vscode\sftp.json: Unexpected token / in JSON at position 7

### ISSUE THREAD

**Issue by Crisimple** [liximomo/vscode-sftp#403]
**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

**To Reproduce**
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.27.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by javanli** [comment]
https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

**Comment by liximomo** [comment]
json 不支持注释哦, 后续会支持支持注释的 jsonc 格式配置.
