### ISSUE TITLE
define the local dir to upload

### ISSUE THREAD

**Issue by fanshengshuai** [liximomo/vscode-sftp#406]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
define the local dir to upload.
in my project, the output dir would upload to server map the remote dir /xxx/xxx/web
but i can not define the local dir in my project.
the file index.html in output,when i upload to server, it upload to  /xxx/xxx/web/output/index.html
i just think output/index.html can upload to /xxx/xxx/web/index.html

**Describe alternatives you've considered**
now, i make a soft link with ln -s 

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
```
"context": "./out"
```
