### ISSUE TITLE
No upload on save after upgrading to vscode 1.29.1

### ISSUE THREAD

**Issue by kercos** [liximomo/vscode-sftp#408]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
After upgrading to cscode 1.29.1 I'm able to access files on sftp server as before but not to upload them on save. No error shows up on the console.

**To Reproduce**
1. Setup settings with "uploadOnSave": true
2. Download file from sftp server
3. Modify it
3. Save it
4. No file is trasfered to the server (and no output to output console even when debug mode is activated)

**Expected behavior**
The file should be uploaded to the server as before.

**Desktop (please complete the following information):**
 - OS: Win
 - VSCode Version: 1.29.1
 - Extension Version: 1.7.7

**Extension Logs** - *required*
```
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload Changed File" from "./fileCommandUploadChangedFile.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[warn] ENOENT: no such file or directory, open 'C:\Users\fede\.ssh\config' load C:\Users\fede\.ssh\config failed
[warn] ENOENT: no such file or directory, open 'C:\Users\fede\.ssh\config' load C:\Users\fede\.ssh\config failed
[warn] ENOENT: no such file or directory, open 'C:\Users\fede\.ssh\config' load C:\Users\fede\.ssh\config failed
[info] config at \workspace\home {"remotePath":"*****","uploadOnSave":true,"downloadOnOpen":true,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"context":"/workspace/home","host":"*****","username":"******","password":"******","syncMode":"update","watcher":{"files":"**/*","autoUpload":false,"autoDelete":true}}
[info] remote -> local \workspace\home\file.test
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
```

**Comment by liximomo** [comment]
`"files":"**/*","autoUpload":false` and  `"uploadOnSave":true` may get conflicted.

**Comment by kercos** [comment]
Hi @liximomo, thanks for your quick reply 😄 
I've tried to remove the watcher option which included `"files":"**/*"`, `"autoUpload":false` and `"autoDelete":true`.

Now these are the current settings:
```
[info] config at \workspace\home {"remotePath":"*****","uploadOnSave":true,"downloadOnOpen":true,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"context":"/workspace/home","host":"*****","username":"******","password":"******","syncMode":"update"}
```

Unfortunately the upload of files on save still doesn't work and there is no other way I know to transfer the changes on the server. Is there anything else I can try?

Thanks, Federico

**Comment by liximomo** [comment]
@kercos  Please try [1.7.8-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by kercos** [comment]
Thanks @liximomo, what shall i do after installing it?

**Comment by liximomo** [comment]
@kercos Reproduce the problem and post the logs.

**Comment by kercos** [comment]
Sorry @liximomo, I had to replace them for privacy concerns, but I did replace them consistently. Could you advice any read/write SFTP hosting that I can use for testing?

**Comment by liximomo** [comment]
> [debug] save file:///local_path/test_file.txt
--> here I press ctrl-s to save file
[debug] isValidFile true
[debug] isInWorksapce false  **notice here**
[debug] workspaceFolders [{"uri":{"$mid":1,"fsPath":"c:\\workspace","external":"file:///c%3A/workspace","path":"/c:/workspace","scheme":"file"},"name":"workspace","index":0}]

Because the file you've saved is not in workspace. So It didn't trigger a upload. And I don't whether it is actually in or not in your workspace because the file path is not the real path.

**Comment by kercos** [comment]
@liximomo Thanks so much for the tip! 

You saved my day 😃 

It looks like that when specifying in "context" the full path `c:/workspace` it works again and says `isInWorkspace true` in the log after saving.

BTW, Could it be that something has changed after introducing changes in workspace (i.e., Multi-root Workspaces)?

**Comment by kercos** [comment]
> [1.7.8-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

forgot to ask, how to unistall the debug version (so that i can keep only the regular version?).

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/49219216-95379480-f40d-11e8-964e-c978edc69f9e.png)
