### ISSUE TITLE
FTPS Support?

### ISSUE THREAD

**Issue by vinnytroia** [liximomo/vscode-sftp#41]
Are there plans to support FTPS / TLS/SSL connections? 
Thanks

**Comment by liximomo** [comment]
Currently, No.

**Comment by liximomo** [comment]
It's will be supported in next release.

**Comment by liximomo** [comment]
It's support now.

**Comment by brudolph** [comment]
For the protocol do we use ftp or ftps? It throws an error when I use ftps. But ftp just times out.

**Comment by trashbytes** [comment]
Doesn't work for me either.
ftps throws an error and ftp tells me that non anonymous sessions must use encryption.

How does it work?
