### ISSUE TITLE
Stop synchronizing files on git branch swiching.

### ISSUE THREAD

**Issue by ghostbody** [liximomo/vscode-sftp#412]
**Is this a similar or duplicate feature request?**
- [x] I don't know. I will go check it.
- [ ] No.

**Is your feature request related to a problem? Please describe.**
When I am switching git branch, for example from a feature branch feature/A to develop(or master) branch using `git checkout develop`. The whole diff will be transfered by vscode-sftp. It makes life harder  when I just want to do git operations like merge and etc.

```
git checkout develop 
```

![image](https://user-images.githubusercontent.com/8371330/49202226-ca78be00-f3de-11e8-85e8-c401591c5643.png)

**Describe the solution you'd like**
I just want to stop vscode-sync when I am doing sth like doing git command.

**Describe alternatives you've considered**
nope

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [x] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by ghostbody** [comment]
@liximomo how to? There is no such command, it seems.

**Comment by liximomo** [comment]
Delete `watcher` from your sftp.json
