### ISSUE TITLE
Configuration - How does it work ?

### ISSUE THREAD

**Issue by dschiller** [liximomo/vscode-sftp#414]
Hi, the Info "Press Ctrl+Shift+P and type 'SFTP: config' " doesnt work for me. There is no such Entry in the Command Console of VS Code. Also a File .vscode/sftp.json with Settings in it does nothing. The only Thing I can see is in the sftp-sync OUTPUT: "Now trying to load configuration from workspace settings.
  error: both [local] and [remotes] for sftp-sync should be set on workspace settings.". I read the Wiki Section here ( https://github.com/liximomo/vscode-sftp/wiki/Setting ) but there is no Information on how to setup the SFTP Extension. Can someone help how I have to configure the Workspace Settings for SFTP ?

If I create a file .vscode/settings.json with Workspace Settings like:

<code>
{
    "sftp-sync": {
        "local": {
            "protocol": "ftp",
            "host": "www.server.com",
            "port": 21,
            "username": "user",
            "remotePath": "/",
            "uploadOnSave": true,
            "password": "pw",
            "ignore": [
                ".gitignore"
            ]
        }
    }
}
</code>

The sftp-sync OUTPUT still saying: "Now trying to load configuration from workspace settings.
  error: both [local] and [remotes] for sftp-sync should be set on workspace settings."

Thank you a lot
Cheers
Dirk

**Comment by liximomo** [comment]
You've installed the wrong extensions. It's `sftp`, not `sftp-sync`.
