### ISSUE TITLE
Open SSH in terminal: Warning: Identity file not accessible: No such file or directory. (Windows backslashes)

### ISSUE THREAD

**Issue by imsadhappy** [liximomo/vscode-sftp#415]
On Windows 10, when running "open ssh in terminal" terminal output results in "Warning: Identity file not accessible: No such file or directory". Using relative, or absolute path in sftp.json won't help solve the problem. Any kind of slashes in "privateKeyPath" - / and \\\\ get converted to \ when sent to terminal (tested). Also, worth noticing that if privateKeyPath has spaces in it (possible in Windows too) will trigger the same error.

A possible quick workaround (to cover possible backslashes and spaces in path) could be wrapping privateKeyPath in quotes right before sending to terminal, say in src/commands/commandOpenSshConnection.ts in function getSshCommand() on line 25, by doing something like sshStr += '\\'' + \` ${extraOpiton}\` + '\\'';

 - OS: Win 10
 - VSCode Version [e.g. 1.29.1]
 - Extension Version [e.g. 1.7.6]

**Extension Logs from Startup**
[info] config at c:\Users\imsadhappy\Projects\projectname {"remotePath":"/","uploadOnSave":false,"downloadOnOpen":false,"ignore":[".vscode",".ssh",".git"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"name":"xxxxxx","host":"xxxxxx","username":"xxxxxx","privateKeyPath":"c:\\Users\\imsadhappy\\Projects\\projectname\\.ssh\\id_rsa"}

**Terminal output when running "open ssh in terminal"**
~/Projects/projectname
$ ssh root@xxxxxx -p 22 -i c:\Users\imsadhappy\Projects\projectname\\.ssh\id_rsa
Warning: Identity file c:UsersimsadhappyProjectsprojectname.sshid_rsa not accessible: No such file or directory. Permission denied (publickey).

**Comment by liximomo** [comment]
@imsadhappy Could you help me to test the  [fix-package](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by imsadhappy** [comment]
Worked like a charm. I've tested different paths - relative, absolute starting with C:, absolute starting with /, different types of slashes - / & double backslash. All seem to work fine. 

One thing to notice is the different slashes in the path. At the moment the output into terminal looks like this: $ ssh root@xxxxxxxxx -p 22 -i "c:/Users\imsadhappy\Projects\projectname\\.ssh\id_rsa"

It's not big deal in Windows as it handles them all fine. Can't tell for sure if there's anything similar on other platforms. If you wish you can go extra mile writing some smart replaces for the slashes to make them all uniform. But even as it is now it will do all fine. I think you can close the thread. Thanks for the fix, really like using your extension!
