### ISSUE TITLE
I work with non-Unix system and I don't need to parse symbols in the path

### ISSUE THREAD

**Issue by JeffyOLOLO** [liximomo/vscode-sftp#417]
**Is this a similar or duplicate feature request?**
- [ ] No.

**Is your feature request related to a problem? Please describe.**
I work with non-Unix system. Commands have to look like:
LIST -al 'USERID.'
But internal parser changes remotePath and commands become like:
LIST -al \\'USERID.\\'
And host can't find needed path.

How can I change parsing or what should I do?

**Comment by liximomo** [comment]
Can you provide the extensions logs?

**Comment by JeffyOLOLO** [comment]
> Can you provide the extensions logs?

Are logs debug output?

[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload Changed File" from "./fileCommandUploadChangedFile.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at c:\Users\Bakozaur\Desktop\ABP {"remotePath":"/'TS7789.'","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"name":"TS7789","host":"rs22.rocketsoftware.com","username":"******","password":"******"}
[debug] < 220-FTPD1 IBM FTP CS V2R3 at RS22.rocketsoftware.com, 02:43:41 on 2018-12-04.
[debug] < 220 Connection will close if idle for more than 5 minutes.
[debug] > USER TS7789
[debug] < 331 Send password please.
[debug] > PASS ******
[debug] < 230 TS7789 is logged on.  Working directory is "TS7789.".
[debug] > FEAT
[debug] < 211- Extensions supported
[debug] <  AUTH TLS
[debug] <  AUTH GSSAPI\r\n CCC\r\n PBSZ\r\n PROT\r\n211 End
[debug] > TYPE I
[debug] < 200 Representation type is Image
[debug] > PASV
[debug] < 227 Entering Passive Mode (192,168,55,22,122,208)
[debug] > LIST -al \\'TS7789.\\'
[debug] < 550 No data sets found.

**Comment by liximomo** [comment]
Please try [1.7.8-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by JeffyOLOLO** [comment]
> Please try [1.7.8-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

Thanks!
That is what i wanted :)
But as it turned out host system doesn't understand any path in LIST command.
