### ISSUE TITLE
Plugin fails to to start

### ISSUE THREAD

**Issue by JefferE** [liximomo/vscode-sftp#418]
**Do you read the FAQ?**
- [X ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

When I try to run SFTP:config in VSCode I get a popup that says "command 'sftp.config' not found"

This only started recently. The last time I used this plugin it worked. I've disabled/reenabled the plugin, uninstalled/reinstalled the plugin, and same results. I'm stumped.

**To Reproduce**
1. Go to 'Ctrl-Shift-P'
2. Run command 'SFTP:config'
3. I get the error

**Expected behavior**
The command works as it used to.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - VSCode Version:

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41

 - Extension Version:

1.7.6 - 2018-11-22

**Extension Logs from Startup** - *required*

When I follow the debug steps I get NO log output. It's like the extension is not really starting at all.

**Comment by JefferE** [comment]
There is a similar issue, but it looks like he had the wrong plugin installed. This is the one I have:

![2018-12-05_1248](https://user-images.githubusercontent.com/555796/49533465-07382f80-f88d-11e8-96c0-12e97c982193.png)

**Comment by keiclone** [comment]
also running into this issue. can't even downgrade to previous version right now because vscode can't detect the VSIX file. Started seeing this today.

**Comment by samuelT2** [comment]
Hi there - not sure if this helps, but I got stuck on an faulty version too in the past. To install an old version, follow these steps:

1. Download whatever version was working for you here: https://liximomo.gallery.vsassets.io/_apis/public/gallery/publisher/liximomo/extension/sftp/[version, eg. 1.5.8]/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
2. Change the extension from the package from .VSIXPackage to .VSIX
3. Clean-up
    a) Open Visual Code
    b) Uninstall SFTP
    c) Disable auto-update with "extensions.autoUpdate": false
    d) Reload Visual Code and make sure to delete the package also from here: C:\Users\{username}\.vscode\extensions
8. Press F1 and type VSIX --> "Extension: Install from VSIX...". Browse to the previously downloaded file. Wait for install-confirmation
9. Reload visual code

**Comment by keiclone** [comment]
ah, didn't change the extension. downgrading to 1.7.5 worked. thanks @samuelT2!

**Comment by liximomo** [comment]
sftp v1.7.6 require VSCode 1.25.0+.

**Comment by liximomo** [comment]
Sftp v1.7.6 requires VS Code 1.25.0+

**Comment by dracarysX** [comment]
@liximomo  VS Code 1.29.1 and Sftp v1.8.0 . when i started vs code, sftp error like this.
![image](https://user-images.githubusercontent.com/12078753/49560882-38793400-f94f-11e8-92f4-6f8f7b3eaf55.png)

**Comment by liximomo** [comment]
@dracarysX what'is your config?

**Comment by JefferE** [comment]
I already had VSCode 1.29.1 with v1.7.6 of the plugin and it wasn't working.

But it is working now for me 1.8.1 - thanks.

**Comment by JefferE** [comment]
P.S. Thanks for fixing that so fast - just made a donation to the project.

**Comment by liximomo** [comment]
@JefferE Thanks for your support.
