### ISSUE TITLE
Stops working with sass live compile

### ISSUE THREAD

**Issue by 13ogue** [liximomo/vscode-sftp#42]
## Expected Behavior
Should upload to the remote directory after saving a file while working with live sass compile by ritwick dey at the same time

## Actual Behavior
Whenever i use the live sass compile in vscode, the sftp functioning just crashes, it wont upload, it wont sync, nothing happens.
I have to then restart vs code for the sftp to start working again.

## Steps to Reproduce the Problem

  1. enable the autowatch feature of live sass compile by ritwick dey
  1.press ctrl+S to save

## Specifications

  - Version: latest
  - Platform: w10 pro x64

**Comment by liximomo** [comment]
Can you provide the logs? And read this carefully.
![image](https://user-images.githubusercontent.com/9816225/31337607-b0988b1a-acc1-11e7-9742-c94080d5dd3c.png)

**Comment by 13ogue** [comment]
where can i find the extension logs?

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/31340239-23ed2040-accb-11e7-8cd5-97d11c679f73.png)

**Comment by Andrew-devcoder** [comment]
did not solve the problem?
