### ISSUE TITLE
how to change default config

### ISSUE THREAD

**Issue by wwwht** [liximomo/vscode-sftp#420]
**Is this a similar or duplicate feature request?**
- [x] I don't know. I will go check it.
- [ ] No.

**Is your feature request related to a problem? Please describe.**
every time i open a new project , i have to set the config again, Can i save my own settings that each time i use `SFTP: Config` the `sftp.json` is my own config settings 

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
No. But you may consider save your config in [User Setting](https://github.com/liximomo/vscode-sftp#config-in-user-setting).

**Comment by wwwht** [comment]
yeah, thats what i exactly want to know, how can i save that in my User Settings....
thanks a lot^^
