### ISSUE TITLE
The extension doesn't save more than 4 connections in the workspace

### ISSUE THREAD

**Issue by AleCss81** [liximomo/vscode-sftp#421]
**Do you read the FAQ?**
- [ x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I have created separated connections through sftp.json and placed inside .vs-code folder of each project. Every time I open the Visual Studio Code I have only four connections saved. Others are disappeared and I have to recreate them every time. So boring.

**To Reproduce**
1. Save more than 4 connection through sftp.json
2. Close Visual Studio Code
3. Open Visual Studio Code and see only four connections saved

**Expected behavior**
I would like to have more than four connections saved.

**Desktop (please complete the following information):**
 - OS: [Windows 10}
 - VSCode Version [e.g. 1.29.1]
 - Extension Version [e.g. 1.8.0]

**Extension Logs from Startup** - *required*

 [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at d:\Google Drive\Krealine\web-ftp\Gp-costruzioni {"remotePath":"/www.gp-costruzioni.it","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"name":"Gp Costruzioni","host":"ftp.gp-costruzioni.it","username":"******","password":"******"}
[info] config at d:\odrive\Google Drive AlecssLab\Lavoro\Siti web\Websites\ZadraInterni {"remotePath":"/www.zadrainterni.it","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"name":"Zadra Interni","host":"ftp.zadrainterni.it","username":"******","password":"******"}
[info] config at d:\odrive\Google Drive AlecssLab\Staging\development.alecsslab {"remotePath":"/development.alecsslab.com","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"name":"Development AleCss Lab","host":"ftp.alecsslab.com","username":"******","password":"******"}
[info] config at d:\odrive\Google Drive AlecssLab\Staging\test.alecss {"remotePath":"/public_html/test","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"name":"Test site alecss.it","host":"ftp.alecss.it","username":"******","password":"******"}

**Comment by minvedacat** [comment]
The concurrency value is always 1, it is never 4 for me
```
{"remotePath":"/public_html/test","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"name":"Test site alecss.it","host":"ftp.alecss.it","username":"******","password":"******"}
```
Just as @AleCss81 posted, I am having the save `"concurrency":1` all the time and there is actually only 1 connection during each uploading.

**Comment by liximomo** [comment]
@AleCss81 What's the content of your sftp.json?

**Comment by liximomo** [comment]
@minvedacat `concurrency` is not supported in FTP.

**Comment by AleCss81** [comment]
> @AleCss81 What's the content of your sftp.json?

@liximomo this is my standard sftp.json content:

{
    "name": "Les Gomines",
    "protocol": "ftp",
    "host": "ftp.xxxxxxx.it",
    "port": 21,
    "username": "xxxxxxxxx",
    "password": "xxxxxxxxx",
    "remotePath": "/xxxxxxxxx"
}

For example, this is the fifth connection that sftp extension doesn't save. All the other four connections have the json structured in the same way and they are stored in the SFTP Remote Explorer.

Another json of a stored connection:

{
    "name": "Zadra Interni",
    "protocol": "ftp",
    "host": "ftp.xxxxxxx.it",
    "port": 21,
    "username": "xxxxxxx",
    "password": "xxxxxxx",
    "remotePath": "/xxxxxxx"
}

**Comment by liximomo** [comment]
What are the full paths of thees sftp.json files?

**Comment by AleCss81** [comment]
@liximomo ok, your question let me discover the problem: after the first four connection, probably for a lack of attention, I've started to use .vs-code folder fon json, instead of .vscode.

Now I have correct this issue and all the connections are stored in remote explorer. Sorry for the bother, thank you for your support.
