### ISSUE TITLE
Upload option no longer appears in Source Control view

### ISSUE THREAD

**Issue by ericpapamarcos** [liximomo/vscode-sftp#429]
In the "Source Control" view, right clicking on files that have changed no longer shows the "Upload" option. This worked a few days ago with a previous version of VS Code and/or the extension.

**Repro steps:**
1. Go to Source Control tab
2. Right click on a file that has changed
3. Look for "Upload" option

Observed: No "Upload" verb appears in the Source Control view. However, it does appear in the normal Explorer view.

I tried re-installing the extension and restarting VS Code, and this didn't address the problem.

**Desktop:**
 - OS: Windows 10
 - VSCode Version 1.30.0
 - Extension Version 1.8.3

**Extension Logs from Startup**
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[warn] ENOENT: no such file or directory, open 'C:\Users\[REDACTED]\.ssh\config' load C:\Users\[REDACTED]\.ssh\config failed
[info] config at [REDACTED] {"remotePath":"[REDACTED]","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":22,"host":"[REDACTED]","username":"[REDACTED]"}

**Comment by ericpapamarcos** [comment]
Options in Source Control view:

![issue1](https://user-images.githubusercontent.com/282771/50045819-96dc9b80-004e-11e9-97b8-e7491e02b5e9.jpg)

Options in Explorer view:

![issue2](https://user-images.githubusercontent.com/282771/50045820-a22fc700-004e-11e9-8846-f39d97001f41.jpg)

**Comment by liximomo** [comment]
It's been removed because of some flaws. You should use `Upload Changed Files` command.

**Comment by ericpapamarcos** [comment]
I don't see the "Upload Changes Files" command. Only "Upload Active File"
and "Upload Active Folder" and "Upload Project". Is any configuration
needed to get this command to appear?

Any chance you'll consider supporting the upload option in Source Control
view in a future update?

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/50062370-c40d8300-01e1-11e9-8819-830438a82b1d.png)
