### ISSUE TITLE
download mishap

### ISSUE THREAD

**Issue by 13ogue** [liximomo/vscode-sftp#43]
## Expected Behavior
download the remote files to a local directory
## Actual Behavior
on download, the files are downloaded to the specified directory but also get redownloaded to parent directories and the root folder

## Steps to Reproduce the Problem

  1.chose command "download" in the open folder in vscode
  1.files gets downloaded to all the folders along with the specified folders
  1.

 

## Specifications

  - Version:latest
  - Platform: win 10

**Comment by liximomo** [comment]
Please provide the directory structure and extension logs.

**Comment by 13ogue** [comment]
![1](https://user-images.githubusercontent.com/26528698/31337832-abc46740-ad1a-11e7-8a1c-f960166fc619.PNG)

**See how the files get downloaded to parent directory of the folder "social-criminals"**

![2](https://user-images.githubusercontent.com/26528698/31337836-adb20800-ad1a-11e7-9fe1-55a60bcca311.PNG)

**The contents of the remote directory also get downloaded to the parent directory of the folder *#RM_PROJECTS*

![3](https://user-images.githubusercontent.com/26528698/31337964-2c49cba8-ad1b-11e7-9481-861e8d560c88.PNG)

**Comment by liximomo** [comment]
Please provide the logs.
![image](https://user-images.githubusercontent.com/9816225/31340282-46437fcc-accb-11e7-81ff-550820f013ab.png)

**Comment by 13ogue** [comment]
**It has just stuck on this point for 2 minutes, the browsing speeds are at 3mbps**

![capture](https://user-images.githubusercontent.com/26528698/31340891-4af8dbfc-ad25-11e7-80ff-f0c4085a3d99.PNG)

**Comment by liximomo** [comment]
Which command did you run on which file or directory? Please provide me as much as possible information.
