### ISSUE TITLE
Problem in sftp.json missing name

### ISSUE THREAD

**Issue by opicron** [liximomo/vscode-sftp#431]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Vscode finds one problem in the sftp.json file. Missing "name".
{
"resource": "/c:/Users/opicr/Desktop/tseportal/.vscode/sftp.json",
"owner": "generated_diagnostic_collection_name#0",
"severity": 4,
"message": "Missing property "name".",
"startLineNumber": 1,
"startColumn": 1,
"endLineNumber": 1,
"endColumn": 2
}

**To Reproduce**
Use the configuration from the following Gist https://gist.github.com/opicron/013e66e9f3f577266d06f06dc39bad2b.

**Expected behavior**
The configuration should be correct. No problems should be mentioned I think.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - VSCode Version 1.3
 - Extension Version 1.8.5 

**Extension Logs from Startup** - *required*
https://gist.github.com/opicron/bfab461531ec1fde60358d082897408a

**Comment by liximomo** [comment]
This is expected. The name is required.

**Comment by opicron** [comment]
Sorry maybe I am stupid, but there are two names defined. If I add another name there is another error. 

Do i miss something here?

**Comment by opicron** [comment]
In the profiles?

**Comment by dolby360** [comment]
I have the same issue
