### ISSUE TITLE
How to change profile ?

### ISSUE THREAD

**Issue by devonecube** [liximomo/vscode-sftp#436]
Hi,

Thanks for this package ;)
I have a production and a staging on a project. I try to change the profile to production but it says No profile available found when I execute command Set Profile

`[
    {
        "protocol": "ftp",
        "host": "www.project.com",
        "context": "/project/src",
        "port": 21,
        "name": "staging",
        "username": "project",
        "password": "password",
        "remotePath": "/staging.password.com/",
        "uploadOnSave": true,
        "defaultProfile": "staging"
    },
    {
        "protocol": "ftp",
        "host": "www.project.com",
        "context": "/project/build",
        "port": 21,
        "name": "production",
        "username": "project",
        "password": "password",
        "remotePath": "/public_html/",
        "uploadOnSave": false
    }
]`

**Comment by liximomo** [comment]
Read the README.
