### ISSUE TITLE
Watcher upload path

### ISSUE THREAD

**Issue by DatXN** [liximomo/vscode-sftp#438]
Hi, 
I configured my watcher like this to upload all file changes in dist folder to html ftp folder
```
"watcher": {
    "files": "dist/**/*",
    "autoUpload": true,
    "autoDelete": false
  }
```
Where I want it to upload to is \var\html\
But the files are keep upload to \var\html\dist

How can I tell watcher to ignore/not create the first level folder (in this case, dont create the **dist** folder on remote )?

**Comment by liximomo** [comment]
`"context": "dist"`
