### ISSUE TITLE
Sync to Remote not working correctly and some files deleted incorrectly

### ISSUE THREAD

**Issue by marktopley** [liximomo/vscode-sftp#44]
## Expected Behavior
I have a Laravel PHP project which I am syncing to a remote FTP.
I have the structure:
app/config/app.php
app/config/dev/app.php

Right click on app/config/dev Sync to Remote.
Automatic file synchronization should copy changes to Remote.

## Actual Behavior
Right click on app/config/dev Sync to Remote the app/config/dev/app.php file is not copied when it doesn't exist on the remote. 
If I right click on app/config/dev/app.php and click upload then it does upload.

More concerning I click upload on this file to upload it ok but then after switching branches on my local this file keeps being deleted on the remote by SFTP.

## Steps to Reproduce the Problem

Please see Behavior above

  ### Extension Logs
Nothing of use logged.

## Specifications

  - Version: 0.8.3, just updated to 0.8.4 and will retest
  - Platform: Windows 10

**Comment by liximomo** [comment]
I need the entire logs of the extension.
set vscode option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)

**Comment by marktopley** [comment]
[info]: config at c:/Work/GitHub/Website/laravel {
    "host": "devsrv",
    "port": 21,
    "protocol": "ftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/Dev/laravel/",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": true,
        "autoDelete": true
    },
    "ignore": [
        "c:/Work/GitHub/Website/laravel/**/.vscode/**",
        "c:/Work/GitHub/Website/laravel/**/.git/**",
        "c:/Work/GitHub/Website/laravel/app/storage/**",
        "c:/Work/GitHub/Website/laravel/**/.DS_Store",
        "/Dev/laravel/**/.vscode/**",
        "/Dev/laravel/**/.git/**",
        "/Dev/laravel/app/storage/**",
        "/Dev/laravel/**/.DS_Store"
    ],
    "configRoot": "c:/Work/GitHub/Website/laravel"
}
[debug]: conncet to remote

c:\Work\GitHub\Website\laravel\app\config\dev Sync To Remote
[debug]: sync remote c:\Work\GitHub\Website\laravel\app\config\dev\mail.php at Wed Oct 11 2017 10:37:30 GMT+0100 (GMT Summer Time)
[debug]: sync remote c:\Work\GitHub\Website\laravel\app\config\dev\topaz.php at Wed Oct 11 2017 10:37:30 GMT+0100 (GMT Summer Time)

c:\Work\GitHub\Website\laravel\app\config\dev\app.php Upload
[debug]: upload c:\Work\GitHub\Website\laravel\app\config\dev\app.php at Wed Oct 11 2017 10:50:44 GMT+0100 (GMT Summer Time)

**Comment by liximomo** [comment]
I didn't see any deletion. And again
![image](https://user-images.githubusercontent.com/9816225/31437591-67b34daa-ae4b-11e7-9774-2795c921931d.png)

**Comment by marktopley** [comment]
Thanks I hadn't seen that in the readme.

I've re-produced the file being deleted again but no deletes logged in the sftp log or the ftp server logs but the file has gone again. Very odd.

**Comment by kinolanka** [comment]
> set vscode option sftp.printDebugLog to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)

Hello, liximomo!
I think you should add this option in readme because somewhere it's really difficult to understand what's going on.

**Comment by marktopley** [comment]
Not had this issue again since enabling syncMode as suggested
