### ISSUE TITLE
符号链接的目录没有同步

### ISSUE THREAD

**Issue by evildiamond** [liximomo/vscode-sftp#441]
准备同步Linux下的一个工程目录，该主目录下有一个目录是归属于我这个用户的/home目录下，其他目录是跟其他用户一起共享，链接到/data目录，此时只会拉取属于我的那个目录，其他目录没有拉取。
单独为符号链接的目录开一个项目，重新配置，可以拉取下来。

**Comment by liximomo** [comment]
这是期待的行为, 不处理符号连接.

**Comment by liximomo** [comment]
关闭了, 与 #123 重复.
