### ISSUE TITLE
How to configure muiti-profiles under multiple contexts?

### ISSUE THREAD

**Issue by s1973** [liximomo/vscode-sftp#444]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x ] No.

**Is your feature request related to a problem? Please describe.**
Can i configure different servers as profiles under one of my contexts? I tried like that:
```
[
    {
      "name": "server1",
      "context": "/project/build",
      "profiles": {
        "dev": {
          "host": "dev-host",
          "remotePath": "/dev",
          "username": "username",
          "password": "password",
          "uploadOnSave": true
        },
        "prod": {
          "host": "prod-host",
          "username": "username",
          "password": "password",
          "remotePath": "/prod"
        }
      },
      "defaultProfile": "dev"
    },
    {
      "name": "server2",
      "context": "/project/src",
      "host": "host",
      "username": "username",
      "password": "password",
      "remotePath": "/remote/project/src"
    }
]
```
But it doesn't work.

**Describe the solution you'd like**
It will be useful if we can switch profiles under sub-directory.

**Describe alternatives you've considered**
Set a config file in sub-derectory to override the main configuration.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Please file a new issue using the ` bug`  template.

**Comment by TuKun33** [comment]
Have you solved this problem?

I tried to fill in the context in the profile, but it creates a new folder in the remote directory, which is not what I want
