### ISSUE TITLE
Multiple Context connection with same context

### ISSUE THREAD

**Issue by seyedabbasseyedi** [liximomo/vscode-sftp#448]
I have two ftp on two separate servers:
one server for test and two for main release, but both context is have same url in my pc.

problem 1: not work this connection, that only show last connection.
```
[
    {
        "name": "server test",
        "protocol": "ftp",
        "host": "host1",
        "port": port,
        "username": "username1",
        "password": "password1",
        "context": "c:/Program Files (x86)/Ampps/www/project/",
        "remotePath": "/domains/serevrtest/public_html/"
    },
    {
        "name": "server main",
        "protocol": "ftp",
        "host": "host2",
        "port": port,
        "username": "username2",
        "password": "password2",
        "context": "c:/Program Files (x86)/Ampps/www/project/",
        "remotePath": "/domains/serevrmain/public_html/"
    }
]
```

problem 2: I can upload files to wanted server, not both server. In fact, I needed ftp same phpstorm intellij ftp.

**Comment by liximomo** [comment]
One context can only map to a single remote.

**Comment by CamelCaseNotation** [comment]
@liximomo Is there a way to have multiple contexts with profiles? For example, if I want only the subfolder `/server` of my project to map to a remotePath in one profile, but for another profile I want _all_ files (not just ones in `/server`) to map to a remotePath?
