### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by 360noscope** [liximomo/vscode-sftp#449]
**Do you read the FAQ?**
- [*] Yes.

**Describe the bug**
When i try to using sftp with vsftpd on ubuntu it give me permission denied error. I tried it on FileZilla client it got no issue with it.

FileZilla Operation
- Create Directory -> success
- Download file -> success
- Upload file -> success

**To Reproduce**
1. Right click on folder in VScode and select sync remote -> local.
(I'm using FileZilla client for temporary right now)

**Expected behavior**
Download all folder and file on remote location to local folder.

**Screenshots**
![capture](https://user-images.githubusercontent.com/9923419/50815254-06446300-134f-11e9-85d9-6134b14bad4c.JPG)

**Desktop (please complete the following information):**
 - Remote Server OS: Ubuntu Server 18.04
 - FTP Server: vsftpd
 - OS: Windows 10 x64 Latest update
 - VSCode Version 1.30.1
 - Extension Version 1.9.0

**Extension Logs from Startup** - *required*

[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at c:\Users\User\Desktop\IDPS {"remotePath":"/","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"host":"xxx.xxx.x.xxx","username":"******","password":"******"}
[info] config at c:\Users\User\Desktop\API {"remotePath":"/","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"host":"AWS SERVER","username":"******","password":"******"}
[info] config at c:\Users\User\Documents\GitHub\NewJudger {"remotePath":"/WEB","uploadOnSave":false,"downloadOnOpen":false,"ignore":[".vscode",".git",".gitignore",".DS_Store"],"concurrency":1,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"passive":false,"remoteTimeOffsetInHours":0,"port":21,"host":"AWS SERVER","username":"******","password":"******"}

**Comment by liximomo** [comment]
**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output

**Comment by bolarson** [comment]
Thank you for the nice product.  I'm getting a similar issue.  It is saying "key is not defined".  It has been working for a while, and the same key is working on all my other applications.  I got this error right after I upgraded to today's new version :-( can you help?  View > Output & stfp.json output below.

sftp.json:
{
    "name": "***.app",
    "protocol": "sftp",
    "host": "***.org",
    "port": 22,
    "username": "****",
    "remotePath": "/home/***/public_html/***.app",
    "privateKeyPath": "***",
    "passphrase": "***",
    "uploadOnSave": true
}

View > Output:
[info] [file-save] e:\Coding Projects\***.app\index.html
[trace] handle upload file for e:\Coding Projects\***.app\index.html
[error] ReferenceError: key is not defined
	at Function.OpenSSH_Old_Private.parse (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\node_modules\ssh2-streams\lib\keyParser.js:779:15)
	at parseKey (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\node_modules\ssh2-streams\lib\keyParser.js:1280:36)
	at Client.connect (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\node_modules\ssh2\lib\client.js:225:19)
	at module.exports.a.default._connectSSHClient.Promise (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\dist\extension.js:70:102790)
	at new Promise (<anonymous>)
	at p.<anonymous> (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\dist\extension.js:70:102431)
	at Generator.next (<anonymous>)
	at module.exports.r (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\dist\extension.js:70:99448)
	at new Promise (<anonymous>)
	at module.exports.r (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\dist\extension.js:70:99225)
	at p._connectSSHClient (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\dist\extension.js:70:102122)
	at p.<anonymous> (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\dist\extension.js:70:100904)
	at Generator.next (<anonymous>)
	at s (C:\Users\***\.vscode\extensions\liximomo.sftp-1.9.0\dist\extension.js:70:99281)
	at <anonymous> download e:\Coding Projects\***.app\index.html

**Comment by bolarson** [comment]
I just converted my key to a ***.ppk and it is now working again :-) Thanks
