### ISSUE TITLE
Please support ed25519 key

### ISSUE THREAD

**Issue by Ehekatl** [liximomo/vscode-sftp#45]
## Expected Behavior
[Description of the expected behavior]
ecDSA is much secure and efficient compare to RSA algorithm and has been support in openssh for long time. Please consider to support the ed25519 format.

## Actual Behavior
[Description of the actual behavior]
When I use a private key with ed25519 format, it gives:
`[liximomo.sftp] Cannot parse privateKey: Unsupported key format: Error: Cannot parse privateKey: Unsupported key format`

## Steps to Reproduce the Problem

  1. generate a ssh key with ed25519 format
  2. use private key based sftp sync

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version: 0.8.4
  - Platform: macOS Sierra 10.12.6

**Comment by liximomo** [comment]
Look at  [this](https://github.com/mscdex/ssh2/issues/352).

**Comment by ekifox** [comment]
any updates maybe?

**Comment by DSpeichert** [comment]
@liximomo Looks like this can be fixed by upgrade of ssh2 package.

**Comment by liximomo** [comment]
@DSpeichert Not until VS Code ship with node v12. https://github.com/mscdex/ssh2/issues/352#issuecomment-486511390
