### ISSUE TITLE
Activity bar icon

### ISSUE THREAD

**Issue by niccolomineo** [liximomo/vscode-sftp#450]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
I would like to suggest a way to add a little more visual integration between VSCode and SFTP, because imo it is not 100% accomplished: the sidebar icon could be improved.

**Describe the solution you'd like**
One could use the "Explorer" icon as a base for the icon. I would be happy to work on it, if you'd allow me to.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
@niccolomineo Yes, please. This is a good idea.

**Comment by niccolomineo** [comment]
Are you able to retrieve the original "Explorer" icon and share it here?

Thank you.

**Comment by niccolomineo** [comment]
Can you try with this one?

[icon-sftp.svg.zip](https://github.com/liximomo/vscode-sftp/files/2743085/icon-sftp.svg.zip)

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/51015360-da231f00-15a6-11e9-9536-3bdd11fad2da.png)

The size doesn't fit. The icon should be 28x28 centered on a 50x40 block.

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/51025671-a60c2600-15c7-11e9-8350-7a0b76df987b.png)
Still feels a little bigger.

You could preview it by yourself.

Windows replace %USERPROFILE%\.vscode\extensions. macOS ~/.vscode/extensions/liximomo.sftp-1.9.1/resources/remote-explorer.svg
macOS / Linux replace ~/.vscode/extensions/liximomo.sftp-1.9.1/resources/remote-explorer.svg

Do a reload after the replacement.

**Comment by niccolomineo** [comment]
Cheers. I just installed VSCode and have no clue where files are. :)

What about like this? Do you like it more?

![schermata 2019-01-11 alle 11 05 15](https://user-images.githubusercontent.com/5409469/51027329-dbe1e800-1590-11e9-988a-2ee0ffd375de.png)

**Comment by jonbp** [comment]
Designer / Front-end developer here, agree that this could do with improving.

Here is my icon design for this:

![mockup](https://user-images.githubusercontent.com/3267483/51263472-383b7200-19ac-11e9-8106-757cb8a32d6d.jpg)

The icon is consistent in size with the rest of the sidebar icons and makes good use of the space with the arrows.

---

I've also designed a matching extension icon for the extension that I've included in the zip file:

![mini_icon](https://user-images.githubusercontent.com/3267483/51261974-3fad4c00-19a9-11e9-9806-4b696effc9ce.png)

### Assets

[sftp_icon_jbp.zip](https://github.com/liximomo/vscode-sftp/files/2765031/sftp_icon_jbp.zip)

**Comment by liximomo** [comment]
@niccolomineo @jonbp Both great works.

**Comment by andremacola** [comment]
On insiders I have a problem with the icon size

![Captura de Tela 2019-07-22 às 16 53 04](https://user-images.githubusercontent.com/3408809/61660859-362ad680-aca1-11e9-97a5-1a6fb9a01c38.png)

**Comment by HamsteRider-m** [comment]
@andremacola nice work bro!
