### ISSUE TITLE
can i config the local path to save the download file?

### ISSUE THREAD

**Issue by huanqingdong** [liximomo/vscode-sftp#455]
i config sftp use Multiple Context mode ,
[
    {
      "name": "210_elk",
      "context": "/210_elk",
      "host": "10.0.11.210",
      "username": "root",
      "password": "?*",
      "remotePath": "/home/elk"
    },
    {
      "name": "211_elk",
      "context": "/211_elk",
      "host": "10.0.11.211",
      "username": "root",
      "password": "?*",
      "remotePath": "/home/elk"
    },
    {
      "name": "212_elk",
      "context": "/212_elk",
      "host": "10.0.11.212",
      "username": "root",
      "password": "?*",
      "remotePath": "/home/elk"
    }
  ],
my config file is **D:\javaDev\sftp\.vscode\sftp.json**
when i edit file on server 210_elk use **Edit in Local** , it create a folder named **210_elk** in path **D://** ,
if edit file on all three Context , it will create three folder in path **D://**  ,
can i config the path to create the folder ?

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/wiki/config#context
