### ISSUE TITLE
Open SSH in Terminal: "Identity file not accessible" when using WSL and privateKey authentication

### ISSUE THREAD

**Issue by owenlwebb** [liximomo/vscode-sftp#456]
On Windows 10, if I have the Windows Subsystem for Linux (WSL) set as my default terminal in VSCode and click "Open SSH in Terminal" the terminal throws the error: "Identity file c:/User/Bob/id_rsa not accessible: No such file or directory."

I believe this issue is occurring because WSL expects Unix-like paths like /mnt/c/User/Bob/id_rsa and can't handle Windows-like paths such as c:/User/Bob/id_rsa . vscode-sftp recognizes that it's running on Windows and automatically prepends "c:/" to the privateKeyPath, when really it should be prepending "/mnt/c" since the user has specified WSL as their default VSCode terminal.

**To Reproduce**
1. With WSL installed, set WSL as the default VSCode terminal in the VSCode command palette 
2. Setup a private key based sftp connection (enter the path of the private key in sftp.json)
3. Begin SFTP connection
4. Right click on the server name and click "Open SSH in Terminal"

**Expected behavior**
With WSL set as my default VSCode terminal, clicking "Open SSH in Terminal" on a private key-based SFTP connection should begin an SSH connection without any errors. 

**Screenshots**
Screenshot of the error
![capture](https://user-images.githubusercontent.com/22690451/51013004-3433ce00-152e-11e9-8f83-db3ed0fce120.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version 1.30.2
 - Extension Version 1.9.1

**Extension Logs from Startup** - *required*
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPENDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[trace] run command 'Open Ssh Connection'
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)

**Comment by liximomo** [comment]
What your config of `privateKeyPath`?

**Comment by owenlwebb** [comment]
This is how I have my sftp.json configured. 

```
 {
        "name": "myserver",
        "host": "example.com",
        "port": 22,
        "privateKeyPath": "c:/Users/owenlwebb/Desktop/id_rsa",
        "passphrase": true,
        "username": "owenlwebb",
        "protocol": "sftp",
        "passive": false,
        "interactiveAuth": true,
        "remotePath": "/",
        "uploadOnSave": true,
        "syncMode": "update",
        "ignore": [
        "**/.vscode/**",
        "**/.git/**",
        "**/.DS_Store"
        ]
    }
```

**Comment by liximomo** [comment]
> vscode-sftp recognizes that it's running on Windows and automatically prepends "c:/" to the privateKeyPath
```
"privateKeyPath": "c:/Users/owenlwebb/Desktop/id_rsa",
```

Why did you say that vscode-sftp prepends the `c:/`?

**Comment by owenlwebb** [comment]
Oh excuse me, I have also tried configuring my `privateKeyPath` like this (to comply with WSL's Unix-like paths):

`"privateKeyPath": "/mnt/c/Users/owenlwebb/Desktop/id_rsa"`

In which case, vscode-sftp will prepend `c:/` (since it recognizes I'm running Windows) to make it an "absolute" path. In that case, this is the error that appears when I try to connect via the usual SFTP GUI:
![error](https://user-images.githubusercontent.com/22690451/51066813-b37edb80-15da-11e9-9928-947549f84593.PNG)

And this is the error that appears when I try to open an SSH connection (with WSL as my default shell)
![error2](https://user-images.githubusercontent.com/22690451/51066822-c7c2d880-15da-11e9-8739-fbdc1c5ba1e4.PNG)

**Comment by liximomo** [comment]
Can you show the setting of `terminal.external.windowsExec`?

**Comment by owenlwebb** [comment]
This line appears in the "default user settings" pane:
`"terminal.external.windowsExec": "C:\\WINDOWS\\System32\\cmd.exe"`

But there's also this line in the "user settings" pane:
`"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe"`
 
I believe it might override `terminal.external.windowsExec`? It probably was put there after I ran the `Terminal: Select Default Shell` command when I switched to WSL.

**Comment by liximomo** [comment]
That helps. I can check the value of `terminal.integrated.shell.windows` to auto prepends the `/mnt`.

**Comment by owenlwebb** [comment]
That should work! Though, you would also have to remove the `:` after `c`

**Comment by liximomo** [comment]
Could you help me test [1.9.2-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by owenlwebb** [comment]
Like I said in my last message, you would still need to remove colon after the `c` WSL-like paths require that there's no colon after the drive letter. 1.9.2-debug correctly prepends the `/mnt` but doesn't remove the `:` after `c`.

**Comment by owenlwebb** [comment]
Also, the `/mnt` is not encapsulated by double quotes. Here's  a screenshot of the exact error message I'm getting on 1.9.2-debug
![capture](https://user-images.githubusercontent.com/22690451/51136998-cf1cf880-180b-11e9-8348-41a37552efff.PNG)

**Comment by liximomo** [comment]
@owenlwebb Try again.

**Comment by owenlwebb** [comment]
Works perfectly, thank you!

**Comment by BernierCR** [comment]
Hello. Nice extension. 

However, I do not like this assumption that C: is mounted to /mnt/c. Sure that's the default WSL location. However, the how to run Docker in WSL guides, say that you have to change this. Don't most of us use Docker? 

I have my C drive mounted to /c not /mnt/c, which means this extension isn't usable right now. I can probably set up a symlink though. It would be nice if I didn't have to do this. 

Though this problem will be going away soon. Once WSL2 comes out, no one will be doing this Docker hack anymore. 

Thank you
