### ISSUE TITLE
Refresh on file/directory delete

### ISSUE THREAD

**Issue by niccolomineo** [liximomo/vscode-sftp#458]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
When deleting a file or a directory, the user has to refresh the remote explorer manually.

**Describe the solution you'd like**
It would be better if the refresh happened automatically.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Can't do this because of lacking support from vs code.
