### ISSUE TITLE
[sftp] Handshake failed: no matching client->server cipher

### ISSUE THREAD

**Issue by luongnv89** [liximomo/vscode-sftp#46]
# Problem
My configuration file:

```
{
    "host": "myhost.com",
    "port": 22,
    "username": "myusername",
    "password": null,
    "protocol": "sftp",
    "agent": "null",
    "privateKeyPath": "~/.ssh/id_rsa",
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/var/www/laravel/",
    "uploadOnSave": false,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "**/.vscode/**",
        "**/.git/**",
        "**/.DS_Store"
    ]
}
```
I am using `privateKey` instead of `password`

I got the error message **`[sftp] Handshake failed: no matching client->server cipher`** when trying to upload/download file.

With the same configuration, it works with `sftp on SublimeText`

# Specifications

  - Version: VSC-1.17.1 (1.17.1), sftp-0.8.4
  - Platform: MacOS High Sierra 10.13

Thanks,

**Comment by liximomo** [comment]
I will add an option allows you to explicitly override the default transport layer algorithms used for the connection. Waiting for next version.

**Comment by liximomo** [comment]
The v0.8.5 now support more cipher algorithms. Try it.

**Comment by luongnv89** [comment]
@liximomo  awesome, it works perfectly now. 
Thank you very much for your amazing work !

**Comment by niiiksh** [comment]
I've got same error with SFTP 1.3.1
VS Code 1.25.1
