### ISSUE TITLE
Slow SSH upload-on-save with some file types

### ISSUE THREAD

**Issue by arcaweb-ch** [liximomo/vscode-sftp#460]
Hi there, I am experiencing a slow upload while saving+uploading files via SFTP, but it only happens with CSS file type, and 90% of the times. No problem with other file types such as PHP or JS.

The debug log looks normal but each operation runs slow, even the [file-save] log line does not come out immediately. Sometimes the full save-upload session takes 30 to 60 seconds, during this time the file is unavailable or blank on the server.

![vscode](https://user-images.githubusercontent.com/43749906/51175227-fb8f4e00-18b9-11e9-9591-7afb3a248a4d.gif)

Any ideas what's causing this?

 - OS: Win10
 - VSCode v1.30.2
 - SFTP v1.9.1

**Comment by liximomo** [comment]
I think this should be a server-side problem.

**Comment by arcaweb-ch** [comment]
thanks @liximomo,

I thought the same but I see there are no transfer issues with other sftp programs. I always see "Running save participants" message before each slow transfer, so I guess it could be related to it.

**Comment by liximomo** [comment]
This could be some other vs code extensions block the saving process. Try only enable sftp.

**Comment by arcaweb-ch** [comment]
In fact, the github extension is causing the vs code to "save participants", I disabled it and now the issue is gone. After reading the vscode forum I see that "save participants" has something to do with multiple file writing on-save, used for example in "filediff" feature, but I have still no idea how this can affect sftp transfer and how it can be fixed.
