### ISSUE TITLE
How to start an SFTP connection with an already established configuration file?

### ISSUE THREAD

**Issue by abobakrd** [liximomo/vscode-sftp#463]
Ive already established an working configuration file (sftp.json), but how do i start it when i close and reopen vscode? 

I have looked everywhere in issues, documentation for this, but with no answers.

Do i need to set the configuration file each time i open vscode? I doubt this, but this is only working method at the moment.

**Comment by liximomo** [comment]
It will automatically start when there is a `sftp.json` file under the `.vscode` folder.

**Comment by abobakrd** [comment]
You mean when its inside the `.vscode` folder right? It is inside, but it still wont start.
