### ISSUE TITLE
Multiple Context in the Remote Explorer

### ISSUE THREAD

**Issue by clayms** [liximomo/vscode-sftp#469]
**Is this a similar or duplicate feature request?**
- [x] No.

**Is your feature request related to a problem? Please describe.**
When using Multiple Context, the Remote Explorer only shows one remote file directory tree.

**Describe the solution you'd like**
Show all remote directory trees in the Remote Explorer that are in the Multiple Contexts in the sftp.json file.

**Describe alternatives you've considered**
Each context works when it is the only one in sftp.json, and I can see the remote directory tree in the Remote Explorer, just not all of them at the same time when I specify multiple contexts.

Please let me know if there is a setting I can change to fix this.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Show me your config, please.

**Comment by clayms** [comment]
```
[
    {
        "name" : "linux",
        "protocol": "sftp",
        "host": "100.100.100.100",
        "username": "username",
        "remotePath": "/home/username/projects",
        "uploadOnSave":true,
        "context": "./",
        "ignore": [
            ".vscode",
            ".git",
            ".gitignore",
            ".DS_Store",
            "__pycache__",
            ".remote-sync.json",
            "*.zip",
            "*.pptx",
            "*.msg"
        ] 
    },
    {
        "name" : "win10",
        "protocol": "sftp",
        "host": "200.200.200.200",
        "username": "domain\\username",
        "remotePath": "C:\\Users\\username\\Documents\\Projects",
        "uploadOnSave":true,
        "context": "./",
        "ignore": [
            ".vscode",
            ".git",
            ".gitignore",
            ".DS_Store",
            "__pycache__",
            ".remote-sync.json",
            "*.zip",
            "*.pptx",
            "*.msg"
        ]  
    }    
]
```

**Comment by liximomo** [comment]
The context must be different.

**Comment by clayms** [comment]
Is it possible to uploadOnSave from the same local folder to multiple remotes, and also see the directory trees for both remotes in the Remote Explorer?

**Comment by liximomo** [comment]
No, can't do that now.

**Comment by brando90** [comment]
@liximomo @clayms what is a context? I want to upload to multiple servers at once on save. So BOTH servers should be updated.

**Comment by clayms** [comment]
@brando90 see if this helps: https://github.com/liximomo/vscode-sftp#multiple-context 

I believe the context has to be a different folder on your local.  I think what @liximomo was saying *(as of 24 Jan 2019)* is that it is not possible to link the same folder (and the files within) to multiple remotes.  Although, @liximomo could have been saying that it is just not possible to *view* multiple remote directory trees in the Remotes Explorer.

**Comment by brando90** [comment]
> @brando90 see if this helps: https://github.com/liximomo/vscode-sftp#multiple-context
> 
> I believe the context has to be a different folder on your local. I think what @liximomo was saying _(as of 24 Jan 2019)_ is that it is not possible to link the same folder (and the files within) to multiple remotes. Although, @liximomo could have been saying that it is just not possible to _view_ multiple remote directory trees in the Remotes Explorer.

Just to make the terminology clear, what exactly is a context? is that just a local folder?

**Comment by brando90** [comment]
> No, can't do that now.

you mean the contexts have to be different? Why is that?

Btw, is contexts just local path?

**Comment by brando90** [comment]
> Is it possible to uploadOnSave from the same local folder to multiple remotes, and also see the directory trees for both remotes in the Remote Explorer?

btw I think the right bash command this extension might do what we want (push to multiple servers at once): https://marketplace.visualstudio.com/items?itemName=appulate.filewatcher
