### ISSUE TITLE
Switchable configs

### ISSUE THREAD

**Issue by X-Tender** [liximomo/vscode-sftp#47]
Hi,
I would love a feature that handle multiple configs.
For example to switch between a dev-server config and a live-server config.
Maybe a posibility to override the "default" settings. like this:
```json
{
    "host": "www.thisisthehost.com",
    "port": 22,
    "username": "username",
    "password": null,
    "protocol": "sftp",
    "uploadOnSave": false,
    "profiles" : {
        "dev" : {
            "remotePath" : "/dev",
            "uploadOnSave": true,
        },
        "live" : {
            "remotePath" : "/live"
        }
    }
}
```
So it could be switch between dev and live or any other profile in the project and upload files. :)

**Comment by ohadcn** [comment]
You can get similar behavior by using array config. I still miss the ability to switch targets on upload (e,g: have `upload to dev` and `upload to production` buttons)

```
[
  {
    "name": "dev",
    ...
    "host": "dev.example.com",
    "remotePath": "/dev",
    "uploadOnSave": true
  },  {
    "name": "prod",
    ...
    "host": "example.com",
    "remotePath": "/live",
    "uploadOnSave": false
  }
]

```

**Comment by liximomo** [comment]
I am working on this now. 😏

**Comment by liximomo** [comment]
Support in v1.2.3. 🎉🎉🎉🎉
