### ISSUE TITLE
upload file failed when remotePath is symbolicLink

### ISSUE THREAD

**Issue by sdir** [liximomo/vscode-sftp#473]
**Describe the bug**
I set  symbolic link directory as remote path.
Failed when uploading a file in directory. 

**Desktop (please complete the following information):**
 - OS: Win10
 - VSCode Version 1.30.2
 - Extension Version 1.9.2

**Comment by Accuraty** [comment]
I would like to add to this... I have experience similar and noticed these additional 'clues':
- it happens intermittently (seriously, sometime I retry and the upload works)
- my symbolic link folder names all start with a dash (not sure if that is relevant), e.g. "-theme"
- the remote FTP server is the latest version of FileZilla
- same OS, VSCode, and ext as stated above

**Comment by CJFulford** [comment]
Adding to this,
I succeeded in uploading a file to a directory within a symlink, but not to the symlink directory itself.

Succeeded
.../<symlink>/<directory>/<file>

Failed
.../<symlink>/<file>
