### ISSUE TITLE
是否能支持本地路径和远程路径不一致的情况

### ISSUE THREAD

**Issue by xiaotan0305** [liximomo/vscode-sftp#475]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [ ] No.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)
我本地的目录结构是
![image](https://user-images.githubusercontent.com/12965330/51784621-c242c200-2186-11e9-9015-46adc2105011.png)
并不是根目录
需要上传的远程路径
"remotePath": "/common_m/m_3385/jslib/modules/im"，
请问我想把dev下的文件传到服务器应该怎么配置？

**Comment by liximomo** [comment]
```
{
  "context": "dev"
}
```
