### ISSUE TITLE
配置文件解析BUG

### ISSUE THREAD

**Issue by qq9349540** [liximomo/vscode-sftp#476]
使用环境：win7sp1x64 vscode：1.30.2 插件版本：1.9.2

配置文件：
{
    "host": "xxx.xxx.xxx.xxx",
    "protocol": "ftp",
    "port": "21",
    "username": "xxx",
    "password": "xxxxxxxxx",
    "remotePath": "/"
}
 如上配置会报错 提示端口非整型，修改成：
{
    "host": "xxx.xxx.xxx.xxx",
    "protocol": "ftp",
    "port": 21,
    "username": "xxx",
    "password": "xxxxxxxxx",
    "remotePath": "/"
}
会报错，提示找不到配置文件。彻底奔溃了，这形成了死循环。

**Comment by liximomo** [comment]
不管端口是数字还是整型，找不到配置文件这个错都是存在的，只不过你是字符串的时候，他没进行到配置存不存在那一步就是败了.  不存在循环。

这就好比你去办银行卡，你生日填个名字，肯定不能通过，你纠正了生日，但是你填别人的名字和身份证号，最终验证还是会失败吧，你不能说你最后失败和你生日怎么填的有关系。

关于为什么找不到配置文件，把详细的 debug log 贴上来。
