### ISSUE TITLE
Why does sftp have this error?

### ISSUE THREAD

**Issue by qiacoucc** [liximomo/vscode-sftp#479]
[warn] ENOENT: no such file or directory, open 'C:\Users\User\.ssh\config' load C:\Users\User\.ssh\config failed

Why does sftp have this error?

**Comment by liximomo** [comment]
It's just a warning. For more information, go to [ssh_config](https://linux.die.net/man/5/ssh_config).

**Comment by qiacoucc** [comment]
You are chinese? 这个应该是SFTP 没有把配置文件写到C:\Users\User.ssh\config
