### ISSUE TITLE
Hostname from .ssh\config results in ENOTFOUND in Windows

### ISSUE THREAD

**Issue by Arlington1985** [liximomo/vscode-sftp#481]
**Do you read the FAQ?**
- [ X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
This is basically same error for https://github.com/liximomo/vscode-sftp/issues/385
I have specified all connection parameters in `C:\\Users\\myuser\\.ssh\\config` file but seems it can't be read by application.
but ssh connection work fine, even from this tool "Open SSH in Terminal"

Here is my sftp.json file
```
{
    "protocol":"sftp",
    "host": "devtop_rovshan",
    "username": "remote-user",
    "remotePath": "/home/remote-user/development/docker",
    "sshConfigPath": "C:\\Users\\myuser\\.ssh\\config",
    "uploadOnSave": true
}
```
devtop_rovshan is configured with proxy and connection works perfectly through ssh

**To Reproduce**
1. Install OpenSSH to Windows
2. Configure your config file in `~\.ssh\config` file
3. Try to reach to remote host via `ssh` command
4. If it works download VSCODE
5. Install sftp from marketplace
6. Configure your config file in .ssh folder
7. Create sftp.json file
8. Save any file inside project folder

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.27.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs from Startup** - *required*
 Here are logs:

```
[info] [file-save] h:\development\docker\Dockerfile
[trace] handle upload file for h:\development\docker\Dockerfile
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying devtop_rovshan on port 22 ...
[error] Error: [devtop_rovshan]: getaddrinfo ENOTFOUND devtop_rovshan devtop_rovshan:22
	at Client.module.exports.a.default._connectSSHClient.e.on.on.e (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.9.3\dist\extension.js:70:106825)
	at emitOne (events.js:121:20)
	at Client.emit (events.js:211:7)
	at Socket.<anonymous> (C:\Users\myuser\.vscode\extensions\liximomo.sftp-1.9.3\node_modules\ssh2\lib\client.js:296:10)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at emitErrorNT (internal/streams/destroy.js:64:8)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9) download h:\development\docker\Dockerfile
```

**Comment by liximomo** [comment]
Can you show me the content of your ssh config file?

**Comment by Arlington1985** [comment]
It really doesn't matter. You can create your own the simplest config file. Just doesn't attempt to read I think. Even there's no config file reading log item

**Comment by Arlington1985** [comment]
And the tool tells that username is mandatory but you can specify it in config file as well and not to use in the command line.

**Comment by liximomo** [comment]
Can you show me the content of your ssh config file?

**Comment by Arlington1985** [comment]
I can't because there is sensitive information

**Comment by dambrogia** [comment]
This issue hasn't been resolved @liximomo there are two issues open and if you use any sort of SSH config file you can easily see that it doesn't read the `~/.ssh/config`.

This should be re-opened.

**Comment by liximomo** [comment]
@dambrogia Please open a new issue.
