### ISSUE TITLE
Support multiple default profiles

### ISSUE THREAD

**Issue by unional** [liximomo/vscode-sftp#482]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
I need to send the changed files to multiple profiles.
I run a test environment consists of multiple machines.
My test suite will run tests across the test environment.
So when I change a file, I need to sync it to all of them.

**Describe the solution you'd like**
Able to define multiple default profiles.

```js
{
  "defaultProfile": [...], // or
  "defaultProfiles": [...]
}
```

**Describe alternatives you've considered**
Currently, I'm using https://github.com/mkloubert/vs-deploy and this is the only reason I keep using it.
I have problems with it when I make multiple file changes at the same time (e.g. find/replace).
It causes VSCode to hang.
So I want to find a different solution.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Duplicated of #107
