### ISSUE TITLE
Error unclear: "SFTP expects to work at a folder"

### ISSUE THREAD

**Issue by fulldecent** [liximomo/vscode-sftp#483]
# Test case

1. Read usage instructions at https://github.com/liximomo/vscode-sftp#usage
2. Install extension
3. Press Cmd+Shift+P, run `SFTP: config`

# Expected result

Enjoy

# Actual result 

Error message:

> SFTP expects to work at a folder

📁⛏ ??

**Comment by ianmcl** [comment]
mkdir
