### ISSUE TITLE
Open SSH in terminal

### ISSUE THREAD

**Issue by budisentosa** [liximomo/vscode-sftp#486]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x ] No.

**Is your feature request related to a problem? Please describe.**
I already use remote path : (and it is no problem on Remote Explorer )
but when I use "Open SSH in terminal" , remote path is not call
i got home directory 
not remote path that i set on sftp.json 

**Describe the solution you'd like**
when i log in by ssh, remote path is call too 

**Describe alternatives you've considered**

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [x ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Support in v1.9.4.
