### ISSUE TITLE
Adding a param description at [Config Wiki]

### ISSUE THREAD

**Issue by d200746** [liximomo/vscode-sftp#487]
**Describe**
Adding a param description at [Config Wiki](https://github.com/liximomo/vscode-sftp/wiki/config) to set the maximum connection time
```
**connectTimeout**
number - the maximum connection time
```

**Reason**
in my development environment, the handshake time is about 20s, but the default time in the plugin is 10s.
I find the parameter 'connectTimeout' when i debug the conection，but this parameter is not metioned in the config wiki.

**Screenshots**
```
in debug console:
[info] config at f:\****** {"remotePath":"xxxx","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"My Server","host":"xxxx","port":22,"username":"******","password":"******"}
```

**Comment by liximomo** [comment]
Done.
