### ISSUE TITLE
Upload on Save stopped working

### ISSUE THREAD

**Issue by GrahamH68** [liximomo/vscode-sftp#49]
## Expected Behavior
Upload to SFTP server on file Save

## Actual Behavior
This has been working flawlessly until recently but has just stopped uploading on save. I can still right-click on a file and select SFTP:Upload which works fine.

## Steps to Reproduce the Problem

  1. Open VSC
  2. VSC shows "SFTP Ready"
  3. Save a file
  4. Does not upload to SFTP server

### Extension Logs
[info]: config at z:/Projects/host {
    "host": "host.example.com",
    "port": 22,
    "username": "username",
    "password": "password",
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/home/username/code",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "z:/Projects/host/**/.vscode/**",
        "z:/Projects/host/**/__pycache__/**",
        "z:/Projects/host/**/.git/**",
        "z:/Projects/host/**/.DS_Store",
        "/home/username/code/**/.vscode/**",
        "/home/username/code/**/__pycache__/**",
        "/home/username/code/**/.git/**",
        "/home/username/code/**/.DS_Store"
    ],
    "configRoot": "z:/Projects/host"
}
 

## Specifications

  - Version: SFTP v0.8.5
  - Platform: Virtual Studio Code v1.17.2 on Windows 10

**Comment by liximomo** [comment]
1. restart vsc.
2. save file and wait.
3. right-click on a file and select SFTP:Upload which works.
4. post the logs to me.

**Comment by joshcummingsdesign** [comment]
I had this too, but then I realized the file had to be modified in order for it to actually upload. I think this is different from the old version. That was my issue, not sure if this helps.

**Comment by joshcummingsdesign** [comment]
Same issue here. Nothing shows up in the logs.

**Comment by GrahamH68** [comment]
This has started working again with the latest update. Thanks for the quick fix.
