### ISSUE TITLE
右键菜单 点击上传文件 能否自动保存下文件 再上传

### ISSUE THREAD

**Issue by qiacoucc** [liximomo/vscode-sftp#492]
右键菜单 点击上传文件 能否自动保存下文件 再上传
不然有时候忘记保存 进行上传 文件是上传没保存的
sublimetext 的SFTP是上传前自动保存当前文档的, 建议考虑下这个功能

**Comment by liximomo** [comment]
Support in v1.11.0.

**Comment by qiacoucc** [comment]
目前测试右键点击上传文件 只是保存了 并没有一键保存并上传 ,需要再次点击后才上传
 
 
------------------ Original ------------------
