### ISSUE TITLE
Wrong path to remote private key when hopping

### ISSUE THREAD

**Issue by vuki** [liximomo/vscode-sftp#493]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

Either I don't understand how hopping works or there is a bug. My setup is as follows. Windows PC to server, then from server to a remote machine through a reverse SSH tunnel. Connection to the first server works, hopping does not. Direct SSH from the server to the remote machine from the server terminal works without problems.

My config:

```
{
    "name": "testing",
    "host": "server",
    "protocol": "sftp",
    "port": 22,
    "username": "user",
    "privateKeyPath": "C:/Users/clientuser/.ssh/private.ppk",
    "passphrase": true,
    "uploadOnSave": true,
    "hop": {
        "host": "localhost",
        "port": 2222,
        "username": "remoteuser",
        "privateKeyPath": "/home/serveruser/.ssh/raspi.key"
    }
}
```

Result (before even trying to connect):

`ENOENT: no such file or directory, open 'C:\home\serveruser\.ssh\raspi.key'`

According to the documentation. if `provateKeyPath` is given in `hop`, then "the key file is assumed on the hop". However, the extension treats this option as a path on the *client* machine and throws an error. Am I missing something?

**To Reproduce**
1. Use the setup as above.
2. Try to connect to the remote machine from a Windows PC.
3. See error

**Expected behavior**
Connection open to the remote device.

**Desktop (please complete the following information):**
 - Windows 10
 - VSCode 1.31.1
 - Extension Version 1.9.5

**Extension Logs from Startup** - *required*

```
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at c:\_ROB_\sftp-test {"remotePath":"./","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"station003","host":"*****","port":22,"username":"******","privateKeyPath":"C:/Users/user/.ssh/private.ppk","passphrase":"******","hop":{"host":"localhost","port":2222,"username":"remoteuser","privateKeyPath":"/home/serveruser/.ssh/raspi.key"}}
```

**Comment by liximomo** [comment]
There is no error in logs.

**Comment by vuki** [comment]
There is no error in logs because the extension does not log such errors. The error is displayed in the notification area of VS code. This error is generated during validation of the config file, before the extension even tries to connect to the server.

**Comment by liximomo** [comment]
@vuki Sorry. I can't reproduce it.

**Comment by liximomo** [comment]
```
{
    "name": "testing",
    "host": "server",
    "protocol": "sftp",
    "port": 22,
    "username": "user",
    "privateKeyPath": "/home/serveruser/.ssh/raspi.key",
    "passphrase": true,
    "uploadOnSave": true,
    "hop": {
        "host": "localhost",
        "port": 2222,
        "username": "remoteuser",
        "privateKeyPath": "C:/Users/clientuser/.ssh/private.ppk"
    }
}
```

**Comment by vuki** [comment]
Oh, so the `hop` section defines the intermediate machine and the main section - the target one? I didn't expect that, I thought that I'm supposed to log into the server first, then hop to the remote. Perhaps the name `hop_from` would be more descriptive.

I changed the order of the entries and still the same error: `ENOENT: no such file or directory, open 'C:\home\serveruser\.ssh\raspi.key'`

So I decided to download the remote key from the server to the client computer and I set the path to the *local* file (on the client) and it finally worked. I was expecting that the private key for connection from the server to the remote is read from the server, but it's not the case: private keys are *always* read from the client.

This is my final config:

```
{
    "name": "testing",
    "host": "localhost",
    "protocol": "sftp",
    "port": 2222,
    "username": "pi",
    "privateKeyPath": "C:/Users/clientuser/.ssh/raspi.key",
    "uploadOnSave": true,
    "hop": {
        "host": "server",
        "port": 22,
        "username": "user",
        "privateKeyPath": "C:/Users/clientuser/.ssh/private.ppk",
        "passphrase": true
    }
}
```

It works, but it's very complicated and the documentation doesn't explain this sufficiently clear.

Thanks for help, problem resolved.

**Comment by liximomo** [comment]
> I was expecting that the private key for connection from the server to the remote is read from the server.

Obviously, this is a bug. I will fix it.

**Comment by liximomo** [comment]
Try [1.10.0](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) with your original config.
```
{
    "name": "testing",
    "host": "server",
    "protocol": "sftp",
    "port": 22,
    "username": "user",
    "privateKeyPath": "C:/Users/clientuser/.ssh/private.ppk",
    "passphrase": true,
    "uploadOnSave": true,
    "hop": {
        "host": "localhost",
        "port": 2222,
        "username": "remoteuser",
        "privateKeyPath": "/home/serveruser/.ssh/raspi.key"
    }
}
```

**Comment by vuki** [comment]
Tested 1.10.0, not working: ```ENOENT: no such file or directory, open 'C:\home\clientuser\.ssh\raspi.key'```.

**Comment by mailtogom** [comment]
I have same issue. Is this resolved?

**Comment by liximomo** [comment]
@vuki Try [1.10.0](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) with your original config again.

**Comment by liximomo** [comment]
@mailtogom Please try the new  [1.10.0](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge)

**Comment by mailtogom** [comment]
I tried with this sftp.json

{
    "name": "web",
    "protocol": "sftp",
    "host": "10.10.20.10",
    "port": 22,
    "username": "ec2-user",
    "remotePath": "/home/ec2-user",
    "privateKeyPath" : "/home/ec2-user/key/AMC-WEB.pem",
    "hop": [
        {
        "host": "52.68.174.74",
        "port": 50022,
        "username": "ec2-user",
        "privateKeyPath": "/Users/mailtogom/amczet.pem"
        },
        {
        "host": "10.10.10.100",
        "port": 50022,
        "username": "ec2-user",
        "privateKeyPath" : "/home/ec2-user/key/AMC-INT-BASTION-A.pem"
        }
    ],

**Comment by mailtogom** [comment]
I tried, 1.10.0 , but no luck. 

[error] Error: ENOENT: no such file or directory, open 'TARGET.pem' 

local -> hopA -> hopB -> target
{
    "name": "web",
    "protocol": "sftp",
    "host": "10.10.20.10",  <--- target
    "port": 22,
    "username": "ec2-user",
    "remotePath": "/home/ec2-user",
    "privateKeyPath" : "/home/ec2-user/key/TARGET.pem",   <-- target pem file in hopB server
    "hop": [
        {
        "host": "52.68.111.11",     <-- hopA
        "port": 10022,
        "username": "ec2-user",
        "privateKeyPath": "/Users/mailtogom/HOPA.pem"  <-- hopA pem file in local system
        },
        {
        "host": "10.10.10.100",    <-- hopB
        "port": 10022,
        "username": "ec2-user",
        "privateKeyPath" : "/home/ec2-user/key/HOPB.pem"   <--- hopB pem file in hopA server
        }
    ]
}

**Comment by vuki** [comment]
> @vuki Try [1.10.0](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) with your original config again.

I tested the new version. Now it works.

**Comment by liximomo** [comment]
@mailtogom with v1.10.0. It should be 
```
local -> hopA -> hopB -> target
{
"name": "web",
"protocol": "sftp",
"host": "hopA", <--- hopA
"port": 22,
"username": "ec2-user",
"remotePath": "/home/ec2-user",
"privateKeyPath" : "/home/ec2-user/key/TARGET.pem", <-- target pem file in hopB server
"hop": [
{
"host": "hopB", <-- hopB
"port": 10022,
"username": "ec2-user",
"privateKeyPath": "/Users/mailtogom/HOPA.pem" <-- hopA pem file in local system
},
{
"host": "target", <-- target
"port": 10022,
"username": "ec2-user",
"privateKeyPath" : "/home/ec2-user/key/HOPB.pem" <--- hopB pem file in hopA server
}
]
}
```

**Comment by liximomo** [comment]
@vuki Great.

**Comment by zhouxincheng** [comment]
(SSH) Channel open failure: open failed.
my configuration is just same as @vuki

**Comment by lobsterdak** [comment]
local -> hop -> target
(SSH) Channel open failure: open failed.
What am I doing wrong?
{
    "name": "test",
    "host": "hopHost",
    "username": "hopUser",
    "password": "hopPassword",
    "hop": {
        "host": "targetHost",
        "username": "targetUser",
        "privateKeyPath": "targetPath" //absolute path on to key file on hop server
    }
}
