### ISSUE TITLE
"Edit in Local" from Command Palette

### ISSUE THREAD

**Issue by vmasrani** [liximomo/vscode-sftp#498]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
Nope! SFTP is great :) 

**Describe the solution you'd like**
When I use the remote explorer, I have to right-click on the file to edit in local. It would be nice to be able to switch to editing mode either with a hotkey or via the command palette.

**Describe alternatives you've considered**
I think using the mouse is the only way to edit currently. 

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/wiki/Setting#downloadwhenopeninremoteexplorer
