### ISSUE TITLE
每一次新增配置文件，都报：config file not found，需重新打开项目才生效

### ISSUE THREAD

**Issue by IIInsomnia** [liximomo/vscode-sftp#5]

**Comment by liximomo** [comment]
检查是否最新版本？如果是的话，请提供一下信息

- 什么平台
- log(查看-输出->sftp)

**Comment by liximomo** [comment]
0.6.7 已经修复了

**Comment by IIInsomnia** [comment]
似乎还是没好，我更新插件了
Mac
[sftp]: (path) config file not found

**Comment by liximomo** [comment]
提供log(查看-输出->sftp)，目录结构也截下图

**Comment by Yaoshicn** [comment]
@IIInsomnia 可以尝试先打开一个工程目录再执行命令

**Comment by liximomo** [comment]
@tanzhihang 更新至1.2.2.

**Comment by tanzhihang** [comment]
@liximomo 我发现，我全局安装了 npm i  typescript -g，就有这个问题，卸载typescirpt，sftp就正常了

**Comment by tanzhihang** [comment]
@liximomo 我发现，我卸载了全局安装的typescript，sftp就能正常使用了
