### ISSUE TITLE
Single Hop stopped working at version 1.10 - Works for version 1.9.5

### ISSUE THREAD

**Issue by ralphsawaya** [liximomo/vscode-sftp#500]
Hi Liximomo,

First, thanks a lot for this plugin :)
When the plugin is set to version 1.10 the single hop server stopped working and I can no longer browse the remote repository. I reversed to version 1.9.5 to make it work again.

OS: Win
VSCode Version 1.32.1
Extension Version 1.10.0

MY CONFIG:

{
    "protocol": "sftp",
    "name": "Test",
    "host": "10.xx.xx.xxx",
    "username": "myuser",
    "remotePath": "/home/myuser/",
    "privateKeyPath": "C:/Users/myuser/ssh/id_rsa",
    "port":22,
    "uploadOnSave": true,
    "hop": [
      {
        "host": "10.xx.xx.x",
        "username": "myuser",
        "port":22,
        "privateKeyPath": "C:/Users/myuser/ssh/id_rsa"
      }
    ]
 }

ERROR LOGS:

"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"test","host":"10.xx.xx.xxx","username":"******","privateKeyPath":"C:/Users/myuser/ssh/id_rsa","port":22,"hop":[{"host":"10.xx.xxx.x","username":"myuser","port":22,"privateKeyPath":"C:/Users/myuser/ssh/id_rsa"}]}
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying 10.xx.xx.x on port 22 ...

POPUP ERROR:
Timed out waiting for hanshake

Thanks
Ralph

**Comment by liximomo** [comment]
The config has changed. See https://github.com/liximomo/vscode-sftp#single-hop.

**Comment by ralphsawaya** [comment]
Hi Liximomo,

Thanks a lot. It is working fine now. Here are few points for you you might want to consider:

1- In the README of Single hop you have an extra comma under section //hop 'privateKeyPath": "/Users/localUser/.ssh/id_rsa", 

2- on version 1.9.5 I only had to store the key on my local machine. I did not have to store the key on the hop machine. I was just pointing to my local key for both privateKeyPath and it was working fine. Whereas for now on the hop machine I must store the key and point to it, which is fine but just saying.

3- I tried to make a donation and tried with two cards Amex and Visa (I live in France) but on both occasion I get the message "The card you specified can not be used for this payment. Enter another card number."

Feel free to close this issue.

Thanks
Ralph

**Comment by liximomo** [comment]
Good advice.

**Comment by Matschik** [comment]
I miss 1.9.5 configuration because I can store the key on my local machine.
I'm 100% with @ralphsawaya that the previous configuration was much better...
So I'm blocking my extension version to 1.9.5.

**Comment by liximomo** [comment]
@Matschik I will consider to add it back in another way.
