### ISSUE TITLE
how to active mode??

### ISSUE THREAD

**Issue by bsk824** [liximomo/vscode-sftp#501]
Hi~
I am using vscode-sftp very well.
How do I set it to acitve mode?
Thank you for making a good program.

**Comment by enriquevgarcia** [comment]
SFTP extension is not working for me and I think it is because I can not set active mode. Is possible to set active ftp mode via config settings?

Thanks.

**Comment by ramumanavalan** [comment]
This SFTP is woking fine with passive mode. But When I try with active mode there is no option to make it.
