### ISSUE TITLE
downloadOnOpen jumps to top of file

### ISSUE THREAD

**Issue by stilliard** [liximomo/vscode-sftp#504]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When using "downloadOnOpen" and you open a file, it jumps from your last position to the top of the file. Same if you find in project and open a file not already open, see steps below. 
Might be a VS Code issue with reloading a file? 

**To Reproduce**
1. Set "downloadOnOpen": true
2. Create a file with about 40 or lines and then a random word at the bottom
3. Close the file and find in project for that word
4. Click the find result for that file, it'll load on the line, but then it'll jump to the top of the file after downloading it 

**Expected behavior**
Shouldn't jump to top or move the user scroll position.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux (maybe others but unsure)
 - VSCode Version 1.32.1
 - Extension Version 1.10.0

**Extension Logs from Startup** - *required*
<details>
<summary>Log output in case needed</summary>
<pre>
[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at /home/andrew/projects/my-project {"remotePath":"/","uploadOnSave":true,"downloadOnOpen":true,"ignore":[".vscode",".git"],"concurrency":4,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":true,"remoteTimeOffsetInHours":0,"name":"my-project","host":"my-project","port":21,"secureOptions":{"rejectUnauthorized":false},"username":"user@my-project","password":"******"}
[info] [file-open] /home/andrew/projects/my-project/folder/file.txt
[trace] handle download file for /home/andrew/projects/my-project/folder/file.txt
[debug] < '220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 2 of 50 allowed.\r\n220-Local time is now 22:21. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220-IPv6 connections are also welcome on this server.\r\n220 You will be disconnected after 15 minutes of inactivity.\r\n'
[debug] > AUTH TLS
[debug] < '234 AUTH TLS OK.\r\n'
[debug] > PBSZ 0
[debug] < '200 PBSZ=0\r\n'
[debug] > PROT P
[debug] < '200 Data protection level set to "private"\r\n'
[debug] > USER user@my-project
[debug] < '331 User user@my-project OK. Password required\r\n'
[debug] > PASS ******
[debug] < '230 OK. Current directory is /\r\n'
[debug] > FEAT
[debug] < '211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n UTF8\r\n TVFS\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n'
[debug] < '211 End.\r\n'
[debug] > TYPE I
[debug] < '200 TYPE is now 8-bit binary\r\n'
[debug] > PASV
[debug] < '227 Entering Passive Mode (x,xxx,xxx,xx,xxx,xxx)\r\n'
[debug] > LIST /folder
[debug] < '150 Accepted data connection\r\n'
[debug] < '226-Options: -a -l \r\n'
[debug] < '226 4 matches total\r\n'
[debug] > PASV
[debug] < '227 Entering Passive Mode (x,xxx,xxx,xx,xxx,xx)\r\n'
[debug] > RETR /folder/file.txt
[debug] < '150 Accepted data connection\r\n'
[debug] < '226-File successfully transferred\r\n'
[debug] < '226 0.000 seconds (measured here), 0.54 Mbytes per second\r\n'
[debug] > MODE S
[debug] < '200 S OK\r\n'
[info] remote -> local /home/andrew/projects/my-project/folder/file.txt
[debug] > NOOP
[debug] < '200 Zzz...\r\n'
</pre>
</details>

**Comment by liximomo** [comment]
It's expected. You can't save the position because the file content may change after a fresh download.

**Comment by stilliard** [comment]
Ah shame, though maybe we could save the position if the content doesn't change?
No worries though.
