### ISSUE TITLE
sftp: open ssh in terminal not working anymore

### ISSUE THREAD

**Issue by PriitGit** [liximomo/vscode-sftp#508]
**Do you read the FAQ?**
- [x ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

1. sftp: open ssh in terminal

2. WITH PUBLIC key
ssh -t virt66165@2A02:29E8:770:0:3::46 -p 22 -i "C:/Users/defix/.ssh/id_rsa"
"cd \"/data02/virt66165/domeenid/www.veebiteenus.ee/keitglass/wp-content/themes
/keitglass\"; exec $SHELL -l"
bash: /usr/bin/bash: No such file or directory
bash: line 0: exec: /usr/bin/bash: cannot execute: No such file or directory
Connection to 2a02:29e8:770:0:3::46 closed.

2a. AND OTHER PROJECT WITH PASS:
ssh -t priit@192.168.8.120 -p 22 "cd \"/\"; exec $SHELL -l"
priit@192.168.8.120's password:
bash: /usr/bin/bash: No such file or directory
Connection to 192.168.8.120 closed.

Remote explorer working correcrly, but not SSH terminal.

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

[trace] run command 'Open Ssh Connection'
[debug] Outgoing: Writing CHANNEL_FAILURE (0)
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[debug] Outgoing: Writing CHANNEL_FAILURE (0)

**Comment by lscloudpro** [comment]
Same here.  Downgrading to version 1.9.3 works just fine.  All versions after 1.9.3 break ... very similar to what has been described by PriitGit.  Connecting SFTP via SSH with any other tooling (XShell5, CyberDuck, etc.) works fine.  Many other people I talked to recently have experienced the same issue.

**Comment by PriitGit** [comment]
ssh connection working now, but not getting remote path("remotePath")
