### ISSUE TITLE
"connecting..." indefinitely 

### ISSUE THREAD

**Issue by M-Pixel** [liximomo/vscode-sftp#51]
## Expected Behavior

With a config that contains

```json
"privateKeyPath": "/some/path",
"passphrase": null
```

and a private key that is protected by a passphrase, when I `SFTP: Sync To Local`, I expect to receive a prompt that allows me to enter my private key's passphrase.

## Actual Behavior
"connecting..." is displayed indefinitely in the bottom status bar.

## Steps to Reproduce the Problem

  1, Create an SSH private key
  1. Create a configuration with the above options
  1. Press F1
  1. SFTP: Sync To Local

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 
```
[info]: config at redacted {
    "host": "redacted",
    "port": 22,
    "username": "core",
    "password": null,
    "protocol": "sftp",
    "agent": "/tmp/ssh-5D4Vv4lQQE4L/agent.7053",
    "privateKeyPath": "/redacted",
    "passphrase": null,
    "passive": false,
    "interactiveAuth": true,
    "remotePath": "/redacted",
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "/redacted/**/.vscode/**",
        "/redacted/**/.vscode/**"
    ],
    "configRoot": "/redacted"
}
[debug]: conncet to remote
```

## Specifications

  - Version: 0.8.5 on VS Code 1.17.2
  - Platform: OpenSUSE Leap 42.3

**Comment by liximomo** [comment]
Sorry. You must set  `passphrase` to the config file currently.
