### ISSUE TITLE
uploadOnSave not working in context mode?

### ISSUE THREAD

**Issue by guidoselva** [liximomo/vscode-sftp#510]
- OS: Win
 - VSCode Version: 1.32.3
 - Extension Version: 1.12.0

I am currently migrating from Notepad++ to VS Code, and your extension is the only possible replacement for the wonderful NppFTP plugin (which has always been the only true reason for me to stick with Notepad++).
I need to access different servers, so I tried the "profiles" config, but switching profile with a manual command is too annoying for me. So I tried the "context" config (whatever it means... not clear in the documentation) with this setting file:

[
  {
    "name": "server1",
    "context": "/users/myuser/.vscode/SFTP/FAF",
    "host": "10.10.10.10",
    "protocol": "sftp",
    "username": "myuser",
    "agent": "pageant",
    "autoUpload": true,
    "uploadOnSave": true,
    "remotePath": "/www"
  },
  {
    "name": "server2",
    "context": "/users/myuser/.vscode/SFTP/SLK",
    "host": "10.10.10.20",
    "protocol": "sftp",
    "username": "myuser",
    "agent": "pageant",
    "autoUpload": true,
    "uploadOnSave": true,
    "remotePath": "/www"
  }
]

I can perfectly browse the servers, download remote files, edit them, but the "uploadOnSave" option does not work at all. Nothing appears in the log when saving the file. Manual upload woks fine.
In the "simple" and "profiles" config the "uploadOnSave" option works fine.

Why is "uploadOnSave" not working in context mode? Am I missing something in my configuration?

Thanks, and congratulations for this *vital* extension.

**Comment by liximomo** [comment]
**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by guidoselva** [comment]
Here the logs (nothing at all is logged when I save the file):

[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at c:\users\Guido Selva\.vscode\SFTP\FAF {"remotePath":"/local/www","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"FAF","context":"c:/users/Guido Selva/.vscode/SFTP/FAF","host":"10.10.10.10","port":22,"username":"******","agent":"pageant","autoUpload":true}
[info] config at c:\users\Guido Selva\.vscode\SFTP\SLK {"remotePath":"/local/www","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"SLK","context":"c:/users/Guido Selva/.vscode/SFTP/SLK","host":"10.10.10.20","port":22,"username":"******","agent":"pageant","autoUpload":true}
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying  ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_7.4'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] (remote) KEX algorithms: curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group14-sha1
[debug] KEX algorithm: diffie-hellman-group14-sha1
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
[debug] Client->Server Cipher: aes128-ctr
[debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
[debug] Server->Client Cipher: aes128-ctr
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Client->Server HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
[debug] Client->Server HMAC algorithm: hmac-sha2-256
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Server->Client HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
[debug] Server->Client HMAC algorithm: hmac-sha2-256
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPENDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[trace] run command 'Edit In Local'
[trace] handle download file for c:\users\Guido Selva\.vscode\SFTP\FAF\testguido.txt
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READ
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READ
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] remote -> local c:\users\Guido Selva\.vscode\SFTP\FAF\testguido.txt
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)

**Comment by liximomo** [comment]
Please try [1.12.1-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) and submit the logs.

**Comment by guidoselva** [comment]
Here it is. I have a new line in the log "[info] save file...", but still no upload:

[debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[debug] register command "Config" from "./commandConfig.ts"
[debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[debug] register command "Set Profile" from "./commandSetProfile.ts"
[debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[debug] register command "Diff" from "./fileCommandDiff.ts"
[debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[debug] register command "Download" from "./fileCommandDownload.ts"
[debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[debug] register command "List" from "./fileCommandList.ts"
[debug] register command "List All" from "./fileCommandListAll.ts"
[debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[debug] register command "Upload" from "./fileCommandUpload.ts"
[debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[info] config at c:\users\Guido Selva\.vscode\SFTP\FAF {"remotePath":"/local/www","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"FAF","context":"c:/users/Guido Selva/.vscode/SFTP/FAF","host":"10.10.10.10","port":22,"username":"******","agent":"pageant","autoUpload":true}
[info] config at c:\users\Guido Selva\.vscode\SFTP\SLK {"remotePath":"/local/www","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"SLK","context":"c:/users/Guido Selva/.vscode/SFTP/SLK","host":"10.10.10.20","port":22,"username":"******","agent":"pageant","autoUpload":true}
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying 10.10.10.10 on port 22 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_7.4'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] (remote) KEX algorithms: curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group14-sha1
[debug] KEX algorithm: diffie-hellman-group14-sha1
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
[debug] Client->Server Cipher: aes128-ctr
[debug] (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
[debug] Server->Client Cipher: aes128-ctr
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Client->Server HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
[debug] Client->Server HMAC algorithm: hmac-sha2-256
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] (remote) Server->Client HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
[debug] Server->Client HMAC algorithm: hmac-sha2-256
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing USERAUTH_REQUEST (none)
[debug] Client: none auth failed
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
[debug] Outgoing: Writing USERAUTH_REQUEST (publickey)
[debug] Outgoing: Writing CHANNEL_OPEN (0, session)
[debug] Outgoing: Writing CHANNEL_REQUEST (0, subsystem: sftp)
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPENDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[trace] run command 'Edit In Local'
[trace] handle download file for c:\users\Guido Selva\.vscode\SFTP\FAF\testguido.txt
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing OPEN
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READ
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing READ
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing CLOSE
[debug] Outgoing: Writing CHANNEL_DATA (0)
[info] remote -> local c:\users\Guido Selva\.vscode\SFTP\FAF\testguido.txt
[info] save file c:\users\Guido Selva\.vscode\SFTP\FAF\testguido.txt

**Comment by liximomo** [comment]
Great. I think I know where is the problem.  Please try the new [1.12.1-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

**Comment by guidoselva** [comment]
Now I have this lines at the end of the log:

[info] remote -> local c:\users\Guido Selva\.vscode\SFTP\FAF\testguido.txt
[info] save file c:\users\Guido Selva\.vscode\SFTP\FAF\testguido.txt
[info] workspaceFolders [{"uri":{"$mid":1,"fsPath":"c:\\Users\\Guido Selva","external":"file:///c%3A/Users/Guido%20Selva","path":"/c:/Users/Guido Selva","scheme":"file"},"name":"Guido Selva","index":0}]

**Comment by aoyulong** [comment]
I also have the same issue and wait for a new update.

**Comment by liximomo** [comment]
OK. I think the newest [1.12.1-debug](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) should fix this. Try it. @guidoselva

**Comment by guidoselva** [comment]
Not yet. Here the new lines in the log file:

[info] [file-save] c:\Users\GAKS\testguido.txt
[trace] handle upload file for c:\Users\GAKS\testguido.txt
[debug] Outgoing: Writing MKDIR
[debug] Outgoing: Writing CHANNEL_DATA (0)
[debug] Outgoing: Writing LSTAT
[debug] Outgoing: Writing CHANNEL_DATA (0)
[error] Error: Failure
	at SFTPStream._transform (C:\Users\GAKS\.vscode\extensions\liximomo.sftp-1.12.1\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (_stream_transform.js:190:10)
	at SFTPStream._read (C:\Users\GAKS\.vscode\extensions\liximomo.sftp-1.12.1\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SFTPStream.Writable.write (_stream_writable.js:294:11)
	at Channel.ondata (_stream_readable.js:672:20)
	at Channel.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Channel.Readable.push (_stream_readable.js:219:10)
	at SSH2Stream.<anonymous> (C:\Users\GAKS\.vscode\extensions\liximomo.sftp-1.12.1\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:182:13)
	at parsePacket (C:\Users\GAKS\.vscode\extensions\liximomo.sftp-1.12.1\node_modules\ssh2-streams\lib\ssh.js:3291:10)
	at SSH2Stream._transform (C:\Users\GAKS\.vscode\extensions\liximomo.sftp-1.12.1\node_modules\ssh2-streams\lib\ssh.js:689:13)
	at SSH2Stream.Transform._read (_stream_transform.js:190:10)
	at SSH2Stream._read (C:\Users\GAKS\.vscode\extensions\liximomo.sftp-1.12.1\node_modules\ssh2-streams\lib\ssh.js:249:15)
	at SSH2Stream.Transform._write (_stream_transform.js:178:12)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at SSH2Stream.Writable.write (_stream_writable.js:294:11)
	at Socket.ondata (_stream_readable.js:672:20)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onread (net.js:636:20) download c:\Users\GAKS\testguido.txt
[debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)

**Comment by guidoselva** [comment]
Sorry, it is actually working now. The error comes from another PC, where I must have another problem...

Thanks for the fix

**Comment by he5310** [comment]
path should be relative 
"context": "./SFTP/FAF",

**Comment by bowenac** [comment]
I have this problem as well, no matter what I have done, it simply will not upload on save, no messages in debug output either, manually choosing to upload works fine. I would really like to figure out how to get upload on save working. I'm coming from Sublime Text and the most useful part of sublime for me is the SFTP plugin, it simply works.

I have tried the patch file above... I do not get any debug output when saving the file, only when opening remote files, or after right clicking on the file and choosing upload.

I have this in my config.
"downloadOnOpen": true,
 "uploadOnSave": true

Anything I'm missing?

**Comment by liximomo** [comment]
@bowenac Open a new issue.

**Comment by brando90** [comment]
> I have this problem as well, no matter what I have done, it simply will not upload on save, no messages in debug output either, manually choosing to upload works fine. I would really like to figure out how to get upload on save working. I'm coming from Sublime Text and the most useful part of sublime for me is the SFTP plugin, it simply works.
> 
> I have tried the patch file above... I do not get any debug output when saving the file, only when opening remote files, or after right clicking on the file and choosing upload.
> 
> I have this in my config.
> "downloadOnOpen": true,
> "uploadOnSave": true
> 
> Anything I'm missing?

where you able to fix this?
