### ISSUE TITLE
how to add more than one host?

### ISSUE THREAD

**Issue by ifridemberg** [liximomo/vscode-sftp#514]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [ ] No.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Does this project help you?**
- [ ] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by MikeTheVike** [comment]
I think this is the same question I have. I want to add a login for dev server and a login for live server. That way I can choose what server the file updates go to. I'm basically trying to mimic features of CODA so I can switch to VS Code. CODA lets me setup a project for dev and live, and when a file has been updated, I can upload that file automatically, or manually(which is safer sometimes). I can also see a list of files that have been updated and marked for publishing.

**Comment by liximomo** [comment]
@MikeTheVike https://github.com/liximomo/vscode-sftp#profiles

**Comment by MikeTheVike** [comment]
Thanks @liximomo , I tried yesterday and must have had something wrong because I was getting an error. I got it working today. If I turn uploadOnSave to false, is there any indicator on which files have been updated so I can manually upload when ready?
