### ISSUE TITLE
 Optional download on open

### ISSUE THREAD

**Issue by gpibarra** [liximomo/vscode-sftp#52]
Add boolean Property "downloadOnOpen" in config file

**Comment by lorro** [comment]
Any idea whether this will be implemented in the near future?
I would like to switch from Sublime Text to VSCode but can't seem to find a ftp extension that supports this behavior. 

Sublime SFTP (https://wbond.net/sublime_packages/sftp) does have it for example. So I'm not willing to make the switch already :/

**Comment by liximomo** [comment]
It has been implemented.
