### ISSUE TITLE
After upgrade to 1.12.2, extension not working any more

### ISSUE THREAD

**Issue by molefirenko** [liximomo/vscode-sftp#528]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
After update VSCode to version 1.33.1 disappeared icon of the extension, and SFTP:Config command leads to error sftp.config command not found.

**Desktop (please complete the following information):**
 - OS: [Win]
 - VSCode Version [e.g. 1.33.1]
 - Extension Version [e.g. 1.12.2]

**Extension Logs from Startup** - *required*
Logs are empty.

**Comment by liximomo** [comment]
**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by liximomo** [comment]
**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by molefirenko** [comment]
I've reinstalled VSCode and removed folder .code from my user folder and plugin began to work.
