### ISSUE TITLE
Ignore does not work on upload

### ISSUE THREAD

**Issue by TomS-** [liximomo/vscode-sftp#534]
**Describe the bug**
Ignore works on download, but not on upload. For example I would like to ignore node_modules to stop that being synced up to the server. The ignore works on download, but not upload.

**To Reproduce**
1. Go to config and add node_modules to ignore
2. Run command sync local to server
3. See error

**Expected behavior**
Should ignore the node_modules folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode Version 1.33.1
 - Extension Version 1.12.2

**Config**
`"ignore": [".vscode", ".git", ".DS_Store", "node_modules/*", "assets/*"]` Doesn't work
`"ignore": [".vscode", ".git", ".DS_Store", "node_modules", "assets"]` Doesn't work
`"ignore": [".vscode", ".git", ".DS_Store", "/node_modules", "/assets"]` Doesn't work

**Comment by soth78** [comment]
Hi!
I'm having this exact same issue, even if I put .DS_Store it always gets uploaded
* OS: Mac
* VSCode Version: 1.76.1
* Extension Version: v1.16.1

Config
`"ignore": [".vscode",".DS_Store",".git",".gitignore",".htaccess","data"]`

Every time I hit Sync Local -> Remote, .DS_Store file gets uploaded
