### ISSUE TITLE
Please add an option to trigger uploadOnSave by a disk operation

### ISSUE THREAD

**Issue by prmshepherd** [liximomo/vscode-sftp#55]
Please add an option to reinstate the behaviour where uploadOnSave is triggered by a disk operation.

My use case is that VS Code is my primary IDE, but there are occasions where I need something more powerful to edit files. Under the old system this worked very well, as this SFTP plugin is one of the best SFTP syncers I've come across.

**Comment by liximomo** [comment]
I will until I figure out how to solve this. #54

**Comment by liximomo** [comment]
You can do it by watcher. 

```
{
"uploadOnSave": false,
"watcher": {
    "files": "**/*",
    "autoUpload": true,
    "autoDelete": false
  }
}
```
