### ISSUE TITLE
Download only NEWER/UPDATED files from Remote -> Local Sync

### ISSUE THREAD

**Issue by eStasicki** [liximomo/vscode-sftp#560]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
Always if I work on another PC than I go back to another PC- every time I must update all my project (Sync Remote -> Local) - this process take a lot of time.

**Describe the solution you'd like**
Maybe author can be create function to detect ONLY modified files than download ONLY modified files from Remote -> Local or Local -> Remote ? 

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/wiki/Common-Config#syncoptionupdate
