### ISSUE TITLE
2 features : force the display of hidden files & keyboard shortcut to upload a open file

### ISSUE THREAD

**Issue by LaRaphale** [liximomo/vscode-sftp#562]
Hello,

Thanks for this extension. 2 features could be added :

1- An option to force the display of hidden files like Filezilla for example
2- A keyboard shortcut to upload a open file

**Comment by liximomo** [comment]
Preferences -> Keyboard Shortcuts

**Comment by LaRaphale** [comment]
Nice. Thanks u very much. It is ok for feature 2.

**Comment by liximomo** [comment]
Close in favor of #561
