### ISSUE TITLE
sftp can no longer handle symlinked .vscode directory

### ISSUE THREAD

**Issue by Shulin** [liximomo/vscode-sftp#57]
## Expected Behavior
I have my .vscode project folder symlinked to a directory on disk located elsewhere ( I use this to keep all my project settings in one convenient place). SFTP should recognize this and still be able to load the configuration files for the project.

## Actual Behavior
In previous versions of sftp this worked fine, but with a recent update this is no longer working: I have my .vscode project folder symlinked to a directory on disk located elsewhere. SFTP no longer reads the configuration from the sym linked directory, thus rendering the plugin useless.

You can choose 'SFTP: Config' from the command drop down, and in the directory explorer, the .vscode directory is not listed.

## Steps to Reproduce the Problem

 1. Create a symlink for .vscode to a directory outside of the main project directory with a valid sftp.json config in it.
 2. Notice that sftp no longer recognizes this
 3. Doing SFTP Config doesn't list the symlinked .vscode directory

## Specifications

  - Version: 0.8.8
  - Platform: macOS High Sierra 10.13.1 (17B48)

**Comment by liximomo** [comment]
Did you remember the version which worked?

**Comment by Shulin** [comment]
I don't sorry. Is there an easy way to downgrade? I can keep stepping back... I know it was at least working when you made the switch to sftp.json from .sftpConfig.json.

**Comment by liximomo** [comment]
Weird. It's work fine for me with the same OS. My test scene is below:
```
|-config
     |- sftp.config
|-workspce
     |- .vscode  (link to  ../config)
```
 You should provide more detail description of your problems and your expectations.

**Comment by Shulin** [comment]
Odd, I tried to repro the problem on a new project, and it worked fine. Not sure if it was my project or what, but I basically started fresh and my project is working again.

 ¯\_(⊙︿⊙)_/¯
