### ISSUE TITLE
How to upload file in a binary mode?

### ISSUE THREAD

**Issue by dzarezenko** [liximomo/vscode-sftp#572]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [ ] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
It always in a binary mode
