### ISSUE TITLE
Feature Request: Run custom command before upload

### ISSUE THREAD

**Issue by DoubleFinned** [liximomo/vscode-sftp#576]
Is it feasible to add a config option that runs a command before uploading to the server. I'm using SASS and this extension will upload to the server before SASS has completed compiling into css.

It'd be nice to be able to set the uploadOnSave option and also have a "beforeUpload" option that you can put commands into.

**Comment by liximomo** [comment]
You should use [watcher](https://github.com/liximomo/vscode-sftp/wiki/Common-Config#watcher) for this.
