### ISSUE TITLE
Unable to fully sync the local working directory. Deleted files are never synced.

### ISSUE THREAD

**Issue by heartofalion** [liximomo/vscode-sftp#579]
When I open a working directory on my local machine, then I'm able to edit a file and the changes are then automatically uploaded to the FTP-server when I change that file. 

**Issue 1:** When I create a file however, it's not automatically uploaded to the remote FTP-server on creation, only when I add text in the file and then save it. So creating the file is not enough. Having the file be empty and then saving it, is also not enough. You have to add text to the file and THEN save it before it's synced to the remote server.

**Issue 2:** When I delete a file locally, it's also not deleted on the remote FTP-server, nor am I able to sync a deleted file, so that the remote FTP-server is synced with the local working directory. So if I delete a file, then this will never get synced with the remote server, even when I do a full sync from local to remote.

Issue 2 is the most important to me, as I don't want to have my remote server run out of sync with my local working directory, however I'd like to get both issues fixed of course.

These are my config settings:
```
{
    "name": "Name",
    "host": "xxx.xxx.xxx.xxx",
    "protocol": "sftp",
    "port": 22,
    "username": "user",    
    "remotePath": "/var/www/html/repo",
    "uploadOnSave": true   
}
```

**Comment by zmj1368** [comment]
yes, I also encountered this problem. Did you solve it?
