### ISSUE TITLE
acl permissions are ignored

### ISSUE THREAD

**Issue by GottZ** [liximomo/vscode-sftp#581]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
write permissions set by setfacl are ignored by this extension.
files will still open in read only mode even though plain sftp and ssh allow modification and creation of files by the said user.

**To Reproduce**
1. create a directory on a remote server
2. add a simple dummy file inside
2. remove `w` permission to your sftp user
3. add access permission to said folder with the following two commands:
    ```
    setfacl -Rm "u:sftpuser:rwX" foldername
    setfacl -Rdm "u:sftpuser:rwX" foldername
    ```
5. try to modify the dummy file through the sftp extension in vscode or try to create a new file in that directory

**Expected behavior**
write access

**Screenshots**
not necessary

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode win32 x64 1.35.0
 - Extension Version 1.12.7

**Extension Logs from Startup** - *required*
https://share.home.gottz.de/2019/06/2019-06-12_11-07-34.txt

**Comment by liximomo** [comment]
You should select `Edit in Local` in document context menu if you want to edit it. See also `https://github.com/liximomo/vscode-sftp/wiki/Setting#downloadwhenopeninremoteexplorer`
