### ISSUE TITLE
多配置文件需求

### ISSUE THREAD

**Issue by prianyu** [liximomo/vscode-sftp#586]
vscode里的一个工作区里有多个项目，不同项目对应到不同的服务器，同时本地和远程的根目录路径不一致的这种怎么处理

**Comment by liximomo** [comment]
每个项目单独配置

**Comment by prianyu** [comment]
使用sftp:config后默认生成配置文件是在工程的根目录，我把它挪到对应的项目里去，然后配置，好像是同步了，但upload之后远程和本地的文件是不一致的。使用mutiple context能否处理呢

**Comment by prianyu** [comment]
目前单独配置有这个问题：
本地的目录是m/***,配置文件保存在了m这个目录下，远程的目录是/opt/page/ROOT/。上传后本地整个m的目录当做了/opt/page/ROOT/的子目录了

**Comment by liximomo** [comment]
> 本地的目录是m/***,配置文件保存在了m这个目录下，远程的目录是/opt/page/ROOT/。上传后本地整个m的目录当做了/opt/page/ROOT/的子目录了

不懂你说的什么， 你想要什么，目前的结果是什么？

**Comment by prianyu** [comment]
目前我的工作区里有三个目录，分别是a,b,c，也就是三个项目。我在a,b,c里分别新建了配置文件。每个配置文件对应的服务器都是不一样的，其中a的配置如下：
{
    "name": "m",
    "host": "192.168.249.157",
    "username": "xxxx",
    "password": "xxxxx",
    "port": 2222,
    "remotePath": "/opt/tomcat/a/webapps/ROOT/   "
},
a在本地的绝对路劲如下：
e://project/a

然后修改a里面的文件，上传后整个a目录变成了/opt/tomcat/a/webapps/ROOT/的子目录，我原本的 目的是a目录对应远程 的/opt/tomcat/a/webapps/ROOT/目录

**Comment by liximomo** [comment]
a 的配置文件的绝对路径可以提供下吗

**Comment by prianyu** [comment]
E:\Projects\a\.vscode\sftp.json
远程目录：/opt/tomcat/a/webapps/ROOT/ ，
本意是a目录对应/opt/tomcat/a/webapps/ROOT/ 目录

**Comment by prianyu** [comment]
E:\Projects\a\.vscode\sftp.json

**Comment by prianyu** [comment]
E:\Projects\a\\.vscode\sftp.json

**Comment by liximomo** [comment]
如果你提供的信息没错的话，你目前的配置确实是 `E:\Projects\a` 对应 `/opt/tomcat/a/webapps/ROOT/`目录的。 `E:\Projects\a\test.txt` 会被上传至 `/opt/tomcat/a/webapps/ROOT/test.text`。提供下日志我看下吧，打开 vscode 的设置，配置 `sftp.debug`  为 `ture`, 重启 vscdeo。然后进行上传，通过 `视图->输出->sftp` 获取 log.

**Comment by prianyu** [comment]
重启后找不到配置了，另外我发现重启了右键菜单等都没了，我再看看是不是我编辑器的问题吧。
`
[06-18 11:32:46] [error] Error: Config Not Found. (file:///e:/Projects/a/index.jsp) 
	at Object.u [as handleCtxFromUri] (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.7\dist\extension.js:1:41886)
	at module.exports.t.createFileCommand.<anonymous> (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.7\dist\extension.js:1:4045)
	at Generator.next (<anonymous>)
	at module.exports.r (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.7\dist\extension.js:1:3325)
	at new Promise (<anonymous>)
	at module.exports.r (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.7\dist\extension.js:1:3102)
	at module.exports.t.createFileCommand.doCommandRun.a.map.t (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.7\dist\extension.js:1:3987)
	at Array.map (<anonymous>)
	at module.exports.t.createFileCommand.<anonymous> (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.7\dist\extension.js:1:3980)
	at Generator.next (<anonymous>)
	at s (c:\Users\Administrator\.vscode\extensions\liximomo.sftp-1.12.7\dist\extension.js:1:3158)
`

**Comment by prianyu** [comment]
`[06-18 11:45:33] [info] config at e:\Projects {"remotePath":"/opt/tomcat/a/webapps/ROOT/","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"m","host":"192.168.249.157","port":2222,"username":"******","password":"******"}
[06-18 11:45:38] [warn] ENOENT: no such file or directory, open 'C:\Users\Administrator\.ssh\config' load C:\Users\Administrator\.ssh\config failed
[06-18 11:45:38] [info] local ➞ remote e:\Projects\a\index.jsp`

**Comment by prianyu** [comment]
测试了下，将a单独作为一个工作区就可以了，就是一个工作区不能同时有个项目

**Comment by liximomo** [comment]
一个工作区可以有多个项目的。。

**Comment by prianyu** [comment]
是支持的，已经结合mutiple context解决了问题，非常感谢！

**Comment by suzixin** [comment]
@prianyu 请问可以提供一下参考配置吗？我也遇到了同样的问题。

**Comment by prianyu** [comment]
> @prianyu 请问可以提供一下参考配置吗？我也遇到了同样的问题。
假如工程目录结构如下：
```shell
Projects
  |----- .vscode
      |-------sftp.json
  |----- A
  |-----B
  |------C
```
以上有A、B、C三个项目，每个目录对应不同的ftp服务器，共用了工程目录下的`sftp.json`
那么最终配置如下：
```json
[
    {
        "name": "a",
        "host": "192.168.16.150",
        "protocol": "sftp",
        "port": 2222,
        "username": "xxx",
        "password": "xxxx",
        "context": "A",
        "remotePath": "xxx/xxx/xxx",
        "uploadOnSave": true,
        "syncMode": "update",
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store",
            "**/xxxx"
        ]
    },
    {
        "name": "b",
        "host": "192.168.16.151",
        "protocol": "sftp",
        "port": 2222,
        "username": "xxx",
        "password": "xxxt",
        "context": "B",
        "remotePath": "/xxx/xxx/xxxx/",
        "uploadOnSave": true,
        "syncMode": "update",
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    },
    {
        "name": "c",
        "host": "192.168.16.152",
        "protocol": "sftp",
        "port": 2222,
        "username": "xxx",
        "password": "xxx",
        "context": "C",
        "remotePath": "/xxx/xxx/xxx",
        "uploadOnSave": true,
        "syncMode": "update",
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
    },
]
```

也就是说使用`context`这个配置项来实现，其值与项目的目录名称一致

**Comment by suzixin** [comment]
按照以上配置弄好了，非常感谢~
