### ISSUE TITLE
Matches multiple schemas when only one must validate.

### ISSUE THREAD

**Issue by parksnow** [liximomo/vscode-sftp#593]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**

I want to switch between different profile, and VS Code gives me:

> Matches multiple schemas when only one must validate.

**To Reproduce**

Here is my `sftp.json`

```json
{
    "name": "Server",
    "profiles": {
        "server1": {
            "host": "1.2.3.4",
            "protocol": "sftp",
            "port": 22,
            "username": "root",
            "remotePath": "/path/to/file",
            "uploadOnSave": false
        },
        "server2": {
            "host": "11.12.13.14",
            "protocol": "sftp",
            "port": 22,
            "username": "root",
            "remotePath": "/path/to/file",
            "uploadOnSave": false
        }
    },
    "defaultProfile": "server1"
}
```

**Expected behavior**

No VS Code warning

**Desktop:**
 - OS: Mac
 - VSCode Version : 1.35.1
 - Extension Version:  1.12.7

**Comment by ManuDoni** [comment]
I have the same problem with sftp 1.12.8 and vscode 1.38.1 (Windows).
How can I setup profiles to connect to two different servers?

**Comment by liximomo** [comment]
Just ignore it.

**Comment by Svish** [comment]
I fixed it by specifying the schema, in my case the sftp one:
```json
{
  "$schema": "https://raw.githubusercontent.com/liximomo/vscode-sftp/master/schema/sftp.schema.json",
  
}
