### ISSUE TITLE
How to Upload only build subfolder in specified remote path?

### ISSUE THREAD

**Issue by mehdico** [liximomo/vscode-sftp#595]
How to Upload only build subfolder in specified remote path?
i want to upload only [build] folder of my react project and i don't want to create [build] subfolder in remote host. if i put config file of sftp in build folder, its not detect by sftp plugin and i have to open build folder directly in vscode to get work.
plaese help!

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by joca-hms** [comment]
@mehdico If I am understanding your issue I think I was fumbling with the same problem today. The "context" option in the setting that allows you to specify the "local root" of your directory you want to sync. For instance, if you have a file: "build/test.txt"

Using a context of "build" will mean that the file test.txt would be copied to the path specified by "remotePath". But if your context is empty/not-specified it would copy "build/test.txt" to "remotePath" meaning you would have a folder called build in the remote.

Hope this helps/is what you were looking for.

**Comment by mehdico** [comment]
@joca-hms Thank you for your answer. i tested ["context":"/build"] but when add this option, then try to upload a file, plugin show's error :

![Screen Shot 1398-04-14 at 19 48 12](https://user-images.githubusercontent.com/1978735/60731870-e092c200-9f5d-11e9-8fd6-d1733a1f5d51.png)
it seems plugin search for another config file in [build] directory, and i don't know why!

my project structure is like this :

![Screen Shot 1398-04-14 at 19 49 13](https://user-images.githubusercontent.com/1978735/60731971-19cb3200-9f5e-11e9-9d16-99446e2e2e1f.png)

**Comment by joca-hms** [comment]
@mehdico 
Try omitting the "/" in your "context":"/build".

I could be mistaken but I think it should be this instead:
"context":"build"

**Comment by mehdico** [comment]
@joca-hms Thank you! Its work! 👍 

but they put / before build is the plugin documentation !

![Screen Shot 1398-04-14 at 19 57 31](https://user-images.githubusercontent.com/1978735/60732577-a88c7e80-9f5f-11e9-8278-68e3f1acd7a6.png)

i think they need to edit this!

**Comment by joca-hms** [comment]
@mehdico yes, the documentation could be clearer, but it is just a path string. Placing a '/' at the beginning is saying go the local system's root directory. On Linux this is literally the "/" root path, on windows this would be presumably equivalent to "C:\". So if your intention was to have files reside outside your normal vscode project directory that you wanted to sync, then this would be how you could do it. Or you could presumably use combinations of "../" to jump to the parent directory of the vscode project (I haven't tried this but this is my assumption of how this field works).

**Comment by mehdico** [comment]
@joca-hms I've tested absolute path of build directory like this :

/Users/mehdi/Programming/web/recipe/build

but its not work. so i think it is relative path.

**Comment by slynagh** [comment]
@mehdico this is exactly what I am doing (upload build folder to remote root) and I have `"context": "build/"` in my settings. It is working that way. However I also have a workspace file saved i my project folder, I wonder is the path relative to workspace?

**Comment by yacinegithub** [comment]
I added folder name respecting upper/lower case to context folowing by a slash "/" and it work perfectly "context":"FolDer/"
AlhamduLilah

**Comment by Infomaquina** [comment]
The context option does not allow it to be inside the profile. This is counterproductive

**Comment by DaveFlashNL** [comment]
hmm, I followed the tips in this thread, but now sftp is only uploading stuff in the root of my build folder, but I have some js and css in ```static/css```  ```static/js```, this is my code: 

```json
{
    "name": "private",
    "host": "ftp01.snip",
    "protocol": "ftp",
    "port": 21,
    "username": "snip",
    "password": "snip",
    "context": "build/",
    "remotePath": "/",
    "uploadOnSave": false,
    "autoUpload": false,
    "syncOption": {
        "update": true,
        "delete": true
    },
    "syncMode": "full",
    "watcher": {
        "files": "*.{js,css,html,map}",
        "autoUpload": true,
        "autoDelete": true
    },
    "ignore": [
        ".idea",
        ".DS_Store",
        ".vscode",
        "node_modules",
        "package-lock.json",
        "package.json",
        ".editorconfig",
        "__MACOSX",
        "README.md",
        "db backup",
        "public",
        "srC"
    ]
}
```

so what am I doing wrong? I only want to update the javascript, html, css files in all folders after 'build'.

**Comment by DaveFlashNL** [comment]
if I remove the filemap ``.{js,css,html,map}`` it will upload everything, including in subfolders, but this is not what I want, as it then always re-uploads existing resources which do get build anew, but aren't changed from one build or the other, like images.

**Comment by Wacki1986** [comment]
`"files": "**/*.{js,css,html,map}",` 
@DaveFlashNL  I think this is the correct notation. 
Hope this helps someone. ☺️
