### ISSUE TITLE
Multiple Editor Windows For Remote Files

### ISSUE THREAD

**Issue by RaisedByWolves1** [liximomo/vscode-sftp#598]
I frequently need to view multiple files in a project, most of which I do not need to edit locally. But I can only have one window open on the remote folder. This is EXTREEEEEMELY aggravating. Why should I have to scroll up and down huge lists of files in big project to display various files I need to inspect in order to follow the logic of the flow of execution in source code?!
This is a huge drag on my efforts.

**Comment by postgres99** [comment]
Yes, its very important! Please!

**Comment by liximomo** [comment]
You can open multiple files by pin the open document.

**Comment by RaisedByWolves1** [comment]
Sorry - Can you point where exactly this "pin" command is accessed in VS Code?
Are you thinking eclipse?

**Comment by liximomo** [comment]
https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
