### ISSUE TITLE
why vscode cannot add new tab when I open new file 

### ISSUE THREAD

**Issue by zheng992328** [liximomo/vscode-sftp#601]
When I use vscode edit file in local PC, the file can be added in new tabs. However, when I use sftp to connect to server, and edit the files in remote server, it cannot add new tabs when I open new files. My settings are below.
![image](https://user-images.githubusercontent.com/16679647/61602233-bd773c00-ac06-11e9-9785-ac5db705b22a.png)

**Comment by liximomo** [comment]
Click the tab title to make it persistent.
