### ISSUE TITLE
How to create a config ?

### ISSUE THREAD

**Issue by Entretoize** [liximomo/vscode-sftp#603]
Sorry but I don't understand how to create a config file, what is the name it must have ? Where must it be ?
It's not explained anywhere or it's not clear.
I tried to create a .sftpConfig.json file with that :

```
{
    "username": "xxxxx",
    "password": "xxxxx",
    "remotePath": "c:/htdocs",
    "watcher": {
      "files": "dist/*.{js,css,php,html}",
      "autoUpload": false,
      "autoDelete": false
    },
    "profiles": {
      "dev": {
        "host": "domain.tld",
        "remotePath": "c:/htdocs",
        "uploadOnSave": true
      }
    },
    "defaultProfile": "dev"
  } 
```
But nothing happens, no message, no help.
Thanks.

**Comment by Entretoize** [comment]
After some tries, I receive a "config not found message" but still no help to guide user.

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp#usage
