### ISSUE TITLE
the download leaves my local document blank.

### ISSUE THREAD

**Issue by rmlSardinha** [liximomo/vscode-sftp#61]
## Expected Behavior
when I click on download, puchar-file the server and replace my file.

## Actual Behavior
when I click download it leaves my local document blank.

## Steps to Reproduce the Problem

1. open the document
2.click on the open document
3.click on sftp: download

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version: 0.8.10
  - Platform: win10

**Comment by liximomo** [comment]
Maybe the remote document is blank？So you just
 download a blank file. And please provide extension logs.

**Comment by rmlSardinha** [comment]
No, my html file on the server is with content. my local file is also with content.
But when I ask to download only my local file goes blank.

the upload works very well, even by clicking or saving. The problem is only in the download

and how can I get the logs?

**Comment by liximomo** [comment]
Preference -> setting -> sftp.printDebugLog to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)

**Comment by rmlSardinha** [comment]
[info]: config at c:/Users/Ross/Google Drive/7startups/Sites/urbi/siteUrbi/www {
    "host": "**********",
    "port": 21,
    "username": "**********",
    "password": "**********",
    "protocol": "ftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "c:/Users/Ross/Google Drive/7startups/Sites/urbi/siteUrbi/www/**/.vscode/**",
        "c:/Users/Ross/Google Drive/7startups/Sites/urbi/siteUrbi/www/**/.git/**",
        "c:/Users/Ross/Google Drive/7startups/Sites/urbi/siteUrbi/www/**/.DS_Store",
        "/**/.vscode/**",
        "/**/.git/**",
        "/**/.DS_Store"
    ],
    "configRoot": "c:/Users/Ross/Google Drive/7startups/Sites/urbi/siteUrbi/www"
}
[debug]: task: download
[debug]: conncet to remote


[debug]: download /public/wp-content/themes/travel-time/footer.php at Sat Nov 25 2017 11:56:29 GMT-0200 (Horário brasileiro de verão)

**Comment by liximomo** [comment]
Does it only happen with this file?

**Comment by rmlSardinha** [comment]
No, any file. if it is saved on the computer, and I do the download, the file will go blank.

I made other ftp accounts, and other domains. all the same.

**Comment by liximomo** [comment]
I've made a fix. Try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) and give me some feedbacks.

**Comment by rmlSardinha** [comment]
[debug]: task: download
[debug]: conncet to remote
[error]: context: undefined reason: TypeError: Cannot read property 'type' of undefined
	at srcFs.lstat.then.stat (C:\Users\Ross\.vscode\extensions\liximomo.sftp-0.8.11\out\src\modules\conveyer.js:387:17)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by liximomo** [comment]
It's very close. Try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again.

**Comment by rmlSardinha** [comment]
[debug]: task: download
[debug]: conncet to remote
[error]: context: undefined reason: TypeError: Cannot read property 'type' of undefined
	at srcFs.lstat.then.stat (C:\Users\Ross\.vscode\extensions\liximomo.sftp-0.8.11\out\src\modules\conveyer.js:387:17)
	at <anonymous>

**Comment by liximomo** [comment]
I mean the new [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again. I have made some change.

**Comment by rmlSardinha** [comment]
[debug]: task: download
[debug]: conncet to remote
[error]: context: undefined reason: TypeError: Cannot read property 'type' of undefined
at srcFs.lstat.then.stat (C:\Users\Ross\.vscode\extensions\liximomo.sftp-0.8.11\out\src\modules\conveyer.js:387:17)
at <anonymous>

I had already downloaded your new debug yesterday. I downloaded it again, the same message, the file is not going blank, but it gives an error.

**Comment by rmlSardinha** [comment]
?

**Comment by liximomo** [comment]
Do you use ftp? If so, It's weird about your debug logs. I've added more logs. Try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge).

**Comment by rmlSardinha** [comment]
I sent it to your email because I have a lot of information.

Yes I use ftp normally, today I have to download the file over ftp, override my local file, then edit in vscode and upload by vscode-sftp.

**Comment by liximomo** [comment]
The logs say that everything works well? Can you confirm this?

**Comment by Yuan-Yu** [comment]
I have the same issue. When I tried to sync the folder, I got the 605 failed.
However, files with empty content were still created. 
I installed the debug-package for getting the debug log, but it showed nothing.
