### ISSUE TITLE
每次重新打开vscode如何直接就可以同步文件

### ISSUE THREAD

**Issue by HelplessMan** [liximomo/vscode-sftp#612]
按照正常操作。例如上班后重新打开编辑器。发现右侧插件：sftp 不存在了。然后在指定生成过配置文件中的项目目录同步也没有 同步命令？ 请问遇到这种情况一般要怎么做才可以同步？
另外使用command + shift+p ， sftp:config的话可以打开sftp的那个扩展，但是也会生成一个配置文件。无法实现我想同步的指定项目

**Comment by HelplessMan** [comment]
另外看到redmine 里面有类似命令： View: Show SFTP  
应该是启动sftp插件的命令吧。
运行了也没有反应的哈。

**Comment by liximomo** [comment]
你要打开相同的文件夹才行。比如你打开了 /a 文件夹，生成了配置，这个配置只有在再次打开 /a 文件夹才有效。
