### ISSUE TITLE
SFTP免密登录,上传下载都没问题,但是连接超时

### ISSUE THREAD

**Issue by coolyaolei** [liximomo/vscode-sftp#615]
{
    "name": "dcn-data",
    "host": "x.x.x.x",
    "protocol": "sftp",
    "port": 22,
    "username": "root",
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/origindata/oapc/workspaces",
    "privateKeyPath":"/home/coolyaolei/.ssh/id_rsa",
    "uploadOnSave": true

**Comment by liximomo** [comment]
超时时间社大点

**Comment by coolyaolei** [comment]
解决了,真没想到是这个问题
