### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by zareshahi** [liximomo/vscode-sftp#616]
Issue Type: <b>Bug</b>

SFTP panel icon size has been smaller after last update ( that change global ui design)

Extension version: 1.12.7
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 4.19.0-5-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-6310 APU with AMD Radeon R4 Graphics (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|6.77GB (3.29GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jiankafei** [comment]
Me too

**Comment by btstw** [comment]
lazy fix, replace this icon on my windows computer works fine.

windows path : %userprofile%\.vscode\extensions\liximomo.sftp-1.12.7\remote-explorer.svg

[remote-explore-icor.zip](https://github.com/liximomo/vscode-sftp/files/3491248/remote-explore-icor.zip)
resources\remote-explorer.svg

**Comment by liximomo** [comment]
Fixed in v1.12.8
