### ISSUE TITLE
context in profile is ignored

### ISSUE THREAD

**Issue by TonyGravagno** [liximomo/vscode-sftp#632]
**Do you read the FAQ?**
- [X] Yes.

**Describe the bug**
Two profiles specified in sftp.json, both have a context specified. Any download/sync operation, the context is ignored. Please check the functionality and then document a few examples of the correct syntax.

**To Reproduce**
1. In your workspace, create an empty folder.
1. In sftp.json set the context in the profile.
1. Connect with any method to download one or more files.
1. All files download into the root of the workspace.
1. The context is defined as a relative path from the workspace root. Try any pattern for relative or absolute, using any valid pattern of slashes or back-slashes. The result is always the same, files land in root. 
1. ctrl-shift-p and go to SFTP: Sync Remote to Local. With two profiles it offers a choice of two destinations. Both of them are always the absolute path to the workspace, completely ignoring anything in the context value.

Example: Where the workspace root is C:\foo, I expect downloads to begin in foo/bar. None of these values for "context": "x" work : bar, .\\bar, .\\\\bar, foo\\bar, C:\\foo\\bar, \\\\foo\\\\bar ... and substitute all \\ or \\\\ with / for /bar, foo/bar, etc.

**Expected behavior**
With "context": "bar", where the workspace root is foo, I expect all downloads to begin in foo/bar. So a remote file with remotePath /tmp would be /tmp/baz.txt and the local files should be C:\\foo\\bar\\baz.txt
If this is not correct, please enhance the wiki notes with valid examples.

**Desktop (please complete the following information):**
 - OS: Windows 8
 - VSCode Version 1.37.1
 - Extension Version 1.12.3

**Extension Logs from Startup** - *required*
Summary: There are no errors in the log. The info line for a file transfer consistently shows remote>local to my workspace root.

**Comment by TonyGravagno** [comment]
Nothing else? No comment? No acknowledgement? Just 'wontfix'? Wow. :unamused:

**Comment by liximomo** [comment]
It's already in the readme. You don't need to switch context, just create [multiple-context](https://github.com/liximomo/vscode-sftp#multiple-context)
![image](https://user-images.githubusercontent.com/9816225/65106443-37f6e900-da09-11e9-85ae-2857e047c026.png)

**Comment by AStupidBear** [comment]
@liximomo Currently multiple-context dosen't work. Am I right?
