### ISSUE TITLE
no option to set a local path ?

### ISSUE THREAD

**Issue by Kevin-Kuehle** [liximomo/vscode-sftp#633]
Hi i come from PhpStorm and would use vscode for the future but i dont find a option to set a local-path to the remote-path. PhpStorm has this option under Remote-Host -> Mapping

can someone help me ?

**Comment by liximomo** [comment]
https://github.com/liximomo/vscode-sftp/wiki/Common-Config#context

**Comment by Kevin-Kuehle** [comment]
I can not believe that I did not see that. Thank you!
