### ISSUE TITLE
Download watcher or "download bundle" command?

### ISSUE THREAD

**Issue by ursbraem** [liximomo/vscode-sftp#637]
**Is this a similar or duplicate feature request?**
- [ x] I don't know. I will go check it.
- [ x] No.

**Is your feature request related to a problem? Please describe.**
When working with SFTP on a server (eg hotfixes) there are often files that are modified on the server, like composer.lock or some config files. They must be downloaded to my PC to be added to git. If forgotten, bad things happen.

**Describe the solution you'd like**
I would like to be able to define a set of files to download, either on change on the server (not sure how robust), or just by some command. So I'd just enter some command and then those files would be downloaded so I don't forget to commit them to git.

**Describe alternatives you've considered**
rsync workflows, but too complex

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!
- [x] Yes. [I want to support you.](https://github.com/liximomo/vscode-sftp#donation)

**Comment by liximomo** [comment]
Define your own keybindings using [commands](https://github.com/liximomo/vscode-sftp/wiki/Commands)

```json
{
    "key": "cmd+d",
    "command": "sftp.upload",
    "args": [
      "path/to/file/a",
      "path/to/file/b",
    ]
  }
```

**Comment by ursbraem** [comment]
Oh! Can you give me a full example? I don't know where to place the code

This is my config:

```
{
    "name": "master",
    "protocol": "sftp",
    "host": "myhost.dev",
    "port": 123,
    "privateKeyPath": "/Users/myuser/.ssh/id_rsa",
    "uploadOnSave": true,
    "username": "mywebuser",
    "remotePath": "/my/path/www/",
    "agent": "$SSH_AUTH_SOCK",
    "passphrase": true,
    "ignore": [
        "**/.idea/**",
        "**/.vscode/**",
        "**/.git/**"
    ]
}
```

**Comment by liximomo** [comment]
`Code -> Preference -> Keyboard Shortcuts` then edit the shortcuts json file.

**Comment by ursbraem** [comment]
aaaaaah... but this is global? I need the setting per-project.

PS: https://stackoverflow.com/questions/52740020/missing-link-to-keybindings-json-in-the-keyboard-shortcuts-editor-is
