### ISSUE TITLE
Support ssh-dss server key type

### ISSUE THREAD

**Issue by hthuong09** [liximomo/vscode-sftp#65]
## Expected Behavior
Able to connection and download file

## Actual Behavior
Error message display: [error] Handshake failed: no matching host key

## Steps to Reproduce the Problem

  1. Generate ssh-dss public key with `ssh-keygen -t rsa -b 4096`
  2. Put in on a server and try to config Visual Studio Code sftp and start download files

### Extension Logs
  Well, you could easily test it out. I don't have log here since I just temporary fixed it with some dirty code.
 

## Specifications

  - Version: 0.8.11
  - Platform: Visual studio Code 1.18.1 on Windows 7 Enterprise 64bit

**Comment by liximomo** [comment]
From https://www.openssh.com/legacy.html
> OpenSSH 7.0 and greater similarly disable the ssh-dss (DSA) public key algorithm. It too is weak and we recommend against its use.

I need consider if this worth an option. 

>The best resolution for these failures is to upgrade the software at the other end. OpenSSH only disables algorithms that we actively recommend against using because they are known to be weak. In some cases, this might not be immediately possible so you may need to temporarily re-enable the weak algorithms to retain access.
 
Tell me what you think.

**Comment by hthuong09** [comment]
Okay, thank you. I think this is my company fault for using old software. Though, I think there should be a workaround instruction for this issue, since I think there are still many people might run into this.

**Comment by liximomo** [comment]
With v1.0.4, you can config this way
```
"algorithms": {
  "serverHostKey": ["ssh-rsa", "ecdsa-sha2-nistp256", "ecdsa-sha2-nistp384",  "ecdsa-sha2-nistp521", "ssh-dss"]
}
```

**Comment by hthuong09** [comment]
Great. Thank you!
