### ISSUE TITLE
Upload to temporary file once done replace

### ISSUE THREAD

**Issue by marcusdiy** [liximomo/vscode-sftp#651]
**Is this a similar or duplicate feature request?**
No.

**Is your feature request related to a problem? Please describe.**
Sometimes the upload fails, and we dont actually know when it failed...

**Describe the solution you'd like**
The idea is to use the same upload method used by NetBeans which uploads the file to an temporary file, once uploaded, only then it replaces the file. 

**Describe alternatives you've considered**
--

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by liximomo** [comment]
Duplicated of #106
