### ISSUE TITLE
为什么 SFTP 插件总莫名其妙的从 vscode 里消失？

### ISSUE THREAD

**Issue by andyzu** [liximomo/vscode-sftp#663]
![image](https://user-images.githubusercontent.com/19669881/66659050-4c7b7980-ec75-11e9-95d3-d5dca85ed660.png)
安装好，配置好，使用完全没有问题，但是经常关闭 vscode 后 sftp 插件就消失了，有次亲眼看到它从有到消失。在已安装的插件列表里还能看到 sftp 插件。但是就是不见。

**Comment by liximomo** [comment]
sftp 只会在打开一个目录时，此目录顶层存在 .vscode/sftp.json 文件，才会被激活
