### ISSUE TITLE
Latest VS Code update uploadOnsave stopped working

### ISSUE THREAD

**Issue by rce02** [liximomo/vscode-sftp#669]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I have uploadOnsave set to true. Previously this was working flawlessly. But today, after VS Code updated, it does not seem to work anymore. I have not made any changes to my .config.

**To Reproduce**
1. try to save a file that you would expect  to upload to remote.

**Expected behavior**
Expected to upload to remote on save.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version 1.39.2
 - Extension Version 1.12.9

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by matmurdock** [comment]
I am having the same issue.  Things were working fine until just recently.

    {
        "name": "theSite",
        "host": "theServer",
        "protocol": "sftp",
        "port": 2260,
        "username": "theUser",
        "password": "thePassword",
        "remotePath": "/var/www/html/",
        "uploadOnSave": true,
        "context": "/project/theProject"
    }
