### ISSUE TITLE
Add configuration of local path

### ISSUE THREAD

**Issue by jzz4012650** [liximomo/vscode-sftp#67]
Would you please add a configuration of local path ? since I can only use the root path of work space as the local path, which can't meet my needs. If i open the sub folder as my work space, then i can't use the git features.

It is a very useful ftp-sync extension in vs code (compare to any other ftp extensions), nice work!

## Expected Behavior
i can config the local path, not only the root path of my work space.  (sub folder of my project).

## Actual Behavior
i can't config local path that sync to remote, it just uses the root path of my work space.

## Steps to Reproduce the Problem
  1. config SFTP
  2. fill in address, port, remote path and so on...

## Specifications

  - Version: 0.8.11
  - Platform: Mac OS 10.13.1 (VS code 1.19)

**Comment by liximomo** [comment]
Working on it! Now you can use [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) as a workaround.

**Comment by liximomo** [comment]
The sftp 0.9.0 now supports it.
