### ISSUE TITLE
Local and remote using different paths

### ISSUE THREAD

**Issue by eoghainanderson** [liximomo/vscode-sftp#677]
Hi,

I have a different path for local_root/../css directory and remote_root/../css directory and was wondering how I configure this in sftp.json.

Thanks
Eog

**Comment by IlanVivanco** [comment]
Have you tried this??
```
{
	"name": "SFTP Connection",
	"uploadOnSave": false,
	"context": "/local_root/../css/",
	"remotePath": "/remote_root/../css/"
}
```

**Comment by eoghainanderson** [comment]
> Have you tried this??

Yes, I tried it but I got an error.  "Config not found:"

Just tried again and it worked! Obviously a typo in my config somewhere before.

Many thanks, Ilán!
