### ISSUE TITLE
How to sync only files matching a particular pattern?

### ISSUE THREAD

**Issue by KiranMohan** [liximomo/vscode-sftp#68]
How to sync only files matching particular pattern?
(i.e, ignore all files except some that match foo*.log pattern)

**Comment by KiranMohan** [comment]
OK.
I noticed i can use the following pattern in ignore files section of the config.

`"**/!(pattern1|pattern2|pattern3)"`

where pattern1, pattern2 and pattern3 are the files i want to sync.

**Comment by liximomo** [comment]
Good job!
