### ISSUE TITLE
How to move config file?

### ISSUE THREAD

**Issue by deadcell1453** [liximomo/vscode-sftp#7]
Hi, is it possible to move the .sftpConfig.json file from the root folder of my project into the .vscode folder, which is also in the root of my project?

I tried editing **exports.configFileName = '.sftpConfig.json';** on line 22 to **exports.configFileName = '.vscode/.sftpConfig.json';** in the config.js but that doesn't work.  Help would really be appreciated.

Thanks!!!

**Comment by liximomo** [comment]
The sftpConfig.json works like a .gitignore file. It only works for the directory that it in. This let give you the ability to put have a sftpConfig.json for every directory under the workspace. So, there is no way to put a sftpConfig.json in a directory and works for another folder under the strategy of current extension.

**Comment by regs01** [comment]
But why? Is this because of "configRoot" option? VSC does not provide an ability to get project location? There are many extensions that are placing their configs into .vscode.

**Comment by liximomo** [comment]
edit: was looking at the code. quite complicated. why not just to read config directly from
${vscode.workspace.rootPath}/.vscode/${exports.configFileName}
Reply: Because of my requirements. I need multiple distinct configs for multiple folders under a single workspace. So I just refer to the mechanism of .gitignore.

**Comment by liximomo** [comment]
I don't think the location of the config matters so much. Is it so important to put the config file into the .vscode folder? If so I would consider adding an option to achieve it.

**Comment by liximomo** [comment]
Now config file does place in the .vscode folder. 🎉🎉🎉

**Comment by regs01** [comment]
It's just not invisible and not really pleasant watching it right among project files.
