### ISSUE TITLE
[sftp] (c:\www\foo\…) config file not found

### ISSUE THREAD

**Issue by viktordanko** [liximomo/vscode-sftp#72]
## Expected Behavior
Right click on a file and choosing "SFTP: Upload" uploads the file.

## Actual Behavior
Error message and no upload:  `[sftp] (c:\www\foo\index.php) config file not found`

### Extension Logs
 
```
[info]: config at c:\www\foo{
    "host": "host",
    "port": 22,
    "username": "login",
    "password": "password",
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "bar",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": true,
        "autoDelete": false
    },
    "ignore": [
        "c:/www/foo/**/.git/**",
        "c:/www/incatering/**/.DS_Store",
        "c:/www/incatering/**/node_modules",
        "bar/**/.git/**",
        "bar/**/.DS_Store",
        "bar/**/node_modules"
    ],
    "context": "c:\\www\\foo"
}

```
and the error itself:
```
[error]: context: undefined reason: Error: (c:\www\foo\index.php) config file not found
	at runTask (C:\Users\X\.vscode\extensions\liximomo.sftp-0.9.4\out\src\helper\createCommand.js:13:19)
	at Array.forEach (native)
	at runTasks (C:\Users\X\.vscode\extensions\liximomo.sftp-0.9.4\out\src\helper\createCommand.js:16:52)
	at getTarget.then.target (C:\Users\X\.vscode\extensions\liximomo.sftp-0.9.4\out\src\helper\createCommand.js:22:9)
	at <anonymous>
```

## Specifications

  - Version: 0.9.4
  - Platform: Windows 8.1 64-bit

**Comment by benabraham** [comment]
I got the same problem on Windows 10.

Visual Studio Code
Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by ryanbowden** [comment]
Same issue here :(

**Comment by liximomo** [comment]
Fix in 0.9.5.

**Comment by RomkaLTU** [comment]
It doesn't. Still same error on 

Windows 10 
Visual Studio Code Version 1.19.0
Plugin version Version: 0.9.5

**Comment by gerwinou** [comment]
I have the same error on MacOS High Sierra (10.13.2). As a workaround, I edited the sftp.json file by adding an extra property, saved it, and then it worked again
