### ISSUE TITLE
Ability to add context to profiles

### ISSUE THREAD

**Issue by massimo-cassandro** [liximomo/vscode-sftp#720]
I often work on projects where I have a local folder to be synchronized remotely with both a test and a production folder.

The ability to set up a local root path in the profile would be very useful.

As an alternative solution: the possibility of using the same `context` parameter in multi-context configurations

**Comment by b1oki** [comment]
Look please maybe it’s the same request #107

**Comment by massimo-cassandro** [comment]
yes, it is
thanks
