### ISSUE TITLE
Error: Config Not Found

### ISSUE THREAD

**Issue by mikexfreeze** [liximomo/vscode-sftp#742]
[03-20 16:50:44] [info] config at c:\my-projects\blog-srouce\project\public {"remotePath":"/www/blog","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"baidu_ecc","host":"duandiwang.com","port":22,"username":"******","password":"******","context":"project/public"}
[03-20 16:50:53] [warn] ENOENT: no such file or directory, open 'C:\Users\mikex\.ssh\config' load C:\Users\mikex\.ssh\config failed

已经设置了 sftp.json 还要读取用户目录下的 config，请问是否一定需要用户目录下的 config 文件？

**Comment by yonghui666** [comment]
> [03-20 16:50:44] [info] config at c:\my-projects\blog-srouce\project\public {"remotePath":"/www/blog","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"baidu_ecc","host":"duandiwang.com","port":22,"username":"******","password":"******","context":"project/public"}
> [03-20 16:50:53] [warn] ENOENT: no such file or directory, open 'C:\Users\mikex.ssh\config' load C:\Users\mikex.ssh\config failed
> 
> 已经设置了 sftp.json 还要读取用户目录下的 config，请问是否一定需要用户目录下的 config 文件？

大佬；你解决这个问题了吗；咱们一样；请教怎么解决

**Comment by mikexfreeze** [comment]
> > [03-20 16:50:44] [info] config at c:\my-projects\blog-srouce\project\public {"remotePath":"/www/blog","uploadOnSave":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"baidu_ecc","host":"duandiwang.com","port":22,"username":"******","password":"******","context":"project/public"}
> > [03-20 16:50:53] [warn] ENOENT: no such file or directory, open 'C:\Users\mikex.ssh\config' load C:\Users\mikex.ssh\config failed
> > 已经设置了 sftp.json 还要读取用户目录下的 config，请问是否一定需要用户目录下的 config 文件？
> 
> 大佬；你解决这个问题了吗；咱们一样；请教怎么解决

配置里面加一行 
```
"profiles": {}
```

**Comment by pengyan518** [comment]
I have the same issues when I update to VS code 1.56.0.
Added "profiles": {} in sftp.json, seems the same issue.

**Comment by erdemece** [comment]
create a folder called config in ~/.ssh
