### ISSUE TITLE
Is there a way to automatically edit in local?

### ISSUE THREAD

**Issue by ArielZabihi** [liximomo/vscode-sftp#750]
I want to edit in local but I hate right clicking and selecting the option every time. Is there a way to edit in local on click as opposed to it opening in read-only mode?

**Comment by robocrax** [comment]
Had same issue. This fixed it: https://github.com/liximomo/vscode-sftp/issues/270#issuecomment-501946457

**Comment by ArielZabihi** [comment]
Thank you @robocrax
