### ISSUE TITLE
Add multiple sftp/ftp host

### ISSUE THREAD

**Issue by YanzhongSu** [liximomo/vscode-sftp#754]
How to add multiple host in sftp.json file? Below config does not work
```
{
    "name": "test1",
    "host": "sftp.plattssp.com",
    "protocol": "sftp",
    "port": 22,
    "username": "test",
    "password": "test",
    "remotePath": "/",
    "uploadOnSave": false
}
{
    "name": "test2",
    "host": "pointconnectte.commodities.thomsonreuters.com",
    "protocol": "ftp",
    "username": "test",
    "password": "tes",
    "remotePath": "/",
    "uploadOnSave": false
}
```

**Comment by laiker** [comment]
I think it's not supported now

**Comment by gawinwong** [comment]
try this
```
{
    "name": "Remote Server",
    "protocol": "sftp",
    "port": 22,
    "ignore": [
        ".vscode",
        ".DS_Store",
        "__debug_bin",
        "*.exe",
        ".git",
        ".gitignore"
    ],
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "profiles": {
        "name1": {
            "host": "xxxxxx",
            "username": "xxxxxx",
            "password": "xxxxxx",
            "remotePath": "xxxxxx"
        },
        "name2": {
            "host": "xxxxxx",
            "username": "xxxxxx",
            "password": "xxxxxx",
            "remotePath": "xxxxxx"
        },
        "name3": {
            "host": "xxxxxx",
            "username": "xxxxxx",
            "password": "xxxxxx",
            "remotePath": "xxxxxx"
        }
    }
}
```

**Comment by zhihuacc** [comment]
> try this
> 
> ```
> {
>     "name": "Remote Server",
>     "protocol": "sftp",
>     "port": 22,
>     "ignore": [
>         ".vscode",
>         ".DS_Store",
>         "__debug_bin",
>         "*.exe",
>         ".git",
>         ".gitignore"
>     ],
>     "watcher": {
>         "files": "**/*",
>         "autoUpload": true,
>         "autoDelete": true
>     },
>     "profiles": {
>         "name1": {
>             "host": "xxxxxx",
>             "username": "xxxxxx",
>             "password": "xxxxxx",
>             "remotePath": "xxxxxx"
>         },
>         "name2": {
>             "host": "xxxxxx",
>             "username": "xxxxxx",
>             "password": "xxxxxx",
>             "remotePath": "xxxxxx"
>         },
>         "name3": {
>             "host": "xxxxxx",
>             "username": "xxxxxx",
>             "password": "xxxxxx",
>             "remotePath": "xxxxxx"
>         }
>     }
> }
> ```

What if I need use different ports for different hosts ?
