### ISSUE TITLE
How does watcher works?

### ISSUE THREAD

**Issue by timhecker** [liximomo/vscode-sftp#78]
Hi, how can I set multiple files in `watcher` config? I need to watch 3 files, I expect something like an array, but `watcher` needs a string.

Now: 
```javascript
    "watcher": {
        "files": "**/css/style.css",
        "autoUpload": true,
        "autoDelete": false
    },
```
I need something like that:
```javascript
    "watcher": {
        "files": [
          "**/css/style.css",
          "**/js/script.js"
        ],
        "autoUpload": true,
        "autoDelete": false
    },
```
Someone can help me? thanks.

## Specifications

  - Version: 0.9.5
  - Platform: Mac High Sierra

**Comment by dennisso** [comment]
I'm interested as well. According to the docs, it uses a glob string.

```
    "uploadOnSave": true,
    "syncMode": "full",
    "watcher": {
        "files": "**",
        "autoUpload": true,
        "autoDelete": true
    },
```
Currently I'm matching everything within the VSCode project directory.

**Comment by liximomo** [comment]
@timhecker `**/{css/style.css, js/script.js}`

**Comment by liximomo** [comment]
@dennisso `uploadOnSave` is just enough? Why do you need to watch the whole project?

**Comment by timhecker** [comment]
> `**/{css/style.css, js/script.js}`

@liximomo sorry, but it seems to not work: only the compiled style.css has been transferred, no way for the compiled script.js :(

**Comment by liximomo** [comment]
```
**/{css/style.css,js/script.js}
```
There should be no space after ','.

**Comment by pearlboy** [comment]
"files": "**/*.{css,css.map}",

**Comment by pearlboy** [comment]
> Hi, how can I set multiple files in `watcher` config? I need to watch 3 files, I expect something like an array, but `watcher` needs a string.
> 
> Now:
> 
> ```js
>     "watcher": {
>         "files": "**/css/style.css",
>         "autoUpload": true,
>         "autoDelete": false
>     },
> ```
> 
> I need something like that:
> 
> ```js
>     "watcher": {
>         "files": [
>           "**/css/style.css",
>           "**/js/script.js"
>         ],
>         "autoUpload": true,
>         "autoDelete": false
>     },
> ```
> 
> Someone can help me? thanks.
> 
> ## Specifications
> * Version: 0.9.5
> * Platform: Mac High Sierra

    "watcher": {
        "files": "**/*{css/style.css,js/script.js}",
        "autoUpload": true,
        "uploadOnSave": true,
        "autoDelete": false
    },

**Comment by piotrszczesniak** [comment]
I worked it out this way 
   "watcher": {
        "files": "**/themes/*{.css,.map}",
        "autoUpload": true,
        "autoDelete": true
thanks!
