### ISSUE TITLE
always connecting... (connection fail ) 

### ISSUE THREAD

**Issue by lodge-seven** [liximomo/vscode-sftp#79]
sftp.json:
{
    "host": "remote path(I use xftp's path,right?)",
    "port": 210,
    "username": "root",
    "password": "xxxxxxxxx",
    "protocol": "sftp", 
    "agent": null,
    "privateKeyPath": null, 
    "passphrase": null, 
    "passive": false, 
    "interactiveAuth": true,
    "remotePath": "./root/profile-manage",
    "uploadOnSave": false,
    "syncMode": "update",
    "ignore": [
        "**/.vscode/**",
        "**/.git/**",
        "**/.DS_Store"
    ],
    "watcher": {
        "files": "glob",
        "autoUpload": true,
        "autoDelete": true
    }

}

then, command-->sftp:Upload
emmmmmm = =. this show connecting,is my config wrong><?

**Comment by liximomo** [comment]
Try another client with the same connection parameters see if it works.

**Comment by lodge-seven** [comment]
0.0  谢谢 换了地址还真是可以了

**Comment by lodge-seven** [comment]
thanks  and the plugin is nb~  -v- nice
