### ISSUE TITLE
Interactive authentication 

### ISSUE THREAD

**Issue by regs01** [liximomo/vscode-sftp#8]
Tryed a one, but doesn't work for me. It will ask for password, but won't ask for verification code, so fails.

And is it possible to hide password with ****?

**Comment by liximomo** [comment]
Can you provide debug logs (with debug level turned all the way up) from the sshd process running on the server?
Yes. It can hide password with ****. Coming next.

**Comment by regs01** [comment]
meh, i was typing wrong password/ everything's fine and works flawlessly.
