### ISSUE TITLE
FTP protocol: The remote path is ignored and begins to download from root.

### ISSUE THREAD

**Issue by AdamJonsson** [liximomo/vscode-sftp#80]
## Expected Behaviour

I am expecting the same result as when I am using the SFTP protocol, the download command is only getting the files from the remote path. 

## Actual Behaviour

When I am using the SFTP protocol everything works fine. But when I am switching to the FTP protocol and beginning to download the files, it is getting all the files from the root. 

An example is that I want to download the files from the following directory: "/home/workspace/a". I set the remotePath to the above path but when I start the download, it is getting the files from the root. 

Also, when it is getting the files from the root, it is saving the files in the parent folder relatively to the context path. 

I have tested two diffrent servers to connect to and the same problem occurs. 

## Steps to Reproduce the Problem

  1. Use the FTP protocol.
  2. Specify the remote path (Not the root).
  3 Download the files to a folder on the computer. 

### Extension Logs
[info]: config at /Users/adamjonsson/Desktop/ElimTest {
    "host": "***",
    "port": 21,
    "username": "***",
    "password": "***",
    "protocol": "ftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/www/",
    "uploadOnSave": false,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "/Users/adamjonsson/Desktop/ElimTest/**/.vscode/**",
        "/Users/adamjonsson/Desktop/ElimTest/**/.git/**",
        "/Users/adamjonsson/Desktop/ElimTest/**/.DS_Store",
        "/www/**/.vscode/**",
        "/www/**/.git/**",
        "/www/**/.DS_Store"
    ],
    "context": "/Users/adamjonsson/Desktop/ElimTest"
}

[debug]: task: download /Users/adamjonsson/Desktop/ElimTest
[debug]: conncet to remote

End of log. After the sftp-plugin have dowloaded almost every folder from the root directory it is getting stuck at some random folder.

## Specifications

  - Version: 0.9.5
  - Platform: macOS 10.13.2

**Comment by liximomo** [comment]
The logs are insufficient. I need full logs.

**Comment by smspivak** [comment]
Same problem

**Comment by liximomo** [comment]
Please provide me the logs.

**Comment by smspivak** [comment]
[info]: config at /home/home/projects/****************** {
    "protocol": "ftp",
    "host": "******************",
    "port": 21,
    "username": "******************",
    "password": "******************",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "interactiveAuth": false,
    "secure": false,
    "secureOptions": null,
    "passive": false,
    "remotePath": "/www/******************",
    "uploadOnSave": true,
    "syncMode": "full",
    "ignore": [
        "/.vscode/**",
        "/.git/**",
        "**/.DS_Store",
        "/node_modules/**",
        "/src/**",
        ".gitignore",
        ".gulpfile.js",
        "package-lock.json",
        "package.json",
        "phpcs.xml.dist",
        "ToDo"
    ],
    "watcher": {
        "files": "**",
        "autoUpload": true,
        "autoDelete": true
    },
    "context": "/home/home/projects/******************"
}


[debug]: task: remove /www/******************/.git/index.lock
[debug]: connect to remote

[debug]: task: upload /home/home/projects/******************/.git/index.lock

[debug]: task: remove /www/******************/.git/index.lock
[debug]: 
ignore: /www/******************/.git/index.lock
[debug]: 
ignore: /home/home/projects/******************/.git/index.lock
[debug]: 
ignore: /www/******************/.git/index.lock

[debug]: task: download /home/home/projects/******************
[debug]: 
------
target: /www/******************
context: transmission dir
error: Error: Timeout
	at makeError (/home/smspivak/.vscode-insiders/extensions/liximomo.sftp-1.0.2/node_modules/ftp/lib/connection.js:1067:13)
	at Parser.<anonymous> (/home/smspivak/.vscode-insiders/extensions/liximomo.sftp-1.0.2/node_modules/ftp/lib/connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (/home/smspivak/.vscode-insiders/extensions/liximomo.sftp-1.0.2/node_modules/ftp/lib/parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (/home/smspivak/.vscode-insiders/extensions/liximomo.sftp-1.0.2/node_modules/ftp/lib/connection.js:273:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
------
[debug]: connect end
[debug]: connect close

**Comment by liximomo** [comment]
The logs seem are unrelated to your problems.

**Comment by liximomo** [comment]
@xVinniVx Please try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) and send me the logs.

**Comment by andreyorst** [comment]
same here with ftp protocol. Yet ftp-simple plugin works fine.

**Comment by liximomo** [comment]
@andreyorst Could you help me to debug this problem? I will make a debug-package with verbose logs. You only need to reproduce the problem and give me the logs.

**Comment by andreyorst** [comment]
@liximomo sure!

**Comment by liximomo** [comment]
@andreyorst Thanks!  Please try with [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) and send me the logs.

**Comment by andreyorst** [comment]
@liximomo I've replaced all occurences of usermane to "usermane". This is not full log, because there were TON of data, and I couldn't even copy it, but at the end of the log you'll see that it started listing `/home/.*` dirs.
[log.txt](https://github.com/liximomo/vscode-sftp/files/1828843/log.txt)

**Comment by liximomo** [comment]
@andreyorst I fixed a possible bug! Please try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) again see if it gets solved.

**Comment by andreyorst** [comment]
@liximomo I'm currently little busy, so I'll try that in a couple of hours

**Comment by andreyorst** [comment]
@liximomo Well now I't isn'y spamming all root content in my $HOME, but it's not working either.
```[info] config at /home/aorst/Downloads/xzzxczx {"protocol":"ftp","host":"ftp","port":21,"username":"username","password":"34910893","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/username/ftp_base","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":[],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"/home/aorst/Downloads/xzzxczx"}
[debug] run command download {"$mid":1,"fsPath":"/home/aorst/Downloads/xzzxczx","external":"file:///home/aorst/Downloads/xzzxczx","path":"/home/aorst/Downloads/xzzxczx","scheme":"file"} [{"$mid":1,"fsPath":"/home/aorst/Downloads/xzzxczx","external":"file:///home/aorst/Downloads/xzzxczx","path":"/home/aorst/Downloads/xzzxczx","scheme":"file"}]
[debug] < 220 (vsFTPd 2.2.2)
[debug] > USER username
[debug] < 331 Please specify the password.
[debug] > PASS ******
[debug] < 230 Login successful.
[debug] > FEAT
[debug] < 211-Features:\r\n EPRT
[debug] <  EPSV\r\n MDTM\r\n PASV\r\n REST STREAM\r\n SIZE
[debug] <  TVFS\r\n UTF8\r\n211 End
[debug] > TYPE I
[debug] < 200 Switching to Binary mode.
[info] connected
[debug] lstat /home/username/ftp_base
[debug] > PASV
[debug] < 227 Entering Passive Mode (192,168,175,44,201,159).
[debug] > LIST /home/username
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] list /home/username/ftp_base
[debug] > PASV
[debug] < 227 Entering Passive Mode (192,168,175,44,162,169).
[debug] > LIST -al /home/username/ftp_base
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] list /home/username/ftp_base/can_error_state
[debug] > PASV
[debug] list /home/username/ftp_base/can_overwrite_test
[debug] list /home/username/ftp_base/can_remote_test
[debug] list /home/username/ftp_base/can_self_test
[debug] < 227 Entering Passive Mode (192,168,175,44,192,30).
[debug] > LIST -al /home/username/ftp_base/can_error_state
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] > PASV
[debug] < 227 Entering Passive Mode (192,168,175,44,141,211).
[debug] > LIST -al /home/username/ftp_base/can_overwrite_test
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] > PASV
[debug] < 227 Entering Passive Mode (192,168,175,44,161,94).
[debug] > LIST -al /home/username/ftp_base/can_remote_test
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] > PASV
[debug] < 227 Entering Passive Mode (192,168,175,44,104,203).
[debug] list /home/username/ftp_base/can_remote_test/SECOND_CHIP
[debug] > PASV
[debug] list /home/username/ftp_base/can_remote_test/rtlrun.two
[debug] < 227 Entering Passive Mode (192,168,175,44,77,183).
[debug] > LIST -al /home/username/ftp_base/can_remote_test/SECOND_CHIP
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] > LIST -al /home/username/ftp_base/can_self_test
[debug] < 425 Use PORT or PASV first.
[debug] > PASV
[error]: Error: Use PORT or PASV first.
	at makeError (/home/aorst/.vscode/extensions/liximomo.sftp-1.1.3/node_modules/ftp/lib/connection.js:1067:13)
	at Parser.<anonymous> (/home/aorst/.vscode/extensions/liximomo.sftp-1.1.3/node_modules/ftp/lib/connection.js:113:25)
	at emitTwo (events.js:106:13)
	at Parser.emit (events.js:194:7)
	at Parser._write (/home/aorst/.vscode/extensions/liximomo.sftp-1.1.3/node_modules/ftp/lib/parser.js:59:10)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (/home/aorst/.vscode/extensions/liximomo.sftp-1.1.3/node_modules/ftp/lib/connection.js:273:20)
	at emitOne (events.js:96:13)
[debug] < 227 Entering Passive Mode (192,168,175,44,119,186).
[debug] > LIST -al /home/username/ftp_base/can_remote_test/rtlrun.two
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] list /home/username/ftp_base/can_remote_test/rtlrun.two/Tests
[debug] > PASV
[debug] list /home/username/ftp_base/can_remote_test/rtlrun.two/Tests2
[debug] < 227 Entering Passive Mode (192,168,175,44,154,26).
[debug] > LIST -al /home/username/ftp_base/can_remote_test/rtlrun.two/Tests
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] > PASV
[debug] < 227 Entering Passive Mode (192,168,175,44,43,249).
[debug] > LIST -al /home/username/ftp_base/can_remote_test/rtlrun.two/Tests2
[debug] < 150 Here comes the directory listing.
[debug] < 226 Directory send OK.
[debug] < 200 NOOP ok.
[debug] < 200 NOOP ok.
```
And endless NOOP messages then.
And i'm not sure what it suppose to mean:
![image](https://user-images.githubusercontent.com/19470159/37655749-2e9e4f08-2c57-11e8-9beb-87566273c7c0.png)

**Comment by liximomo** [comment]
It says you should config  `"passive": true`.

**Comment by andreyorst** [comment]
Seems to work now!

**Comment by andreyorst** [comment]
well, I've figured out that this errors are _random_. If I try to download again it may work. Actually now I able to download a remote directory, edit file and upload it back, but downloading doesn't always work

**Comment by liximomo** [comment]
Set `concurrency: 1` may prevent this error occurs.

**Comment by andreyorst** [comment]
Actually it is still here. And now it can't set connection. `[sftp] Unable to make data connection( Error: connect ECONNRESET ***.***.***.**:*****)` Notepad++ uses mostly the same config (ports, protocol, host, username etc) and works.

**Comment by liximomo** [comment]
Set `passive` back to false.

**Comment by andreyorst** [comment]
> Set passive back to false.

Ok

In terms of issue topic 
> But when I am switching to the FTP protocol and beginning to download the files, it is getting all the files from the root.

01dcbc9 seems to fix that, and my download problems may be a different story.

**Comment by liximomo** [comment]
Thanks for your help! This issue can be closed now. 🎉🎉🎉

**Comment by andreyorst** [comment]
@liximomo when extension will be updated in marketplace?

**Comment by andreyorst** [comment]
Great! Thanks!
