### ISSUE TITLE
last-modified 最后修改时间

### ISSUE THREAD

**Issue by Hughdw** [liximomo/vscode-sftp#81]
## Expected Behavior
文件的最后修改时间属性与 FTP/SFTP 中的一致。

## Actual Behavior
uploadOnSave: true 的情况，ctrl + s 操作之后，本地文件的最后修改时间比服务器上文件的最后修改时间少 1 秒。
通过鼠标右键选择上传文件，本地文件的最后修改时间没有变化的前提下，服务器上文件的最后修改时间会被“上传”的时间点覆盖（什么时候右击选择上传，服务器上文件的最后修改时间就是什么时候）。

## Steps to Reproduce the Problem

  1.配置好 SFTP。
  2.在目录中右击文件。
  3.选中 SFTP: Upload。

## Specifications

  - Version:0.9.5
  - Platform:windows

## Other
  Thank you! 麻烦你了。

**Comment by liximomo** [comment]
v1.6.0 解决了这个问题.
