### ISSUE TITLE
sftp:upload changes all file timestamps

### ISSUE THREAD

**Issue by ghubusr01** [liximomo/vscode-sftp#83]
## Expected Behavior
[Description of the expected behavior]
There should be a functionality where only an edited file is uploaded and the file timestamp is changed only for this file

## Actual Behavior
[Description of the actual behavior]
all files which were downloaded are updated with actual file timestamps, this is completely unacceptable and destroyed file timestamps of my whole home directory of all files!

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version: 0.9.5
  - Platform: Windows

**Comment by ghubusr01** [comment]
ok, so you have to right click on only the file you wish to upload and select sftp:upload, right?
So this means I would have to either right-click on every single file I want to upload or set upload on save to true, right? There is no diff algorithm for the changed files like watcher for created/deleted files, right?

Thanks

**Comment by viT-1** [comment]
Same issue (my behaviour): on git reverted list of files SFTP is not uploaded these files =(

**Comment by liximomo** [comment]
v1.6.0 would work as you expect.
