### ISSUE TITLE
Watcher doesn't work with multiple files

### ISSUE THREAD

**Issue by frogx3** [liximomo/vscode-sftp#84]
Hi,

How can I configure the plugin to watch multiples files, it supposed that is possible, but when I try to configure, the plugin crash when I try to save and upload a file.

The portion of configuration I tried, is the following:

    "watcher": {
        "files": [
            "/path/filename1.ext", 
            "/path/filename2.ext"
        ],
        "autoUpload": false,
        "autoDelete": false
    },

Best regards,
Jorge Aldana

**Comment by sebbler1337** [comment]
Hey Jorge,

i was looking for a solution also just now and all i found was this:

        "files": "{public/css/app.css,public/js/app.js}",

The downside to this is that whenever you update one file, both files get uploaded and not just the on you changed.

Hope it helps!

Sebastian

**Comment by frogx3** [comment]
Hi Sebastian,

Great, If happen as you said, I will need to configure my grunt to build the SASS and the JS in every save action, nothing exceptional and will work almost as expected.

Thank you :)

Best regards,
Jorge Aldana

**Comment by MiroArabadjiev** [comment]
> Hey Jorge,
> 
> i was looking for a solution also just now and all i found was this:
> 
> ```
>     "files": "{public/css/app.css,public/js/app.js}",
> ```
> 
> The downside to this is that whenever you update one file, both files get uploaded and not just the one you changed.
> 
> Hope it helps!
> 
> Sebastian
> 
> EDIT: Comment to why your solution might not be working:
> As the Documentation describes, the files "parameter" only accepts a string. Read more here:
> 
> watcher: {
> /**
> * available value: false or a glob pattern
> * - false: disable watcher
> * - string containing a glob pattern: describes files that will be watched
> */
> files: false,

Thank you for the Files Watcher multiple paths syntax!
