### ISSUE TITLE
Getting command 'sftp.trans.remote' not found when trying to upload/download from Windows VsCode.

### ISSUE THREAD

**Issue by marioanton** [liximomo/vscode-sftp#85]
## Expected Behavior
I should be able to run the upload command (sftp.trans.remote)
## Actual Behavior
After a fresh install i'm unable to run the upload command with basic config.

`{
    "context": ".",
    "host": "XXXX",
    "port": 22,
    "username": "mario.anton",
    "password": null,
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": "C:\\Users\\Ma.........",
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/home/.......",
    "uploadOnSave": false,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "**/.vscode/**",
        "**/.git/**",
        "**/.DS_Store"
    ]
}
`

No output generate in logs.
Tried to run the vsCode as administrator.
Tried to use IP instead names just in case.

## Specifications

  - Version: Vscode 1.8
  - Platform: Windiows 2012

**Comment by liximomo** [comment]
Did you create the config file by `sftp: config` command?

**Comment by hetal1110** [comment]
getting same error  'sftp.trans.local' not found, when executing "sftp:download"..
Any solution?
