### ISSUE TITLE
syncOption delete not working as expected

### ISSUE THREAD

**Issue by coldpumpkin** [liximomo/vscode-sftp#855]
Is this still maintained?

Using 
`    "syncOption": {
        "syncOption.delete": true
    },`

When syncing local > remote for example, it's supposed to delete files on remote that don't exist on local, am I correct? Because it's not working.

**Comment by JustBertC** [comment]
Bit late but using this works:
`"syncOption": { "delete": true },`

**Comment by coldpumpkin** [comment]
Seems to be working great, thank you!
