### ISSUE TITLE
Sync a single file

### ISSUE THREAD

**Issue by mbukovac** [liximomo/vscode-sftp#86]
Hi,

I was just wondering if there is a way to sync (remote to local and back) a single file? Site I'm working on has tons of files and I don't need all of them, so I wish to only sync the ones I need.

Thanks!

**Comment by liximomo** [comment]
With v1.0.0, you can set ignore to this
```
{
  ignore: [ '/*', '!subpath/target.txt']
}
```

**Comment by mbukovac** [comment]
Hi liximomo,

Thanks for the info, but it doesn't seem to work as expected. I managed to get it to work for one file, but adding a subpath doesn't work. For example, this works:
`{
    "host": "myserver.com",
    "port": 22,
    "username": "my-user",
    "password": "my-password",
    "protocol": "sftp",
    "remotePath": "/home/my-user/path/to/myfile",
    "uploadOnSave": true,
    "syncMode": "update",
    "ignore": [ 
        "/*", 
        "!myfile.php" 
    ]
}`
I do a SFTP:Download and then on save, the changes are updated to the file, which is what I want. If change is made on the server, any subsequent SFTP:Download updates my local file.

But, this option doesn't work:
{
    "host": "myserver.com",
    "port": 22,
    "username": "my-user",
    "password": "my-password",
    "protocol": "sftp",
    "remotePath": "/home/my-user",
    "uploadOnSave": true,
    "syncMode": "update",
    "ignore": [ 
        "/*", 
        "!path/to/myfile/myfile.php" 
    ]
}
Nothing gets downloaded on SFTP:Download. This is the version of the config I'd like, because I might have multiple files in different directories that I want to work with. I tried various combinations of the "!path/to/myfile/myfile.php", with full path, leading slash, space between ! and path, and nothing seems to work. 

Any suggestions there? Thanks!

**Comment by ali-han** [comment]
```
{
    "protocol": "ftp",
    "host": "ftp.example.com",
    "port": 21,
    "username": "foo",
    "password": "hidden",
    "remotePath": "/public_html/",
    "uploadOnSave": true,
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "ignore": [
        ".vscode",
        ".git",
        ".DS_Store",
        "wp-admin",
        "wp-includes",
        "google-drive",
        "i",
        "wp-content",
        "!/wp-content/plugins/custom-plugin",
        "!/wp-content/themes/my-theme"
    ],
    "downloadOnOpen": true,
    "syncMode": "full"
}
```
Its my config but excepting not works. Are there any problems with these settings?

**Comment by liximomo** [comment]
@ali-han Please file a new issue with a detailed description.
