### ISSUE TITLE
vscode 1.53下sftp 同步报错：扩展宿主意外终止。

### ISSUE THREAD

**Issue by skyyouare** [liximomo/vscode-sftp#886]
<img width="612" alt="截屏2021-02-18 10 52 17" src="https://user-images.githubusercontent.com/8912113/108298230-906e7f00-71d7-11eb-9d95-eba8e7386765.png">
<img width="1724" alt="截屏2021-02-18 10 52 26" src="https://user-images.githubusercontent.com/8912113/108298234-92d0d900-71d7-11eb-99b3-9fc310a3c5a9.png">

**Comment by zxj17815** [comment]
遇到了相同的问题  我重新安装回1.52版本就可以了

**Comment by skyyouare** [comment]
之前退回1.52，现在更新到1.54.1好了
