### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by gpalleschi** [liximomo/vscode-sftp#889]
When I install last Version 1.53.2, some connections stop to work.

![image](https://user-images.githubusercontent.com/12493269/108818662-0305a300-75ba-11eb-9607-2af51e3147e1.png)

**Comment by liaocyintl-deprecated** [comment]
The same to me.
I disabled all extensions but didn't work.

**Comment by Alban-64** [comment]
Same to me ! I try new installation (vstudio), but nothing work anymore. some pb with Intellisense to !

**Comment by Alban-64** [comment]
see here : https://github.com/microsoft/vscode/issues/115818

**Comment by gpalleschi** [comment]
> see here : [microsoft/vscode#115818](https://github.com/microsoft/vscode/issues/115818)

Thank you @Alban-64.

**Comment by ghost** [comment]
This is related to #881.

**Comment by gpalleschi** [comment]
Thanks @thompsbrian

**Comment by minstyle** [comment]
Issue fixed with latest vscode version 1.54.1.
