### ISSUE TITLE
File explorer does not refresh on download of new files from server

### ISSUE THREAD

**Issue by TamDenholm** [liximomo/vscode-sftp#89]
While this seems to be more an issue with VS code than the plugin itself, i'm wondering if its possible to force a file explorer sidebar refresh when sftp download is triggered. I dont know if this should be a feature request or a bug?

## Expected Behavior
Create a new file on the server
Select local folder in VS Code sidebar file explorer
Select SFTP: Download
File downloads to local filesystem
File appears in sidebar file explorer (File explorer refresh)

## Actual Behavior
Create a new file on the server
Select local folder in VS Code sidebar file explorer
Select SFTP: Download
File downloads to local filesystem
File DOES NOT appear in sidebar file explorer, you must manually refresh it
This leads to the user thinking that the file has not successfully downloaded.

## Steps to Reproduce the Problem

See Above

### Extension Logs
 
Not applicable as extension works correctly

## Specifications

  - Version: VS Code: 1.19.2, sftp extension: 0.9.5
  - Platform: Mac Sierra

**Comment by liximomo** [comment]
The v1.0.0 implement this feature.
