### ISSUE TITLE
If i want put to many host the Sftp only recognize one

### ISSUE THREAD

**Issue by Ariaz39** [liximomo/vscode-sftp#890]
The problem:
If i want put to many host the Sftp only recognize one **(they are different hosts not profiles
)**. that is, the last.  I followed the instructions but it doesn't work for me

**Screenshots**
![image](https://user-images.githubusercontent.com/33878604/108923800-75e93b00-7607-11eb-8d37-b9fa7b70a765.png)
This is the estructure that i'm using

is in W10 with the last upgrade of Sftp extension

I need help pls.

**Comment by war1644** [comment]
me too

**Comment by Ariaz39** [comment]
it finally worked for me, you should use it like this.

> `Code`

[
      {
            "name": "Host1",
            "context": "Host1",
            "host": "host1.com",
            "protocol": "ftp",
            "port": 21,
            "username": "host1",
            "remotePath": "/public_html",
            "password": "Password",
            "uploadOnSave": true
      },
      {
            "name": "Host2",
            "context": "Host2",
            "host": "host2.com",
            "protocol": "ftp",
            "port": 21,
            "username": "host2",
            "remotePath": "/public_html",
            "password": "Password",
            "uploadOnSave": true
      }
]
