### ISSUE TITLE
What does 'a newer version' in 'syncOption.update' option mean?

### ISSUE THREAD

**Issue by microkof** [liximomo/vscode-sftp#891]
syncOption.update
boolean - Update the dest only if a newer version is on the src filesystem.

How can the src filesystem belong to a new version?

**Comment by ghost** [comment]
Perhaps the wording is bad... what it means is that setting `syncOption.update` as `true` will only update the remote file if there are any changes to that file on the local file system.  If it is set to false, then it will be pushed to the remote no matter what (changes or not).  Setting `syncOption.update` to true can save the plugin some work I believe.

**Comment by microkof** [comment]
> Perhaps the wording is bad... what it means is that setting `syncOption.update` as `true` will only update the remote file if there are any changes to that file on the local file system. If it is set to false, then it will be pushed to the remote no matter what (changes or not). Setting `syncOption.update` to true can save the plugin some work I believe.

Thank you!

**Comment by ghost** [comment]
Just adding a note here to fix the documentation...

**Comment by jeremy-farrance** [comment]
I think this need to go further, what is the comparison? My guess would be file datetime local vs. remote. Can we get that clarified?
