### ISSUE TITLE
Can not resolve target because of weird context path

### ISSUE THREAD

**Issue by TheWebDuck** [liximomo/vscode-sftp#90]
## Expected Behavior
[Description of the expected behavior]
When I upload a file I expect the file to upload to the remote in the same directory using the project folder as the local directory
## Actual Behavior
[Description of the actual behavior]
The upload works great however it does not see the open project folder as the actual root. Instead it adds all the parent folders. 

Example: if I want to upload test.php to the root of a remote project, I should just be able to upload it and when I look in the remote I don't see the file. Instead I see the local parent directory/another directory/another directory/project folder name/file i uploaded

I am running vscode on a windows 10 machine and the local source directories for all my projects are on a networked linux machine

## Steps to Reproduce the Problem

  1.just upload a file
  1.
  1.

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version:
  - Platform:

**Comment by liximomo** [comment]
Maybe just a misconfig? Could you provide logs?

**Comment by TheWebDuck** [comment]
Thank you for getting back to me so quickly.

More info. I have tried no "context", a context of "." and a context of
"\\SRVR!\WebDuckDesigns\WebSites\Twin_Cities_Physicians" which is the path
to the project root folder.

As far as logs go, I get no runtime errors.

[info]: config at /SRVR1/WebDuck_Business/WebSites/Twin_Cities_Physicians {
"host": "132.148.5.249",
"port": 22,
"username": "mytcp",
"password": "qp$WlOpyv)U(",
"protocol": "sftp",
"agent": null,
"privateKeyPath": null,
"passphrase": null,
"passive": false,
"interactiveAuth": false,
"remotePath": "/home/mytcp/public_html/",
"uploadOnSave": false,
"syncMode": "update",
"watcher": {
"files": false,
"autoUpload": false,
"autoDelete": false
},
"ignore": [
"/SRVR1/WebDuck_Business/WebSites/Twin_Cities_Physicians/**/.vscode/**",
"/SRVR1/WebDuck_Business/WebSites/Twin_Cities_Physicians/**/.git/**",
"/SRVR1/WebDuck_Business/WebSites/Twin_Cities_Physicians/**/.DS_Store",
"/home/mytcp/public_html/**/.vscode/**",
"/home/mytcp/public_html/**/.git/**",
"/home/mytcp/public_html/**/.DS_Store"
],
"context": "/SRVR1/WebDuck_Business/WebSites/Twin_Cities_Physicians"
}


[debug]: task: upload
\\SRVR1\WebDuck_Business\WebSites\Twin_Cities_Physicians\test.php
[debug]: conncet to remote
[debug]: try to get
/home/mytcp/public_html/SRVR1/WebDuck_Business/WebSites/Twin_Cities_Physicians/test.php
mode fail, default to 0666
[debug]: transmission file
\\SRVR1\WebDuck_Business\WebSites\Twin_Cities_Physicians\test.php at Wed
Jan 24 2018 11:42:33 GMT-0600 (Central Standard Time)

**Comment by liximomo** [comment]
I can see where is going wrong. What is your local machine OS? Why does it have a file path like this `\\SRVR1\WebDuck_Business\WebSites\Twin_Cities_Physicians\test.php`?

**Comment by TheWebDuck** [comment]
My local machine is a windows 10 pc. The file path is because the files are
located on a Linux file share server on my network

**Comment by liximomo** [comment]
I just release `v1.0.0`. I think it should resolve this problem. Please try it and give me some feedback.

**Comment by TheWebDuck** [comment]
i have version 1.01 isn't that newer?

**Comment by liximomo** [comment]
Yes. Does it work?

**Comment by TheWebDuck** [comment]
I will check in the morning. Thank you for all your quick responses. Last
couple days sucked using FileZilla

**Comment by TheWebDuck** [comment]
I have successfully tested the newest update. It worked just as expected.
Thanks for being so incredibly quick about getting it functional. It is
much appreciated

**Comment by TheWebDuck** [comment]
spoke too soon.. it's true it uploads.. but now everything it uploads gives
me a server 500 error :(  I upload the same file/directory with filezilla
and it works just fine.. so it's not a file issue, it's something to do
with the upload itself

**Comment by liximomo** [comment]
Ok. Please provide me logs.

**Comment by TheWebDuck** [comment]
I can in the morning. It is creating shortcuts to the files as opposed to
the actual files

**Comment by liximomo** [comment]
Is the file you upload a symbol link?
