### ISSUE TITLE
Not downloading files in subdirectories

### ISSUE THREAD

**Issue by mbukovac** [liximomo/vscode-sftp#92]
## Expected Behavior
Following instructions in issue [#86](86), I am able to ignore all the files. Allowing the file should be done using `!custom/CustomFile.php` and the file should download when using SFTP:Download. 
 
## Actual Behavior
The files in the ignored subdirectory still get ignored, even when specifically listed as allowed.

## Steps to Reproduce the Problem
Here is the config:

```
{
    "host": "myserver.com",
    "port": 22,
    "username": "my-user",
    "password": "my-password",
    "protocol": "sftp",
    "remotePath": "/home/my-user",
    "uploadOnSave": true,
    "syncMode": "update",
    "ignore": [ 
        "/*",
        "!custom/CustomFile.php",
        "!TestFile.php"
    ]
}
```

In this setup, the file `TestFile.php` gets downloaded and gets synced as it is supposed to. However, file `custom/CustomFile.php` gets ignored because subdirectory `custom` is ignored.

  ### Extension Logs
The logs contain many entries listing directories that are getting ignored, so here is the short version:

```
[debug]: task: download c:\Users\Marko\Desktop\VSCode Test
[debug]: connect to remote
...
[debug]: 
ignore: /home/my-user/custom
...
[debug]: transmission file /home/my-user/TestFile.php at Fri Jan 26 2018 18:06:05 GMT+0000 (GMT Standard Time)
``` 

## Specifications

  - Version: SFTP 1.0.1
  - Platform: Windows 10 for local, not sure which linux on remote

Thanks!

**Comment by liximomo** [comment]
This will work. It's just how gitignore works.
```json
{
  "ignore": [ 
        "/*",
        "!/custom",
        "/custom/*",
        "!/custom/CustomFile.php"
        "!TestFile.php"
  ]
}
```
