### ISSUE TITLE
Today it stopped working with VSC Insider

### ISSUE THREAD

**Issue by robertheessels** [liximomo/vscode-sftp#94]
On Windows 10.
VSC Insider version 1.20.0-insider
sftp version 1.0.1

Since upgrade to these version SFTP stopped working.
No upload or download in workspaces that worked until today. No errors.

When I run SFTP:Config I get error:
command 'sftp.config.default' not found

**Comment by liximomo** [comment]
Any logs？

**Comment by robertheessels** [comment]
Where can I find those, please?

**Comment by liximomo** [comment]
set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)

**Comment by robertheessels** [comment]
Where do I set `sftp.printDebugLog`, please? I tried both user settings and workspace settings.
Never a sftp tab or logs show up in view -> output.

**Comment by liximomo** [comment]
Both user settings and workspace settings could work. Do you hava an sftp.json in .vscode folder？If not the extension will not be activated.

**Comment by robertheessels** [comment]
Yes, I do. And it worked fine until today.
Thanx for all the (very) fast responses, by the way. Really appreciate that!

**Comment by liximomo** [comment]
Maybe it's a bug of vscode insider. You could try a full restart or a stable version.

**Comment by robertheessels** [comment]
It works indeed with the stable VSC.
It does not work with insider Date 2018-01-26T05:15:09.585Z.

I will work with stable for now. Thanx again for the fast help and nice extension! You rock!!! :-)

**Comment by iaimmiac** [comment]
My vscode just updated to 1.20 (stable release), and i am facing this issue.

I get the error `command 'sftp.config.default' not found` when trying to create config
When i use shortcut, i get `command 'sftp.trans.remote' not found`
When i right click and select upload, nothing happens

**Comment by liximomo** [comment]
@iaimmiac See #101.

**Comment by robertheessels** [comment]
Deleting a folder like `/Users/c01nd01r/.vscode/extensions/liximomo.sftp-1.0.4/` and reinstalling sftp fixed my issue!
