### ISSUE TITLE
Reading private key file failed

### ISSUE THREAD

**Issue by Sjorsa** [liximomo/vscode-sftp#973]
**Do you read the FAQ?**
- [ X] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

It's probably not a bug and a fault on my end, sorry for making an issue but I could not find another way to ask this.
I get the following error:
```Reading private key file C/Users/Sjors/Desktop/privateKey.ppk failed, {1}```
with the following configuration:
```{
    "comment": "Please fill the following configuration, save it, then close the tab.",
    "host": "10.0.0.2",
    "port": 22,
    "username": "root",
    "privateKeyFile": "C/Users/Sjors/Desktop/privateKey.ppk"
}
```

I generated the private key file using PuttyGen.

I remember following the exact same procedure on my desktop, but on my laptop it isn't working.

**To Reproduce**
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version [e.g. 1.27.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by Sjorsa** [comment]
I'm using another extension to acces the files on my server now so I'll close this issue.

**Comment by Kodesmeden** [comment]
I have the same issue, what was the extension you chose?

**Comment by Sjorsa** [comment]
I think it was the `Remote - SSH` extension. I don't know if that will work for an ftp server tho.
