### ISSUE TITLE
localPath request

### ISSUE THREAD

**Issue by designofadecade** [liximomo/vscode-sftp#990]
Is it possible to set a  relative  "localPath"? When working with workspaces, it would be great if you can set a "localPath": "html" for example and only files from html/ are synced.

Folders
- nginx
- html
    - js
    - css
- php

**Comment by designofadecade** [comment]
"context" setting is what I was looking for

**Comment by nicolasmol** [comment]
And you don't think that "context" is not more logical to name it than "localPath" ?

**Comment by designofadecade** [comment]
"context" is more logical, I would not go with my original request anymore.
